const Q_COLOR = [
  // ===== DIFFICULTY 1 (基礎) — 33 questions =====
  {
    id: "color_001",
    category: "color",
    type: "single",
    difficulty: 1,
    question: "在 ISP 中，CCM（Color Correction Matrix）通常是什麼維度的矩陣？",
    options: ["2×2", "3×3", "4×4", "5×5"],
    answer: 1,
    acceptAlso: [],
    explanation: "CCM 是 3×3 矩陣，用於將感測器的 RGB 色彩空間轉換到標準色彩空間（如 sRGB），對三個色彩通道進行線性變換。",
    imageDesc: "",
    scenario: "",
    hint: "RGB 有三個通道",
    items: []
  },
  {
    id: "color_002",
    category: "color",
    type: "truefalse",
    difficulty: 1,
    question: "sRGB 的 gamma 值恰好等於 2.2。",
    options: ["正確", "錯誤"],
    answer: false,
    acceptAlso: [],
    explanation: "sRGB 的 transfer function 並非單純的 power law γ=2.2，而是由線性段和指數段拼接而成。低值區使用線性映射，高值區使用約 γ≈2.4 的指數函數，整體近似於 γ=2.2 但並不完全相等。",
    imageDesc: "",
    scenario: "",
    hint: "sRGB 標準有特殊的分段定義",
    items: []
  },
  {
    id: "color_003",
    category: "color",
    type: "single",
    difficulty: 1,
    question: "YUV 色彩空間中，Y 代表什麼？",
    options: ["色相（Hue）", "亮度（Luminance）", "飽和度（Saturation）", "色溫（Color Temperature）"],
    answer: 1,
    acceptAlso: [],
    explanation: "在 YUV 色彩空間中，Y 代表亮度（Luminance），U 和 V 代表色差（Chrominance）分量。這種分離方式便於壓縮和人眼視覺特性匹配。",
    imageDesc: "",
    scenario: "",
    hint: "人眼對亮度變化最敏感",
    items: []
  },
  {
    id: "color_004",
    category: "color",
    type: "single",
    difficulty: 1,
    question: "HSV 色彩模型中的 H、S、V 分別代表什麼？",
    options: [
      "Hue, Saturation, Value",
      "Hue, Sharpness, Volume",
      "Highlight, Shadow, Vibrance",
      "Histogram, Spectrum, Variance"
    ],
    answer: 0,
    acceptAlso: [],
    explanation: "HSV 代表 Hue（色相）、Saturation（飽和度）、Value（明度）。這是一種更直觀的色彩表示方式，常用於色彩調整演算法。",
    imageDesc: "",
    scenario: "",
    hint: "這是一種圓柱座標的色彩模型",
    items: []
  },
  {
    id: "color_005",
    category: "color",
    type: "truefalse",
    difficulty: 1,
    question: "White Balance（白平衡）的目的是讓場景中的白色物體在影像中呈現為中性白色。",
    options: ["正確", "錯誤"],
    answer: true,
    acceptAlso: [],
    explanation: "白平衡的核心目的就是消除光源色溫的影響，讓白色物體在影像中呈現為中性白色（R=G=B），從而使整體色彩還原更準確。",
    imageDesc: "",
    scenario: "",
    hint: "想想在不同燈光下拍攝白紙的效果",
    items: []
  },
  {
    id: "color_006",
    category: "color",
    type: "single",
    difficulty: 1,
    question: "下列哪個色彩空間的色域（Color Gamut）最大？",
    options: ["sRGB", "Adobe RGB", "DCI-P3", "BT.2020"],
    answer: 3,
    acceptAlso: [],
    explanation: "BT.2020 的色域最大，覆蓋了 CIE 1931 色度圖的大部分區域。色域大小排序為：sRGB < Adobe RGB ≈ DCI-P3 < BT.2020。",
    imageDesc: "",
    scenario: "",
    hint: "這是 UHD/4K 電視的標準",
    items: []
  },
  {
    id: "color_007",
    category: "color",
    type: "fillblank",
    difficulty: 1,
    question: "色溫的單位是 ______（英文縮寫）。",
    options: [],
    answer: "K",
    acceptAlso: ["Kelvin", "kelvin"],
    explanation: "色溫以 Kelvin（K）為單位，描述光源的色彩特性。日光約 5500K–6500K，鎢絲燈約 2700K–3000K。",
    imageDesc: "",
    scenario: "",
    hint: "以一位物理學家的名字命名的絕對溫度單位",
    items: []
  },
  {
    id: "color_008",
    category: "color",
    type: "single",
    difficulty: 1,
    question: "Gamma correction 的主要目的是什麼？",
    options: [
      "增加解析度",
      "補償顯示器的非線性亮度響應",
      "減少雜訊",
      "提高對比度"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "Gamma correction 主要用於補償 CRT 及 LCD 顯示器的非線性亮度響應，使影像在螢幕上顯示時能呈現正確的亮度層次。",
    imageDesc: "",
    scenario: "",
    hint: "與顯示設備的物理特性有關",
    items: []
  },
  {
    id: "color_009",
    category: "color",
    type: "single",
    difficulty: 1,
    question: "1D LUT 與 3D LUT 的主要差異是什麼？",
    options: [
      "1D LUT 只能處理灰階影像",
      "1D LUT 對每個通道獨立處理，3D LUT 可處理通道間的交互作用",
      "3D LUT 只能用於 HDR 內容",
      "1D LUT 比 3D LUT 更精確"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "1D LUT 對 R、G、B 各通道獨立做映射，無法處理通道間的耦合效應。3D LUT 以三維查找表的方式，能同時考慮三個通道的交互作用，表達更複雜的色彩轉換。",
    imageDesc: "",
    scenario: "",
    hint: "維度的差異對應著能處理的複雜度",
    items: []
  },
  {
    id: "color_010",
    category: "color",
    type: "truefalse",
    difficulty: 1,
    question: "CIE XYZ 色彩空間是一個與設備無關（device-independent）的色彩空間。",
    options: ["正確", "錯誤"],
    answer: true,
    acceptAlso: [],
    explanation: "CIE XYZ 是基於人眼色彩匹配函數定義的，不依賴任何特定設備，因此被稱為 device-independent 色彩空間，常作為不同色彩空間之間轉換的中介。",
    imageDesc: "",
    scenario: "",
    hint: "CIE 標準是基於人眼視覺實驗建立的",
    items: []
  },
  {
    id: "color_011",
    category: "color",
    type: "single",
    difficulty: 1,
    question: "在白平衡中，如果場景光源偏暖（低色溫），應該增加哪個通道的 gain？",
    options: ["Red", "Green", "Blue", "同時增加 R 和 G"],
    answer: 2,
    acceptAlso: [],
    explanation: "低色溫光源（如鎢絲燈）偏暖偏紅，影像中紅色成分偏多，需增加 Blue 通道的 gain 來補償，使白色物體回歸中性。",
    imageDesc: "",
    scenario: "",
    hint: "偏暖 = 偏紅，需要補償對面的顏色",
    items: []
  },
  {
    id: "color_012",
    category: "color",
    type: "single",
    difficulty: 1,
    question: "ΔE 在色彩科學中代表什麼？",
    options: [
      "色溫差異",
      "兩個顏色之間的感知差異（色差）",
      "動態範圍",
      "曝光補償值"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "ΔE（Delta E）量化兩個顏色之間的感知差異。ΔE < 1 通常被認為人眼無法分辨，ΔE > 5 則表示明顯的色差。",
    imageDesc: "",
    scenario: "",
    hint: "E 來自德文 Empfindung（感知）",
    items: []
  },
  {
    id: "color_013",
    category: "color",
    type: "fillblank",
    difficulty: 1,
    question: "Lab 色彩空間中，L 代表 Lightness，a 代表紅綠軸，b 代表 ______ 軸。",
    options: [],
    answer: "黃藍",
    acceptAlso: ["yellow-blue", "藍黃", "blue-yellow"],
    explanation: "在 CIE Lab 色彩空間中，L 是亮度，a 軸從綠到紅，b 軸從藍到黃。這種設計基於對立色理論（opponent color theory）。",
    imageDesc: "",
    scenario: "",
    hint: "與 a 軸的紅綠互補類似，b 軸也是一對互補色",
    items: []
  },
  {
    id: "color_014",
    category: "color",
    type: "single",
    difficulty: 1,
    question: "下列哪個不是常見的色彩空間？",
    options: ["YCbCr", "HSL", "RGB", "FFT"],
    answer: 3,
    acceptAlso: [],
    explanation: "FFT（Fast Fourier Transform）是頻域轉換技術，不是色彩空間。YCbCr、HSL、RGB 都是常見的色彩空間。",
    imageDesc: "",
    scenario: "",
    hint: "有一個選項屬於訊號處理領域",
    items: []
  },
  {
    id: "color_015",
    category: "color",
    type: "truefalse",
    difficulty: 1,
    question: "8-bit 影像每個通道可表示 256 個色階。",
    options: ["正確", "錯誤"],
    answer: true,
    acceptAlso: [],
    explanation: "8-bit 表示 2^8 = 256 個離散值（0–255），因此每個通道可表示 256 個色階。三通道 RGB 合計可表示約 1677 萬種顏色。",
    imageDesc: "",
    scenario: "",
    hint: "2 的 8 次方",
    items: []
  },
  {
    id: "color_016",
    category: "color",
    type: "single",
    difficulty: 1,
    question: "Color banding（色帶現象）最常見的成因是什麼？",
    options: [
      "鏡頭光學失真",
      "位元深度不足導致量化誤差",
      "白平衡設定錯誤",
      "感測器過熱"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "Color banding 是因為位元深度不足，使得平滑的色彩漸層被量化為有限的離散色階，產生明顯的階梯狀色帶。常見於 8-bit 影像的暗部漸層區域。",
    imageDesc: "",
    scenario: "",
    hint: "與數位化過程中的精度有關",
    items: []
  },
  {
    id: "color_017",
    category: "color",
    type: "single",
    difficulty: 1,
    question: "HSL 與 HSV 的主要差異在於哪個分量？",
    options: [
      "H（Hue）的定義不同",
      "S（Saturation）的定義不同",
      "第三個分量：L 是 Lightness，V 是 Value",
      "HSL 不支援透明度"
    ],
    answer: 2,
    acceptAlso: [],
    explanation: "HSL 使用 Lightness（亮度），L=0 為黑色，L=1 為白色，L=0.5 為純色。HSV 使用 Value（明度），V=0 為黑色，V=1 為最亮的該色。兩者的 S 定義也因此有所不同。",
    imageDesc: "",
    scenario: "",
    hint: "名稱中最後一個字母的差異",
    items: []
  },
  {
    id: "color_018",
    category: "color",
    type: "ordering",
    difficulty: 1,
    question: "請按照色域從小到大排列以下色彩空間：",
    options: ["BT.2020", "sRGB", "DCI-P3", "Adobe RGB"],
    answer: 0,
    acceptAlso: [],
    explanation: "色域大小排序：sRGB < Adobe RGB < DCI-P3 < BT.2020。sRGB 是最常見的標準色域，BT.2020 是目前定義的最大常用色域。",
    imageDesc: "",
    scenario: "",
    hint: "sRGB 是最小的，BT.2020 是最大的",
    items: ["sRGB", "Adobe RGB", "DCI-P3", "BT.2020"]
  },
  {
    id: "color_019",
    category: "color",
    type: "single",
    difficulty: 1,
    question: "Planckian locus（普朗克軌跡）在色度圖上代表什麼？",
    options: [
      "所有可見光的波長分佈",
      "黑體輻射體在不同溫度下的色度座標軌跡",
      "人眼可感知的色域邊界",
      "顯示器的色彩準確度範圍"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "Planckian locus 是黑體（理想輻射體）在不同色溫下的色度座標連線。自然光源和人工光源的色溫通常參考此軌跡來描述。",
    imageDesc: "",
    scenario: "",
    hint: "與黑體輻射和溫度有關",
    items: []
  },
  {
    id: "color_020",
    category: "color",
    type: "fillblank",
    difficulty: 1,
    question: "Tone mapping 的目的是將 ______ 動態範圍的影像映射到低動態範圍的顯示設備上。",
    options: [],
    answer: "高",
    acceptAlso: ["HDR", "high", "High"],
    explanation: "Tone mapping 是 HDR（High Dynamic Range）影像處理中的關鍵步驟，將高動態範圍的場景亮度壓縮到 LDR 顯示設備（如普通螢幕）可顯示的範圍內。",
    imageDesc: "",
    scenario: "",
    hint: "HDR → LDR 的過程",
    items: []
  },
  {
    id: "color_021",
    category: "color",
    type: "truefalse",
    difficulty: 1,
    question: "ICC Profile 是用來描述設備色彩特性的標準格式。",
    options: ["正確", "錯誤"],
    answer: true,
    acceptAlso: [],
    explanation: "ICC（International Color Consortium）Profile 是一種標準化的色彩描述檔，記錄設備（如螢幕、印表機、相機）的色彩特性，用於色彩管理系統進行準確的色彩轉換。",
    imageDesc: "",
    scenario: "",
    hint: "ICC 是一個國際組織制定的標準",
    items: []
  },
  {
    id: "color_022",
    category: "color",
    type: "single",
    difficulty: 1,
    question: "Color Rendering Index（CRI）用來評估什麼？",
    options: [
      "顯示器的色域覆蓋率",
      "光源還原物體真實顏色的能力",
      "影像壓縮的色彩保真度",
      "攝影鏡頭的色差表現"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "CRI（演色性指數）評估光源還原物體顏色的能力，最高為 100（與參考光源完全一致）。日光和白熾燈的 CRI 接近 100，而某些 LED 或螢光燈的 CRI 較低。",
    imageDesc: "",
    scenario: "",
    hint: "這是衡量光源品質的指標",
    items: []
  },
  {
    id: "color_023",
    category: "color",
    type: "single",
    difficulty: 1,
    question: "在色彩科學中，色彩通道間的 crosstalk 是指什麼？",
    options: [
      "不同畫素之間的干擾",
      "一個色彩通道的信號洩漏到其他通道",
      "顯示器的色彩偏移",
      "壓縮過程中的資料遺失"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "Color channel crosstalk 是指感測器中一個色彩通道（如 R）的光信號洩漏到相鄰通道（如 G 或 B），導致色彩不純。這在 CMOS 感測器中是常見問題，CCM 的功能之一就是校正此現象。",
    imageDesc: "",
    scenario: "",
    hint: "與感測器的物理結構有關",
    items: []
  },
  {
    id: "color_024",
    category: "color",
    type: "single",
    difficulty: 1,
    question: "下列哪個色溫代表典型的日光照明？",
    options: ["2700K", "4000K", "5500K", "9000K"],
    answer: 2,
    acceptAlso: [],
    explanation: "典型日光的色溫約為 5500K–6500K。2700K 偏暖（類似白熾燈），4000K 是中性白光，9000K 偏冷偏藍。",
    imageDesc: "",
    scenario: "",
    hint: "標準日光照明通常定義在 D55 或 D65",
    items: []
  },
  {
    id: "color_025",
    category: "color",
    type: "truefalse",
    difficulty: 1,
    question: "Gamma 值為 1.0 表示線性的輸入-輸出關係。",
    options: ["正確", "錯誤"],
    answer: true,
    acceptAlso: [],
    explanation: "Gamma 函數為 output = input^γ。當 γ = 1.0 時，output = input，即線性關係。γ > 1 會使暗部更暗（壓暗），γ < 1 會使暗部更亮（提亮）。",
    imageDesc: "",
    scenario: "",
    hint: "任何數的 1 次方等於它本身",
    items: []
  },
  {
    id: "color_026",
    category: "color",
    type: "image",
    difficulty: 1,
    question: "觀察下圖：一張照片整體偏藍，這最可能是什麼問題？",
    options: [
      "白平衡設定在低色溫模式下拍攝高色溫場景",
      "Gamma 值設定過高",
      "色彩飽和度過度增強",
      "感測器 defective pixel"
    ],
    answer: 0,
    acceptAlso: [],
    explanation: "如果相機的白平衡設定為低色溫（如鎢絲燈模式 ~3000K），但實際場景為高色溫光源（如陰天 ~7000K），相機會過度補償藍色，導致影像整體偏藍。",
    imageDesc: "一張戶外風景照片，整體色調嚴重偏藍，草地和建築物都帶有明顯的藍色色偏",
    scenario: "",
    hint: "白平衡設定與實際光源不匹配",
    items: []
  },
  {
    id: "color_027",
    category: "color",
    type: "single",
    difficulty: 1,
    question: "False color artifact 在 ISP 中通常指什麼現象？",
    options: [
      "高頻紋理區域出現不正確的色彩圖案",
      "影像整體偏色",
      "色彩飽和度不足",
      "黑白影像中出現彩色雜訊"
    ],
    answer: 0,
    acceptAlso: [],
    explanation: "False color 是 demosaic 過程中常見的偽影，在高頻細節區域（如細線條、織物紋理），由於色彩插值錯誤而產生不存在於原始場景中的色彩圖案。",
    imageDesc: "",
    scenario: "",
    hint: "與 Bayer 陣列的 demosaic 過程有關",
    items: []
  },
  {
    id: "color_028",
    category: "color",
    type: "ordering",
    difficulty: 1,
    question: "請按照 ISP 中色彩處理的典型順序排列以下步驟：",
    options: ["Tone mapping", "White balance", "Gamma correction", "Color correction (CCM)"],
    answer: 0,
    acceptAlso: [],
    explanation: "典型 ISP 色彩管線順序：先做白平衡（消除光源色偏），然後 CCM 色彩校正（轉到標準色彩空間），接著 gamma correction（線性到非線性轉換），最後 tone mapping（動態範圍壓縮）。",
    imageDesc: "",
    scenario: "",
    hint: "白平衡需要在線性域進行，gamma 在最後階段",
    items: ["White balance", "Color correction (CCM)", "Gamma correction", "Tone mapping"]
  },
  {
    id: "color_029",
    category: "color",
    type: "single",
    difficulty: 1,
    question: "Saturation（飽和度）為 0 的影像看起來會是什麼樣子？",
    options: [
      "全黑影像",
      "全白影像",
      "灰階影像",
      "色彩反轉影像"
    ],
    answer: 2,
    acceptAlso: [],
    explanation: "飽和度為 0 表示完全沒有色彩資訊，只保留亮度資訊，因此影像呈現為灰階（黑白）。飽和度越高，色彩越鮮豔。",
    imageDesc: "",
    scenario: "",
    hint: "沒有色彩 = 只有黑白灰",
    items: []
  },
  {
    id: "color_030",
    category: "color",
    type: "single",
    difficulty: 1,
    question: "YCbCr 中的 Cb 和 Cr 分別代表什麼？",
    options: [
      "藍色差值分量和紅色差值分量",
      "亮度的高頻和低頻分量",
      "色相和飽和度",
      "對比度和清晰度"
    ],
    answer: 0,
    acceptAlso: [],
    explanation: "Cb = Blue difference chroma（藍色差值色度），Cr = Red difference chroma（紅色差值色度）。它們分別表示藍色和紅色相對於亮度 Y 的偏差。",
    imageDesc: "",
    scenario: "",
    hint: "b = blue, r = red",
    items: []
  },
  {
    id: "color_031",
    category: "color",
    type: "fillblank",
    difficulty: 1,
    question: "Power law gamma correction 的數學公式為 V_out = V_in^______，其中空格處填入的參數名稱是？",
    options: [],
    answer: "γ",
    acceptAlso: ["gamma", "Gamma", "γ值"],
    explanation: "Power law gamma correction 的公式為 V_out = V_in^γ，其中 γ（gamma）是控制曲線彎曲程度的指數參數。γ < 1 提亮暗部，γ > 1 壓暗暗部。",
    imageDesc: "",
    scenario: "",
    hint: "這個參數就是此技術名稱的由來",
    items: []
  },
  {
    id: "color_032",
    category: "color",
    type: "truefalse",
    difficulty: 1,
    question: "DCI-P3 色域主要用於數位電影投影標準。",
    options: ["正確", "錯誤"],
    answer: true,
    acceptAlso: [],
    explanation: "DCI-P3 由 Digital Cinema Initiatives 定義，是數位電影放映的色域標準，比 sRGB 寬約 25%，特別在紅色和綠色區域有更大的覆蓋。現在也廣泛用於高階顯示器和行動裝置。",
    imageDesc: "",
    scenario: "",
    hint: "DCI = Digital Cinema Initiatives",
    items: []
  },
  {
    id: "color_033",
    category: "color",
    type: "single",
    difficulty: 1,
    question: "在進行 hue rotation（色相旋轉）時，將色相旋轉 180° 會產生什麼效果？",
    options: [
      "影像變為灰階",
      "所有顏色變為其互補色",
      "影像亮度反轉",
      "飽和度加倍"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "色相環是 360° 的圓，旋轉 180° 剛好到達互補色的位置。例如紅色（0°）會變為青色（180°），藍色（240°）會變為黃色（60°）。",
    imageDesc: "",
    scenario: "",
    hint: "在色相環上，互補色相隔 180°",
    items: []
  },

  // ===== DIFFICULTY 2 (中階) — 34 questions =====
  {
    id: "color_034",
    category: "color",
    type: "single",
    difficulty: 2,
    question: "CCM 校正時，通常使用什麼工具來獲取參考色彩數據？",
    options: [
      "灰卡（18% Gray Card）",
      "色彩檢查卡（如 Macbeth ColorChecker）",
      "測光表",
      "直方圖分析"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "Macbeth ColorChecker（X-Rite ColorChecker）包含 24 個標準色塊，涵蓋自然色、灰階和原色。通過比較感測器捕獲值與已知標準值，可以計算最佳 CCM 矩陣。",
    imageDesc: "",
    scenario: "",
    hint: "需要已知標準色彩值的參考物",
    items: []
  },
  {
    id: "color_035",
    category: "color",
    type: "scenario",
    difficulty: 2,
    question: "你正在為一款手機相機調校 ISP。測試發現在日光下拍攝 ColorChecker 時，綠色色塊的 ΔE2000 達到 8.5，遠超標準。最可能的優先解決方案是什麼？",
    options: [
      "增加影像銳化強度",
      "重新校正 CCM 矩陣",
      "調高 ISO 感光度",
      "更換鏡頭模組"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "ΔE2000 = 8.5 表示明顯的色差問題。綠色色塊偏差大通常與 CCM 矩陣校正不夠精確有關，需要使用更多校正樣本重新計算 CCM 矩陣，尤其要關注綠色通道的映射。",
    imageDesc: "",
    scenario: "手機相機 ISP 調校過程中發現色彩準確度問題",
    hint: "色彩準確度問題通常與色彩校正矩陣有關",
    items: []
  },
  {
    id: "color_036",
    category: "color",
    type: "single",
    difficulty: 2,
    question: "Von Kries chromatic adaptation model 的核心假設是什麼？",
    options: [
      "人眼的三種錐狀細胞獨立適應光源變化",
      "所有顏色在不同光源下感知相同",
      "色彩適應僅發生在大腦視覺皮層",
      "適應速度與光源亮度成反比"
    ],
    answer: 0,
    acceptAlso: [],
    explanation: "Von Kries adaptation 假設人眼的 L、M、S 三種錐狀細胞各自獨立地調整增益來適應光源變化。數學上表現為在 LMS 空間中對各通道施加獨立的縮放係數。",
    imageDesc: "",
    scenario: "",
    hint: "Von Kries 模型的核心是 gain control",
    items: []
  },
  {
    id: "color_037",
    category: "color",
    type: "single",
    difficulty: 2,
    question: "Bradford transform 相比 Von Kries 的改進之處在於：",
    options: [
      "使用更精確的黑體輻射模型",
      "引入了修正的 LMS-like 空間（稱為 sharpened cone-like space）",
      "不需要白點資訊",
      "計算速度更快"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "Bradford transform 使用一個特殊的「sharpened」錐狀細胞響應空間，而非直接使用 LMS 空間。這種修正的空間在色彩適應計算中提供更好的預測準確度，特別是在大色溫差異下。",
    imageDesc: "",
    scenario: "",
    hint: "Bradford 使用了不同的色彩適應空間",
    items: []
  },
  {
    id: "color_038",
    category: "color",
    type: "multiple",
    difficulty: 2,
    question: "下列哪些是 Global tone mapping 演算法？（選兩個）",
    options: [
      "Reinhard global operator",
      "Bilateral filter-based tone mapping",
      "簡單的 gamma 壓縮",
      "Durand local tone mapping"
    ],
    answer: [0, 2],
    acceptAlso: [],
    explanation: "Global tone mapping 對整張影像套用相同的映射函數。Reinhard global operator 和 gamma 壓縮都是全域方法。Bilateral filter-based 和 Durand 方法是 local tone mapping，會根據像素鄰域資訊做局部調整。",
    imageDesc: "",
    scenario: "",
    hint: "Global = 所有像素使用相同的映射曲線",
    items: []
  },
  {
    id: "color_039",
    category: "color",
    type: "single",
    difficulty: 2,
    question: "Reinhard tone mapping operator 的基本公式 L_d = L / (1 + L) 的特性是什麼？",
    options: [
      "線性映射，不改變對比度",
      "將 [0, ∞) 的亮度壓縮到 [0, 1) 範圍",
      "只壓縮高亮度區域，暗部不變",
      "產生 S 型曲線特性"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "Reinhard 基本公式 L_d = L/(1+L) 是一個漸近函數，當 L→∞ 時 L_d→1，當 L=0 時 L_d=0，因此能將任意非負亮度值壓縮到 [0,1) 範圍內，且低亮度區近似線性。",
    imageDesc: "",
    scenario: "",
    hint: "分析 L 趨近無窮大時公式的極限值",
    items: []
  },
  {
    id: "color_040",
    category: "color",
    type: "single",
    difficulty: 2,
    question: "ACES（Academy Color Encoding System）tone mapping 的主要優勢是什麼？",
    options: [
      "計算量極小，適合即時處理",
      "提供從場景參考到顯示參考的完整色彩管理流程",
      "不需要任何色彩空間轉換",
      "只適用於 sRGB 色域"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "ACES 提供了一套完整的色彩管理框架，從 IDT（Input Device Transform）到 RRT（Reference Rendering Transform）再到 ODT（Output Device Transform），確保從攝影到顯示的全流程色彩一致性。",
    imageDesc: "",
    scenario: "",
    hint: "ACES 是電影工業的標準色彩管理系統",
    items: []
  },
  {
    id: "color_041",
    category: "color",
    type: "fillblank",
    difficulty: 2,
    question: "ΔE2000 公式在 ΔE*ab（CIE76）的基礎上，額外加入了 ______、色度和色相的加權修正因子。",
    options: [],
    answer: "亮度",
    acceptAlso: ["lightness", "Lightness", "L", "明度"],
    explanation: "ΔE2000 對 CIE76 的改進包括：亮度加權（S_L）、色度加權（S_C）、色相加權（S_H）以及色度-色相交互項（R_T），使得色差計算更符合人眼的實際感知。",
    imageDesc: "",
    scenario: "",
    hint: "ΔE2000 考慮了 L、C、H 三個維度的感知差異",
    items: []
  },
  {
    id: "color_042",
    category: "color",
    type: "single",
    difficulty: 2,
    question: "在 RGB 到 YCbCr 轉換中（BT.601 標準），Y 的計算公式中 R、G、B 的權重大小順序是？",
    options: [
      "R > G > B",
      "G > R > B",
      "B > G > R",
      "R = G = B"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "BT.601 中 Y = 0.299R + 0.587G + 0.114B，權重 G(0.587) > R(0.299) > B(0.114)。這反映了人眼對綠色最敏感、對藍色最不敏感的特性。",
    imageDesc: "",
    scenario: "",
    hint: "人眼對綠色的敏感度最高",
    items: []
  },
  {
    id: "color_043",
    category: "color",
    type: "scenario",
    difficulty: 2,
    question: "你在調試一個 ISP pipeline，發現在 CCM 之後的影像出現了嚴重的亮部裁切（highlight clipping）。可能的原因是什麼？",
    options: [
      "CCM 矩陣的列元素之和大於 1，導致亮部增益過大",
      "白平衡 gain 設定太低",
      "Demosaic 演算法有 bug",
      "感測器的黑電平校正不正確"
    ],
    answer: 0,
    acceptAlso: [],
    explanation: "當 CCM 矩陣某一列的元素之和顯著大於 1 時，已經接近飽和的亮部像素會被進一步放大而溢出，造成 highlight clipping。設計 CCM 時需注意保持列和接近 1 或加入 clipping 保護機制。",
    imageDesc: "",
    scenario: "ISP pipeline 調試中遇到亮部裁切問題",
    hint: "CCM 是乘法運算，考慮矩陣元素和的影響",
    items: []
  },
  {
    id: "color_044",
    category: "color",
    type: "multiple",
    difficulty: 2,
    question: "下列哪些因素會影響 3D LUT 的精度？（選三個）",
    options: [
      "LUT 的網格點數量",
      "插值方法（三線性 vs 四面體）",
      "輸入資料的位元深度",
      "顯示器的更新頻率"
    ],
    answer: [0, 1, 2],
    acceptAlso: [],
    explanation: "3D LUT 精度取決於：(1) 網格點數量——更多節點提供更精細的色彩映射；(2) 插值方法——四面體插值通常比三線性更精確；(3) 輸入位元深度——影響地址精度。顯示器更新頻率與 LUT 精度無關。",
    imageDesc: "",
    scenario: "",
    hint: "顯示器的刷新率與色彩映射的精度無關",
    items: []
  },
  {
    id: "color_045",
    category: "color",
    type: "single",
    difficulty: 2,
    question: "在 ISP 中，為什麼白平衡通常需要在 gamma correction 之前執行？",
    options: [
      "白平衡後影像更適合壓縮",
      "白平衡是線性運算，需要在線性域中進行才能保持準確性",
      "Gamma correction 會破壞白平衡的參數",
      "硬體限制要求此順序"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "白平衡是對 R/G/B 通道施加線性增益（乘法），在線性域中進行才能正確反映光源的物理特性。若在 gamma 域操作，非線性的映射會導致色彩補償不準確。",
    imageDesc: "",
    scenario: "",
    hint: "線性運算要在線性域中執行",
    items: []
  },
  {
    id: "color_046",
    category: "color",
    type: "single",
    difficulty: 2,
    question: "Local tone mapping 相比 Global tone mapping 的主要優勢是？",
    options: [
      "計算量更小",
      "更能保留局部對比度和細節",
      "不會產生 halo artifact",
      "色彩還原更準確"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "Local tone mapping 根據像素鄰域的亮度資訊來調整映射，能更好地保留暗部和亮部的局部對比度和細節。但缺點是可能產生 halo artifact，且計算量較大。",
    imageDesc: "",
    scenario: "",
    hint: "局部方法能自適應不同區域的亮度分佈",
    items: []
  },
  {
    id: "color_047",
    category: "color",
    type: "single",
    difficulty: 2,
    question: "sRGB gamma curve 的線性段（low-end linear portion）的分界點約在什麼值？",
    options: ["0.0031308", "0.04045", "0.055", "0.5"],
    answer: 0,
    acceptAlso: [],
    explanation: "sRGB 的 transfer function 定義：當線性值 ≤ 0.0031308 時使用線性映射（乘以 12.92），大於此值時使用 1.055 × V^(1/2.4) - 0.055 的指數映射。0.04045 是對應的 sRGB 編碼值。",
    imageDesc: "",
    scenario: "",
    hint: "這是線性域（scene-referred）的門檻值",
    items: []
  },
  {
    id: "color_048",
    category: "color",
    type: "truefalse",
    difficulty: 2,
    question: "3×3 CCM 矩陣可以完美處理非線性的色彩轉換。",
    options: ["正確", "錯誤"],
    answer: false,
    acceptAlso: [],
    explanation: "3×3 矩陣只能進行線性變換。實際的感測器到標準色彩空間的映射往往包含非線性成分，因此 3×3 CCM 只是近似，無法完美處理。要處理非線性部分，需要結合 LUT 或高階多項式校正。",
    imageDesc: "",
    scenario: "",
    hint: "矩陣乘法本質上是線性運算",
    items: []
  },
  {
    id: "color_049",
    category: "color",
    type: "single",
    difficulty: 2,
    question: "計算最優 CCM 時，常用的最小化目標函數是什麼？",
    options: [
      "最小化 RGB 值的均方誤差",
      "最小化 ΔE（色差）的平均值或加權和",
      "最大化 SNR",
      "最小化矩陣的行列式"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "最優 CCM 應該最小化校正後色彩與參考色彩之間的感知色差（ΔE）。雖然直接最小化 RGB MSE 更容易計算，但 ΔE 更能反映人眼的感知，因此更常作為最終評估和優化目標。",
    imageDesc: "",
    scenario: "",
    hint: "目標是讓人眼感知到最準確的色彩",
    items: []
  },
  {
    id: "color_050",
    category: "color",
    type: "ordering",
    difficulty: 2,
    question: "將 RGB 值轉換為 Lab 值的正確步驟順序是：",
    options: ["RGB → Lab（直接轉換）", "Lab → XYZ → RGB", "RGB → XYZ → Lab", "RGB → HSV → Lab"],
    answer: 0,
    acceptAlso: [],
    explanation: "RGB 到 Lab 的轉換需要經過 XYZ 作為中間色彩空間：先將 RGB（去除 gamma 後）通過矩陣轉換到 CIE XYZ，再從 XYZ 通過非線性轉換到 Lab。不能直接從 RGB 轉到 Lab。",
    imageDesc: "",
    scenario: "",
    hint: "XYZ 是 device-independent 的中間色彩空間",
    items: ["去除 gamma（linearize RGB）", "RGB 矩陣轉換到 XYZ", "XYZ 歸一化（除以白點）", "非線性函數轉換到 Lab"]
  },
  {
    id: "color_051",
    category: "color",
    type: "single",
    difficulty: 2,
    question: "在 3D LUT 中，常用的四面體插值（tetrahedral interpolation）相比三線性插值的優勢是？",
    options: [
      "記憶體使用量更少",
      "連續性更好且色彩過渡更平滑",
      "計算速度更快",
      "不需要浮點運算"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "四面體插值將立方體分為 5 或 6 個四面體，在每個四面體內部使用重心座標進行插值。相比三線性插值，它具有更好的連續性（C0），色彩過渡更平滑，且計算複雜度相當。",
    imageDesc: "",
    scenario: "",
    hint: "插值的平滑度是關鍵考量",
    items: []
  },
  {
    id: "color_052",
    category: "color",
    type: "image",
    difficulty: 2,
    question: "觀察下圖中的色彩漸層：從深藍到淺藍的過渡中出現了明顯的階梯狀色帶。這是什麼問題，如何改善？",
    options: [
      "Moiré pattern，需要加入 optical low-pass filter",
      "Color banding，可透過增加位元深度或加入 dithering 改善",
      "Chromatic aberration，需要校正鏡頭色差",
      "Sensor blooming，需要降低曝光"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "色彩漸層中的階梯狀色帶是典型的 color banding（posterization），由量化精度不足造成。解決方案包括：使用更高位元深度（如 10-bit 或 12-bit）、加入 dithering（抖動）來打破視覺上的色帶效果。",
    imageDesc: "一個從深藍到淺藍的色彩漸層影像，其中可見約 8-10 條明顯的色階分界線，過渡不平滑",
    scenario: "",
    hint: "這與量化精度和顯示位元深度有關",
    items: []
  },
  {
    id: "color_053",
    category: "color",
    type: "single",
    difficulty: 2,
    question: "10-bit 色深相比 8-bit 色深，每通道可表示的色階數量增加了多少倍？",
    options: ["2 倍", "4 倍", "8 倍", "10 倍"],
    answer: 1,
    acceptAlso: [],
    explanation: "8-bit = 2^8 = 256 色階，10-bit = 2^10 = 1024 色階。1024 / 256 = 4 倍。這額外的精度能大幅減少 color banding，特別是在暗部漸層區域。",
    imageDesc: "",
    scenario: "",
    hint: "比較 2^10 和 2^8",
    items: []
  },
  {
    id: "color_054",
    category: "color",
    type: "single",
    difficulty: 2,
    question: "色彩飽和度增強時，如果對所有像素施加相同的增益，最容易出現什麼問題？",
    options: [
      "暗部雜訊增加",
      "已高飽和的顏色溢出（gamut clipping）",
      "白平衡偏移",
      "解析度下降"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "統一增強飽和度時，原本已接近色域邊界的高飽和顏色會被推出可表示範圍，造成 gamut clipping。正確做法是使用自適應飽和度調整，對已飽和的顏色施加較小增益。",
    imageDesc: "",
    scenario: "",
    hint: "接近極限的值被進一步推大會怎樣？",
    items: []
  },
  {
    id: "color_055",
    category: "color",
    type: "multiple",
    difficulty: 2,
    question: "下列哪些是 chromatic adaptation transform（CAT）的應用場景？（選兩個）",
    options: [
      "不同光源下的白平衡轉換",
      "影像降噪",
      "將影像從一個標準照明體（如 D50）轉換到另一個（如 D65）",
      "鏡頭畸變校正"
    ],
    answer: [0, 2],
    acceptAlso: [],
    explanation: "CAT 模擬人眼在不同光源下的色彩適應過程，主要用於：(1) 白平衡——消除不同光源的色偏；(2) 標準照明體之間的轉換——例如 ICC 色彩管理中從 D50 轉換到 D65。",
    imageDesc: "",
    scenario: "",
    hint: "CAT 處理的是光源變化帶來的色彩偏移",
    items: []
  },
  {
    id: "color_056",
    category: "color",
    type: "single",
    difficulty: 2,
    question: "在 ISP pipeline 中，auto white balance（AWB）演算法常用的「灰世界假說」是什麼？",
    options: [
      "場景中的最亮點是白色",
      "場景中所有像素的平均色彩為中性灰",
      "場景中灰色物體的比例超過 50%",
      "感測器的暗電流是灰色的"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "灰世界假說（Gray World Assumption）假設場景中所有像素的平均色彩為中性灰（R_avg ≈ G_avg ≈ B_avg）。據此可計算白平衡增益。此假設在色彩豐富的自然場景中通常成立，但在單色主導的場景會失效。",
    imageDesc: "",
    scenario: "",
    hint: "假設整張影像的平均顏色",
    items: []
  },
  {
    id: "color_057",
    category: "color",
    type: "single",
    difficulty: 2,
    question: "為什麼 ISP 中的色彩管線順序很重要？",
    options: [
      "僅為了硬體佈局方便",
      "因為某些操作是非線性的，在不同域中執行會產生不同結果",
      "順序不影響結果，只是業界慣例",
      "僅為了減少記憶體頻寬"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "ISP pipeline 中包含線性和非線性操作。例如白平衡和 CCM 是線性操作，需在線性域執行；gamma correction 是非線性轉換。如果在 gamma 域執行線性操作，數學上不等價，會產生錯誤的色彩結果。",
    imageDesc: "",
    scenario: "",
    hint: "線性域和非線性域中的運算結果不同",
    items: []
  },
  {
    id: "color_058",
    category: "color",
    type: "truefalse",
    difficulty: 2,
    question: "Adobe RGB 的色域完全包含 DCI-P3 的色域。",
    options: ["正確", "錯誤"],
    answer: false,
    acceptAlso: [],
    explanation: "Adobe RGB 和 DCI-P3 的色域存在交叉：Adobe RGB 在青綠色區域較大，DCI-P3 在紅色區域較大。兩者並非包含關係，各有對方未覆蓋的部分。",
    imageDesc: "",
    scenario: "",
    hint: "兩個色域在色度圖上的三角形形狀不同",
    items: []
  },
  {
    id: "color_059",
    category: "color",
    type: "single",
    difficulty: 2,
    question: "在進行 CCM 優化時，使用最小二乘法（Least Squares）直接在 RGB 空間最小化誤差有什麼缺點？",
    options: [
      "計算太慢",
      "RGB 空間不是感知均勻的，優化結果不一定在視覺上最佳",
      "最小二乘法無法處理 3×3 矩陣",
      "需要太多校正色塊"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "RGB 空間不是感知均勻的——相同的 RGB 數值差異在不同色彩區域會對應不同的視覺感知差異。在 RGB 空間做 least squares 可能在感知上不重要的區域過度優化，而忽略人眼敏感的區域。",
    imageDesc: "",
    scenario: "",
    hint: "人眼對色彩差異的感知是非均勻的",
    items: []
  },
  {
    id: "color_060",
    category: "color",
    type: "single",
    difficulty: 2,
    question: "ICC profile 中的 rendering intent「Perceptual」的特點是什麼？",
    options: [
      "超出目標色域的顏色被裁切到最近的邊界",
      "壓縮整個來源色域以適配目標色域，保持色彩間的相對關係",
      "僅轉換色域內的顏色，超出的顏色保持不變",
      "只處理灰階部分"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "Perceptual rendering intent 會壓縮整個來源色域的色彩映射到目標色域中，保持色彩間的相對關係和整體視覺印象。適合色域差異較大的轉換（如印刷），但所有顏色都會被偏移。",
    imageDesc: "",
    scenario: "",
    hint: "「感知」重在維持整體色彩的和諧感",
    items: []
  },
  {
    id: "color_061",
    category: "color",
    type: "fillblank",
    difficulty: 2,
    question: "BT.709 定義的 RGB 到 Y 的轉換中，Green 的權重約為 ______。",
    options: [],
    answer: "0.7152",
    acceptAlso: ["0.715", "0.72"],
    explanation: "BT.709 定義 Y = 0.2126R + 0.7152G + 0.0722B。Green 的權重高達 0.7152，反映人眼對綠色光的高敏感度。注意這與 BT.601（Y = 0.299R + 0.587G + 0.114B）的係數不同。",
    imageDesc: "",
    scenario: "",
    hint: "BT.709 是 HDTV 的標準，Green 權重比 BT.601 更高",
    items: []
  },
  {
    id: "color_062",
    category: "color",
    type: "single",
    difficulty: 2,
    question: "Auto tone 演算法中的直方圖均衡化（Histogram Equalization）的原理是什麼？",
    options: [
      "使所有像素的亮度相同",
      "使影像的亮度直方圖趨於均勻分佈",
      "只增強暗部的對比度",
      "自動調整色溫"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "直方圖均衡化透過累積分佈函數（CDF）重新映射像素亮度值，使輸出影像的亮度直方圖趨於均勻分佈，從而增強整體對比度。在醫學影像和監控影像中特別常用。",
    imageDesc: "",
    scenario: "",
    hint: "目標是讓各亮度級別被均勻利用",
    items: []
  },
  {
    id: "color_063",
    category: "color",
    type: "single",
    difficulty: 2,
    question: "3D LUT 的大小為 33×33×33，每個節點存儲 RGB 三個 16-bit 值，該 LUT 需要多少記憶體？",
    options: ["約 108 KB", "約 216 KB", "約 432 KB", "約 864 KB"],
    answer: 1,
    acceptAlso: [],
    explanation: "33×33×33 = 35937 個節點，每個節點 3 通道 × 2 bytes = 6 bytes。總計 35937 × 6 = 215622 bytes ≈ 216 KB。",
    imageDesc: "",
    scenario: "",
    hint: "計算：節點數 × 通道數 × 每通道位元組數",
    items: []
  },
  {
    id: "color_064",
    category: "color",
    type: "scenario",
    difficulty: 2,
    question: "在戶外監控場景中，你發現白天和晚上的色彩表現差異很大。白天正常但夜間 LED 照明下嚴重偏色。如何解決？",
    options: [
      "使用固定的白平衡參數",
      "根據偵測到的光源色溫自動切換不同的 CCM 和白平衡參數集",
      "關閉夜間的色彩處理",
      "增加感測器的曝光時間"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "不同光源（日光 vs LED）有不同的光譜特性，單一 CCM 和白平衡設定難以兼顧。正確做法是根據偵測到的光源類型或色溫，自動切換預先校正好的多組 CCM + 白平衡參數，甚至可以在參數集之間做插值。",
    imageDesc: "",
    scenario: "戶外監控攝影機在不同光源下的色彩校正問題",
    hint: "不同光源需要不同的校正參數",
    items: []
  },
  {
    id: "color_065",
    category: "color",
    type: "truefalse",
    difficulty: 2,
    question: "在 ISP 中使用 1D LUT 做 gamma correction 比直接用數學公式計算更節省硬體資源。",
    options: ["正確", "錯誤"],
    answer: true,
    acceptAlso: [],
    explanation: "Power function 的硬體實現需要浮點運算或複雜的定點近似。使用 1D LUT 只需要一次查表操作（加上可能的插值），在硬體上更高效且可靈活配置不同的 gamma 曲線。",
    imageDesc: "",
    scenario: "",
    hint: "查表比計算指數函數簡單得多",
    items: []
  },
  {
    id: "color_066",
    category: "color",
    type: "single",
    difficulty: 2,
    question: "在色彩空間轉換中，從寬色域（如 BT.2020）映射到窄色域（如 sRGB）時，最常見的問題是？",
    options: [
      "影像變得模糊",
      "色域外的顏色被裁切，導致飽和色彩細節遺失",
      "亮度增加",
      "解析度降低"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "從寬色域映射到窄色域時，超出目標色域的顏色必須被處理——簡單裁切（clipping）會導致高飽和度區域的色彩細節遺失。更好的方法是使用 gamut mapping 演算法來壓縮色域。",
    imageDesc: "",
    scenario: "",
    hint: "寬色域中有些顏色在窄色域中不存在",
    items: []
  },
  {
    id: "color_067",
    category: "color",
    type: "single",
    difficulty: 2,
    question: "在 CCM 矩陣設計中，為什麼通常要確保矩陣的每一列之和接近 1？",
    options: [
      "為了使矩陣可逆",
      "為了保持白色（R=G=B）的中性——白點不偏色",
      "為了使行列式等於 1",
      "為了使矩陣正定"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "當每列之和為 1 時，輸入為白色（1,1,1）時輸出仍為（1,1,1），確保白點不會因 CCM 而偏色。實際上這個約束可以稍微放寬，但偏離太多會導致白點偏移和亮部色偏問題。",
    imageDesc: "",
    scenario: "",
    hint: "白色意味著 R=G=B，經過矩陣後也應該保持",
    items: []
  },

  // ===== DIFFICULTY 3 (進階) — 33 questions =====
  {
    id: "color_068",
    category: "color",
    type: "single",
    difficulty: 3,
    question: "在設計多光源 CCM 系統時，如果需要在兩個色溫（如 2856K 和 6504K）的 CCM 之間做插值，最佳的插值方式是？",
    options: [
      "直接對兩個 3×3 矩陣的元素做線性插值",
      "在 1/色溫（mired）空間中做線性插值",
      "在對數色溫空間中做指數插值",
      "不做插值，選擇最接近的 CCM"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "Mired（micro reciprocal degree = 10^6 / T）空間中，人眼對色溫變化的感知更均勻。在 mired 空間做線性插值比在色溫空間直接插值更能產生感知上均勻的過渡，且 CCM 元素在 mired 空間中的變化更趨線性。",
    imageDesc: "",
    scenario: "",
    hint: "人眼對色溫的感知不是線性的",
    items: []
  },
  {
    id: "color_069",
    category: "color",
    type: "scenario",
    difficulty: 3,
    question: "你在開發一款高階相機的 ISP。色彩管線順序為：BLC → WB → Demosaic → CCM → Gamma → 3D LUT。QA 報告說某些飽和的紅色場景出現色彩斷裂。經分析，CCM 後某些像素值變為負數。最佳解決方案是什麼？",
    options: [
      "在 CCM 後加入 clamp(0, max) 將負值截斷為 0",
      "在 CCM 後使用 soft clipping 函數平滑處理負值區域",
      "修改 CCM 使所有元素為正",
      "移除 CCM 模組"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "硬性 clamp 會造成色彩斷裂——負值突然變為 0 產生不連續。使所有 CCM 元素為正會嚴重限制校正能力（CCM 的負元素用於消除通道 crosstalk）。最佳方案是 soft clipping：在接近 0 的區域用平滑曲線過渡，既避免負值又保持色彩連續性。",
    imageDesc: "",
    scenario: "高階相機 ISP 中 CCM 產生負值導致色彩斷裂",
    hint: "突然截斷會造成不連續，需要平滑過渡",
    items: []
  },
  {
    id: "color_070",
    category: "color",
    type: "single",
    difficulty: 3,
    question: "在 ΔE2000 公式中，旋轉項 R_T 的作用是什麼？",
    options: [
      "補償亮度適應效應",
      "校正藍色區域中色度和色相之間的交互影響",
      "使公式適用於 HDR 影像",
      "補償觀察者的年齡差異"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "R_T（旋轉項）專門處理 CIE Lab 空間中藍色區域（色相角約 275°）的特殊問題——在該區域，色度差和色相差之間存在耦合效應，R_T 通過旋轉校正來改善藍色區域的色差預測準確度。",
    imageDesc: "",
    scenario: "",
    hint: "Lab 空間中藍色區域有已知的非均勻性問題",
    items: []
  },
  {
    id: "color_071",
    category: "color",
    type: "multiple",
    difficulty: 3,
    question: "在設計 ISP 的色彩管線時，下列哪些操作必須在線性域（gamma 前）執行才能確保數學正確性？（選三個）",
    options: [
      "White balance gain 應用",
      "3×3 CCM 矩陣乘法",
      "色彩飽和度文字標註（OSD overlay）",
      "Lens shading correction（鏡頭暗角校正）"
    ],
    answer: [0, 1, 3],
    acceptAlso: [],
    explanation: "白平衡、CCM 和鏡頭暗角校正都是線性操作（乘法/加權和），在線性域中執行才能正確反映物理光學特性。在 gamma 域執行這些操作會因非線性導致結果錯誤。OSD overlay 是圖形疊加，與色彩域無關。",
    imageDesc: "",
    scenario: "",
    hint: "哪些操作本質上是線性數學運算？",
    items: []
  },
  {
    id: "color_072",
    category: "color",
    type: "single",
    difficulty: 3,
    question: "在 CCM 優化中使用帶約束的最小二乘法時，常見的約束條件「行和為 1」（row sum = 1）的物理意義是什麼？",
    options: [
      "保持影像總能量守恆",
      "確保中性灰（R=G=B 的輸入）不會產生色偏",
      "使矩陣行列式為正",
      "保證矩陣的特徵值均為實數"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "當 CCM 的每一行之和為 1 時，對於 R=G=B 的中性灰輸入，每個輸出通道的值等於輸入值乘以行和（=1），因此輸出仍為中性灰。這確保了灰階不會產生色偏，是色彩校正中的重要約束。",
    imageDesc: "",
    scenario: "",
    hint: "代入 R=G=B=k 到矩陣公式中看結果",
    items: []
  },
  {
    id: "color_073",
    category: "color",
    type: "single",
    difficulty: 3,
    question: "ACES 系統中的 AP0 色彩空間有什麼特殊之處？",
    options: [
      "與 sRGB 完全相同",
      "其原色點（primaries）包圍了整個 CIE 可見光光譜軌跡",
      "只定義了紅色和藍色的原色",
      "使用非線性編碼"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "ACES AP0（ACES 2065-1）的原色點被設計為完全包圍 CIE 可見光光譜軌跡，因此可以表示所有人眼可見的顏色。這使其成為理想的交換色彩空間（interchange color space），不會在任何轉換中丟失色彩資訊。",
    imageDesc: "",
    scenario: "",
    hint: "AP0 被設計為能容納所有可見色彩",
    items: []
  },
  {
    id: "color_074",
    category: "color",
    type: "fillblank",
    difficulty: 3,
    question: "在 Bradford chromatic adaptation transform 中，從光源 A 的白點適應到光源 B 的白點，核心運算為 M_adapt = M × diag(ρB/ρA, γB/γA, βB/βA) × M^(-1)，其中 M 代表從 XYZ 到 ______ 空間的轉換矩陣。",
    options: [],
    answer: "Bradford cone-like",
    acceptAlso: ["Bradford", "cone-like", "sharpened cone", "LMS-like"],
    explanation: "Bradford transform 使用一個特定的「sharpened cone-like」空間（不是標準 LMS），M 矩陣將 XYZ 轉到這個修正的錐狀細胞響應空間。在此空間中對各通道做獨立的增益調整後再轉回 XYZ。",
    imageDesc: "",
    scenario: "",
    hint: "Bradford 使用了修正過的錐狀細胞響應空間",
    items: []
  },
  {
    id: "color_075",
    category: "color",
    type: "single",
    difficulty: 3,
    question: "在 ISP 中使用多組 CCM（針對不同色溫）時，如何避免在色溫連續變化時產生跳變（visible transition）？",
    options: [
      "使用更多組 CCM 來覆蓋更密的色溫範圍",
      "在相鄰 CCM 之間根據色溫做平滑插值，並加入時域平滑濾波",
      "只使用一個固定的 CCM",
      "在色溫變化超過閾值時快速切換"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "空間插值（根據色溫在相鄰 CCM 之間做加權平均）確保色溫連續變化時 CCM 也連續變化。時域平滑濾波（temporal smoothing）防止色溫快速波動時 CCM 跟著劇烈變化，避免視覺跳變。",
    imageDesc: "",
    scenario: "",
    hint: "需要同時考慮空間和時間兩個維度的平滑",
    items: []
  },
  {
    id: "color_076",
    category: "color",
    type: "scenario",
    difficulty: 3,
    question: "你正在為一款 HDR 相機設計 tone mapping 模組。要求：(1) 保留暗部和亮部細節；(2) 避免 halo artifact；(3) 即時處理（30fps@4K）。下列哪種方案最適合？",
    options: [
      "Reinhard global operator",
      "基於 bilateral filter 的 local tone mapping",
      "基於 guided filter 的 local tone mapping",
      "直接 gamma 壓縮"
    ],
    answer: 2,
    acceptAlso: [],
    explanation: "Guided filter 是 edge-aware filter，具有 O(N) 的時間複雜度，不依賴 kernel size，非常適合即時處理。它能有效分離影像的基礎層和細節層進行 local tone mapping，同時因為保邊特性，halo artifact 遠少於 bilateral filter（且 bilateral filter 計算量大，不適合即時 4K）。",
    imageDesc: "",
    scenario: "HDR 相機 ISP 的即時 tone mapping 設計",
    hint: "考慮計算複雜度和 edge-aware 特性",
    items: []
  },
  {
    id: "color_077",
    category: "color",
    type: "single",
    difficulty: 3,
    question: "在 3D LUT 的設計中，為什麼有些實現會使用非均勻的網格點分佈？",
    options: [
      "為了減少 LUT 大小",
      "在人眼較敏感的色彩區域（如膚色、天空）分配更多網格點以提高精度",
      "因為硬體限制只能支援非均勻分佈",
      "為了與 ICC profile 相容"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "非均勻網格分佈可以在 LUT 大小不變的情況下，將更多的精度集中在視覺敏感區域（如膚色、低飽和度色彩、暗部灰階）。這是一種有效的資源最佳化策略，特別是在記憶體受限的嵌入式 ISP 中。",
    imageDesc: "",
    scenario: "",
    hint: "有限的資源應該分配給最重要的區域",
    items: []
  },
  {
    id: "color_078",
    category: "color",
    type: "multiple",
    difficulty: 3,
    question: "在 ISP 中防止 color banding 的有效方法包括哪些？（選三個）",
    options: [
      "在 quantization 前加入 temporal dithering",
      "使用更高的內部處理位元深度（如 14-bit pipeline 輸出 8-bit）",
      "在漸層區域加入空間域 dithering noise",
      "增加 CCM 的精度"
    ],
    answer: [0, 1, 2],
    acceptAlso: [],
    explanation: "防止 banding 的三種有效方法：(1) Temporal dithering 在時間維度分散量化誤差；(2) 高位元深度 pipeline 保留更多精度到最後量化步驟；(3) 空間域 dithering 在視覺上打破色帶邊界。CCM 精度與 banding 無直接關係。",
    imageDesc: "",
    scenario: "",
    hint: "核心問題是量化誤差在空間上的相關性",
    items: []
  },
  {
    id: "color_079",
    category: "color",
    type: "single",
    difficulty: 3,
    question: "在 CCM 的 least squares 求解 M = P_target × P_sensor^+ 中，P_sensor^+ 代表什麼？",
    options: [
      "P_sensor 的轉置",
      "P_sensor 的 Moore-Penrose 偽逆矩陣",
      "P_sensor 的逆矩陣",
      "P_sensor 的共軛矩陣"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "當色塊數量多於 3 時（超定系統），P_sensor 不是方陣，無法直接求逆。Moore-Penrose 偽逆 P^+ = (P^T × P)^(-1) × P^T 提供最小二乘意義下的最優解，使得 ||P_target - M × P_sensor||² 最小。",
    imageDesc: "",
    scenario: "",
    hint: "超定方程系統的最優解",
    items: []
  },
  {
    id: "color_080",
    category: "color",
    type: "single",
    difficulty: 3,
    question: "為什麼 ΔE2000 在工業色彩管理中逐漸取代了 ΔE*ab（CIE76）？",
    options: [
      "計算更快",
      "它更好地模擬了人眼對不同色彩區域色差的不均勻感知",
      "它不需要 Lab 色彩空間",
      "它只適用於 HDR 影像"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "CIE76 的 ΔE*ab 在 Lab 空間中以歐幾里得距離計算，但 Lab 空間並不完全感知均勻。ΔE2000 加入了亮度、色度、色相的加權函數以及藍色區域的旋轉修正，大幅提升了與人眼感知的一致性。",
    imageDesc: "",
    scenario: "",
    hint: "Lab 空間雖然是為感知均勻設計的，但仍有不足",
    items: []
  },
  {
    id: "color_081",
    category: "color",
    type: "truefalse",
    difficulty: 3,
    question: "在 ISP pipeline 中，3D LUT 可以完全取代 CCM + 1D LUT（gamma）的組合。",
    options: ["正確", "錯誤"],
    answer: true,
    acceptAlso: [],
    explanation: "從理論上講，3D LUT 可以表達任意的 3D 到 3D 色彩映射（包括非線性），因此可以包含 CCM（線性轉換）和 gamma（非線性轉換）的聯合效果。但實際上，3D LUT 需要足夠的網格密度才能精確表達，且在硬體實現上可能比分開的 CCM + 1D LUT 更耗資源。",
    imageDesc: "",
    scenario: "",
    hint: "3D LUT 的表達能力是否足以涵蓋線性和非線性轉換？",
    items: []
  },
  {
    id: "color_082",
    category: "color",
    type: "single",
    difficulty: 3,
    question: "在使用 ACES 的 RRT（Reference Rendering Transform）時，為什麼要設計一個「toe」區域和「shoulder」區域？",
    options: [
      "為了增加計算速度",
      "Toe 壓縮暗部防止 noise 放大，shoulder 壓縮亮部防止 highlight clipping，模擬底片的 S 型曲線",
      "為了與 sRGB gamma 相容",
      "為了減少記憶體使用量"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "ACES RRT 的 S 型曲線設計借鑒了底片的感光特性：toe 區域（暗部）逐漸壓縮到黑色，避免 noise 被放大；shoulder 區域（亮部）逐漸趨於飽和，優雅地處理 highlight 而非硬性裁切。這提供了類似底片的自然視覺表現。",
    imageDesc: "",
    scenario: "",
    hint: "模擬傳統底片的特性曲線",
    items: []
  },
  {
    id: "color_083",
    category: "color",
    type: "single",
    difficulty: 3,
    question: "在 ISP 的色彩管線中，如果需要在 CCM 後進行色彩飽和度增強，最佳的實現方式是什麼？",
    options: [
      "直接放大 R 和 B 通道的值",
      "轉換到 HSV 空間調整 S 分量",
      "使用 3×3 矩陣實現：M_sat = (1-s)×M_gray + s×I，其中 s 為飽和度因子",
      "將所有像素值乘以常數"
    ],
    answer: 2,
    acceptAlso: [],
    explanation: "用 3×3 矩陣表達飽和度調整是高效且精確的方法。M_gray 將 RGB 轉為灰階（使用亮度權重），I 為單位矩陣。s>1 時增強飽和度，s<1 時降低。這個矩陣可以和 CCM 預先合併，在硬體上零額外成本。",
    imageDesc: "",
    scenario: "",
    hint: "矩陣運算可以預先合併以節省硬體資源",
    items: []
  },
  {
    id: "color_084",
    category: "color",
    type: "ordering",
    difficulty: 3,
    question: "在一個完整的 ISP 色彩管線中，按正確順序排列以下模組：",
    options: ["3D LUT color styling", "Gamma correction", "CCM", "Black level correction", "White balance", "Demosaic"],
    answer: 0,
    acceptAlso: [],
    explanation: "正確順序：BLC（去除黑電平）→ WB（線性域白平衡）→ Demosaic（Bayer 插值）→ CCM（色彩校正）→ Gamma（線性到非線性）→ 3D LUT（最終色彩風格調整）。每步都有嚴格的依賴關係和域要求。",
    imageDesc: "",
    scenario: "",
    hint: "BLC 在最前面，非線性處理在後面",
    items: ["Black level correction", "White balance", "Demosaic", "CCM", "Gamma correction", "3D LUT color styling"]
  },
  {
    id: "color_085",
    category: "color",
    type: "single",
    difficulty: 3,
    question: "在高位元深度（如 16-bit float）HDR pipeline 中，為什麼 gamma correction 可能需要用 PQ（Perceptual Quantizer，SMPTE ST 2084）取代傳統的 power law？",
    options: [
      "PQ 計算更簡單",
      "PQ 曲線基於人眼的 absolute luminance 感知模型，能在整個亮度範圍（0.0001 到 10000 nits）提供感知均勻的量化",
      "PQ 不需要 LUT",
      "PQ 只適用於 8-bit 輸出"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "PQ（SMPTE ST 2084）基於 Barten 的人眼對比靈敏度模型，在 0.0001 到 10000 nits 的巨大亮度範圍內提供感知均勻的量化。傳統 gamma 在 HDR 的高亮度區域量化效率極低，PQ 能用更少的 bit 達到視覺無差別。",
    imageDesc: "",
    scenario: "",
    hint: "HDR 的亮度範圍遠超傳統 gamma 的設計範圍",
    items: []
  },
  {
    id: "color_086",
    category: "color",
    type: "single",
    difficulty: 3,
    question: "在 CCM 設計中使用「帶正則化的最小二乘法」（regularized least squares）的目的是什麼？",
    options: [
      "加速計算",
      "防止矩陣元素過大（noise amplification），在色彩準確度和雜訊放大之間取得平衡",
      "使矩陣元素全為整數",
      "確保矩陣可逆"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "無約束最小二乘可能產生極端的矩陣元素值（大正值和大負值），雖然色塊校正準確但會嚴重放大雜訊。正則化（如 Tikhonov regularization）通過懲罰大的矩陣元素，在色彩準確度和雜訊表現之間找到最佳平衡點。",
    imageDesc: "",
    scenario: "",
    hint: "矩陣元素過大 = 增益過大 = 雜訊放大",
    items: []
  },
  {
    id: "color_087",
    category: "color",
    type: "scenario",
    difficulty: 3,
    question: "你正在開發一款支援 BT.2020 HDR 的 ISP。在進行色域映射（gamut mapping）到 sRGB SDR 輸出時，用戶抱怨高飽和度的紅色花朵看起來「燒焦」且失去紋理。最可能的原因和解決方案是？",
    options: [
      "原因：tone mapping 過度壓縮；方案：減少 tone mapping 強度",
      "原因：色域映射使用了硬性 clipping；方案：改用感知意圖（perceptual intent）的漸進式色域壓縮",
      "原因：demosaic 錯誤；方案：更換 demosaic 演算法",
      "原因：白平衡偏移；方案：重新校正白平衡"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "BT.2020 中高飽和度的紅色超出 sRGB 色域範圍。硬性 clipping 會將這些顏色直接截斷到色域邊界，造成紋理和色階遺失（「燒焦」感）。漸進式色域壓縮（soft gamut mapping）會平滑地將色域外的顏色壓縮進來，保留相對的色彩層次和紋理。",
    imageDesc: "",
    scenario: "BT.2020 HDR 到 sRGB SDR 的色域映射問題",
    hint: "「燒焦」= 色階遺失 = 過於暴力的色域處理",
    items: []
  },
  {
    id: "color_088",
    category: "color",
    type: "single",
    difficulty: 3,
    question: "在實現 hue rotation 的 3×3 矩陣時，為什麼不能簡單地繞 (1,1,1) 向量做 rotation matrix？",
    options: [
      "因為 (1,1,1) 不是單位向量",
      "因為 RGB 空間的亮度軸不精確地等於 (1,1,1)，且 RGB 不是感知均勻的空間",
      "因為旋轉矩陣不可逆",
      "因為硬體不支援浮點旋轉"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "在 RGB 空間中，(1,1,1) 方向對應的不是感知亮度軸（因為 R、G、B 對亮度的貢獻不等）。真正的「亮度軸」取決於亮度權重（如 BT.709 的 0.2126, 0.7152, 0.0722）。繞錯誤的軸旋轉會在改變色相的同時意外改變亮度，導致不自然的結果。",
    imageDesc: "",
    scenario: "",
    hint: "R、G、B 對人眼亮度感知的權重不同",
    items: []
  },
  {
    id: "color_089",
    category: "color",
    type: "truefalse",
    difficulty: 3,
    question: "在 CCM 矩陣中使用負的 off-diagonal 元素是不正確的，應該避免。",
    options: ["正確", "錯誤"],
    answer: false,
    acceptAlso: [],
    explanation: "CCM 的 off-diagonal 負元素是正常且必要的——它們用於校正感測器的 color channel crosstalk。例如，紅色濾波器也會通過一些綠色光，CCM 中對應的負元素就是用來扣除這個串擾。完全正的 CCM 矩陣無法有效校正通道串擾。",
    imageDesc: "",
    scenario: "",
    hint: "想想 CCM 如何消除通道間的串擾",
    items: []
  },
  {
    id: "color_090",
    category: "color",
    type: "single",
    difficulty: 3,
    question: "在設計 auto tone 演算法時，CLAHE（Contrast Limited Adaptive Histogram Equalization）相比標準的 Adaptive Histogram Equalization（AHE）的改進是什麼？",
    options: [
      "CLAHE 不需要分塊處理",
      "CLAHE 通過限制局部直方圖的最大計數來防止雜訊過度放大",
      "CLAHE 只處理色度分量",
      "CLAHE 的計算量更小"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "AHE 在均勻區域（直方圖集中在少數 bin）會過度增強雜訊。CLAHE 加入了 clip limit——如果某個 bin 的計數超過閾值，多餘的計數會被均勻分配到其他 bin，從而限制了對比度增強的上限，有效抑制雜訊放大。",
    imageDesc: "",
    scenario: "",
    hint: "CL = Contrast Limited",
    items: []
  },
  {
    id: "color_091",
    category: "color",
    type: "single",
    difficulty: 3,
    question: "在 ISP 中實現 chromatic adaptation 時，為什麼 Bradford transform 要在部分極端色溫差異下引入非線性修正？",
    options: [
      "為了加速計算",
      "因為人眼的色彩適應在極端條件下不完全是 Von Kries 類型的線性增益調整",
      "為了處理 HDR 影像",
      "因為 Bradford 矩陣不可逆"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "研究表明，在色溫差異很大的情況下（如 2500K 到 10000K），人眼的適應機制不完全符合 Von Kries 的線性增益模型。Bradford 在 sharpened 空間的短波通道引入了非線性修正（power function），以更好地預測這些極端條件下的適應效果。",
    imageDesc: "",
    scenario: "",
    hint: "極端條件下線性模型的局限性",
    items: []
  },
  {
    id: "color_092",
    category: "color",
    type: "fillblank",
    difficulty: 3,
    question: "在 ACES pipeline 中，IDT 的全名是 ______。",
    options: [],
    answer: "Input Device Transform",
    acceptAlso: ["input device transform"],
    explanation: "IDT（Input Device Transform）將特定輸入設備（如某型號相機）的原始色彩數據轉換到 ACES 線性色彩空間（AP0 或 AP1）。每種相機/感測器都需要專屬的 IDT，類似於 ICC 的 input profile。",
    imageDesc: "",
    scenario: "",
    hint: "I = Input, D = Device, T = Transform",
    items: []
  },
  {
    id: "color_093",
    category: "color",
    type: "single",
    difficulty: 3,
    question: "在做 CCM 校正時，使用 24 色 ColorChecker 可能不夠充分的原因是什麼？",
    options: [
      "24 個色塊太多，會造成 overfitting",
      "24 個色塊對 9 個未知數（3×3 矩陣）雖然足夠，但色彩分佈不均勻，某些色彩區域（如膚色附近）取樣不足",
      "ColorChecker 只有灰階色塊",
      "CCM 需要至少 100 個色塊"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "標準 24 色 ColorChecker 的色塊在色彩空間中的分佈不夠均勻——某些重要區域（如膚色、天空藍）附近沒有足夠的取樣點。使用 ColorChecker SG（140 色）或自定義色板可以提供更好的覆蓋，但也需注意避免 overfitting。",
    imageDesc: "",
    scenario: "",
    hint: "24 個色塊在色彩空間中的分佈均勻性",
    items: []
  },
  {
    id: "color_094",
    category: "color",
    type: "multiple",
    difficulty: 3,
    question: "在 HDR 影像的 local tone mapping 中，可能出現的 artifact 包括？（選三個）",
    options: [
      "Halo artifact（光暈偽影）",
      "Gradient reversal（梯度反轉）",
      "Moiré pattern",
      "Loss of local contrast consistency（局部對比度不一致）"
    ],
    answer: [0, 1, 3],
    acceptAlso: [],
    explanation: "Local tone mapping 的常見 artifact：(1) Halo——亮暗邊界出現明暗光暈；(2) Gradient reversal——原本單調的梯度被反轉；(3) 局部對比度不一致——不同區域的對比度處理不統一。Moiré 是空間取樣問題，與 tone mapping 無關。",
    imageDesc: "",
    scenario: "",
    hint: "Moiré 是取樣/解映射問題",
    items: []
  },
  {
    id: "color_095",
    category: "color",
    type: "single",
    difficulty: 3,
    question: "在 ISP 中，如果 CCM 的條件數（condition number）很大，意味著什麼？",
    options: [
      "矩陣計算速度很快",
      "矩陣對輸入的微小變化（如雜訊）非常敏感，會顯著放大誤差",
      "色彩校正非常準確",
      "矩陣是單位矩陣"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "高條件數表示矩陣接近奇異（ill-conditioned），對輸入的微小擾動（如感測器雜訊）會產生巨大的輸出變化。在 CCM 設計中，應監控條件數並使用正則化來控制，在色彩準確度和雜訊穩健性之間取得平衡。",
    imageDesc: "",
    scenario: "",
    hint: "條件數是數值穩定性的指標",
    items: []
  },
  {
    id: "color_096",
    category: "color",
    type: "single",
    difficulty: 3,
    question: "在色彩管理中，ICC profile 使用 D50 作為 Profile Connection Space（PCS）的照明體。如果要連接一個基於 D65 白點的設備 profile，應該怎麼處理？",
    options: [
      "忽略差異，直接連接",
      "在 profile 內部使用 chromatic adaptation transform 將設備白點轉換到 D50",
      "將 PCS 改為 D65",
      "使用 gamma correction 補償"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "ICC 標準規定 PCS 使用 D50 照明體。基於 D65 的設備（如大部分顯示器）需要在其 ICC profile 內嵌一個 chromatic adaptation tag（通常使用 Bradford transform），將 D65 白點轉換到 D50，確保所有 profile 在統一的 PCS 下正確互連。",
    imageDesc: "",
    scenario: "",
    hint: "ICC 的 PCS 是固定的 D50",
    items: []
  },
  {
    id: "color_097",
    category: "color",
    type: "scenario",
    difficulty: 3,
    question: "在一個 ISP 專案中，你需要將兩個 3×3 矩陣運算合併為一個，以節省硬體資源。矩陣 A 是 CCM，矩陣 B 是色彩空間轉換（如 sRGB 到 BT.709 YCbCr）。合併後的矩陣應該如何計算？",
    options: [
      "C = A + B",
      "C = (A + B) / 2",
      "C = B × A（先執行 A 再執行 B）",
      "C = A × B（先執行 B 再執行 A）"
    ],
    answer: 2,
    acceptAlso: [],
    explanation: "矩陣運算的級聯：如果輸入向量 v 先經過 A 得到 Av，再經過 B 得到 B(Av) = (BA)v，因此合併矩陣 C = B×A。注意矩陣乘法不滿足交換律，順序很重要：右邊的矩陣先作用於輸入。",
    imageDesc: "",
    scenario: "ISP 硬體優化，合併多個矩陣運算",
    hint: "矩陣級聯的順序：右邊先執行",
    items: []
  },
  {
    id: "color_098",
    category: "color",
    type: "truefalse",
    difficulty: 3,
    question: "在 12-bit RAW 影像上直接做 gamma correction（如 γ=1/2.2）後存為 8-bit，相比先做線性域處理再轉換，會損失暗部的色彩精度。",
    options: ["正確", "錯誤"],
    answer: false,
    acceptAlso: [],
    explanation: "實際上，gamma correction 會「拉伸」暗部，分配更多的 code 給暗部，因此暗部精度反而提高了。Gamma 編碼本身就是一種感知優化的量化方式。真正損失精度的問題在於：如果在線性域做了各種處理後的中間結果沒有足夠位元深度，才會損失精度。",
    imageDesc: "",
    scenario: "",
    hint: "Gamma < 1 的效果是擴展暗部、壓縮亮部",
    items: []
  },
  {
    id: "color_099",
    category: "color",
    type: "single",
    difficulty: 3,
    question: "在評估 ISP 色彩管線的效能時，如果使用 ΔE2000 < 1 作為「視覺無差異」的標準，對 24 色 ColorChecker 的典型要求是什麼？",
    options: [
      "所有 24 色的 ΔE2000 都 < 1",
      "平均 ΔE2000 < 1，且最大 ΔE2000 < 3–4",
      "只有灰色色塊的 ΔE2000 < 1",
      "中位數 ΔE2000 < 0.5"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "工業實踐中，要求所有 24 色都 < 1 通常不切實際（3×3 CCM 的線性限制）。常見的規格是平均 ΔE2000 < 1（表示整體色彩準確），最大 ΔE2000 < 3–4（確保沒有嚴重偏色的色塊）。高階相機可能有更嚴格的規格。",
    imageDesc: "",
    scenario: "",
    hint: "3×3 線性矩陣有其精度上限",
    items: []
  },
  {
    id: "color_100",
    category: "color",
    type: "single",
    difficulty: 3,
    question: "在 ISP 中，為什麼有些設計會在 CCM 之前加入一個多項式擴展（polynomial expansion），例如將 [R,G,B] 擴展為 [R,G,B,RG,RB,GB,R²,G²,B²]？",
    options: [
      "為了減少矩陣大小",
      "為了讓線性矩陣運算能夠近似非線性的色彩映射，提高校正精度",
      "為了增加影像解析度",
      "為了加速白平衡計算"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "標準 3×3 CCM 只能做線性轉換，但感測器到標準色彩空間的實際映射包含非線性成分。通過多項式擴展（如加入交叉項 RG, RB, GB 和平方項），配合更大的矩陣（如 3×9），可以近似二階非線性映射，顯著提高色彩校正精度，特別是對高飽和度顏色。",
    imageDesc: "",
    scenario: "",
    hint: "多項式可以近似非線性函數",
    items: []
  }
];

