const Q_COMPRESSION = [
  // ===== DIFFICULTY 1 (questions 001–017) =====
  {
    id: "compression_001",
    category: "compression",
    type: "single",
    difficulty: 1,
    question: "JPEG 壓縮屬於下列哪種類型？",
    options: ["無損壓縮 (Lossless)", "有損壓縮 (Lossy)", "無壓縮 (Uncompressed)", "混合壓縮 (Hybrid)"],
    answer: 1,
    acceptAlso: [],
    explanation: "JPEG 是典型的有損壓縮格式，透過 DCT 變換與量化來移除人眼不易察覺的高頻細節，以達到較高的壓縮比。雖然 JPEG 也有 lossless mode，但標準 JPEG 預設為有損。",
    imageDesc: "",
    scenario: "",
    hint: "想想 JPEG 圖片儲存後再開啟，畫質是否會完全一樣。"
  },
  {
    id: "compression_002",
    category: "compression",
    type: "truefalse",
    difficulty: 1,
    question: "PNG 是一種無損壓縮 (lossless compression) 的影像格式。",
    options: [],
    answer: true,
    acceptAlso: [],
    explanation: "PNG 使用 Deflate 演算法進行無損壓縮，解壓後的影像與原始影像完全相同，不會損失任何像素資訊。這使得 PNG 非常適合需要精確還原的場景，如螢幕截圖或文字圖片。",
    imageDesc: "",
    scenario: "",
    hint: "PNG 的全名是 Portable Network Graphics，最初設計就是為了取代 GIF。"
  },
  {
    id: "compression_003",
    category: "compression",
    type: "single",
    difficulty: 1,
    question: "在 chroma subsampling 中，4:2:0 表示什麼意思？",
    options: [
      "每 4 個像素取 2 個亮度、0 個色度",
      "水平與垂直方向的色度解析度均減半",
      "只保留亮度，完全丟棄色度",
      "水平方向色度減半，垂直方向不變"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "4:2:0 表示色度 (chroma) 在水平與垂直方向的取樣率均為亮度 (luma) 的一半。每 2×2 的像素區塊共用一組 Cb/Cr 值，因此色度資料量只有 4:4:4 的 1/4。",
    imageDesc: "",
    scenario: "",
    hint: "4:2:0 是目前 ISP 輸出和視訊壓縮中最常見的 subsampling 格式。"
  },
  {
    id: "compression_004",
    category: "compression",
    type: "single",
    difficulty: 1,
    question: "下列哪個是 ISP 常見的輸出格式？",
    options: ["RGB888", "NV12", "RGBA32", "BMP"],
    answer: 1,
    acceptAlso: [],
    explanation: "NV12 是 YUV 4:2:0 的一種半平面 (semi-planar) 排列格式，Y 平面獨立儲存，UV 交錯排列。由於色度資料量減少且硬體友好，NV12 是 ISP 輸出及視訊編碼器輸入最常用的格式之一。",
    imageDesc: "",
    scenario: "",
    hint: "想想 ISP 輸出通常使用哪種色彩空間。"
  },
  {
    id: "compression_005",
    category: "compression",
    type: "truefalse",
    difficulty: 1,
    question: "PSNR 值越高，表示影像品質越好。",
    options: [],
    answer: true,
    acceptAlso: [],
    explanation: "PSNR (Peak Signal-to-Noise Ratio) 以 dB 為單位衡量重建影像與原始影像之間的差異。PSNR 越高代表失真越小，通常 30 dB 以上被認為品質可接受，40 dB 以上被認為非常好。",
    imageDesc: "",
    scenario: "",
    hint: "PSNR 是 Peak Signal-to-Noise Ratio 的縮寫。"
  },
  {
    id: "compression_006",
    category: "compression",
    type: "single",
    difficulty: 1,
    question: "Huffman coding 屬於下列哪種編碼技術？",
    options: ["Transform coding", "Entropy coding", "Predictive coding", "Quantization"],
    answer: 1,
    acceptAlso: [],
    explanation: "Huffman coding 是一種 entropy coding（熵編碼）技術，根據符號出現的頻率分配不同長度的碼字。出現頻率越高的符號使用越短的碼字，從而達到無損壓縮的效果。",
    imageDesc: "",
    scenario: "",
    hint: "Entropy coding 的目標是讓高頻率符號用更少的 bits 表示。"
  },
  {
    id: "compression_007",
    category: "compression",
    type: "fillblank",
    difficulty: 1,
    question: "JPEG 壓縮流程中，將空間域訊號轉換為頻率域的關鍵步驟是 _____ 變換。",
    options: [],
    answer: "DCT",
    acceptAlso: ["dct", "Discrete Cosine Transform", "離散餘弦變換"],
    explanation: "DCT (Discrete Cosine Transform，離散餘弦變換) 將 8×8 像素區塊從空間域轉換為頻率域，使得影像的能量集中在低頻係數上，方便後續量化步驟去除高頻細節。",
    imageDesc: "",
    scenario: "",
    hint: "這個變換與 Fourier Transform 相關，但只使用餘弦函數。"
  },
  {
    id: "compression_008",
    category: "compression",
    type: "single",
    difficulty: 1,
    question: "H.264 的另一個名稱是什麼？",
    options: ["MPEG-2", "AVC", "VP9", "HEVC"],
    answer: 1,
    acceptAlso: [],
    explanation: "H.264 也稱為 AVC (Advanced Video Coding) 或 MPEG-4 Part 10。它是目前應用最廣泛的視訊編碼標準之一，廣泛用於串流媒體、藍光光碟及 ISP 視訊輸出。",
    imageDesc: "",
    scenario: "",
    hint: "這個標準由 ITU-T 和 ISO/IEC 聯合制定。"
  },
  {
    id: "compression_009",
    category: "compression",
    type: "truefalse",
    difficulty: 1,
    question: "NV12 和 NV21 的差異在於 U/V 分量的排列順序不同。",
    options: [],
    answer: true,
    acceptAlso: [],
    explanation: "NV12 的色度平面為 UVUV... 交錯排列，而 NV21 為 VUVU... 交錯排列。兩者都是 YUV 4:2:0 semi-planar 格式，僅 U 和 V 的先後順序不同。Android 相機常使用 NV21，而大多數視訊編碼器偏好 NV12。",
    imageDesc: "",
    scenario: "",
    hint: "NV12 = Y + UV interleaved，NV21 = Y + VU interleaved。"
  },
  {
    id: "compression_010",
    category: "compression",
    type: "single",
    difficulty: 1,
    question: "壓縮比 (compression ratio) 10:1 表示什麼？",
    options: [
      "壓縮後檔案大小為原始的 10 倍",
      "壓縮後檔案大小為原始的 1/10",
      "壓縮過程耗時 10 秒",
      "壓縮使用 10 個步驟"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "壓縮比 10:1 表示原始資料大小與壓縮後資料大小的比值為 10，即壓縮後檔案大小為原始的 1/10。例如 10 MB 的原始影像壓縮後為 1 MB。",
    imageDesc: "",
    scenario: "",
    hint: "壓縮比 = 原始大小 / 壓縮後大小。"
  },
  {
    id: "compression_011",
    category: "compression",
    type: "single",
    difficulty: 1,
    question: "下列哪種壓縮 artifact 最容易在 JPEG 低品質影像的區塊邊界處觀察到？",
    options: ["Ringing artifact", "Blocking artifact", "Mosquito noise", "Moiré pattern"],
    answer: 1,
    acceptAlso: [],
    explanation: "Blocking artifact（方塊效應）是 JPEG 壓縮最常見的失真，因為 JPEG 將影像切割為 8×8 的區塊獨立處理，在低品質設定下相鄰區塊之間的不連續性會變得明顯，形成可見的格子狀邊界。",
    imageDesc: "",
    scenario: "",
    hint: "JPEG 以 8×8 的區塊為單位進行處理。"
  },
  {
    id: "compression_012",
    category: "compression",
    type: "fillblank",
    difficulty: 1,
    question: "H.265 也稱為 _____，其壓縮效率約為 H.264 的兩倍。",
    options: [],
    answer: "HEVC",
    acceptAlso: ["hevc", "High Efficiency Video Coding"],
    explanation: "H.265/HEVC (High Efficiency Video Coding) 在相同畫質下，位元率約為 H.264 的一半。HEVC 使用了更大的 coding tree unit (CTU，最大 64×64)、更靈活的分割方式及更先進的預測技術。",
    imageDesc: "",
    scenario: "",
    hint: "HEVC 的全名是 High Efficiency Video Coding。"
  },
  {
    id: "compression_013",
    category: "compression",
    type: "single",
    difficulty: 1,
    question: "YUV420 格式中，若亮度 (Y) 平面大小為 W×H，則每個色度 (U/V) 平面大小為？",
    options: ["W×H", "(W/2)×(H/2)", "(W/2)×H", "W×(H/2)"],
    answer: 1,
    acceptAlso: [],
    explanation: "在 YUV 4:2:0 中，色度在水平與垂直方向均為亮度的一半取樣率，因此每個色度平面的解析度為 (W/2)×(H/2)。整體資料量為 Y + U + V = W×H + W×H/4 + W×H/4 = 1.5 × W×H。",
    imageDesc: "",
    scenario: "",
    hint: "4:2:0 表示色度在水平和垂直方向各取一半。"
  },
  {
    id: "compression_014",
    category: "compression",
    type: "truefalse",
    difficulty: 1,
    question: "RAW 檔案一定是完全未壓縮的。",
    options: [],
    answer: false,
    acceptAlso: [],
    explanation: "許多相機的 RAW 格式支援無損壓縮甚至有損壓縮。例如 Sony ARW 和 Nikon NEF 都支援 lossless compressed RAW，可在不損失資訊的情況下顯著減少檔案大小。有些相機還提供 lossy compressed RAW 選項。",
    imageDesc: "",
    scenario: "",
    hint: "RAW 是指未經 ISP 完整處理的感測器原始資料，但不代表不能壓縮。"
  },
  {
    id: "compression_015",
    category: "compression",
    type: "single",
    difficulty: 1,
    question: "SSIM 的值域範圍是多少？",
    options: ["0 到 100", "-1 到 1", "0 到 255", "0 到 1"],
    answer: 1,
    acceptAlso: [],
    explanation: "SSIM (Structural Similarity Index Measure) 的值域為 -1 到 1，其中 1 表示兩張影像完全相同。實務上通常值在 0 到 1 之間。SSIM 比 PSNR 更符合人眼的感知品質評估。",
    imageDesc: "",
    scenario: "",
    hint: "SSIM 考量了亮度、對比度和結構三個面向的相似度。"
  },
  {
    id: "compression_016",
    category: "compression",
    type: "single",
    difficulty: 1,
    question: "下列哪個格式使用 HEVC 作為壓縮編碼？",
    options: ["JPEG", "PNG", "HEIF", "BMP"],
    answer: 2,
    acceptAlso: [],
    explanation: "HEIF (High Efficiency Image File Format) 使用 HEVC (H.265) 編碼來壓縮影像，在相同品質下檔案大小約為 JPEG 的一半。Apple 從 iOS 11 開始預設使用 HEIF 格式拍照。",
    imageDesc: "",
    scenario: "",
    hint: "這個格式由 MPEG 組織定義，Apple 率先廣泛採用。"
  },
  {
    id: "compression_017",
    category: "compression",
    type: "truefalse",
    difficulty: 1,
    question: "Bitrate 越高的視訊，畫質一定越好。",
    options: [],
    answer: false,
    acceptAlso: [],
    explanation: "雖然較高的 bitrate 通常能提供更好的畫質，但實際品質還取決於編碼器效率、編碼參數、影像內容複雜度等因素。例如高效率的 H.265 編碼器在較低 bitrate 下可能比低效的 H.264 編碼器在較高 bitrate 下產出更好的畫質。",
    imageDesc: "",
    scenario: "",
    hint: "編碼效率和內容特性也會影響最終畫質。"
  },
  // ===== DIFFICULTY 2 (questions 018–034) =====
  {
    id: "compression_018",
    category: "compression",
    type: "ordering",
    difficulty: 2,
    question: "請將 JPEG 壓縮的主要步驟按正確順序排列：",
    options: [],
    answer: 0,
    acceptAlso: [],
    explanation: "JPEG 編碼流程：(1) 色彩空間轉換（RGB→YCbCr）；(2) Chroma subsampling；(3) 將影像分割為 8×8 區塊；(4) 對每個區塊進行 DCT 變換；(5) 量化 DCT 係數；(6) Zigzag 掃描將 2D 係數轉為 1D 序列；(7) Entropy coding（Huffman 或 Arithmetic）輸出位元流。",
    imageDesc: "",
    scenario: "",
    hint: "先轉換色彩空間，最後才做熵編碼。",
    items: [
      "色彩空間轉換 (RGB → YCbCr)",
      "Chroma subsampling",
      "分割為 8×8 區塊",
      "DCT 變換",
      "量化 (Quantization)",
      "Zigzag 掃描",
      "Entropy coding"
    ]
  },
  {
    id: "compression_019",
    category: "compression",
    type: "single",
    difficulty: 2,
    question: "JPEG 壓縮中，zigzag 掃描的主要目的是什麼？",
    options: [
      "增加壓縮比",
      "將 2D DCT 係數按頻率由低到高排列為 1D 序列",
      "移除高頻噪聲",
      "將 RGB 轉換為 YCbCr"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "Zigzag 掃描將 8×8 的 DCT 係數矩陣按照由低頻到高頻的對角線順序排列為一維序列。由於量化後高頻係數大多為零，zigzag 排列使得零值集中在序列末端，有利於後續 RLE (Run-Length Encoding) 和 entropy coding 進一步壓縮。",
    imageDesc: "",
    scenario: "",
    hint: "DCT 後低頻係數集中在左上角，高頻在右下角。"
  },
  {
    id: "compression_020",
    category: "compression",
    type: "multiple",
    difficulty: 2,
    question: "下列哪些是 JPEG 壓縮常見的 artifact？（複選）",
    options: ["Blocking artifact", "Ringing artifact", "Mosquito noise", "Film grain"],
    answer: [0, 1, 2],
    acceptAlso: [],
    explanation: "Blocking artifact（方塊效應）源於 8×8 區塊獨立處理；Ringing artifact（振鈴效應）出現在強邊緣旁邊的波紋狀失真；Mosquito noise（蚊蟲噪點）是邊緣附近的高頻閃爍失真。Film grain 是底片的物理顆粒，非壓縮造成。",
    imageDesc: "",
    scenario: "",
    hint: "Film grain 是光學現象，不是壓縮產生的。"
  },
  {
    id: "compression_021",
    category: "compression",
    type: "single",
    difficulty: 2,
    question: "JPEG 量化表 (quantization table) 中，右下角的值通常比左上角的值：",
    options: ["更小", "更大", "相同", "為零"],
    answer: 1,
    acceptAlso: [],
    explanation: "量化表中右下角對應高頻係數，使用較大的量化步長（divisor），使得高頻細節被更大幅度地量化（甚至歸零），因為人眼對高頻細節不敏感。左上角對應低頻係數，使用較小的量化步長以保留重要的亮度和色彩資訊。",
    imageDesc: "",
    scenario: "",
    hint: "人眼對低頻資訊比高頻資訊更敏感。"
  },
  {
    id: "compression_022",
    category: "compression",
    type: "scenario",
    difficulty: 2,
    question: "你正在調整 ISP 輸出的 JPEG quality factor。當你將 quality 從 90 降到 50 時，最可能觀察到什麼現象？",
    options: [
      "檔案大小幾乎不變",
      "出現明顯 blocking artifact，檔案大小顯著減少",
      "影像解析度降低",
      "色彩空間從 YCbCr 變為 RGB"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "降低 JPEG quality factor 會增大量化步長，更多 DCT 係數被量化為零。從 90 降到 50 會使檔案大小顯著減少（可能減少 50-70%），但 8×8 區塊邊界處的不連續性會變得明顯，產生 blocking artifact。影像解析度（像素數）不會改變。",
    imageDesc: "",
    scenario: "你負責手機 ISP 的 JPEG 編碼器品質調整。產品經理要求在記憶體受限的情況下減少照片檔案大小。",
    hint: "Quality factor 影響量化表的數值大小。"
  },
  {
    id: "compression_023",
    category: "compression",
    type: "single",
    difficulty: 2,
    question: "Arithmetic coding 相比 Huffman coding 的主要優勢是什麼？",
    options: [
      "編碼速度更快",
      "可以更接近資訊熵的理論極限",
      "不需要機率模型",
      "硬體實現更簡單"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "Arithmetic coding 可以對整個訊息產生一個浮點數區間，不受限於每個符號必須用整數位元表示的限制，因此壓縮效率可更接近 Shannon 資訊熵的理論極限。Huffman coding 每個符號至少需要 1 bit，在符號機率接近 1 時效率較差。",
    imageDesc: "",
    scenario: "",
    hint: "Huffman 的每個符號至少要 1 bit。"
  },
  {
    id: "compression_024",
    category: "compression",
    type: "image",
    difficulty: 2,
    question: "觀察下方影像描述。在 JPEG 高壓縮率影像中，哪種 artifact 最可能出現在文字邊緣的平坦區域？",
    options: ["Blocking artifact", "Ringing artifact", "Color bleeding", "Banding"],
    answer: 1,
    acceptAlso: [],
    explanation: "Ringing artifact（振鈴效應）類似 Gibbs phenomenon，在文字等銳利邊緣旁邊的平坦區域會出現波紋狀的明暗交替失真。這是因為量化過程截斷了表達銳利邊緣所需的高頻 DCT 係數，導致重建時出現振盪。",
    imageDesc: "一張 JPEG 高壓縮率影像，黑色文字印刷在白色背景上。文字邊緣旁邊的白色區域出現灰色波紋狀的失真紋路。",
    scenario: "",
    hint: "這種現象與 Gibbs phenomenon 有關。"
  },
  {
    id: "compression_025",
    category: "compression",
    type: "single",
    difficulty: 2,
    question: "AFBC (Arm Frame Buffer Compression) 的主要目的是什麼？",
    options: [
      "提升影像品質",
      "減少 memory bandwidth 消耗",
      "增加 frame rate",
      "降低 CPU 使用率"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "AFBC 是一種 lossless frame buffer compression 技術，主要目的是減少 SoC 內部各 IP（ISP、GPU、Display）之間透過 DMA 存取 frame buffer 時的記憶體頻寬消耗。在行動裝置中，memory bandwidth 是功耗和效能的關鍵瓶頸。",
    imageDesc: "",
    scenario: "",
    hint: "行動 SoC 中，記憶體存取是功耗的主要來源之一。"
  },
  {
    id: "compression_026",
    category: "compression",
    type: "multiple",
    difficulty: 2,
    question: "下列哪些是 frame buffer compression 技術？（複選）",
    options: ["AFBC (Arm)", "UBWC (Qualcomm)", "DEFLATE", "GPU Tile-based rendering"],
    answer: [0, 1],
    acceptAlso: [],
    explanation: "AFBC (Arm Frame Buffer Compression) 和 UBWC (Universal Bandwidth Compression) 分別是 Arm 和 Qualcomm 的 frame buffer 壓縮技術，用於減少 SoC 內部的 memory bandwidth。DEFLATE 是通用資料壓縮演算法，Tile-based rendering 是 GPU 渲染架構而非壓縮技術。",
    imageDesc: "",
    scenario: "",
    hint: "這兩個技術分別來自兩大行動晶片 IP 供應商。"
  },
  {
    id: "compression_027",
    category: "compression",
    type: "fillblank",
    difficulty: 2,
    question: "在 H.264/H.265 中，CBR 代表 Constant _____ Rate，是一種固定輸出位元率的控制模式。",
    options: [],
    answer: "Bitrate",
    acceptAlso: ["bitrate", "Bit", "bit"],
    explanation: "CBR (Constant Bitrate) 維持固定的輸出位元率，適合需要穩定頻寬的即時串流場景。相對地，VBR (Variable Bitrate) 允許位元率隨內容複雜度變化，通常能在同等檔案大小下達到更好的品質。",
    imageDesc: "",
    scenario: "",
    hint: "這個模式確保輸出的資料流量保持恆定。"
  },
  {
    id: "compression_028",
    category: "compression",
    type: "single",
    difficulty: 2,
    question: "4:2:2 chroma subsampling 相較 4:4:4，色度資料量減少了多少？",
    options: ["25%", "50%", "75%", "不變"],
    answer: 1,
    acceptAlso: [],
    explanation: "4:2:2 在水平方向色度取樣減半，垂直方向不變。因此每個色度平面大小為 (W/2)×H，共兩個色度平面合計為 W×H，而 4:4:4 的兩個色度平面合計為 2×W×H。色度資料減少了 50%。",
    imageDesc: "",
    scenario: "",
    hint: "4:2:2 只在水平方向減少色度取樣。"
  },
  {
    id: "compression_029",
    category: "compression",
    type: "scenario",
    difficulty: 2,
    question: "ISP 輸出 1920×1080 NV12 格式的一幀影像，需要多少 bytes 的記憶體？",
    options: [
      "1,920 × 1,080 = 2,073,600 bytes",
      "1,920 × 1,080 × 1.5 = 3,110,400 bytes",
      "1,920 × 1,080 × 2 = 4,147,200 bytes",
      "1,920 × 1,080 × 3 = 6,220,800 bytes"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "NV12 是 YUV 4:2:0 semi-planar 格式：Y 平面為 1920×1080 = 2,073,600 bytes，UV 交錯平面為 960×540 = 1,036,800 bytes（因為水平和垂直方向各取一半）。總計 2,073,600 + 1,036,800 = 3,110,400 bytes = 1920×1080×1.5。",
    imageDesc: "",
    scenario: "你正在為 ISP 的 DMA 模組計算 frame buffer 所需的記憶體空間配置。",
    hint: "NV12 每個像素平均佔 1.5 bytes (12 bits)。"
  },
  {
    id: "compression_030",
    category: "compression",
    type: "truefalse",
    difficulty: 2,
    question: "SSIM 比 PSNR 更能反映人眼的主觀品質感受。",
    options: [],
    answer: true,
    acceptAlso: [],
    explanation: "SSIM 考慮了影像的結構 (structure)、亮度 (luminance) 和對比度 (contrast) 三個維度的相似性，比單純計算像素均方誤差的 PSNR 更接近人類視覺系統 (HVS) 的感知方式。研究表明 SSIM 與主觀品質評分的相關性高於 PSNR。",
    imageDesc: "",
    scenario: "",
    hint: "SSIM 的設計靈感來自人類視覺系統的特性。"
  },
  {
    id: "compression_031",
    category: "compression",
    type: "single",
    difficulty: 2,
    question: "Color bleeding artifact 最可能在什麼情況下出現？",
    options: [
      "使用 4:4:4 chroma subsampling",
      "使用 4:2:0 chroma subsampling 且影像含有銳利色彩邊緣",
      "使用 PNG 無損壓縮",
      "使用 RAW 格式儲存"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "Color bleeding（色彩溢出）在 chroma subsampling 後色度解析度降低時容易發生，尤其是 4:2:0 格式中色度解析度僅為亮度的 1/4。當影像中有銳利的色彩邊界（如紅色文字在白色背景上），低解析度的色度會導致色彩跨越邊界擴散。",
    imageDesc: "",
    scenario: "",
    hint: "Chroma subsampling 降低了色度的空間解析度。"
  },
  {
    id: "compression_032",
    category: "compression",
    type: "ordering",
    difficulty: 2,
    question: "請將以下視訊編碼標準按照發布時間由早到晚排列：",
    options: [],
    answer: 0,
    acceptAlso: [],
    explanation: "MPEG-2 (1995) → H.264/AVC (2003) → H.265/HEVC (2013) → H.266/VVC (2020)。每一代標準相較前一代約能在同等品質下減少 50% 的位元率，但編碼複雜度也大幅增加。",
    imageDesc: "",
    scenario: "",
    hint: "每一代壓縮效率約提升一倍。",
    items: [
      "MPEG-2",
      "H.264/AVC",
      "H.265/HEVC",
      "H.266/VVC"
    ]
  },
  {
    id: "compression_033",
    category: "compression",
    type: "single",
    difficulty: 2,
    question: "在 ISP pipeline 中，DMA (Direct Memory Access) 的主要功能是什麼？",
    options: [
      "進行影像降噪",
      "在記憶體與硬體模組間直接傳輸資料，不經過 CPU",
      "計算白平衡參數",
      "進行自動曝光控制"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "DMA 允許硬體模組直接讀寫系統記憶體，不需要 CPU 介入。在 ISP 中，DMA 負責將 sensor 資料搬入 ISP、將 ISP 處理結果搬至 frame buffer、以及將 frame buffer 送至編碼器或顯示器。減少 CPU 介入可降低延遲和功耗。",
    imageDesc: "",
    scenario: "",
    hint: "DMA 的核心概念是讓資料傳輸繞過 CPU。"
  },
  {
    id: "compression_034",
    category: "compression",
    type: "fillblank",
    difficulty: 2,
    question: "JPEG 使用的 DCT 區塊大小為 _____ × _____ 像素。",
    options: [],
    answer: "8",
    acceptAlso: ["8x8", "8×8"],
    explanation: "JPEG 標準將影像分割為 8×8 像素的區塊，對每個區塊獨立進行 DCT 變換。這個區塊大小是在壓縮效率和計算複雜度之間的折衷選擇。較大的區塊能提供更好的能量集中，但計算量增加且在低品質時 blocking artifact 更明顯。",
    imageDesc: "",
    scenario: "",
    hint: "這是一個經典的 2 的冪次方數值。"
  },
  // ===== DIFFICULTY 3 (questions 035–050) =====
  {
    id: "compression_035",
    category: "compression",
    type: "single",
    difficulty: 3,
    question: "在 HEVC 中，最大的 Coding Tree Unit (CTU) 尺寸是多少？",
    options: ["16×16", "32×32", "64×64", "128×128"],
    answer: 2,
    acceptAlso: [],
    explanation: "HEVC 引入了 Coding Tree Unit (CTU) 取代 H.264 的 macroblock，最大支援 64×64 像素。CTU 可透過 quadtree 分割為更小的 Coding Unit (CU)，最小到 8×8。這種靈活的分割方式讓 HEVC 能更有效地適應不同區域的內容複雜度。",
    imageDesc: "",
    scenario: "",
    hint: "HEVC 比 H.264 的 16×16 macroblock 大得多。"
  },
  {
    id: "compression_036",
    category: "compression",
    type: "scenario",
    difficulty: 3,
    question: "你正在設計 ISP 的 frame buffer compression 模組。若 4K (3840×2160) YUV420 影像以 30fps 輸出，未壓縮時所需的記憶體頻寬約為多少？",
    options: [
      "約 250 MB/s",
      "約 375 MB/s",
      "約 500 MB/s",
      "約 750 MB/s"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "4K YUV420：3840 × 2160 × 1.5 bytes/pixel = 12,441,600 bytes/frame ≈ 11.87 MB/frame。30fps 時為 11.87 × 30 ≈ 356 MB/s。考慮讀寫雙向（ISP 寫入 + 編碼器讀取），實際頻寬需求約為兩倍。最接近的答案為約 375 MB/s（單向寫入頻寬）。",
    imageDesc: "",
    scenario: "你需要評估 ISP 輸出 4K30fps 視訊時對 DDR memory bandwidth 的需求，以決定是否需要啟用 frame buffer compression。",
    hint: "YUV420 每像素 1.5 bytes，計算每秒資料量。"
  },
  {
    id: "compression_037",
    category: "compression",
    type: "multiple",
    difficulty: 3,
    question: "下列哪些技術可用於降低 ISP 輸出的 memory bandwidth？（複選）",
    options: [
      "AFBC/UBWC frame buffer compression",
      "降低 chroma subsampling（如 4:4:4 → 4:2:0）",
      "使用 tile-based DMA 存取模式",
      "增加 JPEG quality factor"
    ],
    answer: [0, 1, 2],
    acceptAlso: [],
    explanation: "AFBC/UBWC 可壓縮 frame buffer 減少頻寬；4:2:0 比 4:4:4 減少 50% 色度資料；tile-based DMA 可利用空間局部性減少 burst 長度和 bank conflict。增加 JPEG quality factor 反而會增大輸出資料量和頻寬需求。",
    imageDesc: "",
    scenario: "",
    hint: "減少頻寬的方法包括壓縮資料和減少資料量。"
  },
  {
    id: "compression_038",
    category: "compression",
    type: "single",
    difficulty: 3,
    question: "在 H.264 的 rate control 中，QP (Quantization Parameter) 每增加 6，量化步長會如何變化？",
    options: ["增加 6", "增加一倍", "增加 50%", "不變"],
    answer: 1,
    acceptAlso: [],
    explanation: "H.264/H.265 中，QP 每增加 6，量化步長 (Qstep) 增加一倍，位元率大約減半。這是因為量化步長與 QP 之間是指數關係：Qstep = Qstep_base × 2^((QP-4)/6)。這個 6 為倍增的設計讓 rate control 在對數域上具有線性特性。",
    imageDesc: "",
    scenario: "",
    hint: "QP 與量化步長之間是指數關係。"
  },
  {
    id: "compression_039",
    category: "compression",
    type: "scenario",
    difficulty: 3,
    question: "在 perceptual quality optimization 中，為何 JPEG 對亮度和色度使用不同的量化表？",
    options: [
      "為了簡化硬體實現",
      "因為人眼對亮度細節比色度細節更敏感，色度可使用更粗糙的量化",
      "為了加快編碼速度",
      "因為色度分量的 DCT 係數較少"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "人類視覺系統 (HVS) 對亮度 (luminance) 變化的敏感度遠高於色度 (chrominance) 變化。JPEG 利用這個特性，對色度使用更大量化步長的量化表，在不明顯降低主觀品質的前提下大幅減少色度資料量。這是 perceptual quality optimization 的核心概念。",
    imageDesc: "",
    scenario: "你正在為 ISP 的 JPEG 編碼器設計自適應量化策略，需要理解為什麼亮度和色度要分開處理。",
    hint: "這與人類視覺系統的特性直接相關。"
  },
  {
    id: "compression_040",
    category: "compression",
    type: "single",
    difficulty: 3,
    question: "Lossless RAW compression 中，常用哪種預測方式來提升壓縮效率？",
    options: [
      "頻率域預測",
      "相鄰像素差分預測 (DPCM)",
      "區塊匹配預測",
      "雙線性插值預測"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "Lossless RAW compression 通常使用 DPCM (Differential Pulse-Code Modulation)，利用相鄰像素的相關性進行預測，只記錄預測殘差。由於 RAW 的 Bayer pattern 中相鄰同色像素間差異通常很小，殘差值集中在零附近，熵編碼可以非常高效地壓縮。",
    imageDesc: "",
    scenario: "",
    hint: "自然影像中相鄰像素通常很相似。"
  },
  {
    id: "compression_041",
    category: "compression",
    type: "fillblank",
    difficulty: 3,
    question: "UBWC 是 Qualcomm 的 frame buffer compression 技術，全名為 Universal _____ Compression。",
    options: [],
    answer: "Bandwidth",
    acceptAlso: ["bandwidth"],
    explanation: "UBWC (Universal Bandwidth Compression) 是 Qualcomm Snapdragon SoC 的統一頻寬壓縮技術。它在 ISP、GPU、Display、Video 等多個 IP 之間提供透明的 lossless/lossy 壓縮，可減少 40-50% 的 memory bandwidth 消耗，顯著降低功耗。",
    imageDesc: "",
    scenario: "",
    hint: "這個技術的主要目標是減少記憶體頻寬使用。"
  },
  {
    id: "compression_042",
    category: "compression",
    type: "multiple",
    difficulty: 3,
    question: "下列哪些是 H.265/HEVC 相較 H.264/AVC 的改進？（複選）",
    options: [
      "更大的 coding block（CTU 最大 64×64）",
      "支援 35 種 intra prediction 方向",
      "使用 CABAC 取代 CAVLC 作為唯一的 entropy coding",
      "取消了 B frame 的使用"
    ],
    answer: [0, 1, 2],
    acceptAlso: [],
    explanation: "HEVC 的 CTU 最大支援 64×64（vs H.264 的 16×16 macroblock）；Intra prediction 支援 35 種方向（vs H.264 的 9 種）；HEVC 僅使用 CABAC 作為 entropy coding（H.264 還有較簡單的 CAVLC 選項）。HEVC 仍然支援 B frame，並未取消。",
    imageDesc: "",
    scenario: "",
    hint: "HEVC 在各方面都比 H.264 更靈活、更複雜。"
  },
  {
    id: "compression_043",
    category: "compression",
    type: "single",
    difficulty: 3,
    question: "在 ISP 的 JPEG 編碼器中，為何 DC 係數使用 DPCM 編碼而 AC 係數使用 RLE + Huffman？",
    options: [
      "DC 和 AC 的編碼方式其實相同",
      "因為相鄰區塊的 DC 值相近，適合差分編碼；AC 係數量化後大量為零，適合遊程編碼",
      "因為 DC 係數比 AC 係數多",
      "為了降低硬體複雜度而隨意選擇"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "DC 係數代表 8×8 區塊的平均值，相鄰區塊的 DC 值通常非常接近，使用 DPCM 差分編碼可大幅降低需要編碼的數值範圍。AC 係數經過量化和 zigzag 掃描後，大量高頻係數為零，非常適合 RLE 來壓縮連續的零值，再用 Huffman coding 進行最終的 entropy coding。",
    imageDesc: "",
    scenario: "",
    hint: "DC 是區塊的均值，AC 是其他頻率分量。"
  },
  {
    id: "compression_044",
    category: "compression",
    type: "truefalse",
    difficulty: 3,
    question: "CABAC (Context-Adaptive Binary Arithmetic Coding) 的壓縮效率通常比 CAVLC 高約 10-15%。",
    options: [],
    answer: true,
    acceptAlso: [],
    explanation: "CABAC 利用上下文自適應模型和 arithmetic coding，通常比 CAVLC (Context-Adaptive Variable-Length Coding) 的壓縮效率高約 10-15%。但 CABAC 的計算複雜度也更高，序列化特性使其不易平行化。在 H.265 中只保留了 CABAC，淘汰了 CAVLC。",
    imageDesc: "",
    scenario: "",
    hint: "Arithmetic coding 本身就比 variable-length coding 更接近理論極限。"
  },
  {
    id: "compression_045",
    category: "compression",
    type: "image",
    difficulty: 3,
    question: "觀察下方影像描述。在 4:2:0 chroma subsampling 後，一個包含紅色細線條的影像會產生什麼現象？",
    options: [
      "線條完全消失",
      "線條的色彩會擴散模糊（color bleeding）",
      "線條變成綠色",
      "線條不受影響"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "4:2:0 subsampling 將色度解析度降為亮度的 1/4。當紅色細線條寬度接近或小於色度取樣間距時，其色度資訊會與周圍像素混合，導致紅色向兩側擴散模糊。亮度資訊保持完整所以線條形狀還在，但色彩會 bleed 到相鄰區域。",
    imageDesc: "一條清晰的紅色細線畫在灰色背景上。經過 4:2:0 chroma subsampling 後，紅色線條的邊緣變得模糊，紅色擴散到了線條兩側的灰色區域中。",
    scenario: "",
    hint: "色度解析度降低主要影響色彩邊界的銳利度。"
  },
  {
    id: "compression_046",
    category: "compression",
    type: "scenario",
    difficulty: 3,
    question: "你正在評估兩個 JPEG 編碼器的品質。編碼器 A 在 compression ratio 20:1 時 PSNR 為 32 dB、SSIM 為 0.85；編碼器 B 同樣 20:1 時 PSNR 為 34 dB、SSIM 為 0.82。哪個編碼器的主觀品質可能更好？",
    options: [
      "編碼器 A，因為 SSIM 更高",
      "編碼器 B，因為 PSNR 更高",
      "兩者相同",
      "無法判斷"
    ],
    answer: 0,
    acceptAlso: [],
    explanation: "當 PSNR 和 SSIM 的結果不一致時，SSIM 通常更能反映主觀品質。SSIM 考慮結構相似性，更貼近人類視覺系統的感知。編碼器 B 的 PSNR 更高可能是因為整體 MSE 較低，但局部結構失真較嚴重（例如 blocking artifact），導致 SSIM 較低。",
    imageDesc: "",
    scenario: "你負責為 ISP 選擇 JPEG 硬體編碼器 IP，需要根據客觀品質指標做出決策。兩個候選 IP 的規格如題目所述。",
    hint: "哪個指標更貼近人眼感知？"
  },
  {
    id: "compression_047",
    category: "compression",
    type: "single",
    difficulty: 3,
    question: "在 transform coding 中，為何 DCT 比 DFT (Discrete Fourier Transform) 更適合影像壓縮？",
    options: [
      "DCT 計算速度更快",
      "DCT 的基底函數在邊界連續，能量集中效果更好，減少邊界不連續性",
      "DFT 無法處理二維訊號",
      "DCT 可以處理彩色影像，DFT 不行"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "DCT 等效於對信號做偶對稱延拓後再做 DFT，其基底函數在區塊邊界自然連續，不會產生 DFT 因周期性延拓造成的邊界不連續問題。這使得 DCT 的能量集中在少數低頻係數的效果優於 DFT，適合基於區塊的壓縮。",
    imageDesc: "",
    scenario: "",
    hint: "考慮信號在區塊邊界的延拓方式。"
  },
  {
    id: "compression_048",
    category: "compression",
    type: "ordering",
    difficulty: 3,
    question: "請將以下 ISP 輸出到最終壓縮視訊的流程按正確順序排列：",
    options: [],
    answer: 0,
    acceptAlso: [],
    explanation: "ISP 完成影像處理後，先進行色彩空間轉換（RGB → YUV），接著做 chroma subsampling（通常 4:2:0），然後透過 DMA 將資料寫入 frame buffer。視訊編碼器從 frame buffer 讀取資料進行編碼（motion estimation、transform、quantization、entropy coding），最後進行 bitrate control 確保輸出符合目標位元率。",
    imageDesc: "",
    scenario: "",
    hint: "從 ISP 處理完成到最終壓縮輸出的順序。",
    items: [
      "ISP 影像處理完成",
      "色彩空間轉換 (RGB → YUV)",
      "Chroma subsampling (4:2:0)",
      "DMA 寫入 frame buffer",
      "視訊編碼器讀取並壓縮",
      "Bitrate control 調整"
    ]
  },
  {
    id: "compression_049",
    category: "compression",
    type: "single",
    difficulty: 3,
    question: "HEIF 相較 JPEG 的一個關鍵技術優勢是支援哪種 prediction 技術？",
    options: [
      "只支援 intra prediction",
      "支援 inter prediction（利用同檔案中其他影像作為參考）",
      "不使用任何 prediction",
      "只支援 motion compensated prediction"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "HEIF 基於 HEVC 編碼，不僅支援 intra prediction（單張影像內部預測），還可利用 inter prediction 參考同一 HEIF 檔案中的其他影像（如連拍照片或 Live Photo 的相鄰幀），大幅提高壓縮效率。JPEG 僅能對每張影像獨立壓縮，無法利用影像間的冗餘。",
    imageDesc: "",
    scenario: "",
    hint: "HEIF 可以在單一檔案中儲存多張影像。"
  },
  {
    id: "compression_050",
    category: "compression",
    type: "scenario",
    difficulty: 3,
    question: "在 ISP 設計中，AFBC 壓縮後的 frame buffer 為何不能直接被不支援 AFBC 的 IP 模組讀取？",
    options: [
      "因為 AFBC 壓縮後的資料格式與記憶體位寬不匹配",
      "因為 AFBC 使用 tile-based 壓縮，header 中包含每個 tile 的偏移量和大小，非 AFBC IP 無法解析此格式",
      "因為 AFBC 會加密資料",
      "因為 AFBC 壓縮後的資料儲存在專用記憶體中"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "AFBC 將影像分割為 tile（如 16×16 或 32×8），每個 tile 獨立壓縮，壓縮後大小不固定。frame buffer 開頭有 header 記錄每個 tile 的位置和大小。非 AFBC 的 IP 模組期望線性排列的像素資料，無法解析 AFBC 的 tile header 和變長壓縮資料，因此需要 AFBC decoder 先解壓還原為線性格式。",
    imageDesc: "",
    scenario: "你正在整合一個第三方影像處理 IP 到 SoC 中，但該 IP 不支援 AFBC 格式。你需要理解為何不能直接將 ISP 的 AFBC 輸出餵給該 IP。",
    hint: "壓縮後的資料不再是線性排列的像素。"
  }
];
