const Q_DEMOSAIC = [
  // ========== Difficulty 1 (questions 001–017) ==========
  {
    id: "demosaic_001",
    category: "demosaic",
    type: "single",
    difficulty: 1,
    question: "在 Bayer CFA 中，哪種顏色的像素數量最多？",
    options: ["A. 紅色 (Red)", "B. 綠色 (Green)", "C. 藍色 (Blue)", "D. 白色 (White)"],
    answer: 1,
    acceptAlso: [],
    explanation: "Bayer pattern 中綠色像素佔 50%，紅色與藍色各佔 25%。這是因為人眼對綠色（亮度）最敏感，因此綠色通道的取樣密度最高。",
    imageDesc: "",
    scenario: "",
    hint: "想想人眼對哪種色光的靈敏度最高。",
    items: []
  },
  {
    id: "demosaic_002",
    category: "demosaic",
    type: "truefalse",
    difficulty: 1,
    question: "Demosaic 的目的是將單通道的 CFA raw 資料還原為全彩 RGB 影像。",
    options: [],
    answer: true,
    acceptAlso: [],
    explanation: "CFA sensor 每個像素只記錄一種顏色，demosaic（去馬賽克）透過插值將缺失的兩個色彩通道補齊，生成完整的三通道 RGB 影像。",
    imageDesc: "",
    scenario: "",
    hint: "每個感光元件只有一個 color filter。",
    items: []
  },
  {
    id: "demosaic_003",
    category: "demosaic",
    type: "single",
    difficulty: 1,
    question: "Bilinear interpolation 在 demosaic 中的主要缺點是什麼？",
    options: [
      "A. 計算量太大",
      "B. 容易在邊緣產生 color artifact",
      "C. 只能用於綠色通道",
      "D. 需要 GPU 加速"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "Bilinear interpolation 不考慮邊緣方向，在色彩跳變的邊界處會產生明顯的 false color 與 zipper artifact，因為它對所有方向一視同仁地做平均。",
    imageDesc: "",
    scenario: "",
    hint: "Bilinear 是最簡單的方法，沒有考慮影像的結構。",
    items: []
  },
  {
    id: "demosaic_004",
    category: "demosaic",
    type: "single",
    difficulty: 1,
    question: "以下何者不是常見的 demosaic artifact？",
    options: [
      "A. Zipper artifact",
      "B. False color",
      "C. Color moiré",
      "D. Motion blur"
    ],
    answer: 3,
    acceptAlso: [],
    explanation: "Zipper artifact、false color 和 color moiré 都是 demosaic 特有的偽影。Motion blur 則是由曝光時間過長或物體移動造成的，與 demosaic 無關。",
    imageDesc: "",
    scenario: "",
    hint: "哪一個跟插值算法完全無關？",
    items: []
  },
  {
    id: "demosaic_005",
    category: "demosaic",
    type: "truefalse",
    difficulty: 1,
    question: "在 Bayer pattern 中，綠色像素的排列方式為棋盤格 (checkerboard) 形式。",
    options: [],
    answer: true,
    acceptAlso: [],
    explanation: "Bayer CFA 的綠色像素交替分佈在每一行每一列，形成棋盤格排列。這種排列讓綠色通道在水平與垂直方向都有最高的取樣頻率。",
    imageDesc: "",
    scenario: "",
    hint: "觀察 RGGB 的 2x2 重複單元。",
    items: []
  },
  {
    id: "demosaic_006",
    category: "demosaic",
    type: "fillblank",
    difficulty: 1,
    question: "Demosaic 也常被稱為 CFA ______（英文），即色彩濾波陣列的插值還原過程。",
    options: [],
    answer: "interpolation",
    acceptAlso: ["Interpolation", "INTERPOLATION"],
    explanation: "Demosaic 的正式名稱為 CFA interpolation，指的是從 Color Filter Array 取得的單通道資料中，用插值方式重建完整色彩資訊的過程。",
    imageDesc: "",
    scenario: "",
    hint: "是一個以 I 開頭的英文單字。",
    items: []
  },
  {
    id: "demosaic_007",
    category: "demosaic",
    type: "single",
    difficulty: 1,
    question: "為什麼 demosaic 演算法通常優先處理 Green channel？",
    options: [
      "A. 綠色處理速度最快",
      "B. 綠色取樣密度最高，且對亮度貢獻最大",
      "C. 綠色 artifact 最嚴重",
      "D. 紅藍通道不需要插值"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "Green channel 佔 Bayer pattern 的 50%，取樣密度最高；同時綠色對人眼亮度感知貢獻最大（約 59%），因此先精確重建 Green channel，再利用 G 值輔助估計 R 和 B，可以提高整體品質。",
    imageDesc: "",
    scenario: "",
    hint: "想想 Luminance = 0.299R + 0.587G + 0.114B。",
    items: []
  },
  {
    id: "demosaic_008",
    category: "demosaic",
    type: "single",
    difficulty: 1,
    question: "Zipper artifact 最常出現在影像的哪種區域？",
    options: [
      "A. 平坦區域",
      "B. 高對比邊緣",
      "C. 暗部陰影",
      "D. 天空區域"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "Zipper artifact 是沿著邊緣出現的交替亮暗或色彩跳變現象，發生在高對比邊緣處，因為 demosaic 演算法在邊緣兩側取到不同顏色的樣本進行插值。",
    imageDesc: "",
    scenario: "",
    hint: "需要色彩劇烈變化的區域。",
    items: []
  },
  {
    id: "demosaic_009",
    category: "demosaic",
    type: "truefalse",
    difficulty: 1,
    question: "Bicubic interpolation 考慮了比 bilinear 更多的鄰近像素，因此在 demosaic 中通常能產生較平滑的結果。",
    options: [],
    answer: true,
    acceptAlso: [],
    explanation: "Bilinear 使用 2x2 鄰域，bicubic 使用 4x4 鄰域。更多的取樣點讓 bicubic 能更好地保持曲線的連續性，在平滑區域產生較少的塊狀偽影。但 bicubic 仍然不是 edge-aware 的方法。",
    imageDesc: "",
    scenario: "",
    hint: "比較兩種方法使用的鄰域大小。",
    items: []
  },
  {
    id: "demosaic_010",
    category: "demosaic",
    type: "ordering",
    difficulty: 1,
    question: "請依照 demosaic pipeline 的一般處理順序排列以下步驟：",
    options: [],
    answer: 0,
    acceptAlso: [],
    explanation: "典型流程：先插值綠色（取樣密度最高，最可靠），接著利用 G 通道資訊輔助插值紅藍通道，最後做 artifact suppression 以消除 zipper 和 false color。",
    imageDesc: "",
    scenario: "",
    hint: "先處理最可靠的通道。",
    items: [
      "綠色通道插值 (Green interpolation)",
      "紅色與藍色通道插值 (R/B interpolation)",
      "Artifact suppression (偽影抑制)"
    ]
  },
  {
    id: "demosaic_011",
    category: "demosaic",
    type: "single",
    difficulty: 1,
    question: "Color moiré 在 demosaic 中的主要成因是什麼？",
    options: [
      "A. 感光元件過熱",
      "B. 高頻空間細節超過 CFA 的 Nyquist 取樣率",
      "C. 白平衡設定錯誤",
      "D. ISO 設定過高"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "當影像中的空間頻率超過 CFA 在該色彩通道的 Nyquist frequency 時，就會產生 aliasing，表現為不存在的彩色條紋，即 color moiré。",
    imageDesc: "",
    scenario: "",
    hint: "這跟取樣定理 (Nyquist theorem) 有關。",
    items: []
  },
  {
    id: "demosaic_012",
    category: "demosaic",
    type: "single",
    difficulty: 1,
    question: "以下何者是 edge-directed interpolation 的核心概念？",
    options: [
      "A. 沿著邊緣方向插值，避免跨越邊緣取樣",
      "B. 只使用最近的一個像素",
      "C. 對所有方向使用相同權重",
      "D. 僅在水平方向插值"
    ],
    answer: 0,
    acceptAlso: [],
    explanation: "Edge-directed interpolation 先偵測局部邊緣方向，然後沿著邊緣（而非穿越邊緣）進行插值。這樣可以避免在邊緣兩側的不同色彩間做平均，大幅減少 zipper artifact 和 false color。",
    imageDesc: "",
    scenario: "",
    hint: "關鍵是「方向性」。",
    items: []
  },
  {
    id: "demosaic_013",
    category: "demosaic",
    type: "fillblank",
    difficulty: 1,
    question: "Bayer pattern 最常見的排列方式 RGGB 中，每個 2x2 的基本單元包含 1 個 R、______ 個 G、1 個 B。",
    options: [],
    answer: "2",
    acceptAlso: ["二", "兩"],
    explanation: "RGGB 的 2x2 重複單元中有 1R、2G、1B，綠色佔了一半的像素量，這也是為什麼綠色通道解析度最高。",
    imageDesc: "",
    scenario: "",
    hint: "2x2 = 4 個像素，R 和 B 各 1 個。",
    items: []
  },
  {
    id: "demosaic_014",
    category: "demosaic",
    type: "truefalse",
    difficulty: 1,
    question: "False color artifact 是指在影像中出現原始場景不存在的虛假色彩。",
    options: [],
    answer: true,
    acceptAlso: [],
    explanation: "False color 是 demosaic 過程中因為插值錯誤而引入的不真實色彩，特別容易出現在高頻紋理區域（如織物、屋頂瓦片）。它是 CFA aliasing 的直接表現。",
    imageDesc: "",
    scenario: "",
    hint: "想想「虛假」的意思。",
    items: []
  },
  {
    id: "demosaic_015",
    category: "demosaic",
    type: "image",
    difficulty: 1,
    question: "觀察下圖所描述的 Bayer pattern 排列，在紅色像素位置需要插值哪兩個通道？",
    options: [
      "A. Green 和 Blue",
      "B. Red 和 Green",
      "C. Red 和 Blue",
      "D. 三個通道都需要插值"
    ],
    answer: 0,
    acceptAlso: [],
    explanation: "在紅色像素位置，已知 R 值，需要透過插值計算 G 和 B 值；同理，在藍色像素位置需要插值 G 和 R，在綠色像素位置需要插值 R 和 B。",
    imageDesc: "一個 4x4 的 Bayer pattern 示意圖，以 RGGB 排列，紅色像素被圈選標記。",
    scenario: "",
    hint: "已有的通道不需要插值。",
    items: []
  },
  {
    id: "demosaic_016",
    category: "demosaic",
    type: "single",
    difficulty: 1,
    question: "下列哪一種 demosaic 方法的計算複雜度最低？",
    options: [
      "A. Bilinear interpolation",
      "B. AHD (Adaptive Homogeneity-Directed)",
      "C. DLMMSE",
      "D. Malvar-He-Cutler"
    ],
    answer: 0,
    acceptAlso: [],
    explanation: "Bilinear interpolation 只需要對鄰近像素做簡單的加權平均，計算量最小，適合即時預覽等對速度要求極高的場景，但品質最差。",
    imageDesc: "",
    scenario: "",
    hint: "最簡單的方法通常計算量最小。",
    items: []
  },
  {
    id: "demosaic_017",
    category: "demosaic",
    type: "single",
    difficulty: 1,
    question: "Gradient-based demosaic 方法利用什麼資訊來決定插值方向？",
    options: [
      "A. 像素的色溫",
      "B. 水平與垂直方向的亮度梯度差異",
      "C. 影像的 metadata",
      "D. 隨機選擇方向"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "Gradient-based 方法計算水平與垂直（有時也包括對角線）方向的梯度值，選擇梯度較小（變化較平緩）的方向來插值，以避免跨越邊緣。",
    imageDesc: "",
    scenario: "",
    hint: "梯度代表亮度的變化率。",
    items: []
  },

  // ========== Difficulty 2 (questions 018–034) ==========
  {
    id: "demosaic_018",
    category: "demosaic",
    type: "single",
    difficulty: 2,
    question: "Malvar-He-Cutler (MHC) 演算法的主要創新之處是什麼？",
    options: [
      "A. 使用機器學習訓練插值核",
      "B. 利用同位置已知通道的 Laplacian 修正項來改善插值精度",
      "C. 僅使用綠色通道進行插值",
      "D. 採用頻域濾波"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "MHC 演算法在傳統 bilinear 的基礎上，加入了已知色彩通道的二階梯度（Laplacian）修正項。例如在插值 G 時，利用已知的 R 或 B 的 Laplacian 做色彩差異補償，以 5x5 filter 實現，計算效率高且品質顯著優於 bilinear。",
    imageDesc: "",
    scenario: "",
    hint: "想想如何利用已知通道的資訊來修正。",
    items: []
  },
  {
    id: "demosaic_019",
    category: "demosaic",
    type: "multiple",
    difficulty: 2,
    question: "以下哪些是 adaptive demosaicing 演算法的共同特徵？（選擇所有正確答案）",
    options: [
      "A. 根據局部影像內容調整插值策略",
      "B. 在邊緣區域偵測梯度方向",
      "C. 所有像素使用完全相同的固定 kernel",
      "D. 在平坦區域可能退化為較簡單的插值"
    ],
    answer: [0, 1, 3],
    acceptAlso: [],
    explanation: "Adaptive demosaicing 的核心是「自適應」：根據局部內容改變策略(A)、利用梯度偵測邊緣方向(B)、在平坦區域不需要複雜的邊緣處理所以可以簡化(D)。選項 C 描述的是 non-adaptive 方法如 bilinear。",
    imageDesc: "",
    scenario: "",
    hint: "「Adaptive」意味著不是固定不變的。",
    items: []
  },
  {
    id: "demosaic_020",
    category: "demosaic",
    type: "scenario",
    difficulty: 2,
    question: "一位 ISP 工程師發現用 bilinear demosaic 處理一張磚牆照片時，磚牆的水平灰縫線條出現了紅綠交替的色彩條紋。這最可能是什麼問題？",
    options: [
      "A. 感光元件壞點造成的雜訊",
      "B. Zipper artifact，因為 bilinear 跨越了水平邊緣進行插值",
      "C. 鏡頭色散 (chromatic aberration)",
      "D. 白平衡的色溫偏移"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "磚牆的灰縫形成清晰的水平邊緣，bilinear interpolation 在這些邊緣處會從邊緣兩側取樣混合，導致沿邊緣方向出現交替的色彩錯誤，這就是典型的 zipper artifact。改用 edge-directed 方法可大幅改善。",
    imageDesc: "",
    scenario: "ISP 團隊正在評估一款低功耗 ISP 晶片的 demosaic 品質，目前使用 bilinear interpolation。測試影像包含大量建築紋理。",
    hint: "Bilinear 不會區分邊緣方向。",
    items: []
  },
  {
    id: "demosaic_021",
    category: "demosaic",
    type: "single",
    difficulty: 2,
    question: "AHD (Adaptive Homogeneity-Directed) 演算法的核心步驟是什麼？",
    options: [
      "A. 使用 neural network 預測插值方向",
      "B. 分別在水平與垂直方向插值，再以 homogeneity 指標選擇較佳結果",
      "C. 在頻域中分離亮度與色度後個別插值",
      "D. 僅在綠色通道使用 adaptive 方法"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "AHD 先分別沿水平和垂直方向做 directional interpolation（通常使用色差空間），然後將結果轉換到 CIELab 色彩空間，計算每個像素周圍的 homogeneity（同質性）指標，選擇同質性較高的方向作為最終結果。",
    imageDesc: "",
    scenario: "",
    hint: "名字裡的 H 代表 Homogeneity。",
    items: []
  },
  {
    id: "demosaic_022",
    category: "demosaic",
    type: "single",
    difficulty: 2,
    question: "在 chrominance estimation from luminance 的方法中，通常假設什麼性質在局部區域成立？",
    options: [
      "A. 亮度 (luminance) 恆定",
      "B. 色差 (color difference) 在局部區域平滑變化",
      "C. RGB 三通道完全相同",
      "D. 色度 (chrominance) 與亮度無關"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "此方法假設 R-G 和 B-G（色差）在局部區域內變化緩慢（即色度的空間頻率低於亮度）。因此先精確重建 G（代表亮度主體），再對色差做低通插值，就能得到較好的 R 和 B 估計。",
    imageDesc: "",
    scenario: "",
    hint: "自然影像中，色彩通常比邊緣更平滑。",
    items: []
  },
  {
    id: "demosaic_023",
    category: "demosaic",
    type: "truefalse",
    difficulty: 2,
    question: "在頻域分析中，Bayer CFA 的取樣會造成亮度 (luminance) 和色度 (chrominance) 頻譜在基帶產生重疊 (aliasing)。",
    options: [],
    answer: true,
    acceptAlso: [],
    explanation: "Bayer CFA 的 R、B 通道取樣率僅為全解析度的 1/4，G 通道為 1/2。在頻域中，亮度和色度的頻譜會因為欠取樣而在基帶產生重疊。高品質的 demosaic 演算法本質上就是在做 luminance-chrominance 的頻譜分離。",
    imageDesc: "",
    scenario: "",
    hint: "想想取樣不足時在頻域會發生什麼。",
    items: []
  },
  {
    id: "demosaic_024",
    category: "demosaic",
    type: "multiple",
    difficulty: 2,
    question: "以下哪些方法可以有效減少 demosaic 產生的 false color？（選擇所有正確答案）",
    options: [
      "A. 在色差域 (R-G, B-G) 做中值濾波 (median filter)",
      "B. 增加曝光時間",
      "C. 使用 edge-directed interpolation",
      "D. 在 demosaic 後對色度通道做低通濾波"
    ],
    answer: [0, 2, 3],
    acceptAlso: [],
    explanation: "色差域中值濾波(A)可以去除離群的色彩偽影；edge-directed interpolation(C)從源頭減少跨邊緣混色；色度低通濾波(D)可以壓制高頻的假色彩。增加曝光時間(B)與 false color 的產生機制無關。",
    imageDesc: "",
    scenario: "",
    hint: "False color 本質上是高頻的色度雜訊。",
    items: []
  },
  {
    id: "demosaic_025",
    category: "demosaic",
    type: "single",
    difficulty: 2,
    question: "Directional filtering 在 demosaic 中計算水平和垂直梯度時，以下哪個公式最常用於判斷邊緣方向？",
    options: [
      "A. 選擇梯度較大的方向進行插值",
      "B. 選擇梯度較小的方向進行插值",
      "C. 取兩方向梯度的平均值",
      "D. 忽略梯度資訊，僅用距離加權"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "梯度小的方向代表該方向上色彩/亮度變化平緩（沿著邊緣而非穿越邊緣），因此沿該方向插值可以避免混入邊緣另一側的像素，減少 artifact。",
    imageDesc: "",
    scenario: "",
    hint: "我們希望沿著平滑的方向插值。",
    items: []
  },
  {
    id: "demosaic_026",
    category: "demosaic",
    type: "fillblank",
    difficulty: 2,
    question: "DLMMSE 演算法的全稱是 Directional Linear Minimum ______ Error，它利用統計估計理論來最佳化插值結果。",
    options: [],
    answer: "Mean Square",
    acceptAlso: ["Mean-Square", "mean square", "mean-square", "Mean Squared", "mean squared"],
    explanation: "DLMMSE (Directional Linear Minimum Mean Square Error) 結合了方向性分析和 LMMSE 統計估計，在每個像素先判斷局部方向（水平/垂直/均勻），然後使用對應方向的 LMMSE 估計器來計算插值，能有效平衡雜訊抑制與細節保留。",
    imageDesc: "",
    scenario: "",
    hint: "MSE 代表什麼？",
    items: []
  },
  {
    id: "demosaic_027",
    category: "demosaic",
    type: "scenario",
    difficulty: 2,
    question: "工程師在測試中發現一張包含細密斜條紋布料的影像，demosaic 後出現了大範圍的彩虹色偽彩。這最可能是什麼現象？該如何解決？",
    options: [
      "A. Color moiré，可在 CFA 前加 optical low-pass filter (OLPF) 或改用抗混疊能力更強的 demosaic 演算法",
      "B. 白平衡錯誤，需要重新校正色溫",
      "C. Lens flare，需要加遮光罩",
      "D. Dead pixel，需要做壞點校正"
    ],
    answer: 0,
    acceptAlso: [],
    explanation: "細密斜條紋的空間頻率接近或超過 CFA 的 Nyquist limit，造成不同色彩通道的 aliasing pattern 不一致，疊加後出現彩虹色的 color moiré。解決方式包括使用 OLPF 在光學端降低高頻能量，或使用具有更好抗混疊能力的 demosaic 演算法。",
    imageDesc: "",
    scenario: "一家手機廠商的 ISP 團隊正在調校相機畫質，測試影像包含各種布料材質。",
    hint: "細密紋理 + 彩色偽影 = 取樣問題。",
    items: []
  },
  {
    id: "demosaic_028",
    category: "demosaic",
    type: "single",
    difficulty: 2,
    question: "Quad Bayer pattern（如 Samsung Tetracell）在 full-resolution demosaic 時面臨什麼特殊挑戰？",
    options: [
      "A. 完全無法 demosaic",
      "B. 相鄰的同色 2x2 像素組導致有效取樣頻率降低，需要特殊的 remosaic 再 demosaic",
      "C. 只能輸出黑白影像",
      "D. 必須使用 GPU 才能處理"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "Quad Bayer 的每個色彩佔 2x2 像素塊，在 binning 模式下等效於一般 Bayer。但在 full-resolution 模式下，需要先做 remosaic（將 Quad Bayer 重新排列為標準 Bayer 排列），再進行常規 demosaic，或使用專門設計的 Quad Bayer demosaic 算法。",
    imageDesc: "",
    scenario: "",
    hint: "想想 2x2 同色像素塊的特殊排列。",
    items: []
  },
  {
    id: "demosaic_029",
    category: "demosaic",
    type: "ordering",
    difficulty: 2,
    question: "依照計算複雜度由低到高排列以下 demosaic 演算法：",
    options: [],
    answer: 0,
    acceptAlso: [],
    explanation: "Bilinear 最簡單（固定 kernel 加權平均）；MHC 在 bilinear 基礎上加了 Laplacian 修正但仍用固定 kernel；Gradient-based 需要計算並比較多方向梯度；AHD 需要分方向插值、轉換色彩空間、計算 homogeneity map，複雜度最高。",
    imageDesc: "",
    scenario: "",
    hint: "越 adaptive 的方法計算量通常越大。",
    items: [
      "Bilinear interpolation",
      "Malvar-He-Cutler (MHC)",
      "Gradient-based directional",
      "AHD (Adaptive Homogeneity-Directed)"
    ]
  },
  {
    id: "demosaic_030",
    category: "demosaic",
    type: "single",
    difficulty: 2,
    question: "RGBW CFA pattern 加入白色 (W) 像素的主要目的是什麼？",
    options: [
      "A. 增加色彩飽和度",
      "B. 提高低光環境下的感光度 (sensitivity)",
      "C. 減少 demosaic 的計算量",
      "D. 增加影像的空間解析度"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "White pixel 沒有色彩濾光片，能接收全部波段的光線，因此感光度比有色濾光片的像素高 2-3 倍。RGBW pattern 在低光環境中 SNR 更好。但缺點是每個色彩通道的取樣密度進一步降低，demosaic 更具挑戰。",
    imageDesc: "",
    scenario: "",
    hint: "沒有濾光片意味著什麼？",
    items: []
  },
  {
    id: "demosaic_031",
    category: "demosaic",
    type: "truefalse",
    difficulty: 2,
    question: "Maze artifact 是一種在平坦區域出現的網格狀色彩偽影，外觀類似迷宮圖案。",
    options: [],
    answer: true,
    acceptAlso: [],
    explanation: "Maze artifact（迷宮偽影）通常出現在低對比或接近飽和的區域，表現為棋盤格或迷宮狀的色彩圖案。它的成因是 demosaic 演算法在近似均勻的區域中，因為微小的數值差異而做出不一致的方向判斷。",
    imageDesc: "",
    scenario: "",
    hint: "名稱已經暗示了它的外觀。",
    items: []
  },
  {
    id: "demosaic_032",
    category: "demosaic",
    type: "single",
    difficulty: 2,
    question: "在 ISP pipeline 中，demosaic 通常在下列哪個處理步驟之後進行？",
    options: [
      "A. Gamma correction",
      "B. Black level correction 和 lens shading correction",
      "C. JPEG compression",
      "D. Color space conversion (sRGB)"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "Demosaic 在 ISP pipeline 的前段處理，通常在 black level subtraction、defect pixel correction、lens shading correction 之後，但在 white balance、color correction matrix、gamma correction 之前（或在 white balance 之後、gamma 之前）。",
    imageDesc: "",
    scenario: "",
    hint: "Demosaic 是 raw domain 的處理。",
    items: []
  },
  {
    id: "demosaic_033",
    category: "demosaic",
    type: "fillblank",
    difficulty: 2,
    question: "在頻域分析中，Bayer CFA 取樣後綠色通道的 baseband 頻譜位於原點，而其 modulated 副本位於 Nyquist 頻率的 (______, ______) 位置。",
    options: [],
    answer: "π, π",
    acceptAlso: ["(π, π)", "pi, pi", "(pi, pi)"],
    explanation: "Green channel 的棋盤格取樣等效於在水平和垂直方向各以半像素週期調變，其頻譜副本出現在 (π, π) 位置（即 2D 頻域的角落）。理解這個頻譜分佈對於設計頻域 demosaic 濾波器至關重要。",
    imageDesc: "",
    scenario: "",
    hint: "棋盤格取樣的調變頻率是多少？",
    items: []
  },
  {
    id: "demosaic_034",
    category: "demosaic",
    type: "image",
    difficulty: 2,
    question: "觀察下圖描述的 demosaic 前後對比：左側為 bilinear demosaic 結果，右側為 edge-directed demosaic 結果。在黑白交界的斜邊處，哪種方法產生了更明顯的 zipper artifact？",
    options: [
      "A. 左側 (Bilinear)，因為它不考慮邊緣方向",
      "B. 右側 (Edge-directed)，因為方向判斷可能出錯",
      "C. 兩者同樣嚴重",
      "D. 都不會產生 zipper artifact"
    ],
    answer: 0,
    acceptAlso: [],
    explanation: "Bilinear interpolation 對所有方向使用相同的權重，在斜邊處會從邊緣兩側取樣，造成明顯的 zipper artifact。Edge-directed 方法能偵測斜邊方向並沿邊緣插值，大幅減少這種偽影。",
    imageDesc: "左右對比圖：一條從左上到右下的黑白斜邊。左圖 (bilinear) 在邊緣處有明顯的紅綠交替鋸齒狀色彩偽影；右圖 (edge-directed) 邊緣乾淨銳利。",
    scenario: "",
    hint: "哪種方法是 edge-aware？",
    items: []
  },

  // ========== Difficulty 3 (questions 035–050) ==========
  {
    id: "demosaic_035",
    category: "demosaic",
    type: "single",
    difficulty: 3,
    question: "在 Malvar-He-Cutler 演算法中，用於在 Green pixel 位置估計 Red 值的 5x5 kernel 中，哪種修正項起了關鍵作用？",
    options: [
      "A. Red 鄰域的 Gaussian 加權平均",
      "B. Green channel 的二階梯度 (Laplacian of Green)",
      "C. Blue channel 的一階梯度",
      "D. 該像素的 white balance gain"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "MHC 的核心 insight 是：在已知 G 的位置估計 R 時，除了對鄰近 R 像素做加權平均外，還加入 G 通道的 Laplacian（∇²G）作為修正項。由於 R-G 色差在局部平滑，G 的二階梯度可以準確預測 R 在該點的高頻偏離量，形成一個線性 5x5 fixed kernel，兼顧品質與效率。",
    imageDesc: "",
    scenario: "",
    hint: "利用已知通道的高頻資訊來補償。",
    items: []
  },
  {
    id: "demosaic_036",
    category: "demosaic",
    type: "multiple",
    difficulty: 3,
    question: "以下哪些是 AHD 演算法在選擇最終插值方向時使用的 homogeneity metric 的特性？（選擇所有正確答案）",
    options: [
      "A. 在 CIELab 色彩空間中計算以反映人眼感知",
      "B. 比較每個像素與其鄰域的色彩一致性",
      "C. 直接比較 RGB 數值的方差",
      "D. Homogeneity 值越高代表該方向的插值結果越可靠"
    ],
    answer: [0, 1, 3],
    acceptAlso: [],
    explanation: "AHD 將水平和垂直兩個方向的插值結果都轉換到 CIELab 空間(A)，計算每個像素與鄰近像素在 L 和 C(ab) 上的差異來衡量同質性(B)，同質性越高代表該方向插值越平滑一致(D)。它不是直接比較 RGB 方差(C)，而是在感知均勻的色彩空間中做比較。",
    imageDesc: "",
    scenario: "",
    hint: "AHD 使用了哪種色彩空間？",
    items: []
  },
  {
    id: "demosaic_037",
    category: "demosaic",
    type: "scenario",
    difficulty: 3,
    question: "ISP 工程師在設計車用相機的 demosaic 模組時，需要在 FPGA 上實現，要求延遲不超過 2 個 line buffer、支援 4K@30fps，且需要合理的畫質。以下哪個方案最合適？",
    options: [
      "A. AHD 演算法，因為品質最好",
      "B. Malvar-He-Cutler 或類似的固定 5x5 kernel 方法",
      "C. DLMMSE，因為 LMMSE 估計最精確",
      "D. 使用 GPU 運行 deep learning demosaic"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "FPGA 實現需要固定的硬體資源和可預測的延遲。MHC 使用固定的 5x5 kernel（僅需 4 個 line buffer），無需條件分支或複雜的方向判斷，非常適合硬體流水線實現。AHD 需要 CIELab 轉換和兩次完整插值；DLMMSE 需要統計量計算和大 window；GPU deep learning 不適合車用 FPGA。",
    imageDesc: "",
    scenario: "車用 ADAS 相機的 ISP FPGA 設計，資源受限，需要確定性的處理延遲。",
    hint: "FPGA 適合固定管線的演算法。",
    items: []
  },
  {
    id: "demosaic_038",
    category: "demosaic",
    type: "single",
    difficulty: 3,
    question: "從頻域角度分析，Bayer CFA 取樣後 Red channel 的基帶頻譜佔據的空間頻率範圍是 full resolution 的多少？",
    options: [
      "A. 1/2 x 1/2 (水平 x 垂直)",
      "B. 全頻帶",
      "C. 1/4 x 1/4",
      "D. 1/2 x 1 (僅水平降低)"
    ],
    answer: 0,
    acceptAlso: [],
    explanation: "Red pixel 在 Bayer pattern 中水平和垂直方向各隔一個像素取樣，取樣率在兩個方向都是全解析度的 1/2。根據 Nyquist 定理，Red channel 能無混疊表示的最高頻率在水平和垂直方向各為全解析度 Nyquist 頻率的 1/2。",
    imageDesc: "",
    scenario: "",
    hint: "Red 在水平和垂直方向的取樣間距各是多少？",
    items: []
  },
  {
    id: "demosaic_039",
    category: "demosaic",
    type: "fillblank",
    difficulty: 3,
    question: "在 DLMMSE 演算法中，方向性估計使用的統計量是局部的 ______ 和 covariance，用於計算 Wiener filter 係數以最小化均方誤差。",
    options: [],
    answer: "variance",
    acceptAlso: ["Variance", "變異數", "方差"],
    explanation: "DLMMSE 在每個方向（水平/垂直）計算局部的 variance 和 covariance 統計量，這些用於建構 directional Wiener filter。Wiener filter 的係數由信號方差和雜訊方差的比值決定，在 SNR 低時趨向平滑，SNR 高時趨向保留原始值，達到 LMMSE 最佳化。",
    imageDesc: "",
    scenario: "",
    hint: "Wiener filter 需要哪些二階統計量？",
    items: []
  },
  {
    id: "demosaic_040",
    category: "demosaic",
    type: "single",
    difficulty: 3,
    question: "在 Quad Bayer remosaic 過程中，為什麼不能直接將 2x2 同色像素視為獨立取樣點來做標準 Bayer demosaic？",
    options: [
      "A. 因為 2x2 同色像素的位置太集中，實際空間取樣不均勻，直接 demosaic 會嚴重 alias",
      "B. 因為硬體不支援",
      "C. 因為 Quad Bayer 只有兩種顏色",
      "D. 因為像素數量太少"
    ],
    answer: 0,
    acceptAlso: [],
    explanation: "Quad Bayer 中 2x2 同色像素聚集在一起，與標準 Bayer 的均勻分佈不同。如果直接當作標準 Bayer 的 4 倍取樣來處理，相鄰同色像素之間幾乎沒有空間多樣性（它們看到的幾乎是同一個場景點），無法提供真正的高頻空間資訊。需要先透過 remosaic 算法重新估算像素值，使其近似於標準 Bayer 的均勻取樣排列。",
    imageDesc: "",
    scenario: "",
    hint: "空間取樣的均勻性很重要。",
    items: []
  },
  {
    id: "demosaic_041",
    category: "demosaic",
    type: "multiple",
    difficulty: 3,
    question: "在設計 FPGA/ASIC 的 demosaic 硬體時，以下哪些因素會直接影響 line buffer 的需求數量？（選擇所有正確答案）",
    options: [
      "A. 插值 kernel 的垂直尺寸",
      "B. 是否需要多 pass 處理（如 AHD 的兩方向插值加合併）",
      "C. 影像的水平解析度",
      "D. 是否需要在後處理中做 artifact suppression 的垂直鄰域"
    ],
    answer: [0, 1, 3],
    acceptAlso: [],
    explanation: "Line buffer 數量 = kernel 垂直尺寸 - 1(A)。多 pass 演算法可能需要額外的 line buffer 存儲中間結果(B)。後處理的垂直鄰域也需要額外 line buffer(D)。影像水平解析度(C)影響的是每個 line buffer 的長度（記憶體大小），而非 line buffer 的數量。",
    imageDesc: "",
    scenario: "",
    hint: "Line buffer 數量跟「垂直方向需要看幾行」有關。",
    items: []
  },
  {
    id: "demosaic_042",
    category: "demosaic",
    type: "scenario",
    difficulty: 3,
    question: "一位工程師測試了新開發的 edge-directed demosaic 演算法，在銳利邊緣的表現很好，但在灰色漸變天空等平坦區域出現了微弱的棋盤格狀色彩雜訊。問題最可能的根因是什麼？",
    options: [
      "A. 在平坦區域梯度值很小且受雜訊影響，方向判斷不穩定導致 maze artifact",
      "B. 演算法的邊緣偵測閾值太低",
      "C. 記憶體位元寬度不足導致精度損失",
      "D. 感光元件的固定圖案雜訊 (FPN)"
    ],
    answer: 0,
    acceptAlso: [],
    explanation: "在平坦區域，真實的梯度很小，此時感測器雜訊可能主導梯度計算的結果。如果演算法每個像素獨立判斷方向，雜訊會導致相鄰像素做出不同的方向選擇，形成 maze artifact。解決方式包括：在低梯度區域退化為 bilinear、加入方向一致性約束、或對梯度比較加入閾值（只有梯度差異夠大時才做方向性插值）。",
    imageDesc: "",
    scenario: "新演算法在邊緣測試圖表上表現優異，但在實際拍攝的天空場景中出現問題。",
    hint: "雜訊對微弱信號的影響。",
    items: []
  },
  {
    id: "demosaic_043",
    category: "demosaic",
    type: "single",
    difficulty: 3,
    question: "在頻域 demosaic 方法中，下列哪種技術被用來分離 luminance 和 chrominance 頻譜以減少 cross-talk？",
    options: [
      "A. Wiener deconvolution",
      "B. 利用 Bayer CFA 取樣的調變特性設計帶通/帶阻濾波器",
      "C. 直方圖均衡化",
      "D. Gabor filter"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "Bayer CFA 取樣等效於將 chrominance 調變到特定的載波頻率位置。頻域 demosaic 方法利用這個特性，設計適當的帶通濾波器提取各個頻譜分量，並用帶阻濾波器抑制交叉干擾（cross-talk），然後解調回基帶得到完整的 RGB。",
    imageDesc: "",
    scenario: "",
    hint: "CFA 取樣本質上是一種調變 (modulation)。",
    items: []
  },
  {
    id: "demosaic_044",
    category: "demosaic",
    type: "truefalse",
    difficulty: 3,
    question: "RGBW pattern 的 demosaic 比標準 Bayer 更容易，因為 W 像素提供了完整的亮度資訊。",
    options: [],
    answer: false,
    acceptAlso: [],
    explanation: "RGBW 的 demosaic 實際上更困難。雖然 W 像素提供了高 SNR 的亮度資訊，但每個彩色通道（R, G, B）的取樣密度比標準 Bayer 更低（各只有 1/4 的像素量），色彩重建更具挑戰。此外，W 通道的寬頻譜特性與 RGB 窄頻通道之間的關係更複雜，需要更精密的演算法來平衡亮度解析度與色彩精度。",
    imageDesc: "",
    scenario: "",
    hint: "取樣密度降低意味著什麼？",
    items: []
  },
  {
    id: "demosaic_045",
    category: "demosaic",
    type: "ordering",
    difficulty: 3,
    question: "依照 AHD 演算法的執行流程排列以下步驟：",
    options: [],
    answer: 0,
    acceptAlso: [],
    explanation: "AHD 流程：(1)先沿水平方向用 directional filter 做完整 RGB 插值；(2)同樣沿垂直方向做一次；(3)將兩組結果轉換到 CIELab 並計算每像素的 homogeneity map；(4)根據 homogeneity 選擇最終結果，可能還包括對選擇結果做 artifact 後處理。",
    imageDesc: "",
    scenario: "",
    hint: "先做兩個方向各自的插值。",
    items: [
      "水平方向 directional interpolation",
      "垂直方向 directional interpolation",
      "轉換至 CIELab 並計算 homogeneity map",
      "根據 homogeneity 選擇最佳方向並後處理"
    ]
  },
  {
    id: "demosaic_046",
    category: "demosaic",
    type: "single",
    difficulty: 3,
    question: "在 demosaic 演算法的量化評估中，CPSNR (Color Peak Signal-to-Noise Ratio) 相比標準 PSNR 的主要優勢是什麼？",
    options: [
      "A. 計算速度更快",
      "B. 同時考慮三個色彩通道的綜合誤差，更能反映色彩偽影的影響",
      "C. 只測量亮度通道，排除色彩干擾",
      "D. 使用對數刻度，範圍更大"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "CPSNR 計算 RGB 三通道的聯合 MSE（Mean Square Error），再換算為 PSNR。它比單獨看某一通道的 PSNR 更能反映 demosaic 演算法在色彩重建上的整體表現，特別是對 false color 等跨通道偽影更敏感。",
    imageDesc: "",
    scenario: "",
    hint: "C 代表 Color。",
    items: []
  },
  {
    id: "demosaic_047",
    category: "demosaic",
    type: "scenario",
    difficulty: 3,
    question: "團隊在評估一個新的 demosaic 演算法時發現：在 Kodak image dataset 上的 CPSNR 比 AHD 高 0.5dB，但主觀觀感上在某些影像的斜向紋理區域出現了明顯的 color banding。最可能的原因是什麼？",
    options: [
      "A. CPSNR 不夠高，需要進一步優化",
      "B. 演算法可能在方向判斷上使用了離散的有限方向（如僅水平/垂直），對斜向邊緣支援不足",
      "C. 測試影像有問題",
      "D. 顯示器的色域不夠"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "許多 edge-directed 演算法只支援水平和垂直兩個方向（如基本的 AHD）。雖然平均 CPSNR 可能很高，但在 45° 或其他斜向紋理上，兩個方向都不理想，混合結果可能出現 banding。更先進的方法會支援多方向（如對角線）或使用連續的方向加權來解決此問題。這也說明了單一指標（CPSNR）不足以全面評估 demosaic 品質。",
    imageDesc: "",
    scenario: "ISP 研發團隊正在決定是否採用此新演算法替換現有的 AHD 實現。",
    hint: "只支援兩個方向夠用嗎？",
    items: []
  },
  {
    id: "demosaic_048",
    category: "demosaic",
    type: "multiple",
    difficulty: 3,
    question: "以下哪些是在 non-Bayer CFA（如 RGBW、Quad Bayer）上進行 demosaic 時特別需要考慮的問題？（選擇所有正確答案）",
    options: [
      "A. 非均勻的色彩通道取樣密度需要不同的插值策略",
      "B. 傳統的 Bayer demosaic 演算法無法直接套用",
      "C. Cross-talk 校正因為不同 pixel 結構而更複雜",
      "D. 輸出影像的解析度必然比 Bayer 低"
    ],
    answer: [0, 1, 2],
    acceptAlso: [],
    explanation: "Non-Bayer CFA 的非均勻取樣(A)意味著不同通道需要不同的插值策略；傳統 Bayer demosaic 的 kernel 是針對 RGGB 排列設計的，無法直接用於其他 pattern(B)；不同的 pixel 結構（如 Quad Bayer 的大像素、RGBW 的無濾光片像素）有不同的 cross-talk 特性(C)。輸出解析度不必然更低(D)，RGBW 的 W 通道反而可能提升亮度解析度。",
    imageDesc: "",
    scenario: "",
    hint: "Non-Bayer 代表打破了傳統假設。",
    items: []
  },
  {
    id: "demosaic_049",
    category: "demosaic",
    type: "fillblank",
    difficulty: 3,
    question: "在 demosaic 的計算成本分析中，AHD 演算法的計算量大約是 bilinear 的 ______ 倍以上（數量級估計），因為它需要進行兩次方向插值、CIELab 轉換和 homogeneity 計算。",
    options: [],
    answer: "10",
    acceptAlso: ["十", "10x", "10倍"],
    explanation: "Bilinear 每個像素只需要幾次加法和一次除法。AHD 需要：兩次完整的方向性插值（各自需要比 bilinear 更多的運算）、RGB to CIELab 的非線性轉換（包含開立方根運算）、兩個方向的 homogeneity map 計算、以及最終的選擇與後處理。整體計算量通常是 bilinear 的 10-20 倍。",
    imageDesc: "",
    scenario: "",
    hint: "想想 CIELab 轉換本身就需要多少運算。",
    items: []
  },
  {
    id: "demosaic_050",
    category: "demosaic",
    type: "image",
    difficulty: 3,
    question: "觀察下圖所描述的 Bayer CFA 2D 頻域圖。在 full-resolution 取樣的頻域中 (ωx, ωy 各從 -π 到 π)，Bayer pattern 會在哪些位置產生 chrominance 的 modulated replica？",
    options: [
      "A. 僅在 (0, π) 和 (π, 0)",
      "B. 在 (0, π)、(π, 0) 和 (π, π) 三處",
      "C. 僅在 (π, π) 一處",
      "D. 均勻分佈在整個頻域"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "Bayer CFA 取樣在 2D 頻域中產生三個 modulated replica：Green 的調變副本在 (π, π)（因棋盤格取樣），Red 和 Blue 的調變副本在 (0, π) 和 (π, 0)（因水平和垂直方向各半的取樣）。完整的頻域 demosaic 需要設計濾波器將這些分量從基帶的 luminance 頻譜中分離出來。",
    imageDesc: "2D 頻域圖，橫軸 ωx 從 -π 到 π，縱軸 ωy 從 -π 到 π。原點 (0,0) 有 luminance baseband 頻譜（大橢圓），(π,π) 處有 G 通道的 modulated replica（小橢圓），(0,π) 和 (π,0) 處各有 R/B 的 modulated replica（小橢圓）。",
    scenario: "",
    hint: "考慮 Bayer pattern 中各色彩通道的取樣格點形狀。",
    items: []
  }
];
