const Q_HDR = [
  // ===== DIFFICULTY 1 (questions 001–017) =====
  {
    id: "hdr_001",
    category: "hdr",
    type: "single",
    difficulty: 1,
    question: "HDR 的全名是什麼？",
    options: ["High Definition Resolution", "High Dynamic Range", "Hybrid Digital Rendering", "High Density Raster"],
    answer: 1,
    acceptAlso: [],
    explanation: "HDR 全名為 High Dynamic Range（高動態範圍），指的是影像能同時記錄場景中亮部與暗部細節的能力，遠超傳統 SDR（Standard Dynamic Range）的表現範圍。",
    imageDesc: "",
    scenario: "",
    hint: "與影像能記錄的亮度範圍有關。"
  },
  {
    id: "hdr_002",
    category: "hdr",
    type: "truefalse",
    difficulty: 1,
    question: "Dynamic range 可以用 dB（分貝）或 stops 來表示。",
    options: [],
    answer: true,
    acceptAlso: [],
    explanation: "動態範圍常用 dB 或 stops（EV）表示。1 stop 等於亮度加倍，約 6.02 dB。例如一個 sensor 有 72 dB 動態範圍，約等於 12 stops。",
    imageDesc: "",
    scenario: "",
    hint: "想想攝影中常用的曝光單位。"
  },
  {
    id: "hdr_003",
    category: "hdr",
    type: "single",
    difficulty: 1,
    question: "Exposure bracketing 是指什麼技術？",
    options: [
      "以不同白平衡拍攝多張照片",
      "以不同曝光值拍攝多張照片再合成",
      "以不同焦距拍攝多張照片",
      "以不同 ISO 拍攝但曝光時間相同"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "Exposure bracketing（曝光包圍）是以不同曝光等級（通常為短曝光、正常曝光、長曝光）拍攝多幀影像，再合成為一張 HDR 影像，以涵蓋完整的場景動態範圍。",
    imageDesc: "",
    scenario: "",
    hint: "Bracket 有「涵蓋多種情況」的意思。"
  },
  {
    id: "hdr_004",
    category: "hdr",
    type: "truefalse",
    difficulty: 1,
    question: "Tone mapping 的目的是將 HDR 影像壓縮到可顯示的 SDR 範圍。",
    options: [],
    answer: true,
    acceptAlso: [],
    explanation: "Tone mapping（色調映射）是將 HDR 影像的高動態範圍資料映射到標準顯示器可呈現的有限範圍（如 8-bit），同時盡量保留視覺上的亮暗對比與細節。",
    imageDesc: "",
    scenario: "",
    hint: "一般顯示器無法直接呈現 HDR 的完整亮度範圍。"
  },
  {
    id: "hdr_005",
    category: "hdr",
    type: "single",
    difficulty: 1,
    question: "下列何者不是常見的 HDR 標準？",
    options: ["HDR10", "Dolby Vision", "HLG", "HEVC"],
    answer: 3,
    acceptAlso: [],
    explanation: "HEVC（H.265）是視訊壓縮編碼標準，不是 HDR 標準。HDR10、Dolby Vision 和 HLG（Hybrid Log-Gamma）才是常見的 HDR 顯示標準，定義了如何傳輸和顯示 HDR 內容。",
    imageDesc: "",
    scenario: "",
    hint: "其中一個選項是視訊壓縮編碼格式。"
  },
  {
    id: "hdr_006",
    category: "hdr",
    type: "fillblank",
    difficulty: 1,
    question: "動態範圍的定義是影像中可記錄的最亮與最暗訊號的______。",
    options: [],
    answer: "比值",
    acceptAlso: ["比率", "ratio"],
    explanation: "動態範圍（Dynamic Range）定義為感測器可測量的最大訊號與最小可辨識訊號（通常為雜訊底限）之比值。以 dB 表示時為 20×log10(max/min)。",
    imageDesc: "",
    scenario: "",
    hint: "是一種數學關係，涉及最大值與最小值。"
  },
  {
    id: "hdr_007",
    category: "hdr",
    type: "single",
    difficulty: 1,
    question: "HDR 影像合成時，短曝光幀主要用於保留哪個區域的細節？",
    options: ["暗部區域", "亮部區域", "中間調區域", "色彩飽和區域"],
    answer: 1,
    acceptAlso: [],
    explanation: "短曝光幀因為曝光時間短，亮部不會過曝（飽和），因此能保留高亮區域的細節。而長曝光幀則用於記錄暗部細節，兩者合成即可涵蓋完整動態範圍。",
    imageDesc: "",
    scenario: "",
    hint: "短曝光意味著接收較少的光。"
  },
  {
    id: "hdr_008",
    category: "hdr",
    type: "truefalse",
    difficulty: 1,
    question: "WDR（Wide Dynamic Range）和 HDR 在 ISP 領域中完全是同一個概念。",
    options: [],
    answer: false,
    acceptAlso: [],
    explanation: "雖然兩者都處理寬廣的動態範圍，但 WDR 通常指單幀內透過 sensor 或類比電路技術實現的寬動態範圍，而 HDR 更常指多幀合成方式。在監控攝影機領域，WDR 一詞使用更為廣泛。",
    imageDesc: "",
    scenario: "",
    hint: "考慮兩者在實作方式上的差異。"
  },
  {
    id: "hdr_009",
    category: "hdr",
    type: "single",
    difficulty: 1,
    question: "下列哪種 HDR 偽影（artifact）是由場景中移動物體造成的？",
    options: ["Halo artifact", "Color shift", "Ghosting", "Banding"],
    answer: 2,
    acceptAlso: [],
    explanation: "Ghosting（鬼影）是多幀 HDR 合成時，因場景中有移動物體，不同幀之間物體位置不同，合成後出現半透明殘影。這是多幀 HDR 最常見的偽影之一。",
    imageDesc: "",
    scenario: "",
    hint: "移動的物體在不同幀中位於不同位置。"
  },
  {
    id: "hdr_010",
    category: "hdr",
    type: "single",
    difficulty: 1,
    question: "1 stop 的動態範圍代表亮度相差多少倍？",
    options: ["1.5 倍", "2 倍", "4 倍", "10 倍"],
    answer: 1,
    acceptAlso: [],
    explanation: "1 stop（EV）代表亮度加倍或減半。這是攝影中描述曝光量的基本單位。例如 10 stops 動態範圍意味著最亮與最暗之間相差 2^10 = 1024 倍。",
    imageDesc: "",
    scenario: "",
    hint: "與攝影中光圈每調一級的變化相同。"
  },
  {
    id: "hdr_011",
    category: "hdr",
    type: "truefalse",
    difficulty: 1,
    question: "HLG（Hybrid Log-Gamma）標準不需要 metadata 即可向後相容 SDR 顯示器。",
    options: [],
    answer: true,
    acceptAlso: [],
    explanation: "HLG 由 BBC 與 NHK 共同開發，其傳輸函數設計為不需要 metadata。在 SDR 顯示器上會自動以類似傳統 gamma 曲線的方式呈現，達到向後相容，非常適合廣播應用。",
    imageDesc: "",
    scenario: "",
    hint: "名稱中的 Hybrid 暗示了兼容性設計。"
  },
  {
    id: "hdr_012",
    category: "hdr",
    type: "single",
    difficulty: 1,
    question: "Global tone mapping 和 local tone mapping 的主要差異是什麼？",
    options: [
      "Global 只處理亮度，local 只處理色彩",
      "Global 對所有像素套用相同映射曲線，local 會根據鄰近區域調整",
      "Global 用於影片，local 用於靜態影像",
      "Global 需要 GPU，local 只需 CPU"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "Global tone mapping 對整張影像使用同一條映射曲線（如 Reinhard global operator），而 local tone mapping 會根據每個像素的局部鄰域亮度資訊進行自適應調整，能更好地保留局部對比度與細節。",
    imageDesc: "",
    scenario: "",
    hint: "Local 意味著考慮空間上的「區域性」資訊。"
  },
  {
    id: "hdr_013",
    category: "hdr",
    type: "fillblank",
    difficulty: 1,
    question: "PQ curve 的全名是 ______ Quantizer，它是基於人眼感知亮度特性所設計的傳輸函數。",
    options: [],
    answer: "Perceptual",
    acceptAlso: ["perceptual"],
    explanation: "PQ（Perceptual Quantizer）曲線由 Dolby 開發，定義於 SMPTE ST 2084 標準中。它基於 Barten 視覺模型，能在有限的位元深度下最有效率地編碼亮度，支援高達 10,000 nits 的峰值亮度。",
    imageDesc: "",
    scenario: "",
    hint: "與人眼的亮度感知有關。"
  },
  {
    id: "hdr_014",
    category: "hdr",
    type: "single",
    difficulty: 1,
    question: "下列哪個 HDR 標準支援動態 metadata？",
    options: ["HDR10", "HLG", "HDR10+", "SDR"],
    answer: 2,
    acceptAlso: [],
    explanation: "HDR10+ 和 Dolby Vision 支援動態 metadata（逐場景或逐幀調整），而 HDR10 僅支援靜態 metadata，HLG 則不使用 metadata。動態 metadata 可以針對每個場景最佳化 tone mapping。",
    imageDesc: "",
    scenario: "",
    hint: "HDR10 的進階版本加了什麼符號？"
  },
  {
    id: "hdr_015",
    category: "hdr",
    type: "truefalse",
    difficulty: 1,
    question: "多幀 HDR 合成中，使用的幀數越多，最終影像的動態範圍一定越大。",
    options: [],
    answer: false,
    acceptAlso: [],
    explanation: "動態範圍的上限取決於最短曝光幀的亮部容量和最長曝光幀的暗部雜訊底限。單純增加幀數但曝光範圍未擴大，並不會增加動態範圍，反而可能增加合成的複雜度與 ghosting 風險。",
    imageDesc: "",
    scenario: "",
    hint: "重要的是曝光範圍，而非幀數。"
  },
  {
    id: "hdr_016",
    category: "hdr",
    type: "ordering",
    difficulty: 1,
    question: "請將以下 multi-frame HDR 處理步驟按正確順序排列：",
    options: ["多幀對齊 (Alignment)", "曝光包圍拍攝 (Bracketing)", "HDR 合成 (Merge)", "Tone mapping"],
    answer: 0,
    acceptAlso: [],
    explanation: "正確流程為：先進行 exposure bracketing 拍攝不同曝光的多幀 → 對齊各幀以修正手震或位移 → 將對齊後的多幀合成為 HDR 影像 → 最後進行 tone mapping 壓縮到可顯示範圍。",
    imageDesc: "",
    scenario: "",
    hint: "先拍攝，最後才做顯示用的映射。",
    items: ["曝光包圍拍攝 (Bracketing)", "多幀對齊 (Alignment)", "HDR 合成 (Merge)", "Tone mapping"]
  },
  {
    id: "hdr_017",
    category: "hdr",
    type: "image",
    difficulty: 1,
    question: "觀察下圖所示的 histogram，這張影像最可能存在什麼問題？",
    options: [
      "動態範圍不足，暗部與亮部都被截斷",
      "影像過暗，只有暗部有資訊",
      "影像過亮，整體偏白",
      "動態範圍正常，不需要 HDR 處理"
    ],
    answer: 0,
    acceptAlso: [],
    explanation: "當 histogram 的兩端（0 和 255）都有大量像素堆積（clipping），表示場景的動態範圍超過 sensor 的記錄能力，暗部和亮部細節都已丟失，這正是需要 HDR 技術的典型場景。",
    imageDesc: "Histogram 圖表：顯示像素分佈在左端（0）和右端（255）都有明顯的尖峰堆積，中間調的像素較少，呈現 U 形分佈，代表暗部和亮部都發生了 clipping。",
    scenario: "",
    hint: "注意 histogram 兩端的像素堆積現象。"
  },

  // ===== DIFFICULTY 2 (questions 018–034) =====
  {
    id: "hdr_018",
    category: "hdr",
    type: "single",
    difficulty: 2,
    question: "DOL-HDR（Digital Overlap HDR）的主要優勢是什麼？",
    options: [
      "完全消除 rolling shutter 效應",
      "長短曝光在時間上重疊讀出，減少幀間運動差異",
      "不需要額外的記憶體儲存多幀資料",
      "可以無限增加動態範圍"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "DOL-HDR 讓不同曝光的行（row）在讀出時間上交錯重疊，使長短曝光幀之間的時間差極小化，大幅減少因物體移動造成的 motion artifact，相比傳統 staggered HDR 有更好的運動表現。",
    imageDesc: "",
    scenario: "",
    hint: "Digital Overlap 的 overlap 指的是什麼？"
  },
  {
    id: "hdr_019",
    category: "hdr",
    type: "multiple",
    difficulty: 2,
    question: "下列哪些是 sensor-level HDR 的實作方式？（選擇所有正確答案）",
    options: [
      "Split pixel（分割像素）",
      "Dual conversion gain（DCG，雙轉換增益）",
      "Bilateral filter",
      "Staggered HDR（交錯曝光）"
    ],
    answer: [0, 1, 3],
    acceptAlso: [],
    explanation: "Split pixel 將像素分為大小不同的光電二極體區域實現不同靈敏度；DCG 在讀出時切換轉換增益獲得高低兩種動態範圍；Staggered HDR 交錯不同曝光行的讀出時序。Bilateral filter 則是 tone mapping 中使用的邊緣保留濾波器。",
    imageDesc: "",
    scenario: "",
    hint: "其中一個選項屬於影像處理演算法，不是 sensor 技術。"
  },
  {
    id: "hdr_020",
    category: "hdr",
    type: "single",
    difficulty: 2,
    question: "Reinhard tone mapping operator（全域版本）的核心公式為 L_out = L / (1 + L)，當 L 趨近無限大時，L_out 趨近於多少？",
    options: ["0", "0.5", "1", "無限大"],
    answer: 2,
    acceptAlso: [],
    explanation: "當 L → ∞ 時，L/(1+L) → L/L = 1。這意味著 Reinhard operator 將所有亮度壓縮到 [0, 1] 範圍內，且永遠不會超過 1，是一種 soft clipping 的方式，保證輸出不過曝。",
    imageDesc: "",
    scenario: "",
    hint: "分子分母同除以 L 看看。"
  },
  {
    id: "hdr_021",
    category: "hdr",
    type: "scenario",
    difficulty: 2,
    question: "你正在開發車用攝影機的 ISP，需要在明暗反差極大的隧道出入口場景實現 HDR。系統要求即時處理且運動偽影要最小化。下列哪種 HDR 方案最合適？",
    options: [
      "三幀 exposure bracketing + 軟體 deghosting",
      "DOL-HDR 或 staggered HDR（sensor 端交錯曝光）",
      "單幀拍攝後用 tone mapping 拉伸動態範圍",
      "拍攝後離線合成 HDR"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "車用 ADAS 攝影機需要即時處理和最小運動偽影。DOL-HDR 或 staggered HDR 在 sensor 讀出階段就交錯不同曝光，幀間時間差極小，運動偽影最低。軟體 deghosting 會增加延遲，單幀方式動態範圍有限，離線處理無法滿足即時需求。",
    imageDesc: "",
    scenario: "車用前視攝影機正在接近隧道出口，畫面上半部是極亮的天空（>100,000 lux），下半部是隧道內暗處（<10 lux），車輛正以 80 km/h 行駛。",
    hint: "車用場景最重視即時性和運動物體的正確呈現。"
  },
  {
    id: "hdr_022",
    category: "hdr",
    type: "single",
    difficulty: 2,
    question: "Staggered HDR（interleaved exposure）中，長短曝光行的讀出是如何排列的？",
    options: [
      "所有長曝光行讀完後才讀短曝光行",
      "長短曝光行在時間軸上交替讀出",
      "長短曝光行同時讀出到不同 ADC",
      "僅在偶數幀使用長曝光，奇數幀使用短曝光"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "Staggered HDR 的核心概念是長短曝光行在讀出時序上交替（interleave），例如先讀第 N 行的長曝光，接著讀第 N 行的短曝光，再讀第 N+1 行。這種方式使相鄰行的曝光時間差減小，降低運動偽影。",
    imageDesc: "",
    scenario: "",
    hint: "Staggered 和 interleaved 都有「交錯」之意。"
  },
  {
    id: "hdr_023",
    category: "hdr",
    type: "fillblank",
    difficulty: 2,
    question: "在 HDR deghosting 中，常用的方法是先進行 ______ detection，找出不同幀之間有移動的區域，再對這些區域使用單一參考幀的資料。",
    options: [],
    answer: "motion",
    acceptAlso: ["運動", "移動", "Motion"],
    explanation: "HDR deghosting 的關鍵步驟是 motion detection（運動偵測），比較不同曝光幀之間像素的差異，辨識出因物體移動或攝影機晃動造成不一致的區域。這些區域通常會使用單一參考幀的資料來避免 ghosting。",
    imageDesc: "",
    scenario: "",
    hint: "Ghost 出現的原因是幀間的什麼變化？"
  },
  {
    id: "hdr_024",
    category: "hdr",
    type: "single",
    difficulty: 2,
    question: "Local tone mapping 中使用 bilateral filter 的主要目的是什麼？",
    options: [
      "去除高頻雜訊",
      "分離基礎層（base layer）和細節層（detail layer）並保留邊緣",
      "增加色彩飽和度",
      "進行 gamma correction"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "Bilateral filter 是邊緣保留濾波器（edge-preserving filter），在 local tone mapping 中用於將影像分為低頻的 base layer（壓縮此層的對比度）和高頻的 detail layer（保留此層的細節），同時在強邊緣處不會產生 halo artifact。",
    imageDesc: "",
    scenario: "",
    hint: "Bilateral filter 的特性是既考慮空間距離又考慮像素值差異。"
  },
  {
    id: "hdr_025",
    category: "hdr",
    type: "multiple",
    difficulty: 2,
    question: "下列哪些是多幀 HDR 合成中常見的偽影？（選擇所有正確答案）",
    options: [
      "Ghosting（鬼影）",
      "Halo artifact（光暈偽影）",
      "Chromatic aberration（色散）",
      "Color shift（色彩偏移）"
    ],
    answer: [0, 1, 3],
    acceptAlso: [],
    explanation: "Ghosting 由場景中移動物體造成；Halo 出現在 tone mapping 階段的亮暗交界處；Color shift 是不同曝光幀合成時色彩混合不一致造成。Chromatic aberration（色差）是鏡頭光學特性造成的問題，與 HDR 合成無關。",
    imageDesc: "",
    scenario: "",
    hint: "哪個選項是純粹的光學問題而非 HDR 處理問題？"
  },
  {
    id: "hdr_026",
    category: "hdr",
    type: "single",
    difficulty: 2,
    question: "Dual Conversion Gain（DCG）sensor 如何實現寬動態範圍？",
    options: [
      "使用兩個不同大小的 photodiode",
      "在同一像素上切換高低兩種轉換增益進行兩次讀出",
      "使用兩種不同的色彩濾鏡",
      "將像素分為上下兩半分別曝光"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "DCG 在同一像素的 floating diffusion node 上切換電容值，實現高轉換增益（HCG，低雜訊，適合暗部）和低轉換增益（LCG，大 full well capacity，適合亮部）兩次讀出，再合成為寬動態範圍影像。",
    imageDesc: "",
    scenario: "",
    hint: "Conversion gain 與 floating diffusion 的電容有關。"
  },
  {
    id: "hdr_027",
    category: "hdr",
    type: "truefalse",
    difficulty: 2,
    question: "ACES（Academy Color Encoding System）的 tone mapping 曲線可以將 HDR 場景亮度映射到顯示器範圍，其設計主要針對電影產業的色彩管理需求。",
    options: [],
    answer: true,
    acceptAlso: [],
    explanation: "ACES 是由美國電影藝術與科學學院制定的色彩編碼系統，其中的 RRT（Reference Rendering Transform）+ ODT（Output Device Transform）構成完整的 tone mapping 管線，專為電影從拍攝到放映的全流程色彩管理設計。",
    imageDesc: "",
    scenario: "",
    hint: "Academy 指的是哪個機構？"
  },
  {
    id: "hdr_028",
    category: "hdr",
    type: "single",
    difficulty: 2,
    question: "HDR10 標準規定的位元深度和色域分別是？",
    options: [
      "8-bit, sRGB",
      "10-bit, BT.2020",
      "12-bit, DCI-P3",
      "10-bit, BT.709"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "HDR10 標準要求 10-bit 色深（可表示 1024 階），使用 BT.2020 廣色域，搭配 PQ（SMPTE ST 2084）傳輸函數，支援最大 10,000 nits 峰值亮度，並使用靜態 metadata（SMPTE ST 2086）。",
    imageDesc: "",
    scenario: "",
    hint: "名稱中的 10 暗示了什麼？"
  },
  {
    id: "hdr_029",
    category: "hdr",
    type: "image",
    difficulty: 2,
    question: "觀察下圖中 tone mapping 的結果，影像在亮暗交界處出現明顯的發光帶狀偽影，這是什麼問題？",
    options: [
      "Ghosting artifact",
      "Halo artifact",
      "Banding artifact",
      "Moiré pattern"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "Halo artifact（光暈偽影）是 local tone mapping 的典型問題，在亮暗區域的交界處產生不自然的發光帶。原因是 local operator 對鄰域亮度差異過度補償。使用邊緣保留濾波器（如 bilateral filter）或調整 local operator 的 kernel size 可以緩解此問題。",
    imageDesc: "影像顯示一棟建築物的輪廓在明亮天空前，經過 tone mapping 處理後，建築物邊緣與天空交界處出現寬約 20-30 像素的不自然亮帶（halo），使建築輪廓看起來像是在發光。",
    scenario: "",
    hint: "注意亮暗邊界處的不自然光帶。"
  },
  {
    id: "hdr_030",
    category: "hdr",
    type: "scenario",
    difficulty: 2,
    question: "你的監控攝影機 ISP 使用 2-frame staggered HDR（長曝光 T 和短曝光 T/16）。在合成時發現暗區有明顯的雜訊。最可能的原因和解決方向是什麼？",
    options: [
      "短曝光幀的暗區 SNR 太低被錯誤採用，應調整合成權重避免使用短曝光的暗區",
      "長曝光幀產生了過多的固定模式雜訊，應降低 sensor 溫度",
      "Tone mapping 過度拉伸暗區導致雜訊放大，應改用 global operator",
      "ADC 位元不足導致量化雜訊，應升級為 14-bit ADC"
    ],
    answer: 0,
    acceptAlso: [],
    explanation: "在 2-frame HDR 合成中，短曝光幀的暗區因為曝光不足，SNR 極低。如果合成演算法在轉換區間（transition zone）設計不當，錯誤地過多採用短曝光暗區資料，就會引入明顯雜訊。應確保暗區權重以長曝光幀為主，只在亮部區域才切換使用短曝光資料。",
    imageDesc: "",
    scenario: "一台 2MP 監控攝影機使用 1/2.8\" sensor，在夜晚的停車場場景中開啟 HDR 模式。長曝光 33ms，短曝光約 2ms（ratio 16x）。HDR 合成後暗區（如車底陰影、角落）出現明顯的顆粒雜訊。",
    hint: "想想短曝光幀在暗區的信噪比。"
  },
  {
    id: "hdr_031",
    category: "hdr",
    type: "single",
    difficulty: 2,
    question: "Drago tone mapping operator 的設計特點是什麼？",
    options: [
      "使用 sigmoid 函數進行全域壓縮",
      "以對數函數為基礎，自適應調整 base 參數壓縮亮度",
      "完全基於 histogram equalization 進行映射",
      "使用神經網路學習最佳映射曲線"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "Drago 等人提出的 tone mapping operator 使用自適應的對數映射（adaptive logarithmic mapping），根據場景的最大亮度自動調整對數函數的 base 參數（在 log2 和 log10 之間插值），能有效壓縮高動態範圍同時保留對比度細節。",
    imageDesc: "",
    scenario: "",
    hint: "Drago 的方法與對數函數密切相關。"
  },
  {
    id: "hdr_032",
    category: "hdr",
    type: "fillblank",
    difficulty: 2,
    question: "Split pixel HDR sensor 是將每個像素的光電二極體分割為面積不同的兩個區域，較大區域具有較高的______，用於記錄暗部細節。",
    options: [],
    answer: "靈敏度",
    acceptAlso: ["sensitivity", "感光度", "感度"],
    explanation: "Split pixel sensor 中，較大面積的 sub-pixel 具有較高的光靈敏度（sensitivity），能在低光下收集更多光子，適合記錄暗部。較小的 sub-pixel 靈敏度低但 full well capacity 相對較大（不易飽和），適合記錄亮部。兩者合成即可實現單幀 HDR。",
    imageDesc: "",
    scenario: "",
    hint: "較大的光電二極體面積能收集更多光子。"
  },
  {
    id: "hdr_033",
    category: "hdr",
    type: "ordering",
    difficulty: 2,
    question: "請將以下動態範圍從小到大排列：",
    options: ["人眼瞬時動態範圍", "典型 8-bit SDR 影像", "高階 CMOS sensor（單幀）", "真實場景（戶外日光）"],
    answer: 0,
    acceptAlso: [],
    explanation: "8-bit SDR 約 8 stops → 高階 CMOS 單幀約 12-14 stops → 人眼瞬時約 14-16 stops → 戶外日光場景可達 20+ stops。真實場景的動態範圍遠超任何單一 sensor 的能力，這正是 HDR 技術存在的原因。",
    imageDesc: "",
    scenario: "",
    hint: "8-bit 能表示的對比度範圍最有限。",
    items: ["典型 8-bit SDR 影像", "高階 CMOS sensor（單幀）", "人眼瞬時動態範圍", "真實場景（戶外日光）"]
  },
  {
    id: "hdr_034",
    category: "hdr",
    type: "truefalse",
    difficulty: 2,
    question: "Mantiuk tone mapping operator 是基於人眼對比敏感度函數（CSF）設計的，目標是最小化可感知的對比度失真。",
    options: [],
    answer: true,
    acceptAlso: [],
    explanation: "Mantiuk 等人提出的 tone mapping operator 利用人類視覺系統的 Contrast Sensitivity Function（CSF），在頻率域中最小化可感知的對比度變化（visible contrast distortion），是感知驅動（perceptually-driven）tone mapping 的代表性方法。",
    imageDesc: "",
    scenario: "",
    hint: "Mantiuk 的研究著重於人類視覺感知。"
  },

  // ===== DIFFICULTY 3 (questions 035–050) =====
  {
    id: "hdr_035",
    category: "hdr",
    type: "single",
    difficulty: 3,
    question: "在 DOL-HDR 的 readout timing 設計中，長曝光行與短曝光行的讀出時間差（temporal offset）通常控制在什麼範圍以內？",
    options: [
      "一個完整 frame time",
      "數個 row time（行讀出時間）",
      "大於 10ms",
      "完全同步（零延遲）"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "DOL-HDR 設計的核心是將長短曝光行的讀出 temporal offset 控制在極少數 row time（通常 1-4 row time）以內。一個 row time 通常只有數十微秒，因此幀間的時間差極小化，能大幅降低因物體移動造成的位移偽影。",
    imageDesc: "",
    scenario: "",
    hint: "DOL 的 overlap 就是要最小化時間差。"
  },
  {
    id: "hdr_036",
    category: "hdr",
    type: "multiple",
    difficulty: 3,
    question: "下列關於 HDR 與 SNR（Signal-to-Noise Ratio）的敘述，哪些是正確的？（選擇所有正確答案）",
    options: [
      "短曝光幀的暗區 SNR 比長曝光幀的暗區 SNR 低",
      "HDR 合成時，合成權重應考慮各幀在該亮度區間的 SNR",
      "增加 HDR 的曝光比（exposure ratio）不會影響轉換區的 SNR",
      "DCG sensor 的 HCG 模式在暗區有較好的 SNR"
    ],
    answer: [0, 1, 3],
    acceptAlso: [],
    explanation: "短曝光暗區光子數少，SNR 自然較低（A 正確）。合成權重應以 SNR 為依據（B 正確）。增加曝光比會使轉換區的 SNR 下降，因為短曝光在中間亮度的 SNR 降低而長曝光已飽和（C 錯誤）。DCG 的 HCG 模式讀出雜訊低，暗部 SNR 優於 LCG（D 正確）。",
    imageDesc: "",
    scenario: "",
    hint: "思考每種情況下光子數和雜訊的關係。"
  },
  {
    id: "hdr_037",
    category: "hdr",
    type: "scenario",
    difficulty: 3,
    question: "你在設計一個 4K 60fps 車用 ISP 的 HDR 合成模組。Sensor 提供 3-exposure DOL-HDR 輸出（T, T/4, T/16），raw 資料為 12-bit。你發現在 T 和 T/4 的合成轉換區出現明顯的水平線條偽影。最可能的原因是什麼？",
    options: [
      "Tone mapping 的 kernel size 不適當",
      "長短曝光行的 black level 校正不一致",
      "Bayer demosaic 的插值方向錯誤",
      "白平衡增益設定過高"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "DOL-HDR 的不同曝光行可能因為 analog circuit 的差異導致 black level 略有不同。如果在合成前沒有對每種曝光分別做精確的 black level 校正，在合成轉換區（從長曝光切換到短曝光的亮度範圍）會因為 offset 不一致而出現水平亮度跳變線條。這在 ISP 開發中是常見且關鍵的校準問題。",
    imageDesc: "",
    scenario: "4K 60fps 車用攝影機，Sony IMX 系列 DOL-HDR sensor，3-exposure 模式。在中等亮度的灰色牆壁上，HDR 合成後出現水平方向的週期性明暗線條，在均勻場景中尤其明顯。",
    hint: "不同曝光行的類比電路參數可能不完全一致。"
  },
  {
    id: "hdr_038",
    category: "hdr",
    type: "single",
    difficulty: 3,
    question: "在 histogram-based tone mapping 中，為什麼不能直接使用標準的 histogram equalization？",
    options: [
      "計算量太大，無法即時處理",
      "會過度增強低對比區域的雜訊，且可能導致不自然的過飽和效果",
      "無法處理彩色影像",
      "只適用於 8-bit 影像"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "直接對 HDR 影像做 histogram equalization 會給予每個亮度等級相同的顯示面積，導致低對比區域（如天空漸層）被過度拉伸，放大雜訊並產生不自然效果。改良方法包括限制 equalization 程度（如 CLAHE）或結合 percentile clipping 來控制映射曲線的斜率上限。",
    imageDesc: "",
    scenario: "",
    hint: "想想 histogram equalization 對「平坦區域」會做什麼。"
  },
  {
    id: "hdr_039",
    category: "hdr",
    type: "fillblank",
    difficulty: 3,
    question: "在 PQ（Perceptual Quantizer）曲線中，10-bit 編碼可以表示高達 ______ nits 的峰值亮度。",
    options: [],
    answer: "10000",
    acceptAlso: ["10,000", "一萬"],
    explanation: "SMPTE ST 2084 PQ 曲線支援 0 到 10,000 nits 的完整亮度範圍。其非線性特性基於 Barten CSF 模型，使得 10-bit（1024 階）的量化誤差在整個亮度範圍內都低於人眼可辨識的最小亮度差（JND），實現感知上均勻的量化。",
    imageDesc: "",
    scenario: "",
    hint: "PQ 曲線的設計上限是目前顯示技術的理論極限之一。"
  },
  {
    id: "hdr_040",
    category: "hdr",
    type: "single",
    difficulty: 3,
    question: "在 3-exposure HDR 合成中（T, T/4, T/16），如果 sensor 單幀動態範圍為 60 dB，理論上合成後的總動態範圍大約是多少？",
    options: ["60 dB", "72 dB", "84 dB", "96 dB"],
    answer: 2,
    acceptAlso: [],
    explanation: "最長曝光 T 提供 60 dB 基礎動態範圍。T/4 比 T 少 2 stops（12 dB），T/16 比 T 少 4 stops（24 dB）。合成後的動態範圍 ≈ 60 dB + 20×log10(16) = 60 + 24 = 84 dB（約 14 stops）。總動態範圍 = 單幀 DR + 最長與最短曝光的曝光比（以 dB 計）。",
    imageDesc: "",
    scenario: "",
    hint: "曝光比 T/T_min = 16，轉換為 dB 加到基礎動態範圍。"
  },
  {
    id: "hdr_041",
    category: "hdr",
    type: "multiple",
    difficulty: 3,
    question: "下列關於 Dolby Vision 和 HDR10+ 的比較，哪些是正確的？（選擇所有正確答案）",
    options: [
      "Dolby Vision 支援 12-bit 色深，HDR10+ 支援 10-bit",
      "兩者都支援動態 metadata",
      "Dolby Vision 需要專用硬體解碼晶片，HDR10+ 為開放標準",
      "HDR10+ 的動態 metadata 使用 SEI message 嵌入在視訊串流中"
    ],
    answer: [0, 1, 2, 3],
    acceptAlso: [],
    explanation: "全部正確。Dolby Vision 規格支援最高 12-bit 色深且需要 Dolby 授權的硬體 IP；HDR10+ 由 Samsung 等推動，支援 10-bit 且為免授權費標準。兩者都提供逐場景的動態 metadata。HDR10+ 的動態 metadata 透過 HEVC/AV1 的 SEI（Supplemental Enhancement Information）message 傳遞。",
    imageDesc: "",
    scenario: "",
    hint: "這些敘述實際上都是正確的技術描述。"
  },
  {
    id: "hdr_042",
    category: "hdr",
    type: "single",
    difficulty: 3,
    question: "在 local tone mapping 中，為了避免 halo artifact，下列哪種方法最有效？",
    options: [
      "增大 Gaussian blur 的 sigma 值",
      "使用邊緣保留濾波器（如 bilateral filter 或 guided filter）取代 Gaussian blur 做 base/detail 分離",
      "直接降低 tone mapping 的壓縮強度",
      "對輸出結果做 median filter 後處理"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "Halo artifact 的根本原因是在 base/detail 分離時，使用的 low-pass filter（如 Gaussian）在強邊緣處的濾波結果不正確，導致 base layer 在邊緣處出現過度平滑。使用 edge-preserving filter（bilateral filter 或 guided filter）可以在邊緣處維持銳利的轉換，有效避免 halo。",
    imageDesc: "",
    scenario: "",
    hint: "問題出在 base layer 的邊緣處理。"
  },
  {
    id: "hdr_043",
    category: "hdr",
    type: "scenario",
    difficulty: 3,
    question: "你正在調試一個使用 split pixel sensor 的 HDR ISP。Large pixel（LP）和 small pixel（SP）的曝光比為 4:1。你發現 HDR 合成後的影像在中間亮度區域出現色彩不連續（color banding）。下列哪個是最可能的根本原因和解決方案？",
    options: [
      "LP 和 SP 的 spectral response 不一致，需要做 cross-channel 色彩校正",
      "合成區的 blending curve 太陡峭，需要使用更寬的 S 形過渡曲線",
      "Tone mapping 的量化誤差，需要增加 LUT 的位元深度",
      "Sensor 的 read noise 太高，需要降低 analog gain"
    ],
    answer: 0,
    acceptAlso: [],
    explanation: "Split pixel 的 LP 和 SP 因為面積和微透鏡覆蓋方式不同，實際的光譜響應（spectral response）會有差異，尤其是在 CRA（chief ray angle）較大的邊角區域。這導致在不同曝光下同一色彩的 R/G/B 比率不一致，合成時出現色彩跳變。需要針對 LP 和 SP 做獨立的色彩校正（per-exposure color matrix）。",
    imageDesc: "",
    scenario: "使用 OmniVision 的 split pixel HDR sensor，LP/SP ratio 4:1。在拍攝含有平滑漸層色彩的場景（如夕陽天空）時，HDR 合成後在 LP/SP 轉換亮度附近出現可見的色帶，紅色和藍色通道尤其明顯。",
    hint: "LP 和 SP 的物理結構差異不僅影響靈敏度。"
  },
  {
    id: "hdr_044",
    category: "hdr",
    type: "single",
    difficulty: 3,
    question: "計算 HDR 合成中長短曝光幀的最佳合成權重時，基於 SNR 最佳化的權重函數 w(x) 通常與什麼成正比？",
    options: [
      "像素值 x 的平方",
      "像素值 x 的倒數",
      "該曝光幀在像素值 x 處的 variance 的倒數",
      "該曝光幀的總曝光時間"
    ],
    answer: 2,
    acceptAlso: [],
    explanation: "基於統計最佳化的 HDR 合成，每幀的權重 w_i(x) ∝ 1/σ²_i(x)，即與該幀在像素值 x 處的 variance（含 shot noise + read noise）的倒數成正比。這等效於最小 variance 無偏估計（MVUE），能在每個亮度等級選擇 SNR 最高的幀，產生合成後最佳的 SNR。",
    imageDesc: "",
    scenario: "",
    hint: "這是統計學中的最佳線性組合問題。"
  },
  {
    id: "hdr_045",
    category: "hdr",
    type: "truefalse",
    difficulty: 3,
    question: "在 HDR deghosting 中，使用 optical flow 進行運動補償的方法可以完美解決所有 ghosting 問題，包括遮擋（occlusion）區域。",
    options: [],
    answer: false,
    acceptAlso: [],
    explanation: "Optical flow 可以估計物體的運動向量並進行 warping 對齊，但在遮擋區域（一幀中可見但另一幀中被遮擋的區域）無法找到正確的對應點。此外，光流在大位移、重複紋理、過曝/欠曝區域也容易失敗。因此通常需要結合遮擋偵測（occlusion detection）和 fallback 策略。",
    imageDesc: "",
    scenario: "",
    hint: "有些區域在一幀中根本看不到。"
  },
  {
    id: "hdr_046",
    category: "hdr",
    type: "single",
    difficulty: 3,
    question: "在設計 HDR ISP 的 tone mapping 硬體加速器時，如果使用分段線性（piecewise linear）近似 tone curve，為了在暗部保持足夠精度，分段點的間距應如何設計？",
    options: [
      "均勻間距（uniform spacing）",
      "對數間距（logarithmic spacing），暗部間距小、亮部間距大",
      "亮部間距小、暗部間距大",
      "隨機間距以避免 banding"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "人眼對暗部的亮度變化更敏感（Weber's Law），且 tone curve 在暗部通常斜率更大（需要更多拉伸）。因此硬體 LUT 的分段點應使用對數間距（或類似的非均勻分佈），在暗部使用更密的控制點以維持精度，亮部可用較稀的點。這也是 PQ curve 和 gamma 曲線在暗部精度要求較高的原因。",
    imageDesc: "",
    scenario: "",
    hint: "人眼對暗部的亮度變化更敏感。"
  },
  {
    id: "hdr_047",
    category: "hdr",
    type: "fillblank",
    difficulty: 3,
    question: "在 HDR 合成中，兩幀重疊的亮度區間稱為 transition zone（轉換區）。若長曝光 T 在 ADC code ______ 附近達到飽和，此值即為轉換區的上界。",
    options: [],
    answer: "滿量程",
    acceptAlso: ["full scale", "最大值", "full-scale", "4095", "1023"],
    explanation: "長曝光幀的 ADC 接近滿量程（如 12-bit 為 4095, 10-bit 為 1023）時開始飽和，此處即為合成轉換區的上界。實務上通常會在滿量程的 80-90% 處就開始混合短曝光幀，以避免使用非線性區域的長曝光資料。轉換區設計的好壞直接影響合成品質。",
    imageDesc: "",
    scenario: "",
    hint: "ADC 的輸出有最大值限制。"
  },
  {
    id: "hdr_048",
    category: "hdr",
    type: "ordering",
    difficulty: 3,
    question: "請將以下 sensor-level HDR 技術按運動偽影（motion artifact）表現從差到好排列：",
    options: [
      "Split pixel（同時曝光）",
      "Multi-frame bracketing（完整幀間隔）",
      "Staggered HDR（行交錯）",
      "DOL-HDR（數位重疊）"
    ],
    answer: 0,
    acceptAlso: [],
    explanation: "Multi-frame bracketing 幀間時間差最大（整幀間隔），運動偽影最嚴重。Staggered HDR 行交錯讀出，時間差為數十個 row time。DOL-HDR 將時間差縮至 1-4 row time，表現更好。Split pixel 在同一曝光週期內同時獲得長短曝光，幾乎無時間差，運動偽影最小。",
    imageDesc: "",
    scenario: "",
    hint: "時間差越小，運動偽影越少。",
    items: ["Multi-frame bracketing（完整幀間隔）", "Staggered HDR（行交錯）", "DOL-HDR（數位重疊）", "Split pixel（同時曝光）"]
  },
  {
    id: "hdr_049",
    category: "hdr",
    type: "multiple",
    difficulty: 3,
    question: "在設計 HDR ISP 的雜訊抑制策略時，下列哪些考量是正確的？（選擇所有正確答案）",
    options: [
      "HDR 合成應在降噪之前進行，因為合成後可以更準確估計雜訊模型",
      "不同曝光幀的 noise profile 不同，降噪參數應分別調整",
      "HDR 合成的轉換區 SNR 通常是整張影像中最低的",
      "空間域降噪的強度應根據 HDR 合成後的 local SNR map 進行自適應調整"
    ],
    answer: [1, 2, 3],
    acceptAlso: [],
    explanation: "B 正確：不同曝光的 shot noise 和 read noise 比例不同。C 正確：轉換區是長曝光接近飽和、短曝光 SNR 又不夠高的區域，SNR 最差。D 正確：應根據 local SNR 自適應調噪。A 不正確：降噪通常在合成前或合成過程中進行，以避免合成時將短曝光的高雜訊帶入結果。先降噪可以改善合成品質。",
    imageDesc: "",
    scenario: "",
    hint: "思考降噪和合成的先後順序對結果的影響。"
  },
  {
    id: "hdr_050",
    category: "hdr",
    type: "scenario",
    difficulty: 3,
    question: "你在開發一個 HDR10+ 內容的 tone mapping 引擎，需要將 PQ 編碼的 HDR 內容映射到一台峰值亮度僅 400 nits 的電視上。你發現高亮度的雲朵與天空細節完全喪失。最佳的解決策略是什麼？",
    options: [
      "直接對 PQ 訊號做 hard clipping 在 400 nits",
      "利用 HDR10+ 動態 metadata 中的 percentile 亮度資訊，設計 S 形映射曲線保留高光細節",
      "將整體亮度等比例縮放到 400 nits",
      "只使用影像的下半部分亮度範圍"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "HDR10+ 動態 metadata 包含 maxSCL（場景最大亮度）和 distribution percentile（亮度分佈的百分位資訊）。利用這些資訊可以針對每個場景設計自適應的 S 形 tone curve，在目標顯示器能力（400 nits）內做 soft roll-off，將超出範圍的高亮度資訊壓縮而非截斷，保留雲朵天空等高光細節的相對層次。Hard clipping 會丟失所有超過 400 nits 的細節；等比例縮放會讓整體影像變暗。",
    imageDesc: "",
    scenario: "一台中階電視的峰值亮度為 400 nits。播放一段 HDR10+ 編碼的影片，場景中有太陽照射的白雲（原始亮度標記為 2000-4000 nits）。不做任何處理直接顯示，雲朵和天空完全過曝成純白一片。",
    hint: "HDR10+ 的動態 metadata 提供了場景亮度分佈資訊。"
  }
];

