const Q_IQ = [
  // ===== DIFFICULTY 1 (questions 001–023) =====
  {
    id: "iq_001",
    category: "iq",
    type: "single",
    difficulty: 1,
    question: "SNR (Signal-to-Noise Ratio) 的單位通常以什麼表示？",
    options: ["dB (decibel)", "lux", "pixel", "Hz"],
    answer: 0,
    acceptAlso: [],
    explanation: "SNR 通常以分貝 (dB) 為單位表示，計算公式為 20·log₁₀(signal/noise)。dB 為對數尺度，便於表示大範圍的訊噪比差異。",
    imageDesc: "",
    scenario: "",
    hint: "這是一個對數尺度的單位。"
  },
  {
    id: "iq_002",
    category: "iq",
    type: "truefalse",
    difficulty: 1,
    question: "ΔE 值越大，表示兩個顏色之間的差異越小。",
    options: [],
    answer: false,
    acceptAlso: [],
    explanation: "ΔE 代表色差 (color difference)，數值越大表示兩個顏色之間的差異越大。一般認為 ΔE < 1 時人眼幾乎無法分辨差異，ΔE > 5 則明顯可見。",
    imageDesc: "",
    scenario: "",
    hint: "Δ 代表差異，E 來自德文 Empfindung（感知）。"
  },
  {
    id: "iq_003",
    category: "iq",
    type: "single",
    difficulty: 1,
    question: "Macbeth ColorChecker 標準色卡包含多少個色塊？",
    options: ["12", "18", "24", "48"],
    answer: 2,
    acceptAlso: [],
    explanation: "標準 Macbeth ColorChecker 包含 24 個色塊，涵蓋自然色、灰階、飽和色等，廣泛用於色彩準確度的評估與白平衡校正。",
    imageDesc: "",
    scenario: "",
    hint: "這張色卡是 4 行 × 6 列的排列。"
  },
  {
    id: "iq_004",
    category: "iq",
    type: "single",
    difficulty: 1,
    question: "ISO 12233 測試圖主要用於測量什麼？",
    options: ["色彩準確度", "解析度 (Resolution / Sharpness)", "動態範圍", "白平衡"],
    answer: 1,
    acceptAlso: [],
    explanation: "ISO 12233 是國際標準測試圖，包含多種頻率的線對圖案，主要用於量測相機系統的空間解析度與 MTF。",
    imageDesc: "",
    scenario: "",
    hint: "這張測試圖上有很多黑白條紋圖案。"
  },
  {
    id: "iq_005",
    category: "iq",
    type: "truefalse",
    difficulty: 1,
    question: "PSNR (Peak Signal-to-Noise Ratio) 數值越高，表示影像品質越好。",
    options: [],
    answer: true,
    acceptAlso: [],
    explanation: "PSNR 衡量的是最大可能訊號功率與雜訊功率的比值，數值越高代表失真越少、影像品質越好。典型的高品質影像 PSNR 通常在 30–50 dB 之間。",
    imageDesc: "",
    scenario: "",
    hint: "想想訊號與雜訊的關係。"
  },
  {
    id: "iq_006",
    category: "iq",
    type: "single",
    difficulty: 1,
    question: "MTF 的全稱是什麼？",
    options: ["Modulation Transfer Function", "Maximum Transfer Frequency", "Mean Tone Factor", "Multi-Tone Filter"],
    answer: 0,
    acceptAlso: [],
    explanation: "MTF (Modulation Transfer Function) 是描述光學系統或影像處理管線在不同空間頻率下對比度傳遞能力的函數，是衡量銳利度的核心指標。",
    imageDesc: "",
    scenario: "",
    hint: "這個函數描述了「調變」的「傳遞」能力。"
  },
  {
    id: "iq_007",
    category: "iq",
    type: "single",
    difficulty: 1,
    question: "MOS (Mean Opinion Score) 屬於哪種影像品質評估方法？",
    options: ["客觀評估 (Objective)", "主觀評估 (Subjective)", "自動化評估", "物理量測"],
    answer: 1,
    acceptAlso: [],
    explanation: "MOS 是透過多位受測者對影像品質進行打分後取平均值的方法，屬於主觀評估 (Subjective Assessment)。它直接反映人類的視覺感受，是最終品質判斷的金標準。",
    imageDesc: "",
    scenario: "",
    hint: "Opinion 代表「意見」，是來自人的判斷。"
  },
  {
    id: "iq_008",
    category: "iq",
    type: "truefalse",
    difficulty: 1,
    question: "Dead leaves chart 主要用於測量影像的紋理細節保留能力。",
    options: [],
    answer: true,
    acceptAlso: [],
    explanation: "Dead leaves chart 模擬自然場景中隨機分佈的圓形圖案，其頻譜特性接近自然影像，特別適合評估降噪處理後紋理細節的保留程度。",
    imageDesc: "",
    scenario: "",
    hint: "這張圖看起來像是隨機散落的圓形樹葉。"
  },
  {
    id: "iq_009",
    category: "iq",
    type: "single",
    difficulty: 1,
    question: "SSIM 的數值範圍是？",
    options: ["0 到 100", "-1 到 1", "0 到 1", "0 到 255"],
    answer: 2,
    acceptAlso: [],
    explanation: "SSIM (Structural Similarity Index) 的數值範圍為 0 到 1，其中 1 表示兩張影像完全相同。SSIM 比 PSNR 更符合人眼的視覺感受，因為它考慮了亮度、對比度和結構三個面向。",
    imageDesc: "",
    scenario: "",
    hint: "1 代表完全相同。"
  },
  {
    id: "iq_010",
    category: "iq",
    type: "fillblank",
    difficulty: 1,
    question: "動態範圍 (Dynamic Range) 通常以 _____ 為單位，代表感測器能記錄的最亮與最暗之間的比值。",
    options: [],
    answer: "dB",
    acceptAlso: ["decibel", "分貝", "stops", "EV"],
    explanation: "動態範圍可用 dB 或 stops (EV) 表示。1 stop 相當於亮度倍增一倍（約 6 dB）。高動態範圍的感測器可同時捕捉亮部與暗部的細節。",
    imageDesc: "",
    scenario: "",
    hint: "和 SNR 使用相同的單位。"
  },
  {
    id: "iq_011",
    category: "iq",
    type: "single",
    difficulty: 1,
    question: "鏡頭解析度常用什麼單位表示？",
    options: ["pixel/mm", "lp/mm (line pairs per mm)", "dpi (dots per inch)", "megapixel"],
    answer: 1,
    acceptAlso: [],
    explanation: "鏡頭的光學解析度通常以 lp/mm (line pairs per millimeter) 表示，代表每毫米能分辨的黑白線對數。數值越高，鏡頭的解析能力越強。",
    imageDesc: "",
    scenario: "",
    hint: "每毫米的「線對」數。"
  },
  {
    id: "iq_012",
    category: "iq",
    type: "truefalse",
    difficulty: 1,
    question: "白平衡 (White Balance) 的目的是讓白色物體在不同光源下都呈現為白色。",
    options: [],
    answer: true,
    acceptAlso: [],
    explanation: "白平衡校正會根據場景的色溫調整 R/G/B 通道的增益，確保中性色（白色、灰色）不帶有色偏，使影像的色彩還原更自然。",
    imageDesc: "",
    scenario: "",
    hint: "想想在鎢絲燈下拍攝的照片為什麼偏黃。"
  },
  {
    id: "iq_013",
    category: "iq",
    type: "single",
    difficulty: 1,
    question: "Siemens star 測試圖的主要形狀特徵是什麼？",
    options: ["同心圓環", "放射狀扇形條紋", "棋盤格", "隨機雜點"],
    answer: 1,
    acceptAlso: [],
    explanation: "Siemens star 由中心向外放射的黑白交替扇形條紋組成，中心處空間頻率最高。透過觀察條紋模糊開始的半徑，可以直觀判斷系統的解析度極限。",
    imageDesc: "",
    scenario: "",
    hint: "名字裡有 star（星形）。"
  },
  {
    id: "iq_014",
    category: "iq",
    type: "single",
    difficulty: 1,
    question: "色差 (Chromatic Aberration) 是由什麼原因造成的？",
    options: ["感測器過熱", "不同波長的光折射率不同", "曝光時間過長", "記憶體不足"],
    answer: 1,
    acceptAlso: [],
    explanation: "色差是因為鏡頭玻璃對不同波長（顏色）的光有不同的折射率，導致各色光無法聚焦在同一點上，常見於高對比邊緣出現紫邊或綠邊。",
    imageDesc: "",
    scenario: "",
    hint: "和光學中的「色散」現象有關。"
  },
  {
    id: "iq_015",
    category: "iq",
    type: "fillblank",
    difficulty: 1,
    question: "MTF50 是指 MTF 值降到 _____ 時對應的空間頻率，常用來量化銳利度。",
    options: [],
    answer: "50%",
    acceptAlso: ["0.5", "50", "50 percent"],
    explanation: "MTF50 是 MTF 曲線降至 50%（即對比度降為原始的一半）時所對應的空間頻率值。它是一個被廣泛使用的單一數值銳利度指標。",
    imageDesc: "",
    scenario: "",
    hint: "名字中的數字就是答案。"
  },
  {
    id: "iq_016",
    category: "iq",
    type: "single",
    difficulty: 1,
    question: "SFR (Spatial Frequency Response) edge 測試中使用的是什麼樣的圖案？",
    options: ["圓形圖案", "傾斜的黑白邊緣 (slanted edge)", "彩色條紋", "隨機噪點"],
    answer: 1,
    acceptAlso: [],
    explanation: "SFR edge 測試使用略微傾斜（通常約 5°）的黑白邊緣，透過超取樣技術從邊緣剖面推算出系統的 MTF。傾斜設計可避免取樣混疊。",
    imageDesc: "",
    scenario: "",
    hint: "Slanted 意思是「傾斜的」。"
  },
  {
    id: "iq_017",
    category: "iq",
    type: "truefalse",
    difficulty: 1,
    question: "LPIPS (Learned Perceptual Image Patch Similarity) 數值越低，表示影像品質越好。",
    options: [],
    answer: true,
    acceptAlso: [],
    explanation: "LPIPS 使用深度學習模型計算兩張影像之間的感知距離，數值越低表示兩張影像在感知上越相似。與 PSNR/SSIM 相反，LPIPS 是「距離」指標，越低越好。",
    imageDesc: "",
    scenario: "",
    hint: "LPIPS 是一種「距離」度量。"
  },
  {
    id: "iq_018",
    category: "iq",
    type: "single",
    difficulty: 1,
    question: "鏡頭畸變 (Distortion) 中，影像邊緣向外膨脹的變形稱為？",
    options: ["枕形畸變 (Pincushion)", "桶形畸變 (Barrel)", "梯形畸變 (Keystone)", "波浪畸變 (Wavy)"],
    answer: 1,
    acceptAlso: [],
    explanation: "桶形畸變 (Barrel Distortion) 使直線向外彎曲（像桶的形狀），常見於廣角鏡頭。枕形畸變則相反，直線向內凹陷。",
    imageDesc: "",
    scenario: "",
    hint: "想想「桶」的形狀。"
  },
  {
    id: "iq_019",
    category: "iq",
    type: "ordering",
    difficulty: 1,
    question: "請按照 DxOMark 整體評分從高（最佳）到低排列以下感測器特性的重要性：",
    options: [],
    answer: 0,
    acceptAlso: [],
    explanation: "DxOMark 的整體評分主要由三個子項目組成：色彩深度 (Color Depth) 反映色彩辨別能力、動態範圍 (Dynamic Range) 衡量明暗記錄範圍、低光 ISO (Low-Light ISO) 衡量高 ISO 下的 SNR 表現。",
    imageDesc: "",
    scenario: "",
    hint: "DxOMark 有三大核心測量指標。",
    items: ["色彩深度 (Color Depth)", "動態範圍 (Dynamic Range)", "低光 ISO (Low-Light ISO)"]
  },
  {
    id: "iq_020",
    category: "iq",
    type: "single",
    difficulty: 1,
    question: "Visual noise 評估中，人眼對哪種顏色通道的雜訊最敏感？",
    options: ["紅色 (Red)", "綠色 / 亮度 (Green / Luminance)", "藍色 (Blue)", "三者一樣敏感"],
    answer: 1,
    acceptAlso: [],
    explanation: "人眼對亮度（luminance）資訊最敏感，而綠色通道對亮度貢獻最大。因此，亮度通道的雜訊比色度通道的雜訊更容易被察覺。",
    imageDesc: "",
    scenario: "",
    hint: "人眼的視覺系統對亮度比對色彩更敏銳。"
  },
  {
    id: "iq_021",
    category: "iq",
    type: "truefalse",
    difficulty: 1,
    question: "Noise Power Spectrum (NPS) 可以同時描述雜訊的強度與頻率分佈。",
    options: [],
    answer: true,
    acceptAlso: [],
    explanation: "NPS 是雜訊在空間頻率域的功率密度函數，不僅告訴我們雜訊有多大（整體功率），還告訴我們雜訊主要集中在哪些頻率成分上（低頻 vs 高頻）。",
    imageDesc: "",
    scenario: "",
    hint: "NPS 的橫軸是空間頻率，縱軸是功率。"
  },
  {
    id: "iq_022",
    category: "iq",
    type: "fillblank",
    difficulty: 1,
    question: "Flare 和 Ghost 是由鏡頭內部的光線 _____ 造成的不良現象。",
    options: [],
    answer: "反射",
    acceptAlso: ["reflection", "內反射", "多次反射", "散射"],
    explanation: "Flare 和 Ghost 是光線在鏡頭多片鏡片之間多次反射所造成的。Flare 通常呈現為整體霧化或對比度下降，Ghost 則是明確的光斑形狀。鍍膜 (coating) 可有效減少此現象。",
    imageDesc: "",
    scenario: "",
    hint: "光線碰到鏡片表面會發生什麼？"
  },
  {
    id: "iq_023",
    category: "iq",
    type: "single",
    difficulty: 1,
    question: "在 ISP tuning 中，IQ trade-off 最常見的取捨是什麼？",
    options: ["解析度 vs 色彩", "降噪 vs 細節保留", "白平衡 vs 曝光", "對焦 vs 防手震"],
    answer: 1,
    acceptAlso: [],
    explanation: "降噪 (Noise Reduction) 與細節保留 (Detail Preservation) 是 ISP 調校中最經典的取捨。降噪太強會模糊紋理細節，降噪太弱則雜訊明顯。找到最佳平衡點是 IQ tuning 的核心挑戰。",
    imageDesc: "",
    scenario: "",
    hint: "去除雜訊時，容易同時丟失什麼？"
  },

  // ===== DIFFICULTY 2 (questions 024–046) =====
  {
    id: "iq_024",
    category: "iq",
    type: "single",
    difficulty: 2,
    question: "ΔE2000 相較於 ΔE76 (CIE 1976) 的主要改進是什麼？",
    options: ["計算速度更快", "更好地對應人眼的色差感知均勻性", "可以測量更多顏色", "支援 HDR 色域"],
    answer: 1,
    acceptAlso: [],
    explanation: "ΔE2000 引入了亮度、色度、色調的加權函數以及旋轉項 (rotation term)，修正了 CIE L*a*b* 色彩空間中感知不均勻的問題，使得計算出的色差更符合人眼的實際感受。",
    imageDesc: "",
    scenario: "",
    hint: "2000 版改善了「感知均勻性」。"
  },
  {
    id: "iq_025",
    category: "iq",
    type: "multiple",
    difficulty: 2,
    question: "以下哪些是 Macbeth ColorChecker 的 24 個色塊中包含的類型？（選擇所有正確的）",
    options: ["自然色 (skin, foliage, sky)", "灰階 (grayscale)", "飽和色 (saturated primary/secondary)", "螢光色 (fluorescent)"],
    answer: [0, 1, 2],
    acceptAlso: [],
    explanation: "Macbeth ColorChecker 包含自然色（如膚色、天空、樹葉）、6 階灰階（從黑到白）、以及飽和的原色與二次色。它不包含螢光色，因為螢光色的光譜特性特殊，不適合標準反射式校正。",
    imageDesc: "",
    scenario: "",
    hint: "ColorChecker 有三大類別的色塊。"
  },
  {
    id: "iq_026",
    category: "iq",
    type: "scenario",
    difficulty: 2,
    question: "一位 ISP 工程師發現相機在低光環境下拍攝的影像出現大量彩色雜點（chroma noise），但亮度通道的雜訊相對可接受。最適合的處理策略是？",
    options: ["增加整體銳化強度", "僅對色度通道加強降噪", "降低感測器的類比增益", "增加曝光時間到 10 秒"],
    answer: 1,
    acceptAlso: [],
    explanation: "由於人眼對色度的空間解析度較低，可以在 YCbCr 或 YUV 色彩空間中，針對色度通道 (Cb/Cr) 施加較強的降噪，同時保持亮度通道 (Y) 的銳利度，這是 ISP 中非常常見的策略。",
    imageDesc: "",
    scenario: "場景：低光環境，ISO 3200，彩色雜點明顯但亮度雜訊可接受。",
    hint: "人眼對色度的空間解析度比亮度低。"
  },
  {
    id: "iq_027",
    category: "iq",
    type: "single",
    difficulty: 2,
    question: "MS-SSIM (Multi-Scale SSIM) 相較於 SSIM 的主要改進是什麼？",
    options: ["計算速度更快", "能在多個尺度上評估結構相似度", "不需要參考影像", "支援影片品質評估"],
    answer: 1,
    acceptAlso: [],
    explanation: "MS-SSIM 在多個降採樣尺度上計算 SSIM，然後加權組合。這使得評估結果更穩健，能同時考慮粗略結構和精細細節，更貼近人眼的多尺度視覺感知。",
    imageDesc: "",
    scenario: "",
    hint: "Multi-Scale 的意思就是關鍵。"
  },
  {
    id: "iq_028",
    category: "iq",
    type: "single",
    difficulty: 2,
    question: "在 slanted edge SFR 量測中，為什麼邊緣要傾斜約 5 度而不是完全垂直？",
    options: ["為了避免 moiré", "為了利用超取樣 (oversampling) 提高精度", "為了測量對角方向的 MTF", "為了減少鏡頭畸變的影響"],
    answer: 1,
    acceptAlso: [],
    explanation: "傾斜邊緣使得不同像素列的邊緣位置有亞像素級的偏移，透過組合多列資料可實現超取樣 (typically 4x)，大幅提高 Edge Spread Function (ESF) 的空間解析度，進而獲得更精確的 MTF。",
    imageDesc: "",
    scenario: "",
    hint: "傾斜可以利用不同行的邊緣位置差異。"
  },
  {
    id: "iq_029",
    category: "iq",
    type: "fillblank",
    difficulty: 2,
    question: "在 dead leaves chart 分析中，texture MTF 是透過比較拍攝影像與原始圖的 _____ 來計算的。",
    options: [],
    answer: "功率譜",
    acceptAlso: ["power spectrum", "power spectral density", "PSD", "頻譜"],
    explanation: "Texture MTF 是將拍攝影像的功率頻譜密度 (PSD) 除以原始 dead leaves chart 的 PSD，得到各空間頻率下的調變傳遞比值，反映系統對紋理細節的保留能力。",
    imageDesc: "",
    scenario: "",
    hint: "需要在頻率域比較訊號的「能量分佈」。"
  },
  {
    id: "iq_030",
    category: "iq",
    type: "multiple",
    difficulty: 2,
    question: "以下哪些屬於客觀影像品質指標 (Objective IQ Metrics)？（選擇所有正確的）",
    options: ["PSNR", "MOS", "SSIM", "LPIPS"],
    answer: [0, 2, 3],
    acceptAlso: [],
    explanation: "PSNR、SSIM、LPIPS 都是透過數學公式或模型自動計算的客觀指標，不需要人工參與。MOS (Mean Opinion Score) 則需要受測者主觀評分，屬於主觀指標。",
    imageDesc: "",
    scenario: "",
    hint: "哪一個需要「人」來打分？"
  },
  {
    id: "iq_031",
    category: "iq",
    type: "single",
    difficulty: 2,
    question: "Temporal noise 的量測通常需要什麼條件？",
    options: ["使用不同鏡頭拍攝", "在相同場景條件下拍攝多幀影像", "使用 HDR 模式", "在不同曝光下拍攝"],
    answer: 1,
    acceptAlso: [],
    explanation: "Temporal noise（時域雜訊）是指同一場景在不同時間幀之間的隨機變化。量測時需固定所有拍攝條件，拍攝多幀（通常 50–100 幀），然後計算各像素在時間軸上的標準差。",
    imageDesc: "",
    scenario: "",
    hint: "Temporal 意味著與「時間」有關。"
  },
  {
    id: "iq_032",
    category: "iq",
    type: "ordering",
    difficulty: 2,
    question: "請按照典型 ISP IQ tuning 的順序排列以下步驟（從先到後）：",
    options: [],
    answer: 0,
    acceptAlso: [],
    explanation: "ISP tuning 通常從感測器端開始：先校正黑電平和壞點，再處理鏡頭補償（LSC），然後進行白平衡與色彩校正，最後調整降噪與銳化。這個順序確保每一步的輸入都是已校正的資料。",
    imageDesc: "",
    scenario: "",
    hint: "從感測器最原始的訊號開始，逐步優化。",
    items: ["黑電平校正 (BLC)", "鏡頭陰影補償 (LSC)", "白平衡 / 色彩校正 (AWB/CCM)", "降噪與銳化 (NR/Sharpening)"]
  },
  {
    id: "iq_033",
    category: "iq",
    type: "single",
    difficulty: 2,
    question: "ΔE94 相較於 ΔE76 增加了什麼修正？",
    options: ["色調旋轉項", "亮度、色度、彩度的加權因子", "藍色區域的特殊修正", "溫度補償"],
    answer: 1,
    acceptAlso: [],
    explanation: "CIE94 在 ΔE76 的基礎上，加入了亮度 (kL)、色度 (kC)、彩度 (kH) 的加權因子和參數化函數 (SL, SC, SH)，使色差計算對不同色彩區域更均勻，但仍不如 ΔE2000 精確。",
    imageDesc: "",
    scenario: "",
    hint: "94 版引入了 k 和 S 系列的加權參數。"
  },
  {
    id: "iq_034",
    category: "iq",
    type: "scenario",
    difficulty: 2,
    question: "ISP 工程師在 DxOMark 基準測試中發現自家相機的低光 ISO 分數偏低。以下哪個改善方向最有效？",
    options: ["更換更大光圈的鏡頭", "降低感測器讀取雜訊 (read noise)", "增加影像輸出解析度", "改善 JPEG 壓縮品質"],
    answer: 1,
    acceptAlso: [],
    explanation: "DxOMark 的 Low-Light ISO 指標定義為 SNR 達到 30 dB 時的最高 ISO 值。降低感測器的讀取雜訊可以直接提升高 ISO 下的 SNR，從而提高此項分數。鏡頭光圈不計入感測器評分。",
    imageDesc: "",
    scenario: "場景：DxOMark 感測器評測，Low-Light ISO 項目表現不佳。",
    hint: "DxOMark 感測器測試不考慮鏡頭因素。"
  },
  {
    id: "iq_035",
    category: "iq",
    type: "single",
    difficulty: 2,
    question: "Lateral Chromatic Aberration (LCA) 主要影響影像的哪個區域？",
    options: ["中心區域最嚴重", "邊緣和角落最嚴重", "整個畫面均勻", "只影響暗部"],
    answer: 1,
    acceptAlso: [],
    explanation: "Lateral Chromatic Aberration（橫向色差）是因為不同波長的光在影像平面上的放大率不同，導致離軸越遠（越靠近邊緣）色差越大。中心區域幾乎沒有 LCA。",
    imageDesc: "",
    scenario: "",
    hint: "Lateral 表示「側向的」，與離中心距離有關。"
  },
  {
    id: "iq_036",
    category: "iq",
    type: "truefalse",
    difficulty: 2,
    question: "在 ISP tuning 中，sharpening 應該在降噪 (NR) 之前進行。",
    options: [],
    answer: false,
    acceptAlso: [],
    explanation: "銳化 (sharpening) 應在降噪之後進行。如果先銳化再降噪，銳化會同時增強雜訊，使降噪更困難並可能產生偽影。正確的順序是先降噪再銳化，以獲得乾淨且銳利的影像。",
    imageDesc: "",
    scenario: "",
    hint: "如果先增強高頻訊號，雜訊會發生什麼？"
  },
  {
    id: "iq_037",
    category: "iq",
    type: "single",
    difficulty: 2,
    question: "NPS (Noise Power Spectrum) 呈現平坦分佈（白雜訊）代表什麼意義？",
    options: ["雜訊只存在於低頻", "雜訊能量均勻分佈在所有空間頻率上", "雜訊已被完全消除", "雜訊只存在於高頻"],
    answer: 1,
    acceptAlso: [],
    explanation: "白雜訊 (white noise) 的 NPS 在所有空間頻率上具有相同的功率密度，呈現平坦分佈。相較之下，經過降噪處理後的 NPS 通常會在高頻處下降，因為降噪器傾向於衰減高頻成分。",
    imageDesc: "",
    scenario: "",
    hint: "「白」光包含所有波長的均勻分佈。"
  },
  {
    id: "iq_038",
    category: "iq",
    type: "fillblank",
    difficulty: 2,
    question: "MOS 評分通常使用 _____ 分制量表，其中 5 分代表最佳品質。",
    options: [],
    answer: "5",
    acceptAlso: ["五", "1-5", "1到5"],
    explanation: "ITU-R BT.500 建議的 MOS 使用 5 分制量表：5 = Excellent, 4 = Good, 3 = Fair, 2 = Poor, 1 = Bad。受測者至少需要 15 人以上才能獲得統計上有意義的結果。",
    imageDesc: "",
    scenario: "",
    hint: "ITU 標準建議的量表。"
  },
  {
    id: "iq_039",
    category: "iq",
    type: "image",
    difficulty: 2,
    question: "觀察下圖所描述的 MTF 曲線，當空間頻率為 Nyquist frequency 時，理想的 MTF 值應該是？",
    options: ["0（完全無對比度）", "接近 0 但不為 0", "0.5（50%）", "1.0（100%）"],
    answer: 1,
    acceptAlso: [],
    explanation: "在 Nyquist 頻率處（取樣頻率的一半），理想的離散系統 MTF 會趨近於 0 但不會完全為 0。實際系統中，由於抗混疊濾波器 (OLPF) 的作用，MTF 在 Nyquist 頻率附近會被刻意壓低以避免摩爾紋。",
    imageDesc: "一條 MTF 曲線圖，橫軸為空間頻率（cycles/pixel），縱軸為 MTF 值（0 到 1）。曲線從左側 MTF=1 開始，隨頻率增加而逐漸下降，在 Nyquist 頻率（0.5 cycles/pixel）處接近 0。",
    scenario: "",
    hint: "Nyquist 是取樣定理中的關鍵頻率。"
  },
  {
    id: "iq_040",
    category: "iq",
    type: "single",
    difficulty: 2,
    question: "在測量鏡頭畸變 (Distortion) 時，通常使用什麼測試圖案？",
    options: ["灰階漸層圖", "點陣列或棋盤格圖案", "隨機噪點圖", "色彩條紋圖"],
    answer: 1,
    acceptAlso: [],
    explanation: "畸變測量使用規則的幾何圖案（如點陣列或棋盤格），透過比較拍攝後圖案的變形程度與理想位置的偏差，可以精確計算出桶形、枕形和複合畸變的大小。",
    imageDesc: "",
    scenario: "",
    hint: "需要規則的幾何參考點才能量測「彎曲」程度。"
  },
  {
    id: "iq_041",
    category: "iq",
    type: "multiple",
    difficulty: 2,
    question: "以下哪些是 ISP IQ tuning 中常見的 trade-off？（選擇所有正確的）",
    options: ["降噪強度 vs 紋理細節", "銳化強度 vs 偽影 (artifacts)", "色彩飽和度 vs 色彩準確度", "曝光時間 vs 解析度"],
    answer: [0, 1, 2],
    acceptAlso: [],
    explanation: "ISP tuning 中有多組經典 trade-off：降噪會損失細節、銳化會引入 halo/ringing 偽影、提高飽和度會降低色彩準確度。曝光時間主要影響亮度和動態模糊，與解析度無直接 trade-off 關係。",
    imageDesc: "",
    scenario: "",
    hint: "想想每個處理步驟的「副作用」。"
  },
  {
    id: "iq_042",
    category: "iq",
    type: "truefalse",
    difficulty: 2,
    question: "PSNR 的計算需要一張參考影像（ground truth）。",
    options: [],
    answer: true,
    acceptAlso: [],
    explanation: "PSNR 是 full-reference 指標，計算公式為 10·log₁₀(MAX²/MSE)，其中 MSE 是測試影像與參考影像之間的均方誤差。沒有參考影像就無法計算 PSNR。",
    imageDesc: "",
    scenario: "",
    hint: "需要計算兩張影像之間的 MSE。"
  },
  {
    id: "iq_043",
    category: "iq",
    type: "single",
    difficulty: 2,
    question: "在白平衡準確度測試中，通常使用什麼指標來量化色溫偏差？",
    options: ["ΔE of neutral patches", "PSNR", "MTF50", "Distortion percentage"],
    answer: 0,
    acceptAlso: [],
    explanation: "白平衡準確度通常透過拍攝 ColorChecker 或灰卡，計算中性色塊（灰階色塊）在 CIE L*a*b* 色彩空間中與理想中性色的 ΔE 值來量化。ΔE 越小，白平衡越準確。",
    imageDesc: "",
    scenario: "",
    hint: "中性色塊理論上不應該有色偏。"
  },
  {
    id: "iq_044",
    category: "iq",
    type: "single",
    difficulty: 2,
    question: "Visual noise 量測中，為什麼要使用 CSF (Contrast Sensitivity Function) 加權？",
    options: ["為了加速計算", "為了模擬人眼對不同空間頻率雜訊的不同敏感度", "為了去除色彩雜訊", "為了匹配顯示器的 gamma 曲線"],
    answer: 1,
    acceptAlso: [],
    explanation: "人眼對不同空間頻率的對比度敏感度不同（對中頻最敏感，對極低頻和極高頻較不敏感）。CSF 加權使 visual noise 的量化結果更符合人眼的實際感知，避免高估或低估特定頻率的雜訊影響。",
    imageDesc: "",
    scenario: "",
    hint: "人眼是一個帶通濾波器。"
  },
  {
    id: "iq_045",
    category: "iq",
    type: "scenario",
    difficulty: 2,
    question: "你正在調校手機相機的夜景模式，使用者反饋照片看起來「太油畫感」（over-smoothing）。你會優先調整哪個參數？",
    options: ["增加 gamma 值", "降低降噪 (NR) 的強度", "增加 JPEG 壓縮品質", "提高自動曝光的目標亮度"],
    answer: 1,
    acceptAlso: [],
    explanation: "「油畫感」是降噪過度 (over-smoothing) 的典型表現，紋理細節被過度平滑化。應降低降噪強度或調整降噪的空間頻率選擇性，保留更多中高頻紋理，同時可能需要微調銳化來恢復邊緣。",
    imageDesc: "",
    scenario: "場景：手機夜景模式，ISO 6400，使用者抱怨照片有「油畫感」。",
    hint: "油畫感 = 紋理細節被磨平了。"
  },
  {
    id: "iq_046",
    category: "iq",
    type: "single",
    difficulty: 2,
    question: "Longitudinal Chromatic Aberration (LoCA) 與 Lateral Chromatic Aberration (LCA) 的主要差異是？",
    options: ["LoCA 是軸向焦點偏移，LCA 是橫向放大率差異", "LoCA 只影響紅色，LCA 只影響藍色", "LoCA 可用軟體完全修正，LCA 不行", "兩者沒有實質差異"],
    answer: 0,
    acceptAlso: [],
    explanation: "LoCA（縱向色差）是不同波長聚焦在光軸方向的不同位置（前後偏移），表現為散焦色暈。LCA（橫向色差）是不同波長在像面上的放大率不同（橫向偏移），表現為邊緣色條。LCA 較易透過軟體修正，LoCA 較難。",
    imageDesc: "",
    scenario: "",
    hint: "Longitudinal = 前後方向，Lateral = 橫向。"
  },

  // ===== DIFFICULTY 3 (questions 047–070) =====
  {
    id: "iq_047",
    category: "iq",
    type: "single",
    difficulty: 3,
    question: "在使用 dead leaves chart 量測 texture MTF 時，如果降噪演算法具有「texture copy-back」功能，會對結果產生什麼影響？",
    options: ["texture MTF 會偏低", "texture MTF 可能人為偏高，甚至超過 1.0", "不會有任何影響", "只影響低頻部分"],
    answer: 1,
    acceptAlso: [],
    explanation: "Texture copy-back（或稱 texture synthesis/hallucination）會在降噪後重新注入紋理，可能使 dead leaves 測量的 texture MTF 超過 1.0，因為注入的紋理增加了功率頻譜密度。這是 dead leaves chart 作為 IQ 指標的已知限制。",
    imageDesc: "",
    scenario: "",
    hint: "如果降噪後「製造」了新的紋理，功率頻譜會怎樣？"
  },
  {
    id: "iq_048",
    category: "iq",
    type: "scenario",
    difficulty: 3,
    question: "在比較兩台相機的 DxOMark 評分時，相機 A 的 Color Depth 為 26 bits，Dynamic Range 為 14.5 EV；相機 B 為 24.5 bits / 13.8 EV。但實際使用者評測中，相機 B 在人像拍攝的色彩受到更高評價。最可能的原因是？",
    options: ["DxOMark 測量有誤差", "相機 B 的 ISP 色彩調校（如膚色偏好）更符合消費者喜好", "色彩深度不影響照片品質", "使用者不懂如何評價色彩"],
    answer: 1,
    acceptAlso: [],
    explanation: "DxOMark 的 Color Depth 是感測器 RAW 層面的指標，反映的是「色彩記錄能力」。但最終使用者看到的是經過 ISP 處理後的 JPEG/HEIF，ISP 的色彩調校（如膚色偏好、色調映射、飽和度曲線）對主觀感受的影響可能大於 RAW 的色彩深度差異。",
    imageDesc: "",
    scenario: "場景：兩台旗艦手機的 DxOMark 感測器評分差異明顯，但消費者對色彩的主觀喜好與評分不一致。",
    hint: "感測器的客觀能力和最終輸出的主觀喜好不一定正相關。"
  },
  {
    id: "iq_049",
    category: "iq",
    type: "multiple",
    difficulty: 3,
    question: "在設計 NR (Noise Reduction) 演算法的 IQ 評估方案時，以下哪些指標的組合最全面？（選擇所有正確的）",
    options: ["PSNR + SSIM（用於整體失真評估）", "Dead leaves texture MTF（用於紋理保留評估）", "NPS 形狀分析（用於殘留雜訊特性評估）", "CPU 使用率（用於功耗評估）"],
    answer: [0, 1, 2],
    acceptAlso: [],
    explanation: "全面的 NR 評估需要：PSNR/SSIM 衡量整體訊號保真度、dead leaves texture MTF 衡量紋理細節保留、NPS 分析殘留雜訊的頻率分佈和視覺特性。CPU 使用率是效能指標，不屬於 IQ 評估範疇。",
    imageDesc: "",
    scenario: "",
    hint: "IQ 評估應涵蓋失真、紋理和雜訊三個維度。"
  },
  {
    id: "iq_050",
    category: "iq",
    type: "single",
    difficulty: 3,
    question: "LPIPS 使用的深度學習特徵通常取自哪個網路的哪些層？",
    options: ["ResNet 的最後一層", "VGG/AlexNet 的多個中間層", "YOLO 的偵測層", "GAN 的生成器"],
    answer: 1,
    acceptAlso: [],
    explanation: "LPIPS 提取 VGG 或 AlexNet 等預訓練分類網路的多個中間層特徵，計算特徵空間中的加權距離。使用多層特徵能同時捕捉低階（邊緣、紋理）和高階（語義結構）的感知差異。",
    imageDesc: "",
    scenario: "",
    hint: "需要多層次的特徵來模擬人類的感知。"
  },
  {
    id: "iq_051",
    category: "iq",
    type: "fillblank",
    difficulty: 3,
    question: "SNR 在 18% 灰卡（middle gray）上量測時，若感測器的 full well capacity 為 40,000 electrons 且量子效率使得中灰對應約 7,200 electrons，則 shot noise limited SNR 約為 _____ dB。",
    options: [],
    answer: "38.6",
    acceptAlso: ["38.5", "39", "38", "~39"],
    explanation: "Shot noise = √N = √7200 ≈ 84.9 electrons。SNR = N/√N = √N = √7200 ≈ 84.9。轉換為 dB：20·log₁₀(84.9) ≈ 38.6 dB。在 shot noise limited 情況下，SNR (dB) = 10·log₁₀(N)。",
    imageDesc: "",
    scenario: "",
    hint: "Shot noise limited SNR = √N，再換算成 dB。"
  },
  {
    id: "iq_052",
    category: "iq",
    type: "single",
    difficulty: 3,
    question: "在 ΔE2000 公式中，rotation term (RT) 主要修正哪個色彩區域的計算偏差？",
    options: ["紅色高飽和度區域", "藍色至紫色的色調交界區域", "中性灰附近", "綠色高亮度區域"],
    answer: 1,
    acceptAlso: [],
    explanation: "ΔE2000 的 rotation term (RT) 主要修正 CIE L*a*b* 色彩空間中藍色區域（色調角約 275°附近）的感知不均勻性。在此區域，色調差異和色度差異會產生交互作用，RT 項透過旋轉色差向量來補償此效應。",
    imageDesc: "",
    scenario: "",
    hint: "在 a*b* 平面上，哪個象限的感知最不均勻？"
  },
  {
    id: "iq_053",
    category: "iq",
    type: "scenario",
    difficulty: 3,
    question: "你負責調校車用相機的 ISP。該相機需要在白天強光和夜間低光下都能良好運作，但 NR 和 sharpening 參數只能有一組設定（無法切換）。如何制定策略？",
    options: ["以低光優先，使用強降噪", "以強光優先，使用強銳化", "使用 adaptive NR/sharpening，根據 ISO/gain 動態調整強度", "取消降噪和銳化，保持原始訊號"],
    answer: 2,
    acceptAlso: [],
    explanation: "車用相機面臨極端的光線變化，最佳策略是實現 adaptive（自適應）的 NR 和 sharpening，根據 analog gain / ISO / 場景亮度動態調整強度。低光下加強 NR 減弱 sharpening，強光下減弱 NR 加強 sharpening。這需要精心設計 gain-dependent 的參數曲線。",
    imageDesc: "",
    scenario: "場景：車用前視相機，ADAS 應用，白天 100k lux 到夜間 0.1 lux 的動態範圍，需要穩定的 IQ 輸出。",
    hint: "不同光線條件下，雜訊水準差異極大。"
  },
  {
    id: "iq_054",
    category: "iq",
    type: "single",
    difficulty: 3,
    question: "在量測 flare 時，「veiling glare index」的定義是？",
    options: ["最亮區域的飽和程度", "暗區亮度佔亮區亮度的比例", "光暈的面積佔比", "鏡頭鍍膜的反射率"],
    answer: 1,
    acceptAlso: [],
    explanation: "Veiling glare index 定義為在高對比場景中，理應全黑區域所量測到的亮度值與亮區亮度值的比值。典型測量使用黑色中心的光箱，量測黑區的「漏光」程度。數值越低，鏡頭的抗 flare 能力越好。",
    imageDesc: "",
    scenario: "",
    hint: "衡量的是不該亮的地方有多亮。"
  },
  {
    id: "iq_055",
    category: "iq",
    type: "ordering",
    difficulty: 3,
    question: "請按照對人眼視覺感知影響從大到小排列以下雜訊類型：",
    options: [],
    answer: 0,
    acceptAlso: [],
    explanation: "低頻亮度雜訊（如 banding）最刺眼因為人眼對低頻對比度變化很敏感；中頻亮度雜訊次之；高頻色度雜訊（彩色雜點）因為人眼色度空間解析度低而影響較小；均勻白雜訊若粒度夠細則最不明顯。",
    imageDesc: "",
    scenario: "",
    hint: "結合 CSF 與色度空間解析度來思考。",
    items: ["低頻亮度雜訊 (banding)", "中頻亮度雜訊 (grain)", "高頻色度雜訊 (chroma speckle)", "均勻細緻白雜訊 (fine white noise)"]
  },
  {
    id: "iq_056",
    category: "iq",
    type: "single",
    difficulty: 3,
    question: "使用 Siemens star 量測 MTF 時，相較於 slanted edge 方法的主要優勢是？",
    options: ["計算更簡單", "可同時量測所有方向的 MTF", "不受鏡頭像差影響", "精度更高"],
    answer: 1,
    acceptAlso: [],
    explanation: "Siemens star 的放射狀條紋覆蓋 360° 所有方向，因此一次拍攝即可分析各個角度的 MTF，特別適合檢測散光 (astigmatism) 等方向性像差。Slanted edge 每次只能量測一個方向的 MTF。",
    imageDesc: "",
    scenario: "",
    hint: "Siemens star 的條紋指向所有方向。"
  },
  {
    id: "iq_057",
    category: "iq",
    type: "multiple",
    difficulty: 3,
    question: "以下哪些因素會影響 temporal noise 的量測結果？（選擇所有正確的）",
    options: ["感測器溫度漂移", "光源的 flicker（閃爍）", "拍攝幀數不足", "鏡頭的光學解析度"],
    answer: [0, 1, 2],
    acceptAlso: [],
    explanation: "感測器溫度漂移會改變暗電流導致雜訊變化；光源 flicker 會引入非隨機的幀間亮度變化被誤判為雜訊；幀數不足則統計量不穩定。鏡頭解析度影響的是空間頻率響應而非時域雜訊。",
    imageDesc: "",
    scenario: "",
    hint: "temporal noise 是「時間」上的變化量。"
  },
  {
    id: "iq_058",
    category: "iq",
    type: "scenario",
    difficulty: 3,
    question: "在做 A/B 主觀評測時，20 位受測者對兩組影像的 MOS 分別為 3.8 ± 0.6 和 3.5 ± 0.7（平均 ± 標準差）。你能否下結論說影像 A 優於影像 B？",
    options: ["可以，因為 3.8 > 3.5", "不一定，需要進行統計顯著性檢定（如 t-test）", "不能，因為差距小於 1 分", "可以，因為標準差都小於 1"],
    answer: 1,
    acceptAlso: [],
    explanation: "僅比較平均值不足以下結論。需要進行統計顯著性檢定（如 paired t-test 或 Wilcoxon signed-rank test），考慮樣本數、標準差和信賴區間。以此例計算，0.3 分的差異在 n=20 時可能無法達到 p<0.05 的顯著水準。",
    imageDesc: "",
    scenario: "場景：主觀影像品質 A/B 測試，20 位受測者，5 分制 MOS 評分。",
    hint: "平均值的差異不等於統計上的顯著差異。"
  },
  {
    id: "iq_059",
    category: "iq",
    type: "single",
    difficulty: 3,
    question: "在 camera benchmarking 中，為什麼 PSNR 常被批評為不可靠的品質指標？",
    options: ["計算速度太慢", "PSNR 基於像素級 MSE，未考慮人眼的空間敏感度和結構感知", "只能用於灰階影像", "數值範圍太小，無法區分品質差異"],
    answer: 1,
    acceptAlso: [],
    explanation: "PSNR 僅計算逐像素的均方誤差，不考慮空間頻率加權、結構相似性、遮蔽效應等人眼視覺特性。例如，微小的全局亮度偏移會大幅降低 PSNR，但人眼幾乎感知不到；而局部的結構性失真 PSNR 可能不敏感，但人眼很容易察覺。",
    imageDesc: "",
    scenario: "",
    hint: "像素級的均方誤差是否等於人眼感受？"
  },
  {
    id: "iq_060",
    category: "iq",
    type: "fillblank",
    difficulty: 3,
    question: "在 ISP tuning 中，為了同時優化多個 IQ 指標（如 SNR、sharpness、color accuracy），常使用 _____ 方法來找到 Pareto 最優解。",
    options: [],
    answer: "多目標優化",
    acceptAlso: ["multi-objective optimization", "Pareto optimization", "MOO", "多目標最佳化"],
    explanation: "多目標優化 (Multi-Objective Optimization) 可以同時考慮多個互相衝突的 IQ 指標，生成一組 Pareto 前沿解（沒有任何解在所有指標上都優於另一個解），讓工程師根據產品需求在 trade-off 中選擇最適合的參數組合。",
    imageDesc: "",
    scenario: "",
    hint: "有多個目標且互相衝突時，需要一種特殊的優化方法。"
  },
  {
    id: "iq_061",
    category: "iq",
    type: "image",
    difficulty: 3,
    question: "觀察下圖所描述的 NPS 曲線。經過降噪處理後，NPS 在高頻區域明顯下降但在低頻出現隆起 (bump)。這種現象的原因最可能是？",
    options: ["降噪器引入了低頻偽影（如 blotchiness）", "感測器的固定模式雜訊增加", "鏡頭散焦造成的模糊", "量測誤差"],
    answer: 0,
    acceptAlso: [],
    explanation: "許多空間域降噪演算法在抑制高頻雜訊的同時，會在低頻區域引入能量聚集（NPS bump），表現為大尺度的亮度不均勻或「斑塊感」(blotchiness)。這是非局部降噪和 bilateral filter 等方法的常見副作用。",
    imageDesc: "兩條 NPS 曲線：藍色為降噪前（相對平坦的白雜訊），紅色為降噪後（低頻區域有明顯隆起 bump，高頻區域明顯下降至接近零）。",
    scenario: "",
    hint: "高頻雜訊被抑制了，但低頻區域反而增加了能量。"
  },
  {
    id: "iq_062",
    category: "iq",
    type: "single",
    difficulty: 3,
    question: "在進行 color accuracy 校正時，使用 3x3 CCM (Color Correction Matrix) 的根本限制是什麼？",
    options: ["計算量太大", "只能做線性變換，無法修正感測器光譜響應的非理想性所造成的 metamerism 問題", "只支援 sRGB 輸出", "需要超過 24 個校正點"],
    answer: 1,
    acceptAlso: [],
    explanation: "3x3 CCM 只能進行線性映射，但感測器的 spectral response curves 若與 CIE color matching functions 非線性偏離（即 Luther condition 不滿足），則存在 metamerism failure：相同的感測器輸出對應不同的真實顏色。這是線性矩陣無法修正的根本限制。",
    imageDesc: "",
    scenario: "",
    hint: "Luther condition 和 spectral sensitivity 有關。"
  },
  {
    id: "iq_063",
    category: "iq",
    type: "truefalse",
    difficulty: 3,
    question: "MS-SSIM 在所有場景下都比 SSIM 更好地預測人眼的品質感受。",
    options: [],
    answer: false,
    acceptAlso: [],
    explanation: "雖然 MS-SSIM 通常與人眼感知的相關性更高，但在某些特定失真類型（如全局色彩偏移、局部幾何畸變）下，MS-SSIM 也有盲點。沒有單一指標能在所有場景下完美預測人眼感受，這也是為什麼需要多指標組合評估。",
    imageDesc: "",
    scenario: "",
    hint: "任何客觀指標都有其適用範圍和盲點。"
  },
  {
    id: "iq_064",
    category: "iq",
    type: "scenario",
    difficulty: 3,
    question: "你在做鏡頭評估時發現 MTF50 很高，但實際拍攝的照片看起來仍然不夠銳利。檢查發現 MTF 曲線在中頻有一個明顯的凹谷 (dip) 然後在 Nyquist 附近回升。最可能的原因是？",
    options: ["測量誤差", "空間混疊 (aliasing) 造成偽銳利度", "鏡頭溫度變化", "感測器壞點"],
    answer: 1,
    acceptAlso: [],
    explanation: "MTF 在 Nyquist 附近回升通常是 aliasing 的跡象。缺乏適當的 OLPF (Optical Low-Pass Filter) 時，高於 Nyquist 的頻率會被摺疊回來，造成 MTF 曲線的「假回升」。MTF50 數值可能看起來不錯，但視覺上會出現 moiré 和 false detail，反而降低感知銳利度。",
    imageDesc: "",
    scenario: "場景：新鏡頭評估，MTF50 測試結果良好（超過競品），但主觀看起來銳利度不佳，且有 moiré 現象。",
    hint: "Nyquist 附近的 MTF 回升是什麼的訊號？"
  },
  {
    id: "iq_065",
    category: "iq",
    type: "multiple",
    difficulty: 3,
    question: "在建立一套完整的 IQ tuning workflow 時，以下哪些是必要的步驟？（選擇所有正確的）",
    options: ["建立 golden reference（基準參考影像集）", "定義各項 IQ 指標的目標值和容許範圍", "在不同光照和色溫條件下進行驗證", "確保所有 IQ 指標同時達到最大值"],
    answer: [0, 1, 2],
    acceptAlso: [],
    explanation: "完整的 IQ tuning workflow 需要：golden reference 作為品質基準、明確的指標目標值做為 pass/fail 判據、多條件驗證確保穩健性。但由於 IQ 指標之間存在 trade-off，不可能所有指標同時達到最大值，需要在 trade-off 中取得平衡。",
    imageDesc: "",
    scenario: "",
    hint: "第四個選項在實際上是否可行？"
  },
  {
    id: "iq_066",
    category: "iq",
    type: "fillblank",
    difficulty: 3,
    question: "在 ISO 19567-1 標準中，distortion 的計算使用 _____ 模型來擬合徑向畸變曲線。",
    options: [],
    answer: "多項式",
    acceptAlso: ["polynomial", "Brown-Conrady", "radial polynomial", "多項式模型"],
    explanation: "ISO 19567-1 使用徑向多項式模型 (radial polynomial model)，通常包含 k1, k2, k3 等係數，描述畸變隨距離中心半徑的變化關係：r' = r(1 + k1·r² + k2·r⁴ + k3·r⁶ + ...)。Brown-Conrady 模型也常被使用。",
    imageDesc: "",
    scenario: "",
    hint: "用一系列遞增次方的項來擬合曲線。"
  },
  {
    id: "iq_067",
    category: "iq",
    type: "single",
    difficulty: 3,
    question: "在比較兩種降噪演算法時，算法 A 的 PSNR 高於算法 B，但 LPIPS 分數算法 B 更好（更低）。這表明什麼？",
    options: ["測量有錯誤", "算法 B 在感知品質上更好，但逐像素精度較低", "算法 A 在所有方面都更好", "兩者品質相同"],
    answer: 1,
    acceptAlso: [],
    explanation: "PSNR 衡量逐像素精度，LPIPS 衡量感知相似度。算法 B 的 LPIPS 更好意味著在深度特徵空間中更接近原圖（感知品質更高），但像素級 MSE 較大。這在現代生成式降噪（如 neural network-based NR）中很常見：生成的紋理感知上合理但像素對不準。",
    imageDesc: "",
    scenario: "",
    hint: "PSNR 和 LPIPS 衡量的是不同維度的品質。"
  },
  {
    id: "iq_068",
    category: "iq",
    type: "ordering",
    difficulty: 3,
    question: "請按照計算複雜度從低到高排列以下影像品質指標：",
    options: [],
    answer: 0,
    acceptAlso: [],
    explanation: "PSNR 只需逐像素計算 MSE，複雜度最低 O(N)。SSIM 需要計算局部統計量（均值、方差、協方差），使用滑動窗口。MS-SSIM 需要多尺度下採樣和多次 SSIM 計算。LPIPS 需要執行深度神經網路前向傳播（如 VGG-16），計算複雜度最高。",
    imageDesc: "",
    scenario: "",
    hint: "從簡單的數學運算到需要 GPU 的深度學習推理。",
    items: ["PSNR", "SSIM", "MS-SSIM", "LPIPS"]
  },
  {
    id: "iq_069",
    category: "iq",
    type: "scenario",
    difficulty: 3,
    question: "你正在為一款 120MP 手機相機進行 IQ benchmarking。使用 ISO 12233 chart 進行 MTF 量測時，發現 center 和 corner 的 MTF50 差距超過 40%。進一步分析發現這個差距在 full resolution 模式下出現，但在 pixel-binning 的 30MP 模式下差距縮小到 15%。最可能的解釋是？",
    options: ["ISO 12233 chart 的印刷品質不夠", "full resolution 下像素尺寸太小，邊角的光學像差被更明顯地暴露出來", "pixel-binning 模式的 ISP 處理不同", "感測器邊角壞點多"],
    answer: 1,
    acceptAlso: [],
    explanation: "120MP 的極小像素 pitch（~0.7μm）意味著對光學解析度的要求極高。邊角的像差（如 field curvature、coma、astigmatism）在 full resolution 下會被小像素完全「看到」，但 pixel-binning 後等效像素尺寸增大（~1.4μm），有效降低了取樣頻率，相當於內建了低通濾波，使光學像差的相對影響減小。",
    imageDesc: "",
    scenario: "場景：120MP 手機相機的 full resolution 與 30MP binning 模式 MTF 差異分析。",
    hint: "更小的像素對光學品質的要求更高。"
  },
  {
    id: "iq_070",
    category: "iq",
    type: "single",
    difficulty: 3,
    question: "在進行主觀 vs 客觀品質評估的相關性分析時，常使用哪兩種相關係數，各自的用途是什麼？",
    options: [
      "Pearson (線性相關度) 和 Spearman (排名相關度)",
      "R² (決定係數) 和 F-score",
      "RMSE 和 MAE",
      "Cosine similarity 和 Euclidean distance"
    ],
    answer: 0,
    acceptAlso: [],
    explanation: "Pearson Linear Correlation Coefficient (PLCC) 衡量客觀指標與 MOS 之間的線性一致性（通常需先做非線性擬合），Spearman Rank-Order Correlation Coefficient (SROCC) 衡量排名一致性。SROCC 不要求線性關係，更穩健。兩者結合使用是 IQA (Image Quality Assessment) 研究的標準做法。",
    imageDesc: "",
    scenario: "",
    hint: "一個看數值的線性關係，一個看排名的一致性。"
  }
];
