const Q_NR = [
  // ===== DIFFICULTY 1 (nr_001 ~ nr_050) =====
  {
    id: "nr_001",
    category: "nr",
    type: "truefalse",
    difficulty: 1,
    question: "Shot noise 是由光子到達感測器時的統計波動所產生的，屬於 signal-dependent noise。",
    options: ["正確", "錯誤"],
    answer: true,
    acceptAlso: [],
    explanation: "Shot noise 源自光子抵達的 Poisson 統計特性，其變異量與訊號強度的平方根成正比，因此是 signal-dependent noise。",
    imageDesc: "",
    scenario: "",
    hint: "想想光子計數的隨機性。",
    items: []
  },
  {
    id: "nr_002",
    category: "nr",
    type: "single",
    difficulty: 1,
    question: "下列哪種雜訊主要來自感測器電子電路的隨機電子波動？",
    options: ["Shot noise", "Read noise", "Quantization noise", "Fixed pattern noise"],
    answer: 1,
    acceptAlso: [],
    explanation: "Read noise（讀取雜訊）是在讀取感測器資料時，由電路中電子的隨機熱擾動產生的，與訊號強度無關。",
    imageDesc: "",
    scenario: "",
    hint: "這種雜訊即使在零曝光時也存在。",
    items: []
  },
  {
    id: "nr_003",
    category: "nr",
    type: "single",
    difficulty: 1,
    question: "Thermal noise（熱雜訊）的強度主要受什麼因素影響？",
    options: ["光圈大小", "感測器溫度", "鏡頭焦距", "影像解析度"],
    answer: 1,
    acceptAlso: [],
    explanation: "Thermal noise 又稱 Johnson-Nyquist noise，其能量與絕對溫度成正比。降低感測器溫度是減少 thermal noise 的有效方法。",
    imageDesc: "",
    scenario: "",
    hint: "天文攝影常用冷卻相機來減少此雜訊。",
    items: []
  },
  {
    id: "nr_004",
    category: "nr",
    type: "truefalse",
    difficulty: 1,
    question: "Fixed pattern noise (FPN) 是一種隨機雜訊，每次拍攝都會不同。",
    options: ["正確", "錯誤"],
    answer: false,
    acceptAlso: [],
    explanation: "Fixed pattern noise 是固定模式雜訊，由感測器製造差異造成，在相同條件下每次拍攝都呈現相同的空間模式，因此不是隨機雜訊。",
    imageDesc: "",
    scenario: "",
    hint: "注意「Fixed」這個字的含義。",
    items: []
  },
  {
    id: "nr_005",
    category: "nr",
    type: "single",
    difficulty: 1,
    question: "Dark current noise 在什麼情況下最為嚴重？",
    options: ["短曝光、低溫度", "長曝光、高溫度", "高 ISO、低溫度", "短曝光、高溫度"],
    answer: 1,
    acceptAlso: [],
    explanation: "Dark current 隨曝光時間線性增加，且溫度每升高約 6-8°C，dark current 大約加倍。因此長曝光加上高溫度時最嚴重。",
    imageDesc: "",
    scenario: "",
    hint: "Dark current 與曝光時間和溫度都有關。",
    items: []
  },
  {
    id: "nr_006",
    category: "nr",
    type: "fillblank",
    difficulty: 1,
    question: "Quantization noise 是將類比訊號轉換為 ______ 訊號時產生的誤差。",
    options: [],
    answer: "數位",
    acceptAlso: ["digital", "數字"],
    explanation: "ADC（類比轉數位轉換器）將連續的類比訊號量化為離散的數位值時，不可避免地產生 quantization noise。",
    imageDesc: "",
    scenario: "",
    hint: "ADC 的全名是什麼？",
    items: []
  },
  {
    id: "nr_007",
    category: "nr",
    type: "single",
    difficulty: 1,
    question: "SNR（Signal-to-Noise Ratio）的定義是什麼？",
    options: ["雜訊功率除以訊號功率", "訊號功率除以雜訊功率", "訊號振幅加上雜訊振幅", "雜訊振幅減去訊號振幅"],
    answer: 1,
    acceptAlso: [],
    explanation: "SNR 定義為訊號功率與雜訊功率的比值（或其 dB 表示）。SNR 越高代表影像品質越好。",
    imageDesc: "",
    scenario: "",
    hint: "S 在分子還是分母？",
    items: []
  },
  {
    id: "nr_008",
    category: "nr",
    type: "truefalse",
    difficulty: 1,
    question: "PSNR（Peak Signal-to-Noise Ratio）值越高，表示影像品質越差。",
    options: ["正確", "錯誤"],
    answer: false,
    acceptAlso: [],
    explanation: "PSNR 越高表示訊號相對於雜訊越大，即影像品質越好。一般認為 PSNR > 30 dB 表示品質可接受。",
    imageDesc: "",
    scenario: "",
    hint: "PSNR 以 dB 為單位，數值越高越好。",
    items: []
  },
  {
    id: "nr_009",
    category: "nr",
    type: "single",
    difficulty: 1,
    question: "Gaussian filter 進行降噪時，主要缺點是什麼？",
    options: ["計算量太大", "會模糊邊緣", "只能處理彩色影像", "需要 GPU 加速"],
    answer: 1,
    acceptAlso: [],
    explanation: "Gaussian filter 對所有像素均勻地進行平滑，不區分邊緣和平坦區域，因此在降噪的同時會模糊邊緣細節。",
    imageDesc: "",
    scenario: "",
    hint: "Gaussian filter 不考慮像素的空間結構差異。",
    items: []
  },
  {
    id: "nr_010",
    category: "nr",
    type: "single",
    difficulty: 1,
    question: "Median filter 最適合去除哪種雜訊？",
    options: ["Gaussian noise", "Salt-and-pepper noise", "Thermal noise", "Quantization noise"],
    answer: 1,
    acceptAlso: [],
    explanation: "Median filter 取鄰域中值作為輸出，對於脈衝型的 salt-and-pepper noise（椒鹽雜訊）特別有效，因為離群值不會影響中位數。",
    imageDesc: "",
    scenario: "",
    hint: "中位數對離群值（outlier）不敏感。",
    items: []
  },
  {
    id: "nr_011",
    category: "nr",
    type: "fillblank",
    difficulty: 1,
    question: "Bilateral filter 同時考慮像素的空間距離和 ______ 差異來決定權重。",
    options: [],
    answer: "強度",
    acceptAlso: ["intensity", "亮度", "灰度", "像素值"],
    explanation: "Bilateral filter 結合空間域（spatial domain）和值域（range domain）兩個高斯核，使其能在降噪的同時保留邊緣。",
    imageDesc: "",
    scenario: "",
    hint: "除了距離，還考慮像素之間的什麼差異？",
    items: []
  },
  {
    id: "nr_012",
    category: "nr",
    type: "truefalse",
    difficulty: 1,
    question: "提高 ISO 感光度會增加影像中的雜訊。",
    options: ["正確", "錯誤"],
    answer: true,
    acceptAlso: [],
    explanation: "提高 ISO 本質上是放大感測器訊號，同時也放大了雜訊。在相同曝光條件下，ISO 越高，雜訊越明顯。",
    imageDesc: "",
    scenario: "",
    hint: "ISO 是對訊號的增益放大。",
    items: []
  },
  {
    id: "nr_013",
    category: "nr",
    type: "single",
    difficulty: 1,
    question: "在 ISP pipeline 中，Noise Reduction 通常分為哪兩大處理域？",
    options: ["RGB 域和 HSV 域", "Raw 域和 YUV 域", "頻率域和空間域", "時間域和空間域"],
    answer: 1,
    acceptAlso: [],
    explanation: "ISP 中的 NR 通常在 raw domain（Bayer 資料）和 YUV domain（色彩空間轉換後）各做一次，以分別處理不同特性的雜訊。",
    imageDesc: "",
    scenario: "",
    hint: "ISP pipeline 前段和後段分別使用什麼資料格式？",
    items: []
  },
  {
    id: "nr_014",
    category: "nr",
    type: "single",
    difficulty: 1,
    question: "Chroma noise（色度雜訊）在影像中表現為什麼現象？",
    options: ["影像整體變暗", "出現隨機的彩色斑點", "影像解析度降低", "出現條紋狀紋理"],
    answer: 1,
    acceptAlso: [],
    explanation: "Chroma noise 是色彩通道中的雜訊，表現為影像中出現不自然的隨機彩色斑點，在暗部區域尤其明顯。",
    imageDesc: "",
    scenario: "",
    hint: "Chroma 指的是色彩。",
    items: []
  },
  {
    id: "nr_015",
    category: "nr",
    type: "truefalse",
    difficulty: 1,
    question: "Low-pass filter（低通濾波器）可以用於降噪，因為雜訊通常包含高頻成分。",
    options: ["正確", "錯誤"],
    answer: true,
    acceptAlso: [],
    explanation: "雜訊通常表現為高頻成分，low-pass filter 可以濾除高頻，從而達到降噪效果。但同時也可能損失影像的高頻細節。",
    imageDesc: "",
    scenario: "",
    hint: "雜訊在頻率域中通常位於哪個頻段？",
    items: []
  },
  {
    id: "nr_016",
    category: "nr",
    type: "single",
    difficulty: 1,
    question: "Multi-frame averaging（多幀平均）降噪的基本原理是什麼？",
    options: ["取多幀中的最大值", "對同一場景的多幀取平均", "只保留最清晰的一幀", "對多幀做差分運算"],
    answer: 1,
    acceptAlso: [],
    explanation: "將同一場景的多幀影像取平均，隨機雜訊會相互抵消（趨近於零均值），而訊號會被保留，從而提升 SNR。",
    imageDesc: "",
    scenario: "",
    hint: "隨機雜訊的均值為零。",
    items: []
  },
  {
    id: "nr_017",
    category: "nr",
    type: "fillblank",
    difficulty: 1,
    question: "對 N 幀影像進行平均可以使 SNR 提升約 ______ 倍。",
    options: [],
    answer: "√N",
    acceptAlso: ["根號N", "sqrt(N)", "sqrtN", "√n"],
    explanation: "多幀平均時，訊號維持不變但雜訊的標準差降低為原來的 1/√N，因此 SNR 提升 √N 倍。",
    imageDesc: "",
    scenario: "",
    hint: "與統計學中的標準誤差公式有關。",
    items: []
  },
  {
    id: "nr_018",
    category: "nr",
    type: "single",
    difficulty: 1,
    question: "NR 強度（strength）設定過高時最可能出現什麼問題？",
    options: ["雜訊增加", "過度平滑導致細節丟失", "影像變得更銳利", "色彩飽和度增加"],
    answer: 1,
    acceptAlso: [],
    explanation: "NR 強度過高會過度平滑影像，導致紋理和細節被抹除，產生所謂的「蠟像感」或「油畫效果」。",
    imageDesc: "",
    scenario: "",
    hint: "降噪和保留細節是一對矛盾。",
    items: []
  },
  {
    id: "nr_019",
    category: "nr",
    type: "truefalse",
    difficulty: 1,
    question: "Luma noise（亮度雜訊）通常比 Chroma noise（色度雜訊）更容易被人眼察覺。",
    options: ["正確", "錯誤"],
    answer: false,
    acceptAlso: [],
    explanation: "人眼對色彩異常比亮度細微變化更敏感，因此 chroma noise 的彩色斑點往往比 luma noise 的灰度顆粒更令人不適。但在實務上，luma NR 需要更謹慎以避免丟失細節。",
    imageDesc: "",
    scenario: "",
    hint: "人眼對不自然的色彩偏差非常敏感。",
    items: []
  },
  {
    id: "nr_020",
    category: "nr",
    type: "single",
    difficulty: 1,
    question: "在 ISP 中對 Chroma 和 Luma 分開降噪的主要好處是？",
    options: ["減少計算量", "可以對色度施加更強的降噪而不影響亮度細節", "避免產生 ghosting", "提高影像解析度"],
    answer: 1,
    acceptAlso: [],
    explanation: "人眼對色度的空間解析度較低，因此可以對 chroma 施加更強的降噪而不會明顯感覺到細節損失，同時保留 luma 的細節。",
    imageDesc: "",
    scenario: "",
    hint: "人眼對亮度和色度的敏感度不同。",
    items: []
  },
  {
    id: "nr_021",
    category: "nr",
    type: "ordering",
    difficulty: 1,
    question: "請將以下雜訊從最低頻到最高頻排序：",
    options: ["Fixed pattern noise", "Gaussian noise 的低頻成分", "Shot noise", "Quantization noise"],
    answer: 0,
    acceptAlso: [],
    explanation: "FPN 是空間上緩慢變化的低頻雜訊，Gaussian noise 有低頻成分，Shot noise 和 Quantization noise 則傾向高頻分佈。",
    imageDesc: "",
    scenario: "",
    hint: "固定模式雜訊的空間頻率最低。",
    items: ["Fixed pattern noise", "Gaussian noise 的低頻成分", "Shot noise", "Quantization noise"]
  },
  {
    id: "nr_022",
    category: "nr",
    type: "single",
    difficulty: 1,
    question: "Noise floor（雜訊底線）指的是什麼？",
    options: ["影像中雜訊的最大值", "感測器能檢測到的最小訊號水準", "影像的最暗區域", "雜訊的空間頻率"],
    answer: 1,
    acceptAlso: [],
    explanation: "Noise floor 是系統中固有的最低雜訊水準，任何低於此水準的訊號都無法被有效偵測，它決定了感測器的動態範圍下限。",
    imageDesc: "",
    scenario: "",
    hint: "低於此水準的訊號會被雜訊淹沒。",
    items: []
  },
  {
    id: "nr_023",
    category: "nr",
    type: "truefalse",
    difficulty: 1,
    question: "Wavelet denoising 的基本概念是在小波域中對小係數進行閾值處理（thresholding）。",
    options: ["正確", "錯誤"],
    answer: true,
    acceptAlso: [],
    explanation: "小波變換後，雜訊通常表現為小係數，訊號則對應大係數。透過閾值處理（soft 或 hard thresholding）去除小係數即可降噪。",
    imageDesc: "",
    scenario: "",
    hint: "小波域中訊號和雜訊的係數大小有明顯差異。",
    items: []
  },
  {
    id: "nr_024",
    category: "nr",
    type: "single",
    difficulty: 1,
    question: "Temporal NR（時域降噪）可能產生的主要偽影是什麼？",
    options: ["色彩偏移", "Ghosting（鬼影）", "摩爾紋", "紫邊"],
    answer: 1,
    acceptAlso: [],
    explanation: "Temporal NR 利用連續幀的資訊降噪，當場景中有運動物體時，若運動補償不準確，會產生 ghosting 偽影。",
    imageDesc: "",
    scenario: "",
    hint: "運動物體在多幀融合時可能留下殘影。",
    items: []
  },
  {
    id: "nr_025",
    category: "nr",
    type: "fillblank",
    difficulty: 1,
    question: "BM3D 演算法名稱中的 BM 代表 Block ______。",
    options: [],
    answer: "Matching",
    acceptAlso: ["matching"],
    explanation: "BM3D 全名為 Block-Matching and 3D filtering，先透過 block matching 找到相似的 patch，再進行 3D 協同濾波。",
    imageDesc: "",
    scenario: "",
    hint: "BM3D 的第一步是尋找相似的影像塊。",
    items: []
  },
  {
    id: "nr_026",
    category: "nr",
    type: "single",
    difficulty: 1,
    question: "DnCNN 是一種基於什麼技術的降噪方法？",
    options: ["傳統濾波器", "深度學習（Deep Learning）", "傅立葉變換", "形態學運算"],
    answer: 1,
    acceptAlso: [],
    explanation: "DnCNN（Denoising Convolutional Neural Network）是一種使用深度卷積神經網路的降噪方法，透過學習殘差（residual learning）來預測雜訊。",
    imageDesc: "",
    scenario: "",
    hint: "名稱中有 CNN。",
    items: []
  },
  {
    id: "nr_027",
    category: "nr",
    type: "truefalse",
    difficulty: 1,
    question: "在 raw domain 做降噪的好處之一是雜訊模型較為簡單且準確。",
    options: ["正確", "錯誤"],
    answer: true,
    acceptAlso: [],
    explanation: "Raw 資料尚未經過 demosaic、gamma、tone mapping 等非線性處理，雜訊仍符合較單純的 Poisson-Gaussian 模型，有利於精確降噪。",
    imageDesc: "",
    scenario: "",
    hint: "ISP 後續處理會改變雜訊的統計特性。",
    items: []
  },
  {
    id: "nr_028",
    category: "nr",
    type: "single",
    difficulty: 1,
    question: "Noise profile（雜訊剖面）描述的是什麼關係？",
    options: ["雜訊與色溫的關係", "雜訊水準與訊號強度的關係", "雜訊與快門速度的關係", "雜訊與鏡頭焦距的關係"],
    answer: 1,
    acceptAlso: [],
    explanation: "Noise profile 描述不同訊號強度下的雜訊變異量，通常以 noise level function (NLF) 表示，是 NR 調校的基礎。",
    imageDesc: "",
    scenario: "",
    hint: "不同亮度區域的雜訊程度不同。",
    items: []
  },
  {
    id: "nr_029",
    category: "nr",
    type: "single",
    difficulty: 1,
    question: "Guided filter 需要一張什麼影像來引導濾波過程？",
    options: ["噪聲影像", "引導影像（guidance image）", "黑場影像", "白場影像"],
    answer: 1,
    acceptAlso: [],
    explanation: "Guided filter 使用一張引導影像來決定濾波的邊緣保留特性。引導影像可以是原始輸入影像本身，也可以是另一張結構影像。",
    imageDesc: "",
    scenario: "",
    hint: "名稱中的 Guided 表示需要「引導」。",
    items: []
  },
  {
    id: "nr_030",
    category: "nr",
    type: "truefalse",
    difficulty: 1,
    question: "Dual gain sensor 可以在同一次曝光中使用兩種不同的類比增益。",
    options: ["正確", "錯誤"],
    answer: true,
    acceptAlso: [],
    explanation: "Dual gain（或 dual conversion gain）感測器可在同一曝光中對每個像素產生高增益和低增益兩種讀取，藉此擴展動態範圍並優化不同亮度區域的 SNR。",
    imageDesc: "",
    scenario: "",
    hint: "Dual 代表兩個不同的增益設定。",
    items: []
  },
  {
    id: "nr_031",
    category: "nr",
    type: "single",
    difficulty: 1,
    question: "ISO invariance 的感測器有什麼特性？",
    options: [
      "在任何 ISO 都不會產生雜訊",
      "後期提亮低 ISO 影像的效果與拍攝高 ISO 相似",
      "不需要降噪處理",
      "可以無限提高 ISO"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "ISO invariant 感測器的 read noise 在低 ISO 時已很低，因此在低 ISO 拍攝欠曝後再後期提亮，其雜訊表現與直接使用高 ISO 拍攝接近。",
    imageDesc: "",
    scenario: "",
    hint: "這與 read noise 在不同 ISO 下的表現有關。",
    items: []
  },
  {
    id: "nr_032",
    category: "nr",
    type: "fillblank",
    difficulty: 1,
    question: "Wiener filter 是一種在 ______ 域中工作的最佳線性濾波器。",
    options: [],
    answer: "頻率",
    acceptAlso: ["frequency", "頻域", "傅立葉"],
    explanation: "Wiener filter 在頻率域中操作，透過最小化訊號估計值與真實訊號之間的均方誤差（MSE）來實現最佳降噪。",
    imageDesc: "",
    scenario: "",
    hint: "Wiener filter 的數學推導涉及功率譜密度。",
    items: []
  },
  {
    id: "nr_033",
    category: "nr",
    type: "single",
    difficulty: 1,
    question: "在影像降噪中，所謂的 texture preservation 是指什麼？",
    options: ["保留影像的色彩", "保留影像中的紋理細節", "保留影像的亮度", "保留影像的解析度"],
    answer: 1,
    acceptAlso: [],
    explanation: "Texture preservation 是指降噪過程中盡量保留影像中的紋理細節（如毛髮、草地、布料紋理），避免被誤當作雜訊而去除。",
    imageDesc: "",
    scenario: "",
    hint: "紋理和雜訊在空間頻率上有重疊。",
    items: []
  },
  {
    id: "nr_034",
    category: "nr",
    type: "truefalse",
    difficulty: 1,
    question: "DCT denoising 是在離散餘弦變換域中進行的降噪方法。",
    options: ["正確", "錯誤"],
    answer: true,
    acceptAlso: [],
    explanation: "DCT（Discrete Cosine Transform）denoising 將影像塊轉換到 DCT 域，對係數進行閾值處理後再反變換回空間域，原理類似 wavelet denoising。",
    imageDesc: "",
    scenario: "",
    hint: "DCT 常用於 JPEG 壓縮中。",
    items: []
  },
  {
    id: "nr_035",
    category: "nr",
    type: "single",
    difficulty: 1,
    question: "Morphological filtering（形態學濾波）中，opening 操作可以去除什麼？",
    options: ["大面積暗區", "小亮點雜訊", "邊緣模糊", "色彩偏移"],
    answer: 1,
    acceptAlso: [],
    explanation: "Opening（先侵蝕後膨脹）可以去除小的亮點（如 salt noise），同時大致保持物體的形狀和大小。",
    imageDesc: "",
    scenario: "",
    hint: "Opening = erosion + dilation。",
    items: []
  },
  {
    id: "nr_036",
    category: "nr",
    type: "single",
    difficulty: 1,
    question: "在 Poisson-Gaussian noise model 中，Poisson 部分建模的是哪種雜訊？",
    options: ["Read noise", "Shot noise", "Quantization noise", "Fixed pattern noise"],
    answer: 1,
    acceptAlso: [],
    explanation: "Poisson 分佈建模光子計數的統計波動（shot noise），而 Gaussian 部分建模讀取電路的雜訊（read noise）。",
    imageDesc: "",
    scenario: "",
    hint: "光子到達的隨機性服從什麼分佈？",
    items: []
  },
  {
    id: "nr_037",
    category: "nr",
    type: "ordering",
    difficulty: 1,
    question: "請將典型 ISP pipeline 中的降噪步驟按正確順序排列：",
    options: ["Raw domain NR", "Demosaic", "YUV domain NR", "JPEG 壓縮輸出"],
    answer: 0,
    acceptAlso: [],
    explanation: "典型 ISP 先在 raw domain 做初步降噪，接著 demosaic，轉換到 YUV 後再做第二輪降噪，最後壓縮輸出。",
    imageDesc: "",
    scenario: "",
    hint: "Raw domain NR 在 demosaic 之前進行。",
    items: ["Raw domain NR", "Demosaic", "YUV domain NR", "JPEG 壓縮輸出"]
  },
  {
    id: "nr_038",
    category: "nr",
    type: "truefalse",
    difficulty: 1,
    question: "Random noise（隨機雜訊）可以透過多幀平均有效降低。",
    options: ["正確", "錯誤"],
    answer: true,
    acceptAlso: [],
    explanation: "隨機雜訊的統計特性是均值為零，多幀平均時隨機雜訊會相互抵消趨近於零，而訊號則被保留。",
    imageDesc: "",
    scenario: "",
    hint: "平均可以消除零均值的隨機成分。",
    items: []
  },
  {
    id: "nr_039",
    category: "nr",
    type: "single",
    difficulty: 1,
    question: "下列哪種方法屬於 frequency domain NR？",
    options: ["Bilateral filter", "Median filter", "Wavelet denoising", "Guided filter"],
    answer: 2,
    acceptAlso: [],
    explanation: "Wavelet denoising 在小波變換域（頻率域的一種）中進行，其餘三者都是空間域方法。",
    imageDesc: "",
    scenario: "",
    hint: "哪一個需要做頻率變換？",
    items: []
  },
  {
    id: "nr_040",
    category: "nr",
    type: "fillblank",
    difficulty: 1,
    question: "NLM（Non-Local Means）降噪的核心思想是利用影像中 ______ 相似的 patch 進行加權平均。",
    options: [],
    answer: "非局部",
    acceptAlso: ["non-local", "遠距離", "全域"],
    explanation: "NLM 不像傳統濾波器只考慮局部鄰域，而是在整張影像中搜尋與目標 patch 相似的所有 patch，進行加權平均。",
    imageDesc: "",
    scenario: "",
    hint: "Non-Local 意味著不限於局部鄰域。",
    items: []
  },
  {
    id: "nr_041",
    category: "nr",
    type: "scenario",
    difficulty: 1,
    question: "一位攝影師在夜間使用 ISO 12800 拍攝，發現照片中有大量彩色斑點，尤其在暗部區域。這主要是什麼類型的雜訊？",
    options: ["Luma noise", "Chroma noise", "Fixed pattern noise", "Quantization noise"],
    answer: 1,
    acceptAlso: [],
    explanation: "高 ISO 暗部的彩色斑點是典型的 chroma noise。高增益放大了色彩通道中的雜訊，在暗部（SNR 低）特別明顯。",
    imageDesc: "",
    scenario: "夜間高 ISO 攝影，暗部出現彩色斑點。",
    hint: "彩色斑點對應的是色度還是亮度雜訊？",
    items: []
  },
  {
    id: "nr_042",
    category: "nr",
    type: "single",
    difficulty: 1,
    question: "Gain（增益）與雜訊的關係是？",
    options: ["增益增加，雜訊減少", "增益增加，訊號和雜訊都被放大", "增益只放大訊號不放大雜訊", "增益與雜訊無關"],
    answer: 1,
    acceptAlso: [],
    explanation: "類比增益（gain）同時放大訊號和雜訊。雖然 SNR 在增益前後不變（理想情況），但絕對雜訊量增加使其更可見。",
    imageDesc: "",
    scenario: "",
    hint: "增益是不分青紅皂白地放大。",
    items: []
  },
  {
    id: "nr_043",
    category: "nr",
    type: "truefalse",
    difficulty: 1,
    question: "Noise calibration（雜訊校準）的目的是建立感測器在不同條件下的雜訊特性模型。",
    options: ["正確", "錯誤"],
    answer: true,
    acceptAlso: [],
    explanation: "Noise calibration 透過拍攝標準目標（如均勻灰卡）在不同 ISO、溫度、曝光條件下建立雜訊模型參數，供 NR 演算法使用。",
    imageDesc: "",
    scenario: "",
    hint: "校準是為了讓 NR 更精確地知道雜訊特性。",
    items: []
  },
  {
    id: "nr_044",
    category: "nr",
    type: "single",
    difficulty: 1,
    question: "Heteroscedastic noise 的特點是什麼？",
    options: [
      "雜訊變異量在整張影像中是均勻的",
      "雜訊變異量隨訊號強度變化",
      "雜訊只存在於影像邊緣",
      "雜訊只存在於色度通道"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "Heteroscedastic（異方差）noise 的變異量不是常數，而是隨訊號強度改變。典型例子是 shot noise，其變異量與訊號強度成正比。",
    imageDesc: "",
    scenario: "",
    hint: "Hetero = 不同，scedastic = 方差。",
    items: []
  },
  {
    id: "nr_045",
    category: "nr",
    type: "single",
    difficulty: 1,
    question: "Over-smoothing（過度平滑）在影像中最明顯的表現是什麼？",
    options: ["影像變得過暗", "皮膚呈現蠟像般不自然的效果", "影像出現摩爾紋", "色彩變得過飽和"],
    answer: 1,
    acceptAlso: [],
    explanation: "過度平滑會抹除自然的皮膚紋理和毛孔，使人像呈現不自然的蠟像效果，這是 NR 強度過高的典型表現。",
    imageDesc: "",
    scenario: "",
    hint: "想想手機美顏過度的效果。",
    items: []
  },
  {
    id: "nr_046",
    category: "nr",
    type: "fillblank",
    difficulty: 1,
    question: "3D 降噪中的三個維度分別是：影像的水平方向、垂直方向和 ______ 方向。",
    options: [],
    answer: "時間",
    acceptAlso: ["temporal", "時域"],
    explanation: "3D NR（或 spatio-temporal NR）結合了空間的二維資訊（水平和垂直）以及時間維度（相鄰幀），以更有效地降噪。",
    imageDesc: "",
    scenario: "",
    hint: "視訊是由連續的幀組成的。",
    items: []
  },
  {
    id: "nr_047",
    category: "nr",
    type: "truefalse",
    difficulty: 1,
    question: "Blind denoising 需要事先知道雜訊的精確統計參數。",
    options: ["正確", "錯誤"],
    answer: false,
    acceptAlso: [],
    explanation: "Blind denoising（盲降噪）的特點正是不需要事先知道雜訊參數，而是從含噪影像本身估計雜訊特性或直接學習降噪映射。",
    imageDesc: "",
    scenario: "",
    hint: "Blind 意味著「不知道」。",
    items: []
  },
  {
    id: "nr_048",
    category: "nr",
    type: "single",
    difficulty: 1,
    question: "NR 中 edge preservation（邊緣保留）的重要性在於？",
    options: ["加速計算", "防止邊緣被模糊而損失影像結構", "增加影像壓縮率", "減少記憶體使用"],
    answer: 1,
    acceptAlso: [],
    explanation: "邊緣是影像中最重要的結構資訊之一，若 NR 將邊緣模糊，會嚴重降低影像的感知品質和銳度。",
    imageDesc: "",
    scenario: "",
    hint: "邊緣定義了物體的輪廓。",
    items: []
  },
  {
    id: "nr_049",
    category: "nr",
    type: "single",
    difficulty: 1,
    question: "Signal-dependent noise 的特性是什麼？",
    options: [
      "雜訊強度與訊號強度無關",
      "雜訊強度隨訊號強度變化",
      "雜訊只出現在特定區域",
      "雜訊呈週期性分佈"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "Signal-dependent noise（如 shot noise）的變異量取決於訊號強度。亮部的 shot noise 絕對值較大，但相對於訊號的比例較小（SNR 較高）。",
    imageDesc: "",
    scenario: "",
    hint: "Shot noise 是最典型的 signal-dependent noise。",
    items: []
  },
  {
    id: "nr_050",
    category: "nr",
    type: "scenario",
    difficulty: 1,
    question: "工程師發現感測器在暗場拍攝（完全遮光）時，某些像素始終偏亮。這是什麼問題？",
    options: ["Shot noise", "Read noise", "Hot pixel（熱像素）導致的 dark current noise", "Quantization noise"],
    answer: 2,
    acceptAlso: [],
    explanation: "Hot pixel 是 dark current 異常高的像素，即使在無光照條件下也會產生明顯的訊號。這是 dark current noise 的極端表現。",
    imageDesc: "",
    scenario: "暗場拍攝時某些像素固定偏亮。",
    hint: "暗場拍攝時不應有訊號，偏亮的像素有異常的暗電流。",
    items: []
  },

  // ===== DIFFICULTY 2 (nr_051 ~ nr_100) =====
  {
    id: "nr_051",
    category: "nr",
    type: "single",
    difficulty: 2,
    question: "Bilateral filter 的計算複雜度相較於 Gaussian filter 較高，主要原因是什麼？",
    options: [
      "需要更大的 kernel",
      "需要計算空間域和值域兩個權重",
      "需要做傅立葉變換",
      "需要多次迭代"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "Bilateral filter 除了計算空間距離的高斯權重外，還要計算像素值差異的高斯權重，且由於值域核的存在，無法利用可分離性加速。",
    imageDesc: "",
    scenario: "",
    hint: "Bilateral filter 有兩個高斯核。",
    items: []
  },
  {
    id: "nr_052",
    category: "nr",
    type: "multiple",
    difficulty: 2,
    question: "下列哪些是 BM3D 演算法的主要步驟？（複選）",
    options: [
      "Block matching 尋找相似 patch",
      "3D 變換域的協同濾波",
      "Wiener 濾波精煉",
      "光流估計"
    ],
    answer: [0, 1, 2],
    acceptAlso: [],
    explanation: "BM3D 包含兩個階段：(1) block matching + 3D hard thresholding、(2) block matching + Wiener filtering 精煉。光流估計不是 BM3D 的組成部分。",
    imageDesc: "",
    scenario: "",
    hint: "BM3D 有兩個濾波階段。",
    items: []
  },
  {
    id: "nr_053",
    category: "nr",
    type: "single",
    difficulty: 2,
    question: "Non-Local Means (NLM) 相比於 Gaussian filter 的主要優勢是什麼？",
    options: [
      "計算速度更快",
      "利用影像的自相似性進行更好的細節保留",
      "不需要設定參數",
      "只處理邊緣區域"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "NLM 利用影像中重複出現的相似 patch（自相似性）來進行加權平均，相比局部 Gaussian filter 能更好地保留紋理和細節。",
    imageDesc: "",
    scenario: "",
    hint: "NLM 的核心是搜尋全域的相似 patch。",
    items: []
  },
  {
    id: "nr_054",
    category: "nr",
    type: "single",
    difficulty: 2,
    question: "Wiener filter 需要知道什麼先驗資訊才能達到最佳降噪效果？",
    options: [
      "影像的解析度",
      "雜訊的功率譜密度和原始訊號的功率譜密度",
      "感測器的溫度",
      "影像的色彩空間"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "Wiener filter 的最佳化需要雜訊和原始訊號的功率譜密度（PSD），以計算最小均方誤差意義下的最佳濾波器。",
    imageDesc: "",
    scenario: "",
    hint: "Wiener filter 是基於統計最佳化的方法。",
    items: []
  },
  {
    id: "nr_055",
    category: "nr",
    type: "truefalse",
    difficulty: 2,
    question: "Motion-compensated temporal NR 需要進行運動估計來對齊相鄰幀。",
    options: ["正確", "錯誤"],
    answer: true,
    acceptAlso: [],
    explanation: "為了在時域上進行有效的降噪而不產生 ghosting，motion-compensated TNR 先透過運動估計（如光流法）對齊相鄰幀，再進行時域融合。",
    imageDesc: "",
    scenario: "",
    hint: "Motion-compensated 這個詞已經暗示了答案。",
    items: []
  },
  {
    id: "nr_056",
    category: "nr",
    type: "single",
    difficulty: 2,
    question: "Recursive temporal filter 的主要特點是什麼？",
    options: [
      "每次處理一整組幀",
      "使用前一幀的濾波結果作為當前幀的參考",
      "只對靜止區域進行濾波",
      "需要未來幀的資訊"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "Recursive temporal filter 使用 IIR（Infinite Impulse Response）結構，將前一幀的濾波輸出以一定比例混合到當前幀中，形成遞迴處理。",
    imageDesc: "",
    scenario: "",
    hint: "Recursive 意味著結果會回饋到下一次計算中。",
    items: []
  },
  {
    id: "nr_057",
    category: "nr",
    type: "multiple",
    difficulty: 2,
    question: "下列哪些是 NR 可能產生的偽影？（複選）",
    options: [
      "Over-smoothing（過度平滑）",
      "Ghosting（鬼影）",
      "Detail loss（細節丟失）",
      "Barrel distortion（桶形畸變）"
    ],
    answer: [0, 1, 2],
    acceptAlso: [],
    explanation: "NR 可能導致過度平滑、時域降噪的 ghosting、以及細節丟失。Barrel distortion 是鏡頭光學畸變，與 NR 無關。",
    imageDesc: "",
    scenario: "",
    hint: "想想 NR 的副作用，不要混入光學問題。",
    items: []
  },
  {
    id: "nr_058",
    category: "nr",
    type: "single",
    difficulty: 2,
    question: "VBM3D 與 BM3D 的主要區別是什麼？",
    options: [
      "VBM3D 使用更大的 block size",
      "VBM3D 加入了時間維度用於視訊降噪",
      "VBM3D 不需要 block matching",
      "VBM3D 只用於彩色影像"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "VBM3D（Video BM3D）將 BM3D 擴展到視訊領域，在空間和時間維度上同時尋找相似 patch，利用時域冗餘進一步提升降噪效果。",
    imageDesc: "",
    scenario: "",
    hint: "V 代表 Video。",
    items: []
  },
  {
    id: "nr_059",
    category: "nr",
    type: "fillblank",
    difficulty: 2,
    question: "FFDNet 的一個關鍵設計是將 ______ map 作為網路的額外輸入，使其能適應不同雜訊水準。",
    options: [],
    answer: "noise level",
    acceptAlso: ["noise", "雜訊水準", "雜訊等級", "噪聲水平"],
    explanation: "FFDNet 接受一張可調的 noise level map 作為輸入，使得單一模型可以處理不同雜訊水準的影像，增加了靈活性。",
    imageDesc: "",
    scenario: "",
    hint: "FFDNet 如何知道當前的雜訊有多大？",
    items: []
  },
  {
    id: "nr_060",
    category: "nr",
    type: "single",
    difficulty: 2,
    question: "CBDNet（Convolutional Blind Denoising Network）的「Blind」體現在什麼方面？",
    options: [
      "不需要訓練資料",
      "能自動估計雜訊水準並進行降噪",
      "不需要 GPU 進行推理",
      "只能處理灰階影像"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "CBDNet 包含一個雜訊估計子網路和一個降噪子網路，能從含噪影像中自動估計 noise level map，不需要事先知道雜訊參數。",
    imageDesc: "",
    scenario: "",
    hint: "Blind = 不需要已知雜訊參數。",
    items: []
  },
  {
    id: "nr_061",
    category: "nr",
    type: "ordering",
    difficulty: 2,
    question: "請按照 BM3D 第一階段的正確處理順序排列：",
    options: [
      "Block matching 找相似 patch",
      "組成 3D 陣列",
      "3D 變換",
      "Hard thresholding 並反變換"
    ],
    answer: 0,
    acceptAlso: [],
    explanation: "BM3D 第一階段：(1) 對參考 patch 做 block matching 找到相似 patch，(2) 堆疊成 3D 陣列，(3) 做 3D 變換，(4) 進行 hard thresholding 後反變換。",
    imageDesc: "",
    scenario: "",
    hint: "先找相似塊，再做協同濾波。",
    items: ["Block matching 找相似 patch", "組成 3D 陣列", "3D 變換", "Hard thresholding 並反變換"]
  },
  {
    id: "nr_062",
    category: "nr",
    type: "single",
    difficulty: 2,
    question: "Noise Level Function (NLF) 通常將雜訊方差表示為什麼的函數？",
    options: ["像素位置", "訊號強度（亮度）", "色彩通道", "影像大小"],
    answer: 1,
    acceptAlso: [],
    explanation: "NLF 將雜訊的變異量（variance）表示為訊號強度的函數，反映了 signal-dependent noise 的特性。",
    imageDesc: "",
    scenario: "",
    hint: "不同亮度下雜訊程度不同。",
    items: []
  },
  {
    id: "nr_063",
    category: "nr",
    type: "scenario",
    difficulty: 2,
    question: "一個視訊監控系統在靜態場景下 temporal NR 效果很好，但當有行人經過時出現了模糊的殘影。工程師應如何改善？",
    options: [
      "增加 temporal NR 的強度",
      "加入 motion detection 並在運動區域降低 temporal NR 的混合比例",
      "完全關閉 temporal NR",
      "改用更高的幀率"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "在運動區域應降低 temporal NR 的融合權重（甚至回退為純空間域 NR），靜止區域則維持較強的 temporal NR，這就是 motion-adaptive TNR 的概念。",
    imageDesc: "",
    scenario: "視訊監控中 temporal NR 在運動區域產生 ghosting。",
    hint: "需要根據運動區域動態調整 temporal NR 的行為。",
    items: []
  },
  {
    id: "nr_064",
    category: "nr",
    type: "multiple",
    difficulty: 2,
    question: "下列哪些屬於空間域（spatial domain）降噪方法？（複選）",
    options: [
      "Gaussian filter",
      "Bilateral filter",
      "Wavelet denoising",
      "Non-Local Means"
    ],
    answer: [0, 1, 3],
    acceptAlso: [],
    explanation: "Gaussian filter、Bilateral filter 和 NLM 都在空間域中操作。Wavelet denoising 需要先做小波變換到頻率域。",
    imageDesc: "",
    scenario: "",
    hint: "哪些方法不需要頻率域變換？",
    items: []
  },
  {
    id: "nr_065",
    category: "nr",
    type: "single",
    difficulty: 2,
    question: "DnCNN 使用 residual learning 策略的好處是什麼？",
    options: [
      "減少訓練資料量",
      "網路只需學習雜訊成分而非整張清晰影像，簡化了學習任務",
      "加快推理速度",
      "不需要 batch normalization"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "DnCNN 學習的是含噪影像與清晰影像之間的殘差（即雜訊），比直接學習清晰影像映射更容易，加上 batch normalization 提升了訓練穩定性。",
    imageDesc: "",
    scenario: "",
    hint: "學習雜訊比學習整張影像更簡單。",
    items: []
  },
  {
    id: "nr_066",
    category: "nr",
    type: "truefalse",
    difficulty: 2,
    question: "在 Poisson-Gaussian model 中，亮部區域的雜訊以 Poisson noise（shot noise）為主導。",
    options: ["正確", "錯誤"],
    answer: true,
    acceptAlso: [],
    explanation: "在亮部區域訊號強度大，Poisson noise（shot noise）的變異量隨訊號增加而增大，成為主要雜訊源。在暗部則 Gaussian noise（read noise）佔主導。",
    imageDesc: "",
    scenario: "",
    hint: "Shot noise 的方差與訊號強度成正比。",
    items: []
  },
  {
    id: "nr_067",
    category: "nr",
    type: "single",
    difficulty: 2,
    question: "Guided filter 相比 bilateral filter 的一個主要優勢是？",
    options: [
      "降噪效果更好",
      "具有 O(N) 的計算複雜度，與 kernel 大小無關",
      "不需要設定參數",
      "可以處理視訊"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "Guided filter 可以用均值濾波器在 O(N) 時間內完成計算，且與 kernel 半徑無關，而 bilateral filter 的暴力實現是 O(Nr²)。",
    imageDesc: "",
    scenario: "",
    hint: "Guided filter 的計算效率是其重要優勢。",
    items: []
  },
  {
    id: "nr_068",
    category: "nr",
    type: "image",
    difficulty: 2,
    question: "觀察下圖的雜訊特性描述：影像暗部有明顯的隨機彩色斑點，亮部則相對乾淨。這最可能反映了什麼雜訊特性？",
    options: [
      "雜訊在整張影像均勻分佈",
      "Signal-dependent noise，暗部 SNR 低所以雜訊更明顯",
      "Fixed pattern noise 只出現在暗部",
      "感測器光學缺陷"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "暗部 SNR 較低，雜訊相對於訊號更明顯。加上色彩通道的增益放大，chroma noise 在暗部特別突出。這是 signal-dependent noise 的典型表現。",
    imageDesc: "一張高 ISO 夜景照片，暗部可見明顯的紅、綠、藍色隨機斑點，亮部（如路燈）相對乾淨。",
    scenario: "",
    hint: "暗部和亮部的雜訊表現為什麼不同？",
    items: []
  },
  {
    id: "nr_069",
    category: "nr",
    type: "single",
    difficulty: 2,
    question: "Wavelet denoising 中，soft thresholding 與 hard thresholding 的主要區別是？",
    options: [
      "Soft thresholding 不改變大係數，hard thresholding 會",
      "Soft thresholding 將小係數歸零並縮減大係數，hard thresholding 只將小係數歸零",
      "兩者完全相同",
      "Hard thresholding 需要更多計算"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "Hard thresholding 將絕對值小於閾值的係數設為零，保留其餘不變。Soft thresholding 除了歸零外，還將保留的係數向零收縮（減去閾值），產生更平滑的結果。",
    imageDesc: "",
    scenario: "",
    hint: "Soft 會額外做什麼處理？",
    items: []
  },
  {
    id: "nr_070",
    category: "nr",
    type: "fillblank",
    difficulty: 2,
    question: "BM3D 的第二階段使用 ______ filtering 來精煉第一階段的結果。",
    options: [],
    answer: "Wiener",
    acceptAlso: ["wiener"],
    explanation: "BM3D 第二階段使用第一階段的輸出作為先驗估計，以 Wiener filtering 取代 hard thresholding 進行更精確的協同濾波。",
    imageDesc: "",
    scenario: "",
    hint: "這是一種基於 MSE 最小化的經典濾波方法。",
    items: []
  },
  {
    id: "nr_071",
    category: "nr",
    type: "scenario",
    difficulty: 2,
    question: "ISP 工程師發現在低光源場景下，Chroma NR 後影像中膚色區域出現明顯的色彩偏移（color shift）。可能的原因和解法是？",
    options: [
      "Chroma NR 強度不夠，應增加",
      "Chroma NR 在大面積平坦區域過度平滑導致色彩偏移，需加入邊緣感知機制",
      "應完全關閉 Chroma NR",
      "這是 Luma NR 的問題"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "過強的 Chroma NR 可能在色彩邊界處將不同物體的色彩混合，或在大範圍平均時引入偏差。加入邊緣感知可避免跨邊界的色彩混合。",
    imageDesc: "",
    scenario: "低光源下 Chroma NR 後膚色出現色彩偏移。",
    hint: "色彩偏移可能是跨邊界平均造成的。",
    items: []
  },
  {
    id: "nr_072",
    category: "nr",
    type: "single",
    difficulty: 2,
    question: "Temporal bilateral filter 與普通 bilateral filter 的區別在於？",
    options: [
      "使用更大的空間 kernel",
      "在時間維度上也考慮像素值的相似性來融合相鄰幀",
      "只在色度通道上工作",
      "計算複雜度更低"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "Temporal bilateral filter 在空間 bilateral filter 的基礎上增加了時間維度，透過比較相鄰幀對應位置的像素值相似性來決定時域融合權重。",
    imageDesc: "",
    scenario: "",
    hint: "Temporal 指的是時間維度。",
    items: []
  },
  {
    id: "nr_073",
    category: "nr",
    type: "multiple",
    difficulty: 2,
    question: "下列哪些是深度學習降噪相比傳統方法的優勢？（複選）",
    options: [
      "能學習複雜的非線性映射",
      "不需要手動設計濾波器",
      "一定比傳統方法更快",
      "可從大量資料中學習影像先驗"
    ],
    answer: [0, 1, 3],
    acceptAlso: [],
    explanation: "深度學習方法能學習複雜的非線性映射、自動從資料中提取特徵、學習影像先驗。但推理速度取決於模型大小，不一定比傳統方法快。",
    imageDesc: "",
    scenario: "",
    hint: "不是所有方面深度學習都佔優勢。",
    items: []
  },
  {
    id: "nr_074",
    category: "nr",
    type: "single",
    difficulty: 2,
    question: "Multi-pass NR（多次降噪）在 ISP 中的典型做法是？",
    options: [
      "用同一個演算法重複降噪多次",
      "在 raw 域做一次 NR，在 YUV 域再做一次 NR",
      "對每個色彩通道分別降噪",
      "先升頻再降噪"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "Multi-pass NR 的典型做法是在 ISP pipeline 的不同階段分別降噪：raw 域的雜訊模型較單純適合精確降噪，YUV 域可針對亮度和色度分別調整。",
    imageDesc: "",
    scenario: "",
    hint: "ISP pipeline 中不同位置的資料格式不同。",
    items: []
  },
  {
    id: "nr_075",
    category: "nr",
    type: "truefalse",
    difficulty: 2,
    question: "BM4D 是 BM3D 的擴展版本，用於三維體資料（如 MRI）的降噪。",
    options: ["正確", "錯誤"],
    answer: true,
    acceptAlso: [],
    explanation: "BM4D 將 BM3D 的概念擴展到三維體數據（3D volumetric data），在 3D 空間中做 block matching 後在 4D 變換域中進行協同濾波，常用於醫學影像。",
    imageDesc: "",
    scenario: "",
    hint: "BM3D 處理 2D 影像，BM4D 處理 3D 體積資料。",
    items: []
  },
  {
    id: "nr_076",
    category: "nr",
    type: "single",
    difficulty: 2,
    question: "Noise variance estimation（雜訊方差估計）中，常用的 MAD（Median Absolute Deviation）方法是基於什麼原理？",
    options: [
      "計算影像的直方圖",
      "在小波域高頻子帶中估計雜訊的散佈程度",
      "比較相鄰像素的差異",
      "使用機器學習分類器"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "MAD 方法假設小波域的最高頻子帶主要由雜訊貢獻，透過計算該子帶係數的中位絕對偏差來穩健地估計雜訊標準差：σ = MAD / 0.6745。",
    imageDesc: "",
    scenario: "",
    hint: "小波高頻子帶的訊號成分較少。",
    items: []
  },
  {
    id: "nr_077",
    category: "nr",
    type: "single",
    difficulty: 2,
    question: "3D bilateral filter 用於視訊降噪時，其三個維度分別使用什麼核函數？",
    options: [
      "空間高斯、時間高斯、頻率高斯",
      "空間高斯、時間高斯、值域高斯",
      "三個維度都使用均勻核",
      "空間高斯、時間均勻、值域高斯"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "3D bilateral filter 使用空間距離的高斯核、時間距離的高斯核、以及像素值差異的高斯核（值域核），三者相乘作為最終權重。",
    imageDesc: "",
    scenario: "",
    hint: "Bilateral 的核心特點是有值域核。",
    items: []
  },
  {
    id: "nr_078",
    category: "nr",
    type: "scenario",
    difficulty: 2,
    question: "一位手機 ISP 工程師需要在有限的硬體資源下實現 edge-preserving 降噪。BM3D 計算量過大，Gaussian filter 會模糊邊緣。最適合的選擇是？",
    options: [
      "DnCNN 深度學習方法",
      "Guided filter",
      "Non-Local Means",
      "Wavelet denoising"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "Guided filter 具有 O(N) 的計算複雜度（與 kernel 大小無關），能保留邊緣，且易於硬體實現，是手機 ISP 中非常實用的選擇。",
    imageDesc: "",
    scenario: "手機 ISP 需要低計算量的 edge-preserving NR。",
    hint: "哪個方法的計算複雜度最低且能保邊？",
    items: []
  },
  {
    id: "nr_079",
    category: "nr",
    type: "fillblank",
    difficulty: 2,
    question: "DnCNN 的網路結構主要由多層 Conv + ______ + ReLU 組成。",
    options: [],
    answer: "Batch Normalization",
    acceptAlso: ["BN", "batch normalization", "BatchNorm", "batch norm"],
    explanation: "DnCNN 的每一層由 Convolution、Batch Normalization 和 ReLU 激活函數組成（首層無 BN，末層無 BN 和 ReLU）。BN 有助於加速訓練和提升殘差學習的效果。",
    imageDesc: "",
    scenario: "",
    hint: "這是一種常用於加速訓練和穩定性的技術。",
    items: []
  },
  {
    id: "nr_080",
    category: "nr",
    type: "single",
    difficulty: 2,
    question: "NR tuning 中所謂的 strength vs detail trade-off 是指什麼？",
    options: [
      "降噪速度與影像大小的取捨",
      "降噪強度越高雜訊越少但細節損失越多",
      "空間域與頻率域的取捨",
      "色度與亮度的取捨"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "這是 NR 中最基本的取捨：加大降噪強度可以更有效地去除雜訊，但同時會損失更多的影像細節和紋理。NR tuning 的目標是找到最佳平衡點。",
    imageDesc: "",
    scenario: "",
    hint: "雜訊和細節在頻率域有重疊。",
    items: []
  },
  {
    id: "nr_081",
    category: "nr",
    type: "truefalse",
    difficulty: 2,
    question: "在 YUV 域做 NR 時，通常對 Y 通道（亮度）施加的降噪強度比 U/V 通道（色度）更強。",
    options: ["正確", "錯誤"],
    answer: false,
    acceptAlso: [],
    explanation: "相反，由於人眼對色度的空間解析度較低，通常對 U/V（色度）通道施加更強的降噪，而對 Y（亮度）通道則較為保守以保留細節。",
    imageDesc: "",
    scenario: "",
    hint: "人眼對哪個通道的細節更敏感？",
    items: []
  },
  {
    id: "nr_082",
    category: "nr",
    type: "single",
    difficulty: 2,
    question: "Collaborative filtering 在 BM3D 中的含義是什麼？",
    options: [
      "多人協作標註訓練資料",
      "將相似 patch 組合在一起進行聯合濾波以互相增強降噪效果",
      "使用多個不同的濾波器",
      "在多個解析度上同時濾波"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "BM3D 的 collaborative filtering 是指將匹配到的相似 patch 堆疊成 3D 陣列後進行聯合濾波，利用 patch 間的冗餘性來更好地區分訊號和雜訊。",
    imageDesc: "",
    scenario: "",
    hint: "多個相似 patch 一起協同工作。",
    items: []
  },
  {
    id: "nr_083",
    category: "nr",
    type: "multiple",
    difficulty: 2,
    question: "下列哪些因素會影響 shot noise 的大小？（複選）",
    options: [
      "入射光子數量",
      "感測器溫度",
      "曝光時間",
      "讀取電路的電子雜訊"
    ],
    answer: [0, 2],
    acceptAlso: [],
    explanation: "Shot noise 的方差等於光子數量（N），而光子數量與曝光時間和光強度成正比。溫度主要影響 thermal/dark current noise，讀取電路影響 read noise。",
    imageDesc: "",
    scenario: "",
    hint: "Shot noise 純粹來自光子的量子特性。",
    items: []
  },
  {
    id: "nr_084",
    category: "nr",
    type: "single",
    difficulty: 2,
    question: "Spatio-temporal filtering（時空濾波）相比純空間域濾波的主要優勢是？",
    options: [
      "不需要設定參數",
      "可以利用時間維度的冗餘資訊進一步提升 SNR",
      "計算量更小",
      "只需要單幀影像"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "時空濾波同時利用空間和時間維度的冗餘資訊，在靜止或慢速運動場景中可以大幅提升 SNR 而不過度模糊空間細節。",
    imageDesc: "",
    scenario: "",
    hint: "額外的維度 = 額外的資訊。",
    items: []
  },
  {
    id: "nr_085",
    category: "nr",
    type: "fillblank",
    difficulty: 2,
    question: "PSNR 的計算公式為 PSNR = 10 × log₁₀(MAX² / ______)，其中 MAX 是像素最大值。",
    options: [],
    answer: "MSE",
    acceptAlso: ["mse", "均方誤差", "Mean Squared Error"],
    explanation: "PSNR = 10 × log₁₀(MAX² / MSE)，其中 MSE 是含噪影像與原始影像之間的均方誤差。PSNR 以 dB 為單位。",
    imageDesc: "",
    scenario: "",
    hint: "分母是衡量誤差的指標。",
    items: []
  },
  {
    id: "nr_086",
    category: "nr",
    type: "ordering",
    difficulty: 2,
    question: "請按照感測器雜訊源產生的先後順序排列（從光子到數位輸出）：",
    options: [
      "Shot noise（光子統計波動）",
      "Dark current noise（暗電流累積）",
      "Read noise（讀取電路雜訊）",
      "Quantization noise（ADC 量化誤差）"
    ],
    answer: 0,
    acceptAlso: [],
    explanation: "光子先到達產生 shot noise，曝光期間累積 dark current noise，讀取時加入 read noise，最後 ADC 轉換產生 quantization noise。",
    imageDesc: "",
    scenario: "",
    hint: "按照訊號在感測器中的處理流程思考。",
    items: ["Shot noise（光子統計波動）", "Dark current noise（暗電流累積）", "Read noise（讀取電路雜訊）", "Quantization noise（ADC 量化誤差）"]
  },
  {
    id: "nr_087",
    category: "nr",
    type: "single",
    difficulty: 2,
    question: "在深度學習降噪的訓練策略中，使用合成雜訊（synthetic noise）訓練的模型在真實雜訊上效果常不理想，原因是？",
    options: [
      "合成雜訊的資料量不夠",
      "真實雜訊比簡單的 AWGN 模型更複雜，存在 domain gap",
      "深度學習模型容量不足",
      "訓練時 learning rate 太高"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "真實感測器雜訊包含 signal-dependent noise、空間相關性、色彩通道間相關性等，簡單的 AWGN 合成雜訊無法完全模擬，導致 domain gap。",
    imageDesc: "",
    scenario: "",
    hint: "真實雜訊比理想模型複雜得多。",
    items: []
  },
  {
    id: "nr_088",
    category: "nr",
    type: "truefalse",
    difficulty: 2,
    question: "Blind noise estimation 可以從單張含噪影像中估計雜訊水準，無需額外的參考影像。",
    options: ["正確", "錯誤"],
    answer: true,
    acceptAlso: [],
    explanation: "Blind noise estimation 方法（如 MAD、PCA-based、或深度學習方法）能從單張含噪影像中估計雜訊的統計參數，不需要乾淨的參考影像。",
    imageDesc: "",
    scenario: "",
    hint: "Blind 意味著不需要額外資訊。",
    items: []
  },
  {
    id: "nr_089",
    category: "nr",
    type: "single",
    difficulty: 2,
    question: "在 NR 後影像出現「color shift（色彩偏移）」，最可能的原因是？",
    options: [
      "NR 演算法只處理了亮度通道",
      "NR 對不同色彩通道的處理不一致",
      "NR 強度太低",
      "影像的白平衡設定錯誤"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "如果 NR 對 R、G、B 或 Cb、Cr 通道的降噪強度、kernel 大小等不一致，或在色彩邊界處處理不當，可能導致色彩偏移。",
    imageDesc: "",
    scenario: "",
    hint: "不同通道的 NR 行為需要保持一致性。",
    items: []
  },
  {
    id: "nr_090",
    category: "nr",
    type: "single",
    difficulty: 2,
    question: "Non-Local Means 的搜尋視窗大小（search window）對效能的影響是？",
    options: [
      "搜尋視窗越大，計算量線性增加",
      "搜尋視窗越大，計算量二次方增加",
      "搜尋視窗大小不影響計算量",
      "搜尋視窗越大，計算量指數增加"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "NLM 需要在搜尋視窗內比較每個 patch，計算量與搜尋視窗面積成正比（O(S²)，S 為搜尋視窗邊長），因此是二次方增加。",
    imageDesc: "",
    scenario: "",
    hint: "搜尋視窗是二維的。",
    items: []
  },
  {
    id: "nr_091",
    category: "nr",
    type: "scenario",
    difficulty: 2,
    question: "工程師在調校 ISP 的 NR 模組時，發現 ISO 100 下影像紋理正常，但 ISO 3200 下同一 NR 參數導致嚴重的過度平滑。應該怎麼做？",
    options: [
      "固定使用 ISO 100 拍攝",
      "建立隨 ISO 變化的 NR 參數表，高 ISO 時平衡降噪強度和細節保留",
      "完全關閉 NR",
      "改用更大的感測器"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "NR 參數應根據 ISO（增益）動態調整。通常建立一張 NR 參數 vs ISO 的查找表（LUT），在不同雜訊水準下使用不同的降噪策略。",
    imageDesc: "",
    scenario: "同一 NR 參數在不同 ISO 下效果差異巨大。",
    hint: "不同 ISO 下雜訊水準不同，NR 參數也應不同。",
    items: []
  },
  {
    id: "nr_092",
    category: "nr",
    type: "single",
    difficulty: 2,
    question: "Patch matching 在 BM3D 中的相似度衡量通常使用什麼指標？",
    options: [
      "結構相似度（SSIM）",
      "L2 距離（歐幾里得距離）",
      "互資訊（mutual information）",
      "相關係數"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "BM3D 的 block matching 通常計算 patch 之間的 L2 距離（歐幾里得距離），距離小於閾值的 patch 被認為是相似的。",
    imageDesc: "",
    scenario: "",
    hint: "最直接的距離度量方法。",
    items: []
  },
  {
    id: "nr_093",
    category: "nr",
    type: "truefalse",
    difficulty: 2,
    question: "Chroma noise 在感測器的綠色通道（G channel）通常比紅色（R）和藍色（B）通道更嚴重。",
    options: ["正確", "錯誤"],
    answer: false,
    acceptAlso: [],
    explanation: "在 Bayer 排列中，G 通道有雙倍的像素數量（RGGB），且綠色通常接收更多光子（人造光源和日光的光譜特性），因此 G 通道的 SNR 通常較高。R 和 B 通道雜訊更明顯。",
    imageDesc: "",
    scenario: "",
    hint: "Bayer pattern 中 G 像素數量是 R 和 B 的兩倍。",
    items: []
  },
  {
    id: "nr_094",
    category: "nr",
    type: "single",
    difficulty: 2,
    question: "深度學習降噪中，使用 paired training data（含噪-乾淨配對資料）的挑戰是什麼？",
    options: [
      "配對資料太容易取得",
      "真實場景中很難取得完美對齊的含噪-乾淨影像對",
      "深度學習不需要訓練資料",
      "配對資料會導致過擬合"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "真實環境中難以取得同一場景的含噪和對應的完美乾淨影像。即使用長曝光作為 ground truth，也可能存在對齊誤差和動態場景變化。",
    imageDesc: "",
    scenario: "",
    hint: "現實中如何取得「真正乾淨」的參考影像？",
    items: []
  },
  {
    id: "nr_095",
    category: "nr",
    type: "fillblank",
    difficulty: 2,
    question: "在 raw domain NR 中，Bayer 格式資料的 R、Gr、Gb、B 四個通道通常需要 ______ 處理。",
    options: [],
    answer: "分別",
    acceptAlso: ["分開", "independently", "各自", "獨立"],
    explanation: "由於 Bayer 資料中 R、Gr、Gb、B 四個通道的雜訊特性（增益、暗電流等）可能不同，通常需要分別進行降噪處理。",
    imageDesc: "",
    scenario: "",
    hint: "四個通道的感光特性不完全相同。",
    items: []
  },
  {
    id: "nr_096",
    category: "nr",
    type: "image",
    difficulty: 2,
    question: "觀察下圖描述：左圖為降噪前的影像，右圖為降噪後。右圖中的頭髮絲和布料紋理明顯消失，皮膚呈現塑膠般的光滑感。這說明了什麼問題？",
    options: [
      "降噪演算法不夠先進",
      "NR 強度過高導致紋理丟失（over-smoothing）",
      "影像解析度不足",
      "對焦不準"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "頭髮絲和布料紋理的消失，以及皮膚的塑膠感，是 NR 過度平滑的典型表現。應降低 NR 強度或使用 texture-aware 的降噪方法。",
    imageDesc: "左右對比圖：左圖有可見雜訊但紋理清晰（頭髮絲、布料紋理可見），右圖雜訊消除但紋理也消失，皮膚呈現不自然的光滑塑膠感。",
    scenario: "",
    hint: "紋理和雜訊都是高頻資訊。",
    items: []
  },
  {
    id: "nr_097",
    category: "nr",
    type: "single",
    difficulty: 2,
    question: "Gain-noise relationship 中，analogue gain 加倍通常對 read noise（以 DN 為單位）的影響是？",
    options: [
      "Read noise 不變",
      "Read noise 也加倍",
      "Read noise 變為四倍",
      "Read noise 減半"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "類比增益（analogue gain）會等比例放大所有訊號（包括 read noise），因此增益加倍時 read noise 的 DN 值也加倍。但以電子數（e⁻）為單位的 read noise 不變。",
    imageDesc: "",
    scenario: "",
    hint: "類比增益是在 ADC 之前放大所有訊號。",
    items: []
  },
  {
    id: "nr_098",
    category: "nr",
    type: "multiple",
    difficulty: 2,
    question: "下列哪些方法可以用於 blind noise estimation？（複選）",
    options: [
      "小波域 MAD 估計",
      "PCA-based 方法",
      "直接使用固定的雜訊參數",
      "深度學習噪聲估計網路"
    ],
    answer: [0, 1, 3],
    acceptAlso: [],
    explanation: "MAD、PCA-based 方法和深度學習噪聲估計網路都能從含噪影像中估計雜訊。使用固定參數不算「估計」，也不適應不同場景。",
    imageDesc: "",
    scenario: "",
    hint: "Blind estimation 需要自適應地估計雜訊。",
    items: []
  },
  {
    id: "nr_099",
    category: "nr",
    type: "single",
    difficulty: 2,
    question: "在 NR tuning 中，根據影像內容自適應調整降噪強度的做法稱為什麼？",
    options: [
      "Global NR",
      "Content-adaptive NR / Spatially-varying NR",
      "Fixed NR",
      "Temporal NR"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "Content-adaptive NR 根據局部影像特徵（如邊緣、紋理、平坦區域）動態調整降噪強度：平坦區域可用較強的 NR，紋理和邊緣區域則降低強度以保留細節。",
    imageDesc: "",
    scenario: "",
    hint: "不同區域使用不同的 NR 強度。",
    items: []
  },
  {
    id: "nr_100",
    category: "nr",
    type: "ordering",
    difficulty: 2,
    question: "請按照 NR 演算法的歷史發展順序排列（從早到晚）：",
    options: [
      "Gaussian filter",
      "Bilateral filter",
      "BM3D",
      "DnCNN"
    ],
    answer: 0,
    acceptAlso: [],
    explanation: "Gaussian filter 最早被使用，Bilateral filter 約 1998 年提出，BM3D 約 2007 年提出，DnCNN 約 2017 年提出，反映了從簡單到複雜的演進。",
    imageDesc: "",
    scenario: "",
    hint: "從傳統濾波到深度學習的演進。",
    items: ["Gaussian filter", "Bilateral filter", "BM3D", "DnCNN"]
  },

  // ===== DIFFICULTY 3 (nr_101 ~ nr_150) =====
  {
    id: "nr_101",
    category: "nr",
    type: "single",
    difficulty: 3,
    question: "在 Poisson-Gaussian noise model y = αp + n 中，若 α 為系統增益，p ~ Poisson(x/α)，n ~ N(0, σ²_read)，則觀測值 y 的總方差為？",
    options: [
      "αx + σ²_read",
      "α²x + σ²_read",
      "αx + σ_read",
      "x + σ²_read"
    ],
    answer: 0,
    acceptAlso: [],
    explanation: "Poisson 部分的方差為 α² × (x/α) = αx，加上 read noise 的方差 σ²_read，總方差為 αx + σ²_read。這就是典型的 affine noise model。",
    imageDesc: "",
    scenario: "",
    hint: "Var(αp) = α² × Var(p) = α² × (x/α) = αx。",
    items: []
  },
  {
    id: "nr_102",
    category: "nr",
    type: "multiple",
    difficulty: 3,
    question: "BM3D 的 collaborative filtering 中使用的 3D 變換通常由哪些組合而成？（複選）",
    options: [
      "2D DCT 或 2D Bior 小波（沿空間維度）",
      "1D Haar 或 1D DCT（沿 patch 堆疊維度）",
      "3D Fourier transform",
      "Gabor transform"
    ],
    answer: [0, 1],
    acceptAlso: [],
    explanation: "BM3D 的 3D 變換是可分離的：先對每個 patch 做 2D 變換（DCT 或 Bior 小波），再沿 patch 堆疊的第三維度做 1D 變換（Haar 或 DCT）。",
    imageDesc: "",
    scenario: "",
    hint: "3D 變換由 2D 空間變換 + 1D 組間變換組合而成。",
    items: []
  },
  {
    id: "nr_103",
    category: "nr",
    type: "single",
    difficulty: 3,
    question: "Variance Stabilizing Transform (VST)，如 Anscombe transform，在降噪中的作用是什麼？",
    options: [
      "將影像從空間域轉到頻率域",
      "將 Poisson 或 Poisson-Gaussian noise 轉換為近似 AWGN，便於使用假設 AWGN 的降噪方法",
      "增強影像對比度",
      "校正鏡頭畸變"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "Anscombe transform f(x) = 2√(x + 3/8) 可將 Poisson 分佈的數據轉換為近似方差穩定的 Gaussian 分佈，使得基於 AWGN 假設的降噪方法（如 BM3D）可以直接使用。",
    imageDesc: "",
    scenario: "",
    hint: "讓 signal-dependent noise 變成 signal-independent。",
    items: []
  },
  {
    id: "nr_104",
    category: "nr",
    type: "scenario",
    difficulty: 3,
    question: "一位研究者用 DnCNN 在合成 AWGN 資料上訓練了降噪模型，在 AWGN 測試集上 PSNR 很高，但用在真實手機拍攝的含噪影像上效果很差。以下哪種策略最可能有效改善？",
    options: [
      "增加訓練的 epoch 數",
      "改用真實含噪影像配對資料訓練，或使用更接近真實的 noise model（如 Poisson-Gaussian + ISP pipeline 模擬）",
      "增大 DnCNN 的深度到 100 層",
      "使用更小的 learning rate"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "AWGN 與真實感測器雜訊存在 domain gap。需要用更寫實的 noise model（考慮 signal-dependent noise、ISP 的非線性處理、空間相關性等）或真實配對資料來訓練。",
    imageDesc: "",
    scenario: "DnCNN 在合成 AWGN 上表現好但在真實影像上效果差。",
    hint: "訓練資料和真實資料的分佈不一致是關鍵問題。",
    items: []
  },
  {
    id: "nr_105",
    category: "nr",
    type: "single",
    difficulty: 3,
    question: "Generalized Anscombe Transform (GAT) 用於處理 Poisson-Gaussian 混合雜訊，其公式近似為 f(y) = 2√(y/α + 3/8 + σ²/(α²))。相較於基本 Anscombe transform，GAT 額外考慮了什麼？",
    options: [
      "色彩通道間的相關性",
      "Gaussian noise 成分（read noise）",
      "空間相關性",
      "temporal noise"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "基本 Anscombe transform 只處理 Poisson noise，而 GAT 額外將 Gaussian noise（read noise）的方差 σ² 納入變換公式，使得 Poisson-Gaussian 混合雜訊也能被穩定化。",
    imageDesc: "",
    scenario: "",
    hint: "公式中的 σ² 項對應什麼雜訊？",
    items: []
  },
  {
    id: "nr_106",
    category: "nr",
    type: "fillblank",
    difficulty: 3,
    question: "NLM 的權重公式為 w(i,j) = exp(-||P(i) - P(j)||² / ______)，其中 P(i) 和 P(j) 是 patch。",
    options: [],
    answer: "h²",
    acceptAlso: ["h^2", "h平方"],
    explanation: "NLM 的濾波參數 h 控制衰減速度。h 越大，更多不相似的 patch 也會有較大的權重，降噪更強但可能更模糊。h 通常設定為與雜訊水準相關。",
    imageDesc: "",
    scenario: "",
    hint: "h 是 NLM 的濾波強度參數。",
    items: []
  },
  {
    id: "nr_107",
    category: "nr",
    type: "single",
    difficulty: 3,
    question: "在 deep learning NR 中，Noise2Noise 訓練策略的核心創新是什麼？",
    options: [
      "使用更深的網路架構",
      "只需要含噪影像對（不需要乾淨影像）進行訓練",
      "使用 GAN 生成乾淨影像",
      "在推理時不需要 GPU"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "Noise2Noise 證明了只需要同一場景的兩張不同噪聲實例作為訓練對（不需要乾淨的 ground truth），就能訓練出有效的降噪網路，因為網路會學到噪聲的期望值（即乾淨影像）。",
    imageDesc: "",
    scenario: "",
    hint: "訓練不需要 clean target。",
    items: []
  },
  {
    id: "nr_108",
    category: "nr",
    type: "multiple",
    difficulty: 3,
    question: "下列哪些是 CBDNet 的組成模組？（複選）",
    options: [
      "Noise estimation sub-network",
      "Non-blind denoising sub-network",
      "光流估計模組",
      "Asymmetric loss function 用於雜訊估計的訓練"
    ],
    answer: [0, 1, 3],
    acceptAlso: [],
    explanation: "CBDNet 由噪聲估計子網路和非盲降噪子網路組成，並使用非對稱損失函數（低估雜訊比高估雜訊的懲罰更大）來訓練噪聲估計模組。不包含光流模組。",
    imageDesc: "",
    scenario: "",
    hint: "CBDNet 有兩個子網路和一個特殊的損失函數。",
    items: []
  },
  {
    id: "nr_109",
    category: "nr",
    type: "single",
    difficulty: 3,
    question: "Guided filter 的核心假設是什麼？",
    options: [
      "雜訊服從均勻分佈",
      "在引導影像的局部視窗內，輸出是引導影像的線性變換",
      "影像的頻譜是平坦的",
      "所有像素的雜訊方差相同"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "Guided filter 假設在局部視窗 ωk 內：q_i = a_k × I_i + b_k，其中 I 是引導影像，q 是輸出。參數 a_k 和 b_k 透過最小化與輸入的均方誤差求得。",
    imageDesc: "",
    scenario: "",
    hint: "這是一種局部線性模型。",
    items: []
  },
  {
    id: "nr_110",
    category: "nr",
    type: "truefalse",
    difficulty: 3,
    question: "BM3D 在低雜訊影像上可能比簡單的 Gaussian filter 效果更差，因為 block matching 在低噪聲下可能找到錯誤的匹配。",
    options: ["正確", "錯誤"],
    answer: false,
    acceptAlso: [],
    explanation: "低噪聲下 block matching 更準確（因為噪聲干擾更小），BM3D 在各種雜訊水準下通常都優於 Gaussian filter。但在極低雜訊下 BM3D 的改善可能不如高雜訊時顯著。",
    imageDesc: "",
    scenario: "",
    hint: "噪聲越低，patch 匹配越準確。",
    items: []
  },
  {
    id: "nr_111",
    category: "nr",
    type: "single",
    difficulty: 3,
    question: "在 ISP 的 raw domain NR 中，為什麼需要考慮 Bayer pattern 的空間排列？",
    options: [
      "為了加速計算",
      "因為相鄰像素屬於不同色彩通道，直接做空間濾波會造成色彩串擾",
      "為了相容不同的感測器廠商",
      "為了節省記憶體"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "Bayer pattern 中相鄰像素屬於不同色彩通道（RGGB），如果直接做空間濾波會混合不同通道的值，造成色彩串擾和偽色。應分通道處理。",
    imageDesc: "",
    scenario: "",
    hint: "Bayer 的 RGGB 排列意味著相鄰像素色彩不同。",
    items: []
  },
  {
    id: "nr_112",
    category: "nr",
    type: "scenario",
    difficulty: 3,
    question: "一個 4K 60fps 的即時視訊處理系統需要加入 temporal NR，但 motion-compensated TNR 的光流估計計算量太大。有什麼替代方案？",
    options: [
      "放棄 temporal NR，只用空間域 NR",
      "使用簡單的 recursive temporal filter 配合 motion detection（而非精確光流），在靜止區域做時域融合",
      "降低解析度到 1080p",
      "使用純 BM3D"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "Recursive temporal filter 只需比較前一幀的像素值差異（作為簡易 motion detection），計算量遠低於光流估計。在靜止區域有效降噪，運動區域自動降低融合比例避免 ghosting。",
    imageDesc: "",
    scenario: "4K 60fps 系統需要低計算量的 temporal NR。",
    hint: "不需要精確的光流也能做基本的 temporal NR。",
    items: []
  },
  {
    id: "nr_113",
    category: "nr",
    type: "single",
    difficulty: 3,
    question: "FFDNet 相比 DnCNN 的主要設計改進是什麼？",
    options: [
      "使用更深的網路",
      "接受 noise level map 作為輸入以處理空間可變的雜訊",
      "使用 U-Net 架構",
      "在頻率域中處理"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "FFDNet 將可調的 noise level map 作為額外輸入通道，使得單一模型可以處理不同強度的雜訊，且能適應影像中空間變化的雜訊水準（如 signal-dependent noise）。",
    imageDesc: "",
    scenario: "",
    hint: "FFDNet 的 F 代表 Flexible。",
    items: []
  },
  {
    id: "nr_114",
    category: "nr",
    type: "fillblank",
    difficulty: 3,
    question: "在 Wiener filter 的頻率域公式 H(f) = S_xx(f) / (S_xx(f) + S_nn(f)) 中，S_xx(f) 代表原始訊號的功率譜密度，S_nn(f) 代表 ______ 的功率譜密度。",
    options: [],
    answer: "雜訊",
    acceptAlso: ["noise", "噪聲"],
    explanation: "Wiener filter 的最佳解取決於訊號和雜訊的功率譜比值。在 SNR 高的頻率上 H(f) ≈ 1（保留），在 SNR 低的頻率上 H(f) ≈ 0（抑制）。",
    imageDesc: "",
    scenario: "",
    hint: "H(f) 在雜訊大的頻率處趨近零。",
    items: []
  },
  {
    id: "nr_115",
    category: "nr",
    type: "multiple",
    difficulty: 3,
    question: "下列哪些是 real-world noise 相比於簡單 AWGN 更複雜的特性？（複選）",
    options: [
      "Signal-dependent（信號相關性）",
      "Spatially correlated（空間相關性）",
      "Channel-dependent（通道相關性）",
      "完全隨機且獨立同分佈"
    ],
    answer: [0, 1, 2],
    acceptAlso: [],
    explanation: "真實感測器雜訊是 signal-dependent（shot noise）、spatially correlated（ISP 處理後）、channel-dependent（不同色彩通道特性不同），而非簡單的 AWGN（獨立同分佈）。",
    imageDesc: "",
    scenario: "",
    hint: "AWGN 是最理想化的雜訊模型。",
    items: []
  },
  {
    id: "nr_116",
    category: "nr",
    type: "single",
    difficulty: 3,
    question: "在 temporal NR 中，IIR 型遞迴濾波器 output_t = α × input_t + (1-α) × output_(t-1) 的等效平均幀數約為？",
    options: [
      "1/α",
      "α",
      "1/(1-α)",
      "α/(1-α)"
    ],
    answer: 0,
    acceptAlso: [],
    explanation: "IIR 型遞迴濾波的等效平均幀數約為 1/α。例如 α=0.1 時，等效於平均約 10 幀。α 越小，時域平滑越強，但 ghosting 風險也越高。",
    imageDesc: "",
    scenario: "",
    hint: "α 是新幀的混合比例。",
    items: []
  },
  {
    id: "nr_117",
    category: "nr",
    type: "truefalse",
    difficulty: 3,
    question: "Noise2Void 方法的訓練完全不需要任何乾淨影像，只需要單張含噪影像即可訓練。",
    options: ["正確", "錯誤"],
    answer: true,
    acceptAlso: [],
    explanation: "Noise2Void 使用盲點策略（blind-spot），在預測目標像素時遮蔽該像素本身，迫使網路從周圍像素推斷乾淨值。理論上只需一張含噪影像即可訓練（但實務上多張效果更好）。",
    imageDesc: "",
    scenario: "",
    hint: "Noise2Void 是 self-supervised 的極端情況。",
    items: []
  },
  {
    id: "nr_118",
    category: "nr",
    type: "single",
    difficulty: 3,
    question: "在 NR 的 SSIM（Structural Similarity Index）評估中，相比 PSNR 其主要優勢是什麼？",
    options: [
      "計算速度更快",
      "更符合人類視覺感知，考慮了結構、亮度和對比度的相似性",
      "不需要參考影像",
      "值域更大"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "SSIM 結合了亮度、對比度和結構三個維度的比較，比單純基於像素均方誤差的 PSNR 更符合人眼對影像品質的主觀判斷。",
    imageDesc: "",
    scenario: "",
    hint: "SSIM 考慮的面向比 PSNR 更全面。",
    items: []
  },
  {
    id: "nr_119",
    category: "nr",
    type: "ordering",
    difficulty: 3,
    question: "請按照降噪方法的計算複雜度從低到高排列（假設影像大小 N，patch 大小 p，搜尋視窗 S）：",
    options: [
      "Gaussian filter O(N)",
      "Bilateral filter O(Nr²)",
      "NLM O(NpS²) 或近似加速版",
      "BM3D（含兩階段）"
    ],
    answer: 0,
    acceptAlso: [],
    explanation: "Gaussian filter 最快（可分離 O(N)），Bilateral filter 中等，NLM 需要大範圍搜尋，BM3D 包含兩階段各自的 block matching 和 3D 濾波最為複雜。",
    imageDesc: "",
    scenario: "",
    hint: "搜尋範圍越大、步驟越多，計算量越高。",
    items: ["Gaussian filter O(N)", "Bilateral filter O(Nr²)", "NLM O(NpS²) 或近似加速版", "BM3D（含兩階段）"]
  },
  {
    id: "nr_120",
    category: "nr",
    type: "scenario",
    difficulty: 3,
    question: "團隊開發了一個 raw domain NR 模組，使用 Poisson-Gaussian noise model。在校準時發現不同 ISO 下的 noise model 參數（α, σ²）差異很大。最佳的工程做法是？",
    options: [
      "使用所有 ISO 的平均參數",
      "建立 α 和 σ² 與 ISO（增益）的對應查找表（LUT），並在不同 ISO 間進行插值",
      "只校準 ISO 100 的參數",
      "忽略 Poisson 項只使用 Gaussian 模型"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "α 與類比增益成正比，σ² 與增益的平方成正比。建立 ISO-to-noise-parameter LUT 並做插值，可確保 NR 在所有 ISO 下都有準確的雜訊模型。",
    imageDesc: "",
    scenario: "不同 ISO 的 Poisson-Gaussian 參數差異大。",
    hint: "雜訊參數與增益有確定的數學關係。",
    items: []
  },
  {
    id: "nr_121",
    category: "nr",
    type: "single",
    difficulty: 3,
    question: "在 dual gain sensor 中，conversion gain 的切換通常發生在哪個位置？",
    options: [
      "ADC 之後",
      "像素層級的浮動擴散區（floating diffusion）",
      "ISP 後處理階段",
      "鏡頭內部"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "Dual conversion gain 在像素內部的 floating diffusion 節點實現，透過切換節點的電容大小來改變電荷-電壓轉換增益，從而在同一曝光中取得高低兩種增益的讀取。",
    imageDesc: "",
    scenario: "",
    hint: "Conversion gain 與像素的電荷-電壓轉換有關。",
    items: []
  },
  {
    id: "nr_122",
    category: "nr",
    type: "fillblank",
    difficulty: 3,
    question: "BM3D 中 block matching 的搜尋是在以參考 patch 為中心的局部 ______ 視窗內進行的。",
    options: [],
    answer: "搜尋",
    acceptAlso: ["search", "搜索"],
    explanation: "BM3D 不在全域搜尋，而是在參考 patch 周圍的局部搜尋視窗（如 39×39）內尋找相似 patch，以平衡效果和計算效率。",
    imageDesc: "",
    scenario: "",
    hint: "全域搜尋計算量太大，所以限制範圍。",
    items: []
  },
  {
    id: "nr_123",
    category: "nr",
    type: "single",
    difficulty: 3,
    question: "Unsharp masking 有時在 NR pipeline 中的角色是什麼？",
    options: [
      "取代 NR",
      "在 NR 後恢復部分因降噪損失的銳度",
      "在 NR 前先去除雜訊",
      "用於估計雜訊水準"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "NR 不可避免地會造成一些銳度損失，因此常在 NR 後接一個適度的 sharpening 步驟（如 unsharp masking）來恢復邊緣銳度，但需要注意不要同時放大殘留雜訊。",
    imageDesc: "",
    scenario: "",
    hint: "NR 和 sharpening 是互補的處理。",
    items: []
  },
  {
    id: "nr_124",
    category: "nr",
    type: "multiple",
    difficulty: 3,
    question: "下列哪些是 self-supervised denoising 方法？（複選）",
    options: [
      "Noise2Noise",
      "Noise2Void",
      "Noise2Self",
      "DnCNN（使用乾淨-含噪配對訓練）"
    ],
    answer: [1, 2],
    acceptAlso: [],
    explanation: "Noise2Void 和 Noise2Self 是 self-supervised 方法（只需含噪影像本身）。Noise2Noise 需要兩張不同噪聲的影像（weakly supervised）。DnCNN 需要含噪-乾淨配對（fully supervised）。",
    imageDesc: "",
    scenario: "",
    hint: "Self-supervised 意味著只需要含噪影像本身。",
    items: []
  },
  {
    id: "nr_125",
    category: "nr",
    type: "single",
    difficulty: 3,
    question: "在 ISP 中，raw domain NR 後的 demosaic 操作可能對雜訊產生什麼影響？",
    options: [
      "完全消除殘留雜訊",
      "將獨立的像素級雜訊轉變為空間相關的雜訊",
      "不影響雜訊",
      "將雜訊從高頻轉到低頻"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "Demosaic 通過插值從鄰近像素推算缺失的色彩通道，這個過程會引入像素間的空間相關性，使得原本獨立的雜訊變為空間相關的雜訊，也可能引入偽色。",
    imageDesc: "",
    scenario: "",
    hint: "插值會讓鄰近像素的值產生關聯。",
    items: []
  },
  {
    id: "nr_126",
    category: "nr",
    type: "truefalse",
    difficulty: 3,
    question: "在 Anscombe transform 後使用 BM3D 降噪，最後需要用 exact unbiased inverse Anscombe transform 才能得到最佳結果。",
    options: ["正確", "錯誤"],
    answer: true,
    acceptAlso: [],
    explanation: "簡單的代數逆變換會引入偏差。Exact unbiased inverse Anscombe transform 考慮了降噪後估計值的分佈，給出無偏的逆變換結果，對最終的 PSNR 有顯著改善。",
    imageDesc: "",
    scenario: "",
    hint: "直接的代數逆變換不是最佳的。",
    items: []
  },
  {
    id: "nr_127",
    category: "nr",
    type: "single",
    difficulty: 3,
    question: "為什麼 deep learning NR 方法在手機 ISP 中面臨挑戰？",
    options: [
      "深度學習效果不好",
      "模型計算量大、功耗高，且需要低延遲處理，難以在有限的手機 NPU/GPU 上即時運行",
      "手機影像不包含雜訊",
      "手機不支持深度學習推理"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "手機 ISP 要求即時處理（30-60fps）、低延遲、低功耗。深度學習模型通常計算量較大，需要模型壓縮、量化、輕量化設計才能部署到手機端。",
    imageDesc: "",
    scenario: "",
    hint: "手機的計算資源和功耗預算有限。",
    items: []
  },
  {
    id: "nr_128",
    category: "nr",
    type: "scenario",
    difficulty: 3,
    question: "在 temporal NR 系統中，recursive filter 的 α 值固定為 0.05（等效約 20 幀平均）。使用者反映在手持拍攝場景（非三腳架）下出現嚴重的 ghosting。工程師應如何改善？",
    options: [
      "將 α 固定改為 0.5",
      "根據 motion detection 結果動態調整 α：運動大的區域增大 α（降低時域融合），靜止區域保持低 α",
      "完全移除 temporal NR",
      "加入更多的空間域 NR 來補償"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "Motion-adaptive temporal NR 根據每個像素的運動程度動態調整 α：運動區域 α 趨近 1（基本不做時域融合），靜止區域 α 保持低值（充分利用時域降噪），這是解決 ghosting 的標準做法。",
    imageDesc: "",
    scenario: "手持拍攝場景下 recursive temporal filter 產生 ghosting。",
    hint: "需要區分運動區域和靜止區域。",
    items: []
  },
  {
    id: "nr_129",
    category: "nr",
    type: "single",
    difficulty: 3,
    question: "CBDNet 使用 asymmetric loss 訓練 noise estimation sub-network 的原因是什麼？",
    options: [
      "對稱損失訓練更慢",
      "低估雜訊水準會導致 NR 不足（殘留雜訊），比高估更有害",
      "高估雜訊水準會導致影像更暗",
      "為了減少訓練時間"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "低估雜訊時 NR 強度不足，殘留的雜訊非常明顯；高估雜訊時只是輕微的過度平滑。因此 asymmetric loss 對低估施加更大的懲罰。",
    imageDesc: "",
    scenario: "",
    hint: "殘留雜訊 vs 輕微過度平滑，哪個更嚴重？",
    items: []
  },
  {
    id: "nr_130",
    category: "nr",
    type: "multiple",
    difficulty: 3,
    question: "下列哪些技術可以幫助 deep learning NR 模型在手機上即時部署？（複選）",
    options: [
      "模型量化（Quantization）",
      "知識蒸餾（Knowledge Distillation）",
      "增加模型深度到 200 層",
      "使用 depthwise separable convolution"
    ],
    answer: [0, 1, 3],
    acceptAlso: [],
    explanation: "模型量化降低精度減少計算、知識蒸餾將大模型的知識轉移到小模型、depthwise separable convolution 大幅減少參數量。增加深度會增加而非減少計算量。",
    imageDesc: "",
    scenario: "",
    hint: "目標是減少計算量和模型大小。",
    items: []
  },
  {
    id: "nr_131",
    category: "nr",
    type: "single",
    difficulty: 3,
    question: "在 multi-frame HDR + NR 融合中，為什麼短曝光幀可以提供亮部的低噪聲資訊？",
    options: [
      "短曝光幀的 read noise 更低",
      "亮部在短曝光幀中未飽和，且光子充足使得 shot noise 相對較低（SNR 高）",
      "短曝光幀的解析度更高",
      "短曝光幀不含 shot noise"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "短曝光幀中亮部不會飽和，且亮部光子數量充足，shot noise 相對於訊號的比例小（SNR 高）。長曝光幀則提供暗部的低噪聲資訊（更多光子）。",
    imageDesc: "",
    scenario: "",
    hint: "亮部在短曝光時既未飽和又有足夠的光子。",
    items: []
  },
  {
    id: "nr_132",
    category: "nr",
    type: "fillblank",
    difficulty: 3,
    question: "Guided filter 中的正則化參數 ε（epsilon）控制邊緣保留的程度。ε 越大，濾波結果越接近 ______ filter。",
    options: [],
    answer: "均值",
    acceptAlso: ["mean", "box", "平均"],
    explanation: "當 ε 很大時，guided filter 的線性係數 a_k 趨近零，b_k 趨近局部均值，退化為均值濾波器（模糊邊緣）。ε 很小時則保留更多邊緣。",
    imageDesc: "",
    scenario: "",
    hint: "ε 控制「平滑」vs「保邊」的程度。",
    items: []
  },
  {
    id: "nr_133",
    category: "nr",
    type: "single",
    difficulty: 3,
    question: "在 noise calibration 中，通常使用 photon transfer curve (PTC) 來分析感測器雜訊。PTC 的 x 軸和 y 軸分別是什麼？",
    options: [
      "x: 溫度, y: 雜訊",
      "x: 平均訊號值（mean signal）, y: 訊號的方差或標準差（variance/std）",
      "x: ISO, y: PSNR",
      "x: 曝光時間, y: 動態範圍"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "PTC 繪製平均訊號值 vs 訊號方差（或標準差），可以分析出 shot noise（斜率 = 增益）、read noise（截距）和全井容量（滿阱前的拐點）。",
    imageDesc: "",
    scenario: "",
    hint: "PTC 是分析雜訊與訊號關係的標準工具。",
    items: []
  },
  {
    id: "nr_134",
    category: "nr",
    type: "truefalse",
    difficulty: 3,
    question: "Non-Local Means 的加速版本可以使用積分影像（integral image）或隨機子採樣來降低計算複雜度。",
    options: ["正確", "錯誤"],
    answer: true,
    acceptAlso: [],
    explanation: "NLM 的加速方法包括：使用積分影像（integral image）快速計算 patch 距離、只計算預選的候選 patch、使用 PCA 降維、block-wise 處理等。",
    imageDesc: "",
    scenario: "",
    hint: "原始 NLM 的計算量很大，有很多加速技巧。",
    items: []
  },
  {
    id: "nr_135",
    category: "nr",
    type: "single",
    difficulty: 3,
    question: "在 deep learning NR 中，perceptual loss 相比 L2 loss（MSE）的優勢是什麼？",
    options: [
      "計算更簡單",
      "能保留更多的高頻紋理細節，避免過度平滑",
      "收斂更快",
      "不需要預訓練模型"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "L2 loss 傾向於產生模糊的平均結果。Perceptual loss 在預訓練的 VGG 等網路的特徵空間中計算，能更好地保留紋理和結構，產生更銳利的結果。",
    imageDesc: "",
    scenario: "",
    hint: "L2 loss 的最優解是條件期望值，趨於模糊。",
    items: []
  },
  {
    id: "nr_136",
    category: "nr",
    type: "scenario",
    difficulty: 3,
    question: "一個安防攝影機系統在紅外夜視模式下的影像雜訊模式與日光模式明顯不同。工程師應如何設計 NR 系統？",
    options: [
      "使用同一套 NR 參數",
      "為日光模式和紅外夜視模式分別校準雜訊模型和 NR 參數，根據模式自動切換",
      "只在日光模式下啟用 NR",
      "只使用 spatial NR 不用 temporal NR"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "紅外模式下感測器的光譜響應、增益設定、雜訊特性都與日光模式不同，需要獨立校準。自動切換確保在每種模式下都使用最佳的 NR 設定。",
    imageDesc: "",
    scenario: "安防攝影機的日光/紅外兩種模式雜訊特性不同。",
    hint: "不同工作模式需要不同的雜訊校準。",
    items: []
  },
  {
    id: "nr_137",
    category: "nr",
    type: "single",
    difficulty: 3,
    question: "在 wavelet denoising 中，BayesShrink 閾值選擇方法的核心思想是什麼？",
    options: [
      "使用固定的通用閾值",
      "針對每個小波子帶估計其訊號和雜訊方差，計算貝葉斯最佳 soft threshold",
      "隨機選擇閾值",
      "使用梯度下降優化閾值"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "BayesShrink 在每個小波子帶中分別估計雜訊方差（用 MAD）和訊號方差（用子帶方差減去雜訊方差），計算子帶自適應的 soft threshold：T = σ²_n / σ_x。",
    imageDesc: "",
    scenario: "",
    hint: "子帶自適應的閾值選擇。",
    items: []
  },
  {
    id: "nr_138",
    category: "nr",
    type: "multiple",
    difficulty: 3,
    question: "下列哪些做法可以改善 temporal NR 的 ghosting 問題？（複選）",
    options: [
      "Motion-adaptive blending（根據運動強度調整融合權重）",
      "使用光流進行 motion compensation",
      "增加 temporal NR 的融合幀數",
      "在偵測到大運動時回退到純空間域 NR"
    ],
    answer: [0, 1, 3],
    acceptAlso: [],
    explanation: "Motion-adaptive blending、motion compensation 和大運動時回退到空間 NR 都可以減少 ghosting。增加融合幀數反而會加重 ghosting。",
    imageDesc: "",
    scenario: "",
    hint: "ghosting 的根本原因是運動區域的錯誤融合。",
    items: []
  },
  {
    id: "nr_139",
    category: "nr",
    type: "single",
    difficulty: 3,
    question: "在 ISP NR pipeline 中，為什麼有些系統會在 tone mapping 之前做一次 NR，tone mapping 之後再做一次？",
    options: [
      "為了增加處理時間",
      "Tone mapping 的非線性會改變雜訊的統計特性，所以需要在兩個域中分別處理",
      "為了相容不同的顯示器",
      "第二次 NR 是多餘的"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "Tone mapping 的非線性壓縮（如 gamma）會改變雜訊的分佈特性。在 tone mapping 前做的 NR 利用線性域的精確雜訊模型；之後的 NR 處理 tone mapping 引入或改變的雜訊特性。",
    imageDesc: "",
    scenario: "",
    hint: "非線性處理會改變雜訊的統計特性。",
    items: []
  },
  {
    id: "nr_140",
    category: "nr",
    type: "ordering",
    difficulty: 3,
    question: "請將以下 deep learning 降噪的訓練策略按照對標註資料的依賴程度從高到低排列：",
    options: [
      "Supervised（含噪-乾淨配對）",
      "Noise2Noise（含噪-含噪配對）",
      "Noise2Void（僅含噪影像）",
      "Noise2Self（僅含噪影像）"
    ],
    answer: 0,
    acceptAlso: [],
    explanation: "Supervised 需要完美的含噪-乾淨配對（依賴最高），Noise2Noise 需要兩張含噪配對，Noise2Void 和 Noise2Self 只需含噪影像本身（依賴最低）。",
    imageDesc: "",
    scenario: "",
    hint: "從需要最多額外資訊到最少。",
    items: ["Supervised（含噪-乾淨配對）", "Noise2Noise（含噪-含噪配對）", "Noise2Void（僅含噪影像）", "Noise2Self（僅含噪影像）"]
  },
  {
    id: "nr_141",
    category: "nr",
    type: "truefalse",
    difficulty: 3,
    question: "在 raw domain 進行 NR 時，由於尚未做 white balance，不同色彩通道的增益不同，因此各通道的雜訊水準也不同。",
    options: ["正確", "錯誤"],
    answer: true,
    acceptAlso: [],
    explanation: "White balance 會對不同色彩通道施加不同的增益倍數（如 R ×2.1, B ×1.6）。在 WB 前的 raw domain 中，各通道的增益相同，但 WB 後的增益差異會導致雜訊水準不同。不過即使在 raw 域，R/B 通道的量子效率本身也不同，雜訊特性也有差異。",
    imageDesc: "",
    scenario: "",
    hint: "不同通道對光的敏感度不同。",
    items: []
  },
  {
    id: "nr_142",
    category: "nr",
    type: "single",
    difficulty: 3,
    question: "在 NR 的研究中，近年來提出的 transformer-based 降噪方法（如 Restormer）相比 CNN 方法的主要優勢是？",
    options: [
      "參數量更少",
      "能透過 self-attention 捕獲更大範圍的上下文資訊（長距離依賴）",
      "訓練速度更快",
      "不需要 GPU"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "Transformer 的 self-attention 機制能捕獲全域（或大範圍）的上下文依賴，類似 NLM 的非局部概念，相比 CNN 的有限感受野能利用更多的結構冗餘。",
    imageDesc: "",
    scenario: "",
    hint: "Self-attention 的感受野比 convolution 更大。",
    items: []
  },
  {
    id: "nr_143",
    category: "nr",
    type: "fillblank",
    difficulty: 3,
    question: "在 noise calibration 中，dark frame 的拍攝方式是在感測器完全 ______ 的狀態下進行曝光。",
    options: [],
    answer: "遮光",
    acceptAlso: ["遮蔽", "無光", "黑暗", "covered", "capped"],
    explanation: "Dark frame 在感測器完全遮光的條件下拍攝，捕捉的訊號全部來自 dark current 和 read noise，用於校準 FPN 和暗電流雜訊。",
    imageDesc: "",
    scenario: "",
    hint: "Dark frame 不應包含任何光訊號。",
    items: []
  },
  {
    id: "nr_144",
    category: "nr",
    type: "single",
    difficulty: 3,
    question: "GAN-based（生成對抗網路）降噪方法可能產生的獨特問題是什麼？",
    options: [
      "訓練太快無法控制",
      "可能生成不存在於原始影像中的假紋理（hallucination）",
      "只能處理灰階影像",
      "無法去除高斯雜訊"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "GAN 的 generator 可能為了欺騙 discriminator 而生成看起來真實但實際不存在的紋理（hallucination），這在醫學影像等需要忠實還原的場景中尤其危險。",
    imageDesc: "",
    scenario: "",
    hint: "GAN 擅長生成「看起來真實」的內容。",
    items: []
  },
  {
    id: "nr_145",
    category: "nr",
    type: "scenario",
    difficulty: 3,
    question: "ISP 團隊在開發 multi-frame NR 功能時，發現在手持夜景模式下，對齊後的多幀融合結果在建築物邊緣出現了彩色偽影。最可能的原因和解法是？",
    options: [
      "曝光時間太短",
      "幀間對齊誤差導致不同幀的 Bayer pattern 未精確對齊，在融合時產生色彩串擾；需確保次像素級對齊精度",
      "感測器溫度過高",
      "White balance 設定錯誤"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "Multi-frame 融合在 raw domain 時，若對齊精度不足（尤其是非整數像素的偏移），不同幀的 Bayer pattern 會錯位，導致 R/G/B 通道混合產生彩色偽影。需要次像素級的精確對齊。",
    imageDesc: "",
    scenario: "多幀融合在建築物邊緣出現彩色偽影。",
    hint: "Bayer pattern 的對齊精度對融合品質至關重要。",
    items: []
  },
  {
    id: "nr_146",
    category: "nr",
    type: "multiple",
    difficulty: 3,
    question: "下列哪些因素會影響 BM3D 的降噪效果？（複選）",
    options: [
      "Block size（patch 大小）",
      "搜尋視窗大小",
      "Hard threshold 的值",
      "影像的 EXIF 資訊"
    ],
    answer: [0, 1, 2],
    acceptAlso: [],
    explanation: "Block size 影響 patch 匹配的穩定性、搜尋視窗影響可用的相似 patch 數量、threshold 決定去除雜訊的強度。EXIF 資訊不直接影響 BM3D 的運算。",
    imageDesc: "",
    scenario: "",
    hint: "BM3D 有多個可調參數。",
    items: []
  },
  {
    id: "nr_147",
    category: "nr",
    type: "single",
    difficulty: 3,
    question: "在 ISP NR 調校中，noise profile 通常需要在哪些維度上進行校準？",
    options: [
      "只需校準一個固定的 ISO",
      "ISO（增益）、色溫（光源類型）、溫度",
      "只需要考慮影像解析度",
      "只需要校準暗場"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "完整的 noise profile 校準需考慮：ISO/增益（直接影響雜訊量）、色溫/光源（影響不同色彩通道的 shot noise 比例）、感測器溫度（影響 dark current 和 thermal noise）。",
    imageDesc: "",
    scenario: "",
    hint: "雜訊會隨多個環境變數變化。",
    items: []
  },
  {
    id: "nr_148",
    category: "nr",
    type: "truefalse",
    difficulty: 3,
    question: "Demosaicing 前進行 NR 可以減少 demosaic 產生的偽色（false color），因為雜訊是引發偽色的原因之一。",
    options: ["正確", "錯誤"],
    answer: true,
    acceptAlso: [],
    explanation: "雜訊會干擾 demosaic 演算法的插值判斷（尤其是邊緣方向判斷），導致更多偽色。在 demosaic 前先做適度的 NR 可以提供更乾淨的輸入，減少偽色的產生。",
    imageDesc: "",
    scenario: "",
    hint: "Demosaic 的品質取決於輸入資料的品質。",
    items: []
  },
  {
    id: "nr_149",
    category: "nr",
    type: "ordering",
    difficulty: 3,
    question: "在 ISP pipeline 中，以下處理步驟的合理順序是（從前到後）：",
    options: [
      "Black level subtraction",
      "Raw domain NR",
      "White balance + Demosaic",
      "YUV conversion + Chroma/Luma NR"
    ],
    answer: 0,
    acceptAlso: [],
    explanation: "先做黑位校正（減去暗電流基底），然後在乾淨的線性 raw 資料上做 NR，接著 WB 和 demosaic，最後轉到 YUV 空間做分通道 NR。",
    imageDesc: "",
    scenario: "",
    hint: "黑位校正是最基礎的前處理。",
    items: ["Black level subtraction", "Raw domain NR", "White balance + Demosaic", "YUV conversion + Chroma/Luma NR"]
  },
  {
    id: "nr_150",
    category: "nr",
    type: "scenario",
    difficulty: 3,
    question: "一個天文攝影系統需要對長時間曝光（數分鐘）的影像進行降噪。影像中同時存在嚴重的 dark current noise（熱像素和暗電流梯度）、shot noise 和 read noise。最佳的處理策略是？",
    options: [
      "直接對原始影像做 BM3D",
      "先用同溫同曝光的 dark frame 做 dark subtraction 去除 FPN 和 dark current 後，再用 Poisson-Gaussian noise model 進行降噪",
      "只做 temporal NR",
      "用 median filter 處理一切"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "天文攝影的標準流程：(1) dark frame subtraction 去除可校準的 FPN 和 dark current noise，(2) 對殘留的 shot noise + read noise 使用基於 Poisson-Gaussian 模型的降噪（如 GAT + BM3D）。Dark subtraction 是處理長曝光暗電流的最有效方法。",
    imageDesc: "",
    scenario: "天文攝影長時間曝光，含嚴重 dark current noise、shot noise 和 read noise。",
    hint: "先去除可校準的雜訊，再處理隨機雜訊。",
    items: []
  }
];

