const Q_PREPROCESS = [
  // ========== DIFFICULTY 1 (questions 001–017) ==========
  {
    id: "preprocess_001",
    category: "preprocess",
    type: "single",
    difficulty: 1,
    question: "在 ISP pipeline 中，bad pixel correction 主要處理哪種感測器缺陷？",
    options: [
      "A. 感測器上輸出異常值的像素",
      "B. 鏡頭表面的灰塵",
      "C. 色彩空間轉換誤差",
      "D. 壓縮造成的 artifact"
    ],
    answer: 0,
    acceptAlso: [],
    explanation: "Bad pixel correction 專門處理感測器上因製造缺陷或老化導致輸出異常值（過亮、過暗或固定值）的像素，通常透過鄰近像素內插來修復。",
    imageDesc: "",
    scenario: "",
    hint: "想想感測器本身的物理缺陷。",
    items: []
  },
  {
    id: "preprocess_002",
    category: "preprocess",
    type: "truefalse",
    difficulty: 1,
    question: "Dead pixel 是指永遠輸出零值（全黑）的感測器像素。",
    options: ["True", "False"],
    answer: true,
    acceptAlso: [],
    explanation: "Dead pixel 因電路斷路或光電二極體失效，無法產生光電流，因此永遠輸出零值或接近零值，在影像上呈現為固定的黑點。",
    imageDesc: "",
    scenario: "",
    hint: "Dead 意味著完全無反應。",
    items: []
  },
  {
    id: "preprocess_003",
    category: "preprocess",
    type: "single",
    difficulty: 1,
    question: "Hot pixel 與 stuck pixel 的主要差異為何？",
    options: [
      "A. Hot pixel 隨溫度升高而惡化，stuck pixel 固定在某一亮度值",
      "B. Hot pixel 只出現在綠色通道，stuck pixel 出現在所有通道",
      "C. Hot pixel 是軟體 bug，stuck pixel 是硬體問題",
      "D. 兩者完全相同，只是不同廠商的叫法"
    ],
    answer: 0,
    acceptAlso: [],
    explanation: "Hot pixel 主要因暗電流過高引起，其異常程度隨感測器溫度和曝光時間增加而惡化。Stuck pixel 則固定卡在某一數值（通常是滿值或某固定值），與溫度無顯著相關。",
    imageDesc: "",
    scenario: "",
    hint: "思考溫度對暗電流的影響。",
    items: []
  },
  {
    id: "preprocess_004",
    category: "preprocess",
    type: "single",
    difficulty: 1,
    question: "Lens shading correction (LSC) 主要補償哪種光學現象？",
    options: [
      "A. 影像邊緣亮度衰減（vignetting）",
      "B. 色像差（chromatic aberration）",
      "C. 動態模糊（motion blur）",
      "D. 摩爾紋（moiré pattern）"
    ],
    answer: 0,
    acceptAlso: [],
    explanation: "LSC 補償由鏡頭光學特性造成的影像中心到邊緣亮度漸減現象，這包含 cos⁴ law 自然衰減以及鏡頭機械遮擋等因素。",
    imageDesc: "",
    scenario: "",
    hint: "鏡頭邊緣進光量較少。",
    items: []
  },
  {
    id: "preprocess_005",
    category: "preprocess",
    type: "truefalse",
    difficulty: 1,
    question: "Optical black (OB) clamping 使用感測器上被遮光的像素區域來估算黑電平。",
    options: ["True", "False"],
    answer: true,
    acceptAlso: [],
    explanation: "感測器邊緣設有被金屬遮光的 OB 像素區域，這些像素不受光照影響，其輸出值代表當前的黑電平（含暗電流與固定偏移），可用來進行 black level clamping。",
    imageDesc: "",
    scenario: "",
    hint: "遮光區域不會接收到光線。",
    items: []
  },
  {
    id: "preprocess_006",
    category: "preprocess",
    type: "fillblank",
    difficulty: 1,
    question: "在 dark frame subtraction 中，需要拍攝一張 ________ 的影像來取得暗電流分布圖。",
    options: [],
    answer: "完全遮光",
    acceptAlso: ["遮光", "全暗", "蓋上鏡頭蓋", "無光"],
    explanation: "Dark frame 是在完全無光照條件下（如蓋上鏡頭蓋），以相同曝光時間、ISO 和溫度拍攝的影像，記錄了感測器各像素的暗電流雜訊分布。",
    imageDesc: "",
    scenario: "",
    hint: "要量測暗電流，就不能有光線進入。",
    items: []
  },
  {
    id: "preprocess_007",
    category: "preprocess",
    type: "single",
    difficulty: 1,
    question: "Fixed pattern noise (FPN) 的特性是什麼？",
    options: [
      "A. 在相同條件下每幀都出現在固定位置",
      "B. 每幀隨機變化的高頻雜訊",
      "C. 僅在高 ISO 時才出現",
      "D. 與感測器溫度完全無關"
    ],
    answer: 0,
    acceptAlso: [],
    explanation: "FPN 是一種空間上固定的雜訊模式，在相同操作條件（溫度、增益等）下，每次曝光都出現在相同位置。它主要來自像素間的製造差異。",
    imageDesc: "",
    scenario: "",
    hint: "Fixed pattern 暗示了可重複性。",
    items: []
  },
  {
    id: "preprocess_008",
    category: "preprocess",
    type: "truefalse",
    difficulty: 1,
    question: "Flat field correction 可以同時補償鏡頭 vignetting 和感測器像素靈敏度不均勻。",
    options: ["True", "False"],
    answer: true,
    acceptAlso: [],
    explanation: "Flat field correction 透過拍攝均勻光源影像取得校正參考，該參考同時包含了鏡頭 vignetting 和感測器像素間靈敏度差異，因此一次校正可同時補償兩種因素。",
    imageDesc: "",
    scenario: "",
    hint: "均勻光源照射時，殘餘的不均勻來自哪些因素？",
    items: []
  },
  {
    id: "preprocess_009",
    category: "preprocess",
    type: "single",
    difficulty: 1,
    question: "Pedestal removal 在 ISP 前處理中的作用是？",
    options: [
      "A. 去除感測器 ADC 人為加上的固定偏移量",
      "B. 去除鏡頭色差",
      "C. 移除 Bayer pattern 中的偽色",
      "D. 消除運動造成的拖影"
    ],
    answer: 0,
    acceptAlso: [],
    explanation: "許多感測器的 ADC 會加入一個固定的 pedestal（偏移量），避免類比訊號在零值附近被截斷。ISP 必須在處理前減去此 pedestal，確保黑電平正確。",
    imageDesc: "",
    scenario: "",
    hint: "ADC 通常會加一個 offset 避免負值截斷。",
    items: []
  },
  {
    id: "preprocess_010",
    category: "preprocess",
    type: "single",
    difficulty: 1,
    question: "Column noise（行雜訊）通常是由感測器的哪個部分造成？",
    options: [
      "A. 行讀取放大器（column readout amplifier）的增益差異",
      "B. 鏡頭畸變",
      "C. Bayer filter 的色彩洩漏",
      "D. ISP 的 gamma 校正誤差"
    ],
    answer: 0,
    acceptAlso: [],
    explanation: "CMOS 感測器每一行（column）都有獨立的讀取放大器，這些放大器間的增益與偏移差異導致整行像素出現一致性偏移，形成垂直條紋狀的 column noise。",
    imageDesc: "",
    scenario: "",
    hint: "CMOS 感測器的 column-parallel 讀出架構。",
    items: []
  },
  {
    id: "preprocess_011",
    category: "preprocess",
    type: "ordering",
    difficulty: 1,
    question: "請將以下 ISP 前處理步驟依照典型執行順序排列（從先到後）：",
    options: [],
    answer: 0,
    acceptAlso: [],
    explanation: "典型順序為：先做 OB clamping 確定黑電平 → 再做 bad pixel correction 修復壞點 → 接著進行 dark frame subtraction 去除暗電流 → 最後做 LSC 補償亮度衰減。",
    imageDesc: "",
    scenario: "",
    hint: "黑電平校正通常最先執行。",
    items: [
      "OB clamping",
      "Bad pixel correction",
      "Dark frame subtraction",
      "Lens shading correction"
    ]
  },
  {
    id: "preprocess_012",
    category: "preprocess",
    type: "single",
    difficulty: 1,
    question: "Linearization 在 ISP 前處理中的目的是什麼？",
    options: [
      "A. 將感測器的非線性響應校正為線性響應",
      "B. 將影像轉為灰階",
      "C. 線性內插遺失的 Bayer 像素",
      "D. 將 RAW 資料壓縮為 JPEG"
    ],
    answer: 0,
    acceptAlso: [],
    explanation: "感測器的光電轉換可能因電路限制呈現非線性特性，linearization 透過 lookup table 或多項式將輸出校正回與入射光量成正比的線性關係，確保後續處理的正確性。",
    imageDesc: "",
    scenario: "",
    hint: "ISP 後續演算法大多假設輸入是線性的。",
    items: []
  },
  {
    id: "preprocess_013",
    category: "preprocess",
    type: "truefalse",
    difficulty: 1,
    question: "Green imbalance correction 是為了修正 Bayer pattern 中 Gr 和 Gb 兩個綠色通道之間的響應差異。",
    options: ["True", "False"],
    answer: true,
    acceptAlso: [],
    explanation: "Bayer pattern 中有 Gr（與紅色同行的綠色）和 Gb（與藍色同行的綠色）兩組綠色像素，由於在感測器上的物理位置不同，它們可能受到不同程度的 crosstalk 和製程差異影響，需要做 green imbalance correction。",
    imageDesc: "",
    scenario: "",
    hint: "Bayer pattern 有兩組綠色像素。",
    items: []
  },
  {
    id: "preprocess_014",
    category: "preprocess",
    type: "single",
    difficulty: 1,
    question: "Sensor crosstalk 是指什麼現象？",
    options: [
      "A. 相鄰像素之間的光電信號互相干擾",
      "B. 不同感測器晶片之間的電磁干擾",
      "C. ISP 處理過程中的資料溢出",
      "D. 鏡頭組之間的反射光"
    ],
    answer: 0,
    acceptAlso: [],
    explanation: "Sensor crosstalk 發生在相鄰像素之間，光線或電子信號從一個像素洩漏到鄰近像素，導致訊號串擾。這在像素尺寸縮小的現代感測器中尤為嚴重。",
    imageDesc: "",
    scenario: "",
    hint: "像素間距越小，干擾越容易發生。",
    items: []
  },
  {
    id: "preprocess_015",
    category: "preprocess",
    type: "fillblank",
    difficulty: 1,
    question: "Vignetting 造成的亮度衰減大致遵循 cos 的 ________ 次方定律（cos⁴ law）。",
    options: [],
    answer: "4",
    acceptAlso: ["四", "cos4", "cos⁴"],
    explanation: "自然 vignetting 遵循 cos⁴θ 定律，其中 θ 為離光軸的角度。亮度按照 cos 的四次方衰減，影像邊角的亮度可能降至中心的 50% 以下。",
    imageDesc: "",
    scenario: "",
    hint: "這是光學中著名的餘弦定律。",
    items: []
  },
  {
    id: "preprocess_016",
    category: "preprocess",
    type: "single",
    difficulty: 1,
    question: "Defect pixel cluster 是指什麼？",
    options: [
      "A. 多個相鄰壞點形成的群組",
      "B. 分散在感測器各處的單一壞點",
      "C. 一種 demosaic 演算法",
      "D. 壞點偵測的統計方法"
    ],
    answer: 0,
    acceptAlso: [],
    explanation: "Defect pixel cluster 是指多個壞點集中在相鄰區域形成的群組，這比單一壞點更難修復，因為缺乏足夠的正常鄰近像素作為內插參考。",
    imageDesc: "",
    scenario: "",
    hint: "Cluster 代表聚集在一起。",
    items: []
  },
  {
    id: "preprocess_017",
    category: "preprocess",
    type: "truefalse",
    difficulty: 1,
    question: "Row noise 在 CCD 感測器中比 CMOS 感測器更常見。",
    options: ["True", "False"],
    answer: false,
    acceptAlso: [],
    explanation: "Row noise 主要出現在 CMOS 感測器中，因為 CMOS 使用逐行讀取架構，每行有獨立的放大器。CCD 則使用統一的輸出放大器，較不會產生 row-to-row 差異。",
    imageDesc: "",
    scenario: "",
    hint: "想想 CCD 和 CMOS 的讀出架構差異。",
    items: []
  },

  // ========== DIFFICULTY 2 (questions 018–034) ==========
  {
    id: "preprocess_018",
    category: "preprocess",
    type: "multiple",
    difficulty: 2,
    question: "以下哪些方法常用於偵測 bad pixel？（複選）",
    options: [
      "A. 靜態壞點表（static defect map）",
      "B. 動態閾值偵測（dynamic threshold detection）",
      "C. Fourier transform 分析",
      "D. 與鄰近像素值的差異比較"
    ],
    answer: [0, 1, 3],
    acceptAlso: [],
    explanation: "靜態壞點表在工廠校準時建立；動態偵測在每幀即時比較像素與鄰近像素的差異；與鄰近像素值比較也是動態偵測的核心。Fourier transform 不是壞點偵測的典型方法。",
    imageDesc: "",
    scenario: "",
    hint: "壞點偵測分為離線和即時兩種策略。",
    items: []
  },
  {
    id: "preprocess_019",
    category: "preprocess",
    type: "scenario",
    difficulty: 2,
    question: "某款手機在長曝光夜拍模式下，影像出現大量隨機分布的亮點，但短曝光時幾乎看不到。最可能的原因是什麼？",
    options: [
      "A. Hot pixel 因長曝光累積暗電流而變得明顯",
      "B. 鏡頭 vignetting 加劇",
      "C. Bayer pattern 對齊錯誤",
      "D. JPEG 壓縮品質過低"
    ],
    answer: 0,
    acceptAlso: [],
    explanation: "Hot pixel 的暗電流會隨曝光時間線性累積。短曝光時暗電流產生的信號低於可見閾值，但長曝光下累積量足以產生明顯亮點。這也是為何天文攝影特別需要 dark frame subtraction。",
    imageDesc: "",
    scenario: "工程師正在 tuning 夜拍模式，發現長曝光影像品質問題。",
    hint: "暗電流與曝光時間成正比。",
    items: []
  },
  {
    id: "preprocess_020",
    category: "preprocess",
    type: "single",
    difficulty: 2,
    question: "LSC 校正表通常使用什麼格式儲存？",
    options: [
      "A. 低解析度的 per-channel gain map",
      "B. 全解析度的 binary mask",
      "C. 單一的全域增益值",
      "D. 頻域的 DCT 係數"
    ],
    answer: 0,
    acceptAlso: [],
    explanation: "LSC gain map 通常以低於感測器解析度的格式（如 17x13 grid）儲存每個通道的增益值，實際使用時透過雙線性內插得到每個像素的校正增益，以節省記憶體和運算。",
    imageDesc: "",
    scenario: "",
    hint: "需要在記憶體用量和精確度之間取得平衡。",
    items: []
  },
  {
    id: "preprocess_021",
    category: "preprocess",
    type: "single",
    difficulty: 2,
    question: "在 OB clamping 中，若 OB 區域的平均值為 64（10-bit ADC），則對整幅影像的正確處理是？",
    options: [
      "A. 每個像素值減去 64",
      "B. 每個像素值加上 64",
      "C. 每個像素值除以 64",
      "D. 只處理值低於 64 的像素"
    ],
    answer: 0,
    acceptAlso: [],
    explanation: "OB 區域的平均值代表當前的黑電平偏移，需要從所有像素值中減去此值，使真正的黑色對應到零值。減去後若出現負值，通常 clamp 到 0。",
    imageDesc: "",
    scenario: "",
    hint: "黑電平代表「零光照」時的數位值。",
    items: []
  },
  {
    id: "preprocess_022",
    category: "preprocess",
    type: "image",
    difficulty: 2,
    question: "觀察影像描述：一張影像中心明亮、四角明顯偏暗，呈現輻射狀漸變。這是哪種現象，應使用什麼校正？",
    options: [
      "A. Vignetting，使用 lens shading correction",
      "B. Fixed pattern noise，使用 dark frame subtraction",
      "C. Column noise，使用 column FPN correction",
      "D. Chromatic aberration，使用色差校正"
    ],
    answer: 0,
    acceptAlso: [],
    explanation: "中心亮、邊角暗的輻射狀漸變是典型的 vignetting 特徵，由鏡頭光學特性引起，需要透過 LSC 以位置相關的增益補償來校正。",
    imageDesc: "影像呈現從中心向四角逐漸變暗的輻射狀亮度衰減，中心區域正常曝光，四個角落明顯偏暗約 40%。",
    scenario: "",
    hint: "輻射對稱的亮度衰減是光學特徵。",
    items: []
  },
  {
    id: "preprocess_023",
    category: "preprocess",
    type: "multiple",
    difficulty: 2,
    question: "Flat field correction 的校準影像拍攝時需要注意哪些要點？（複選）",
    options: [
      "A. 使用均勻且穩定的光源照射",
      "B. 曝光時間應使影像處於線性範圍內",
      "C. 必須使用最高 ISO 設定",
      "D. 需要拍攝多張取平均以降低隨機雜訊"
    ],
    answer: [0, 1, 3],
    acceptAlso: [],
    explanation: "均勻光源確保非均勻性僅來自鏡頭和感測器；線性範圍確保校正比例正確；多張取平均降低隨機雜訊。不需要最高 ISO，高 ISO 反而會增加不必要的雜訊。",
    imageDesc: "",
    scenario: "",
    hint: "校正參考影像的品質直接影響校正效果。",
    items: []
  },
  {
    id: "preprocess_024",
    category: "preprocess",
    type: "single",
    difficulty: 2,
    question: "Column FPN correction 通常會利用哪個區域的資料來估算每行的偏移？",
    options: [
      "A. Optical black (OB) 行的像素值",
      "B. 影像中心的像素值",
      "C. 上一幀的像素值",
      "D. 外部校準檔案的固定值"
    ],
    answer: 0,
    acceptAlso: [],
    explanation: "OB 行的像素被遮光，其值僅包含黑電平和雜訊。比較不同 column 在 OB 行的值差異，可以估算各 column 的固定偏移，用於 column FPN correction。",
    imageDesc: "",
    scenario: "",
    hint: "需要一個不受場景影響的參考。",
    items: []
  },
  {
    id: "preprocess_025",
    category: "preprocess",
    type: "fillblank",
    difficulty: 2,
    question: "Sensor crosstalk 可分為 optical crosstalk 和 ________ crosstalk 兩大類。",
    options: [],
    answer: "electrical",
    acceptAlso: ["電性", "electronic", "電子"],
    explanation: "Optical crosstalk 是光線穿過微透鏡或色彩濾光片邊緣進入相鄰像素；electrical crosstalk 是光生載子（photo-generated carriers）在矽基板中擴散到鄰近像素的光電二極體。",
    imageDesc: "",
    scenario: "",
    hint: "除了光學路徑，電子信號也可能洩漏。",
    items: []
  },
  {
    id: "preprocess_026",
    category: "preprocess",
    type: "scenario",
    difficulty: 2,
    question: "工程師發現同一款感測器在不同溫度下，OB clamping 後的黑電平仍有差異。最可能的改善方案是？",
    options: [
      "A. 使用逐幀動態 OB 計算取代固定值",
      "B. 增加 JPEG 壓縮品質",
      "C. 調整白平衡增益",
      "D. 使用更大的 demosaic kernel"
    ],
    answer: 0,
    acceptAlso: [],
    explanation: "暗電流隨溫度變化，因此黑電平會動態改變。使用逐幀從 OB 區域即時計算黑電平，可以追蹤溫度引起的變化，比使用固定校準值更準確。",
    imageDesc: "",
    scenario: "產品在戶外使用時，溫度範圍從 -10°C 到 50°C，需要穩定的黑電平。",
    hint: "暗電流每升溫約 8°C 會增加一倍。",
    items: []
  },
  {
    id: "preprocess_027",
    category: "preprocess",
    type: "single",
    difficulty: 2,
    question: "Green imbalance 如果不校正，最可能在影像中造成什麼視覺 artifact？",
    options: [
      "A. 在高頻紋理區域出現迷宮狀偽色（maze artifact）",
      "B. 影像整體偏紅",
      "C. 垂直條紋雜訊",
      "D. 影像邊緣模糊"
    ],
    answer: 0,
    acceptAlso: [],
    explanation: "Gr/Gb 不平衡會在 demosaic 時造成綠色通道的高頻不連續，在紋理豐富的區域產生迷宮狀（maze-like）的偽色 artifact，這是因為 demosaic 演算法假設 Gr 和 Gb 響應一致。",
    imageDesc: "",
    scenario: "",
    hint: "Demosaic 假設同色通道的鄰近像素值平滑過渡。",
    items: []
  },
  {
    id: "preprocess_028",
    category: "preprocess",
    type: "ordering",
    difficulty: 2,
    question: "請依照正確順序排列以下 linearization 相關步驟：",
    options: [],
    answer: 0,
    acceptAlso: [],
    explanation: "先用多個已知亮度拍攝取得實際響應曲線，接著擬合校正函數（LUT 或多項式），最後在 ISP 前處理中套用此函數將原始值映射回線性值。",
    imageDesc: "",
    scenario: "",
    hint: "校準 → 建模 → 套用。",
    items: [
      "在不同曝光量下拍攝校準影像取得感測器響應曲線",
      "擬合 LUT 或多項式校正函數",
      "在 ISP pipeline 中對每個像素套用校正函數"
    ]
  },
  {
    id: "preprocess_029",
    category: "preprocess",
    type: "truefalse",
    difficulty: 2,
    question: "LSC 的 gain map 對不同色溫的光源是完全相同的，無需隨光源變化調整。",
    options: ["True", "False"],
    answer: false,
    acceptAlso: [],
    explanation: "LSC gain map 會因光源色溫而異，因為不同波長的光通過鏡頭時的折射和衰減特性不同。通常需要在多個色溫下校準，並在 ISP 中根據 AWB 結果內插選擇合適的 gain map。",
    imageDesc: "",
    scenario: "",
    hint: "不同波長的光在鏡頭中的行為不同。",
    items: []
  },
  {
    id: "preprocess_030",
    category: "preprocess",
    type: "image",
    difficulty: 2,
    question: "觀察影像描述：影像中出現規則的垂直條紋，在暗部區域更明顯，條紋寬度為一個像素。最可能是什麼問題？",
    options: [
      "A. Column FPN（行固定模式雜訊）",
      "B. 鏡頭 flare",
      "C. Dead pixel cluster",
      "D. Bayer pattern 旋轉錯誤"
    ],
    answer: 0,
    acceptAlso: [],
    explanation: "寬度為一個像素的規則垂直條紋是典型的 column FPN 特徵，由各 column 讀取電路的增益和偏移差異造成。暗部更明顯是因為信噪比低時，固定偏移相對於信號更顯著。",
    imageDesc: "影像中可見等間距的單像素寬垂直條紋，在影像暗部區域（如陰影處）尤為明顯，亮部區域條紋不太可見。",
    scenario: "",
    hint: "逐行的固定偏差形成條紋。",
    items: []
  },
  {
    id: "preprocess_031",
    category: "preprocess",
    type: "single",
    difficulty: 2,
    question: "在修復 defect pixel cluster 時，相較於單一壞點修復的最大挑戰是什麼？",
    options: [
      "A. 缺乏足夠的正常鄰近像素作為內插參考",
      "B. 壞點的數位值太高無法處理",
      "C. 無法在 Bayer domain 操作",
      "D. 需要使用 GPU 加速"
    ],
    answer: 0,
    acceptAlso: [],
    explanation: "單一壞點周圍有充足的正常像素可供內插，但 cluster 中相鄰像素都是壞的，可用的參考像素更遠，內插精度下降。可能需要使用更大的搜索窗口或方向性內插策略。",
    imageDesc: "",
    scenario: "",
    hint: "內插需要正常的鄰近值。",
    items: []
  },
  {
    id: "preprocess_032",
    category: "preprocess",
    type: "fillblank",
    difficulty: 2,
    question: "Dark frame subtraction 的公式為：corrected = raw - ________。",
    options: [],
    answer: "dark frame",
    acceptAlso: ["dark_frame", "darkframe", "暗場影像", "暗幀"],
    explanation: "校正後影像等於原始影像減去暗場影像。暗場影像記錄了暗電流和固定偏移的空間分布，逐像素相減可去除這些系統性雜訊。",
    imageDesc: "",
    scenario: "",
    hint: "直接的減法運算。",
    items: []
  },
  {
    id: "preprocess_033",
    category: "preprocess",
    type: "multiple",
    difficulty: 2,
    question: "以下哪些因素會影響 sensor crosstalk 的嚴重程度？（複選）",
    options: [
      "A. 像素尺寸（pixel pitch）",
      "B. 微透鏡設計",
      "C. JPEG 壓縮比",
      "D. 入射光角度（chief ray angle）"
    ],
    answer: [0, 1, 3],
    acceptAlso: [],
    explanation: "像素越小，相鄰像素距離越近，crosstalk 越嚴重。微透鏡的聚焦能力影響光線是否偏移到鄰近像素。大入射角的光更容易穿入相鄰像素。JPEG 壓縮是後端處理，不影響感測器層的 crosstalk。",
    imageDesc: "",
    scenario: "",
    hint: "都是感測器物理層面的因素。",
    items: []
  },
  {
    id: "preprocess_034",
    category: "preprocess",
    type: "scenario",
    difficulty: 2,
    question: "在手機 camera tuning 中，LSC 校準後在 D65 光源下效果良好，但在 A 光源下影像邊角仍然偏色。最可能的原因和解決方案？",
    options: [
      "A. LSC gain map 未針對不同色溫分別校準，需新增 A 光源下的校準資料",
      "B. Bad pixel map 過時，需要更新",
      "C. OB clamping 值不正確",
      "D. Gamma 曲線設定錯誤"
    ],
    answer: 0,
    acceptAlso: [],
    explanation: "不同色溫光源的光譜分布不同，通過鏡頭時各通道的 vignetting 程度也不同。僅在 D65 校準的 gain map 無法正確補償 A 光源下的色彩 shading，需要多色溫校準並在 runtime 內插。",
    imageDesc: "",
    scenario: "Camera tuning 工程師在驗證不同光源下的影像品質。",
    hint: "不同光源的光譜成分不同。",
    items: []
  },

  // ========== DIFFICULTY 3 (questions 035–050) ==========
  {
    id: "preprocess_035",
    category: "preprocess",
    type: "single",
    difficulty: 3,
    question: "在 BSI (back-side illuminated) 感測器中，optical crosstalk 相較 FSI 感測器有何變化？",
    options: [
      "A. 因金屬佈線不在光路上，optical crosstalk 減少但仍受像素間距限制",
      "B. Optical crosstalk 完全消除",
      "C. Optical crosstalk 大幅增加",
      "D. 與 FSI 完全相同"
    ],
    answer: 0,
    acceptAlso: [],
    explanation: "BSI 將金屬佈線層移到光電二極體背面，光路上障礙物減少，降低了光線散射造成的 optical crosstalk。但像素間的光學隔離仍受物理尺寸限制，且 electrical crosstalk 仍然存在。",
    imageDesc: "",
    scenario: "",
    hint: "BSI 改變了光路結構但沒有改變像素間距。",
    items: []
  },
  {
    id: "preprocess_036",
    category: "preprocess",
    type: "scenario",
    difficulty: 3,
    question: "某 ISP 團隊發現在啟用 HDR staggered exposure 模式後，原本校準好的 static bad pixel map 無法正確修復所有壞點。最可能的原因是？",
    options: [
      "A. 不同曝光時間下 hot pixel 的表現不同，短曝光幀中部分 hot pixel 低於偵測閾值",
      "B. HDR 模式改變了 Bayer pattern 排列",
      "C. Bad pixel 在 HDR 融合後自動消失",
      "D. Static map 只能在 SDR 模式使用"
    ],
    answer: 0,
    acceptAlso: [],
    explanation: "Hot pixel 的異常值與曝光時間相關。在 staggered HDR 中，長曝光幀的 hot pixel 可能很明顯，但短曝光幀中同一像素的暗電流累積不足以觸發靜態閾值。需要針對不同曝光配置分別建立壞點表或使用動態偵測。",
    imageDesc: "",
    scenario: "ISP 工程師在開發 HDR video 功能，使用長短曝光交錯讀出。",
    hint: "暗電流累積量與曝光時間成正比。",
    items: []
  },
  {
    id: "preprocess_037",
    category: "preprocess",
    type: "multiple",
    difficulty: 3,
    question: "在設計 LSC calibration flow 時，需要控制哪些變數以確保校正精確度？（複選）",
    options: [
      "A. 光源的色溫和均勻度",
      "B. 鏡頭的焦距和光圈設定",
      "C. 感測器的溫度",
      "D. 以上全部"
    ],
    answer: [0, 1, 2],
    acceptAlso: [],
    explanation: "光源色溫影響各通道 shading 差異；均勻度確保不均勻性來自鏡頭而非光源。焦距和光圈改變光學路徑和 vignetting 程度。溫度影響感測器響應和暗電流。全面的校準需要在多種組合下進行。",
    imageDesc: "",
    scenario: "",
    hint: "所有影響光學路徑和感測器響應的因素都要控制。",
    items: []
  },
  {
    id: "preprocess_038",
    category: "preprocess",
    type: "single",
    difficulty: 3,
    question: "在 DSNU (Dark Signal Non-Uniformity) 和 PRNU (Photo Response Non-Uniformity) 中，dark frame subtraction 主要處理哪一種？",
    options: [
      "A. DSNU",
      "B. PRNU",
      "C. 同時處理兩者",
      "D. 都不處理"
    ],
    answer: 0,
    acceptAlso: [],
    explanation: "DSNU 是零光照下各像素暗信號的差異（加性雜訊），dark frame subtraction 直接減去這些差異。PRNU 是各像素對光的響應靈敏度差異（乘性雜訊），需要 flat field correction（除法運算）來補償。",
    imageDesc: "",
    scenario: "",
    hint: "加性雜訊用減法校正，乘性雜訊用除法校正。",
    items: []
  },
  {
    id: "preprocess_039",
    category: "preprocess",
    type: "fillblank",
    difficulty: 3,
    question: "Flat field correction 的公式為：corrected(x,y) = [raw(x,y) - dark(x,y)] × K / [flat(x,y) - ________]。",
    options: [],
    answer: "dark(x,y)",
    acceptAlso: ["dark", "dark frame"],
    explanation: "完整的 flat field correction 需先對 raw 和 flat field 參考影像都減去 dark frame，然後用校正後的 flat field 做除法歸一化。K 是歸一化常數（通常為 flat field 的平均值）。",
    imageDesc: "",
    scenario: "",
    hint: "Flat field 參考本身也包含暗電流。",
    items: []
  },
  {
    id: "preprocess_040",
    category: "preprocess",
    type: "image",
    difficulty: 3,
    question: "觀察影像描述：一張暗場影像中，有一小片約 5×5 大小的區域呈現明顯高值，周圍像素正常。這代表什麼，應如何處理？",
    options: [
      "A. Defect pixel cluster，需使用擴展搜索範圍的特殊修復演算法",
      "B. 單一 hot pixel 的正常擴散",
      "C. Lens flare 殘留",
      "D. 數位增益造成的假象"
    ],
    answer: 0,
    acceptAlso: [],
    explanation: "5×5 區域的高值群組是典型的 defect pixel cluster。由於群組內缺乏可靠的鄰近正常像素，需要使用大於 cluster 尺寸的搜索窗口，參考更遠處的正常像素進行方向性內插。部分算法會先偵測 cluster 邊界，再從外圍向內填充。",
    imageDesc: "暗場影像（全黑背景）中，有一小塊約 5×5 像素的區域明顯發亮，亮度約為背景的 10-20 倍，形狀不規則但集中。周圍像素值接近暗場的正常水準。",
    scenario: "",
    hint: "多個相鄰壞點需要特殊處理策略。",
    items: []
  },
  {
    id: "preprocess_041",
    category: "preprocess",
    type: "ordering",
    difficulty: 3,
    question: "在精確的感測器校準流程中，以下步驟的正確順序為何？",
    options: [],
    answer: 0,
    acceptAlso: [],
    explanation: "必須先量測黑電平特性才能正確減去暗信號；有了正確的黑電平後才能準確量測線性度；確認線性度後才能正確進行 flat field 校正；最後在以上基礎上進行顏色相關的 LSC 校準。",
    imageDesc: "",
    scenario: "",
    hint: "每一步都依賴前一步的準確性。",
    items: [
      "量測 OB 及 dark current 特性",
      "進行 linearization 校正",
      "拍攝並分析 flat field 影像",
      "在多色溫下校準 LSC gain map"
    ]
  },
  {
    id: "preprocess_042",
    category: "preprocess",
    type: "single",
    difficulty: 3,
    question: "當使用 radial polynomial model（如 r², r⁴, r⁶ 項）來擬合 LSC correction 時，相較於 grid-based gain map，其主要優勢和限制是什麼？",
    options: [
      "A. 優勢是記憶體用量極低，限制是無法精確擬合非對稱的 shading pattern",
      "B. 優勢是精度最高，限制是運算量太大",
      "C. 優勢是支援所有鏡頭，限制是需要 GPU",
      "D. 優勢是不需校準，限制是只適用於可見光"
    ],
    answer: 0,
    acceptAlso: [],
    explanation: "Radial polynomial 只需少量係數即可描述中心對稱的 shading（記憶體極省），但現實中鏡頭的 shading 常因機械公差、組裝偏心等因素呈現非對稱分布，此時 grid-based gain map 能更精確地描述任意形狀的 shading。",
    imageDesc: "",
    scenario: "",
    hint: "真實鏡頭的 shading 不一定是完美的圓形對稱。",
    items: []
  },
  {
    id: "preprocess_043",
    category: "preprocess",
    type: "scenario",
    difficulty: 3,
    question: "工程師在調試行車紀錄器 ISP 時，發現在引擎啟動後影像逐漸出現愈來愈多的亮點，關閉引擎冷卻後亮點減少。動態壞點偵測的閾值已設定，但仍有遺漏。最佳改善策略為何？",
    options: [
      "A. 實作溫度自適應的動態閾值，隨感測器溫度升高降低偵測門檻",
      "B. 增加 JPEG 壓縮品質",
      "C. 使用更小的鏡頭",
      "D. 關閉 HDR 功能"
    ],
    answer: 0,
    acceptAlso: [],
    explanation: "引擎產生的熱量導致感測器溫度上升，暗電流指數增加，使更多像素的暗電流超過正常範圍但仍低於固定閾值。溫度自適應閾值可根據即時溫度或 OB 統計值動態調整偵測靈敏度。",
    imageDesc: "",
    scenario: "行車紀錄器安裝在引擎附近，夏季車內溫度可達 70°C 以上。",
    hint: "暗電流與溫度呈指數關係。",
    items: []
  },
  {
    id: "preprocess_044",
    category: "preprocess",
    type: "truefalse",
    difficulty: 3,
    question: "在 stacked CMOS 感測器中，由於邏輯層與像素層分離，column FPN 問題已完全消除。",
    options: ["True", "False"],
    answer: false,
    acceptAlso: [],
    explanation: "Stacked CMOS 將 ADC 和邏輯電路移到獨立的晶片層，改善了佈局靈活性，但 column 讀取電路仍然存在，各 column 的類比前端仍有製程差異。雖然 stacking 可能降低某些干擾源，但 column FPN 並未完全消除。",
    imageDesc: "",
    scenario: "",
    hint: "類比電路的製程差異無法靠堆疊完全解決。",
    items: []
  },
  {
    id: "preprocess_045",
    category: "preprocess",
    type: "multiple",
    difficulty: 3,
    question: "在 automotive ISP 中，前處理模組的設計相較消費級產品需額外考慮哪些因素？（複選）",
    options: [
      "A. 極端溫度範圍（-40°C to +125°C）下的校正穩定性",
      "B. LED flicker 對 OB 統計的潛在影響",
      "C. 功能安全要求（如壞點數量監控與報警）",
      "D. 支援 Instagram 濾鏡"
    ],
    answer: [0, 1, 2],
    acceptAlso: [],
    explanation: "車規 ISP 需要在極端溫度範圍可靠運作，校正參數需覆蓋寬溫範圍。LED 交通號誌的閃爍可能影響某些 ISP 統計。ASIL 功能安全要求對壞點等缺陷需要監控和診斷報告機制。",
    imageDesc: "",
    scenario: "",
    hint: "車規產品的可靠性和安全性要求極高。",
    items: []
  },
  {
    id: "preprocess_046",
    category: "preprocess",
    type: "single",
    difficulty: 3,
    question: "在進行 green imbalance correction 時，為何不能簡單地將 Gr 和 Gb 取平均來消除差異？",
    options: [
      "A. 在邊緣區域取平均會模糊真實的高頻細節，需要邊緣感知的自適應校正",
      "B. Gr 和 Gb 在 Bayer pattern 中不相鄰",
      "C. 取平均會改變白平衡",
      "D. 取平均的運算量超過硬體限制"
    ],
    answer: 0,
    acceptAlso: [],
    explanation: "Gr/Gb 在影像邊緣區域可能有真實的亮度差異（因為它們位於不同行，採樣位置不同）。簡單平均會模糊這些邊緣。正確做法是使用邊緣偵測，僅在平坦區域校正 Gr/Gb 差異，在邊緣區域保留原始值或使用方向性校正。",
    imageDesc: "",
    scenario: "",
    hint: "空間位置不同的像素本來就可能有不同的真實值。",
    items: []
  },
  {
    id: "preprocess_047",
    category: "preprocess",
    type: "fillblank",
    difficulty: 3,
    question: "對於 10-bit ADC 且 pedestal 為 64 的感測器，linearization 之前的有效動態範圍為 ________ 個 code。",
    options: [],
    answer: "960",
    acceptAlso: ["1024-64", "1024 - 64"],
    explanation: "10-bit ADC 的總範圍為 0-1023（1024 個 code），減去 pedestal 64 後，有效的信號範圍為 64-1023，即 960 個有效 code。這也說明了 pedestal 會佔用部分動態範圍。",
    imageDesc: "",
    scenario: "",
    hint: "10-bit 共有 1024 個數位值。",
    items: []
  },
  {
    id: "preprocess_048",
    category: "preprocess",
    type: "scenario",
    difficulty: 3,
    question: "ISP 團隊在開發 4×4 remosaic 感測器的前處理模組時，發現傳統的 2×2 Bayer-based green imbalance correction 效果不佳。最根本的原因和解決方向是？",
    options: [
      "A. 4×4 pattern 中有更多綠色子像素位於不同相對位置，需擴展為多組 green imbalance 校正",
      "B. 4×4 感測器不需要 green imbalance correction",
      "C. 只需將 4×4 binning 為 2×2 後再校正即可",
      "D. 使用更強的降噪替代 green imbalance correction"
    ],
    answer: 0,
    acceptAlso: [],
    explanation: "4×4 remosaic（如 Quad Bayer / Nonacell）pattern 中，每個 2×2 色彩 block 內的像素有不同的微透鏡偏移和 PD 結構，導致多種類型的 green imbalance。需要根據像素在 4×4 pattern 中的具體位置，分別建立校正關係。",
    imageDesc: "",
    scenario: "團隊正在開發支援 Quad Bayer 感測器的 ISP firmware。",
    hint: "4×4 pattern 的複雜度遠超 2×2。",
    items: []
  },
  {
    id: "preprocess_049",
    category: "preprocess",
    type: "single",
    difficulty: 3,
    question: "在 crosstalk correction 中，常用的 3×3 或 5×5 correction matrix 本質上是在做什麼運算？",
    options: [
      "A. 對相鄰像素間的信號洩漏做反卷積（deconvolution）以還原真實信號",
      "B. 簡單的高斯模糊平滑",
      "C. 色彩空間從 RGB 轉換到 YUV",
      "D. 將像素值量化到較低位元深度"
    ],
    answer: 0,
    acceptAlso: [],
    explanation: "Crosstalk 可建模為一個 PSF（point spread function），相鄰像素接收到洩漏的信號。校正矩陣本質上是此 PSF 的逆運算（deconvolution），將混合的信號分離回各自像素，還原真實的光電信號分布。",
    imageDesc: "",
    scenario: "",
    hint: "信號洩漏是一種卷積過程。",
    items: []
  },
  {
    id: "preprocess_050",
    category: "preprocess",
    type: "multiple",
    difficulty: 3,
    question: "在高幀率 (>120fps) 影片模式下，ISP 前處理模組面臨哪些額外挑戰？（複選）",
    options: [
      "A. 每幀處理時間預算大幅縮減，需簡化演算法或使用 pipeline 架構",
      "B. 短曝光時間使 OB 統計的 sample 數量減少，精度下降",
      "C. 部分感測器在高幀率下使用 sub-sampling 讀出，改變了 FPN 的 pattern",
      "D. 高幀率下自動對焦更準確，無其他影響"
    ],
    answer: [0, 1, 2],
    acceptAlso: [],
    explanation: "高幀率意味著每幀的處理時間窗口更短，需要更高效的硬體實現。短曝光減少了 OB 統計可用的信號量。部分感測器在高幀率下使用 binning 或 sub-sampling，改變了像素讀出的電路路徑，可能產生不同於全解析度模式的 FPN pattern。",
    imageDesc: "",
    scenario: "",
    hint: "時間預算和讀出方式都會改變。",
    items: []
  }
];
