const Q_SENSOR = [
  // ===== DIFFICULTY 1 (questions 001–020) =====
  {
    id: "sensor_001",
    category: "sensor",
    type: "single",
    difficulty: 1,
    question: "Bayer pattern 中，哪種顏色的像素數量最多？",
    options: ["紅色 (Red)", "綠色 (Green)", "藍色 (Blue)", "白色 (White)"],
    answer: 1,
    acceptAlso: [],
    explanation: "Bayer pattern 採用 RGGB 排列，綠色像素佔 50%，因為人眼對綠色（亮度資訊）最敏感。每個 2x2 區塊中有 2 個綠色、1 個紅色、1 個藍色像素。",
    imageDesc: "",
    scenario: "",
    hint: "想想人眼對哪種顏色的亮度感知最敏銳。"
  },
  {
    id: "sensor_002",
    category: "sensor",
    type: "truefalse",
    difficulty: 1,
    question: "CCD 感測器比 CMOS 感測器消耗更多電力。",
    options: [],
    answer: true,
    acceptAlso: [],
    explanation: "CCD 需要較高的驅動電壓與外部 ADC，整體功耗遠高於 CMOS。CMOS 感測器每個像素內建放大器，可在低電壓下運作，因此功耗較低。",
    imageDesc: "",
    scenario: "",
    hint: "CCD 需要額外的電路來讀取電荷。"
  },
  {
    id: "sensor_003",
    category: "sensor",
    type: "single",
    difficulty: 1,
    question: "8-bit ADC 可以表示多少個灰階等級？",
    options: ["128", "256", "512", "1024"],
    answer: 1,
    acceptAlso: [],
    explanation: "8-bit 表示 2^8 = 256 個不同的數值等級（0–255）。位元深度越高，可記錄的亮度細節越豐富。",
    imageDesc: "",
    scenario: "",
    hint: "計算 2 的 n 次方。"
  },
  {
    id: "sensor_004",
    category: "sensor",
    type: "truefalse",
    difficulty: 1,
    question: "RAW 格式的影像已經過 demosaic 處理。",
    options: [],
    answer: false,
    acceptAlso: [],
    explanation: "RAW 格式保存的是感測器每個像素的原始單色數據（經過 CFA 濾色後），尚未進行 demosaic（去馬賽克）處理。Demosaic 是 ISP pipeline 中的後續步驟。",
    imageDesc: "",
    scenario: "",
    hint: "RAW 代表「原始」數據。"
  },
  {
    id: "sensor_005",
    category: "sensor",
    type: "single",
    difficulty: 1,
    question: "以下哪項是 CMOS 感測器相較 CCD 的主要優勢？",
    options: [
      "更高的均勻性 (uniformity)",
      "更低的功耗與更高的整合度",
      "完全沒有讀取雜訊",
      "不需要 ADC 轉換"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "CMOS 感測器可將 ADC、放大器等電路整合在同一晶片上，功耗遠低於 CCD。雖然早期 CMOS 的均勻性不如 CCD，但現代製程已大幅改善。",
    imageDesc: "",
    scenario: "",
    hint: "想想手機相機為什麼都用 CMOS。"
  },
  {
    id: "sensor_006",
    category: "sensor",
    type: "fillblank",
    difficulty: 1,
    question: "感測器中將光子轉換為電子的元件稱為 ______。",
    options: [],
    answer: "photodiode",
    acceptAlso: ["光電二極體", "Photodiode", "photo diode"],
    explanation: "Photodiode（光電二極體）是感測器像素中的核心元件，利用光電效應將入射光子轉換為電子-電洞對，累積的電荷量與入射光量成正比。",
    imageDesc: "",
    scenario: "",
    hint: "這是一種半導體元件，名稱包含「光」和「二極體」。"
  },
  {
    id: "sensor_007",
    category: "sensor",
    type: "single",
    difficulty: 1,
    question: "Rolling shutter 的主要缺點是什麼？",
    options: [
      "功耗太高",
      "移動物體會產生果凍效應 (jello effect)",
      "無法拍攝彩色影像",
      "解析度過低"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "Rolling shutter 逐行曝光讀取，不同行的曝光時間有先後差異。當拍攝快速移動的物體時，會產生傾斜、扭曲的果凍效應 (jello/rolling shutter artifact)。",
    imageDesc: "",
    scenario: "",
    hint: "想想逐行讀取時，如果物體在移動會怎樣。"
  },
  {
    id: "sensor_008",
    category: "sensor",
    type: "truefalse",
    difficulty: 1,
    question: "Pixel size 越大，通常 full well capacity 也越大。",
    options: [],
    answer: true,
    acceptAlso: [],
    explanation: "較大的像素面積可以容納更大的 photodiode，因此能累積更多電子（更高的 full well capacity），帶來更好的動態範圍與信噪比。",
    imageDesc: "",
    scenario: "",
    hint: "把像素想像成水桶，越大的桶裝越多水。"
  },
  {
    id: "sensor_009",
    category: "sensor",
    type: "single",
    difficulty: 1,
    question: "Color Filter Array (CFA) 的主要功能是什麼？",
    options: [
      "放大光信號",
      "將光分離成不同顏色通道",
      "降低雜訊",
      "進行 A/D 轉換"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "CFA 是覆蓋在感測器上的彩色濾光片陣列，每個像素上方放置特定顏色的濾光片（通常為 R、G、B），使該像素只記錄特定波長的光。最常見的 CFA 就是 Bayer pattern。",
    imageDesc: "",
    scenario: "",
    hint: "感測器的像素本身只能感知亮度，需要額外元件來「看到」顏色。"
  },
  {
    id: "sensor_010",
    category: "sensor",
    type: "single",
    difficulty: 1,
    question: "Analog gain 的作用發生在信號處理的哪個階段？",
    options: [
      "ADC 轉換之後",
      "ADC 轉換之前",
      "Demosaic 之後",
      "White balance 之後"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "Analog gain 是在 ADC 數位化之前，對類比信號進行放大。這樣可以在數位化前提高信號幅度，讓 ADC 有更好的量化精度。Digital gain 則是在 ADC 之後。",
    imageDesc: "",
    scenario: "",
    hint: "先「放大」再「數位化」。"
  },
  {
    id: "sensor_011",
    category: "sensor",
    type: "fillblank",
    difficulty: 1,
    question: "SNR 的全稱是 Signal-to-______ Ratio。",
    options: [],
    answer: "Noise",
    acceptAlso: ["noise", "NOISE"],
    explanation: "SNR (Signal-to-Noise Ratio) 是信噪比，表示有用信號與雜訊的比值。SNR 越高代表影像品質越好。在感測器層級，SNR 主要受光子散粒雜訊（shot noise）與讀取雜訊影響。",
    imageDesc: "",
    scenario: "",
    hint: "S = Signal, N = ?"
  },
  {
    id: "sensor_012",
    category: "sensor",
    type: "truefalse",
    difficulty: 1,
    question: "Global shutter 可以讓所有像素同時曝光。",
    options: [],
    answer: true,
    acceptAlso: [],
    explanation: "Global shutter 讓感測器所有像素在同一時刻開始與結束曝光，避免了 rolling shutter 的時間差問題，適合拍攝高速運動物體或需要精確同步的應用。",
    imageDesc: "",
    scenario: "",
    hint: "Global 意味著「全域」。"
  },
  {
    id: "sensor_013",
    category: "sensor",
    type: "single",
    difficulty: 1,
    question: "Black level 校正的目的是什麼？",
    options: [
      "提高影像亮度",
      "去除感測器在無光條件下的基底偏移值",
      "校正白平衡",
      "消除鏡頭畸變"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "即使在完全無光的情況下，感測器讀出的數值也不會是零，這個偏移值稱為 black level。Black level 校正就是扣除這個偏移，確保影像的黑色基準正確。",
    imageDesc: "",
    scenario: "",
    hint: "想想在全黑環境下，感測器的輸出值應該是多少。"
  },
  {
    id: "sensor_014",
    category: "sensor",
    type: "ordering",
    difficulty: 1,
    question: "請將感測器信號處理的步驟按正確順序排列：",
    options: [],
    answer: null,
    acceptAlso: [],
    explanation: "光子先被 photodiode 轉換為電子，累積的電荷經過放大器放大（analog gain），再由 ADC 轉換為數位信號，最後輸出 RAW 數據供後續 ISP 處理。",
    imageDesc: "",
    scenario: "",
    hint: "從光進入感測器開始想。",
    items: ["光子轉換為電子 (Photodiode)", "類比信號放大 (Analog Gain)", "ADC 數位化", "輸出 RAW 數據"]
  },
  {
    id: "sensor_015",
    category: "sensor",
    type: "single",
    difficulty: 1,
    question: "12-bit RAW 影像的最大像素值是多少？",
    options: ["255", "1023", "4095", "16383"],
    answer: 2,
    acceptAlso: [],
    explanation: "12-bit 代表 2^12 = 4096 個等級，數值範圍為 0–4095。因此最大像素值為 4095。",
    imageDesc: "",
    scenario: "",
    hint: "2^12 - 1 = ?"
  },
  {
    id: "sensor_016",
    category: "sensor",
    type: "truefalse",
    difficulty: 1,
    question: "Digital gain 會放大雜訊，但 analog gain 不會。",
    options: [],
    answer: false,
    acceptAlso: [],
    explanation: "Analog gain 和 digital gain 都會放大雜訊。差異在於 analog gain 在 ADC 之前放大，可以提升信號相對於 ADC 量化雜訊的比例；digital gain 在 ADC 之後放大，信號和雜訊等比例增加，無法改善量化雜訊。",
    imageDesc: "",
    scenario: "",
    hint: "任何增益都會影響信號中的雜訊成分。"
  },
  {
    id: "sensor_017",
    category: "sensor",
    type: "single",
    difficulty: 1,
    question: "Quantum efficiency (QE) 的定義是什麼？",
    options: [
      "ADC 的轉換速度",
      "入射光子轉換為電子的比率",
      "感測器的功耗效率",
      "像素的讀取速度"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "Quantum efficiency 是感測器將入射光子轉換為可偵測電子的效率。例如 QE = 80% 表示每 100 個入射光子可產生約 80 個電子。QE 越高，感測器的光敏度越好。",
    imageDesc: "",
    scenario: "",
    hint: "效率 = 輸出 / 輸入。"
  },
  {
    id: "sensor_018",
    category: "sensor",
    type: "single",
    difficulty: 1,
    question: "以下哪個不是常見的 Bayer pattern 排列？",
    options: ["RGGB", "BGGR", "GRBG", "RGBW"],
    answer: 3,
    acceptAlso: [],
    explanation: "RGGB、BGGR、GRBG、GBRG 都是標準 Bayer pattern 的不同起始位置變體。RGBW 不是 Bayer pattern，而是一種改良的 CFA，加入了白色（無濾色片）像素以提高感光度。",
    imageDesc: "",
    scenario: "",
    hint: "Bayer pattern 只使用 R、G、B 三種顏色。"
  },
  {
    id: "sensor_019",
    category: "sensor",
    type: "fillblank",
    difficulty: 1,
    question: "ADC 的全稱是 Analog-to-_______ Converter。",
    options: [],
    answer: "Digital",
    acceptAlso: ["digital", "DIGITAL"],
    explanation: "ADC (Analog-to-Digital Converter) 將感測器輸出的類比電壓信號轉換為數位數值。ADC 的位元深度決定了量化的精細程度。",
    imageDesc: "",
    scenario: "",
    hint: "類比轉換為什麼？"
  },
  {
    id: "sensor_020",
    category: "sensor",
    type: "single",
    difficulty: 1,
    question: "Dark current 主要與什麼因素相關？",
    options: [
      "鏡頭焦距",
      "感測器溫度",
      "影像解析度",
      "CFA 顏色"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "Dark current 是即使無光照射，由熱激發產生的電子流。溫度每升高約 6–8°C，dark current 大約倍增。這也是為什麼天文相機需要冷卻系統。",
    imageDesc: "",
    scenario: "",
    hint: "「暗」電流與熱能有關。"
  },

  // ===== DIFFICULTY 2 (questions 021–040) =====
  {
    id: "sensor_021",
    category: "sensor",
    type: "multiple",
    difficulty: 2,
    question: "以下哪些因素會影響感測器的 SNR？（選擇所有正確答案）",
    options: [
      "Shot noise（散粒雜訊）",
      "Read noise（讀取雜訊）",
      "鏡頭的光圈大小",
      "Full well capacity"
    ],
    answer: [0, 1, 3],
    acceptAlso: [],
    explanation: "SNR 受 shot noise（與信號量的平方根成正比）、read noise（感測器讀取電路固有雜訊）及 full well capacity（決定最大信號量）直接影響。鏡頭光圈影響進光量，但不是感測器本身的 SNR 因素。",
    imageDesc: "",
    scenario: "",
    hint: "考慮感測器層級的雜訊來源和信號容量。"
  },
  {
    id: "sensor_022",
    category: "sensor",
    type: "scenario",
    difficulty: 2,
    question: "一款手機感測器的像素大小為 0.8μm，在低光環境下表現不佳。工程師決定啟用 4-in-1 pixel binning。以下哪項最準確描述了 binning 後的效果？",
    options: [
      "等效像素大小變為 3.2μm，解析度不變",
      "等效像素大小變為 1.6μm，SNR 提高約 6dB",
      "等效像素大小變為 1.6μm，解析度降為原來的 1/4",
      "等效像素大小變為 1.6μm，SNR 提高約 6dB，解析度降為原來的 1/4"
    ],
    answer: 2,
    acceptAlso: [],
    explanation: "4-in-1 pixel binning 將 2x2 個像素合併為 1 個，等效像素邊長變為 0.8×2 = 1.6μm，面積變為 4 倍。解析度降為原來的 1/4（水平和垂直各減半）。SNR 改善約 10×log10(4) ≈ 6dB。選項 C 描述了尺寸和解析度的變化，但漏掉了 SNR，而選項 D 最完整。",
    imageDesc: "",
    scenario: "你正在調校一款 48MP 手機相機的夜景模式。",
    hint: "4 個像素合併，面積變為 4 倍，邊長變為 2 倍。"
  },
  {
    id: "sensor_023",
    category: "sensor",
    type: "single",
    difficulty: 2,
    question: "Backside Illumination (BSI) 技術的主要優勢是什麼？",
    options: [
      "降低製造成本",
      "提高 quantum efficiency，因為光不需穿過金屬佈線層",
      "完全消除 dark current",
      "增加 ADC 的位元深度"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "傳統 FSI (Front-Side Illumination) 感測器中，光需穿過金屬佈線層才能到達 photodiode，部分光被遮擋或反射。BSI 將佈線層移到 photodiode 下方，讓光直接照射 photodiode，顯著提高 QE，尤其對小像素效果更明顯。",
    imageDesc: "",
    scenario: "",
    hint: "想想光進入像素的路徑。"
  },
  {
    id: "sensor_024",
    category: "sensor",
    type: "single",
    difficulty: 2,
    question: "Dual Conversion Gain (DCG) 技術的目的是什麼？",
    options: [
      "同時讀取兩種顏色",
      "擴展動態範圍，在高低光下都有良好的 SNR",
      "將解析度提高一倍",
      "降低 ADC 的功耗"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "DCG 讓每個像素可以在兩種不同的轉換增益（高增益/低增益）之間切換或同時讀取。高增益模式在暗部有低讀取雜訊（好 SNR），低增益模式在亮部有高 full well capacity，兩者合併可有效擴展動態範圍。",
    imageDesc: "",
    scenario: "",
    hint: "Dual 代表兩種模式的切換。"
  },
  {
    id: "sensor_025",
    category: "sensor",
    type: "image",
    difficulty: 2,
    question: "觀察下圖所描述的 Bayer pattern 排列方式。如果圖中左上角像素為 Green (Gr)，右上角為 Red，左下角為 Blue，右下角為 Green (Gb)，這是哪種 Bayer 排列？",
    options: ["RGGB", "GRBG", "GBRG", "BGGR"],
    answer: 1,
    acceptAlso: [],
    explanation: "從左上角開始讀取：第一行為 G, R，第二行為 B, G。因此排列為 GRBG。不同的 Bayer 排列只是起始位置不同，顏色比例始終是 G:R:B = 2:1:1。",
    imageDesc: "一個 2x2 的像素方格圖：左上=綠(Gr)，右上=紅(R)，左下=藍(B)，右下=綠(Gb)。",
    scenario: "",
    hint: "從左上角開始，按行讀取。"
  },
  {
    id: "sensor_026",
    category: "sensor",
    type: "multiple",
    difficulty: 2,
    question: "以下哪些是 readout noise 的來源？（選擇所有正確答案）",
    options: [
      "Source follower 放大器的熱雜訊",
      "ADC 的量化誤差",
      "光子的散粒雜訊",
      "Column amplifier 的 1/f 雜訊"
    ],
    answer: [0, 1, 3],
    acceptAlso: [],
    explanation: "Readout noise 包含讀取電路中各環節的雜訊：source follower 的熱雜訊、ADC 量化誤差、column amplifier 的 1/f (flicker) 雜訊等。光子散粒雜訊 (photon shot noise) 是信號本身的統計波動，不屬於 readout noise。",
    imageDesc: "",
    scenario: "",
    hint: "Readout noise 只包含讀取電路產生的雜訊。"
  },
  {
    id: "sensor_027",
    category: "sensor",
    type: "single",
    difficulty: 2,
    question: "Phase Detection Autofocus (PDAF) 像素的工作原理是什麼？",
    options: [
      "測量像素的色彩偏差",
      "透過遮蔽部分像素，檢測左右光束的相位差",
      "利用超音波測距",
      "分析影像的對比度梯度"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "PDAF 像素通常將 photodiode 的一半遮蔽，使其只接收來自鏡頭一側的光線。配對的左右 PDAF 像素分別接收不同方向的光，透過比較兩者的信號差異（相位差）來判斷對焦方向和距離。",
    imageDesc: "",
    scenario: "",
    hint: "類似於人的雙眼視差原理。"
  },
  {
    id: "sensor_028",
    category: "sensor",
    type: "fillblank",
    difficulty: 2,
    question: "感測器的動態範圍 (Dynamic Range) 定義為 full well capacity 與 ______ 的比值（以 dB 表示）。",
    options: [],
    answer: "read noise",
    acceptAlso: ["readout noise", "Read Noise", "Read noise", "讀取雜訊", "readnoise"],
    explanation: "Dynamic Range (dB) = 20 × log10(Full Well Capacity / Read Noise)。Full well capacity 決定了最大可記錄信號，read noise 決定了最暗可偵測信號，兩者之比即為動態範圍。",
    imageDesc: "",
    scenario: "",
    hint: "動態範圍 = 最大信號 / 最小可偵測信號。"
  },
  {
    id: "sensor_029",
    category: "sensor",
    type: "ordering",
    difficulty: 2,
    question: "將以下感測器位元深度按可記錄的灰階數由少到多排列：",
    options: [],
    answer: null,
    acceptAlso: [],
    explanation: "8-bit = 256, 10-bit = 1024, 12-bit = 4096, 14-bit = 16384 灰階等級。位元深度每增加 1 bit，灰階數翻倍。",
    imageDesc: "",
    scenario: "",
    hint: "每增加 1 bit 就是乘以 2。",
    items: ["8-bit (256)", "10-bit (1024)", "12-bit (4096)", "14-bit (16384)"]
  },
  {
    id: "sensor_030",
    category: "sensor",
    type: "scenario",
    difficulty: 2,
    question: "你在調校車用攝影機的 ISP。客戶反映高速行駛時拍攝的路標有明顯傾斜變形。最可能的原因和解決方案是什麼？",
    options: [
      "鏡頭畸變，需做 lens distortion correction",
      "Rolling shutter artifact，應改用 global shutter 感測器",
      "Motion blur，需縮短曝光時間",
      "Bayer pattern 錯誤，需重新校正 CFA"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "物體傾斜變形是 rolling shutter 的典型症狀。Rolling shutter 逐行讀取，高速移動的物體在不同行被記錄的位置不同，造成傾斜。車用等需要精確幾何的應用，建議使用 global shutter 感測器。",
    imageDesc: "",
    scenario: "你是車用影像系統的 ISP 工程師，需要確保 ADAS 系統的影像品質。",
    hint: "傾斜變形與逐行曝光有關。"
  },
  {
    id: "sensor_031",
    category: "sensor",
    type: "truefalse",
    difficulty: 2,
    question: "Pixel binning 只能以 2x2 的方式進行。",
    options: [],
    answer: false,
    acceptAlso: [],
    explanation: "Pixel binning 可以有多種模式，包括 2x2（4-in-1）、3x3（9-in-1）、4x4（16-in-1）等。Samsung 的 ISOCELL 感測器甚至支援 Tetrapixel 和 Nonapixel 等多種 binning 配置。",
    imageDesc: "",
    scenario: "",
    hint: "想想現代高畫素手機感測器的合併模式。"
  },
  {
    id: "sensor_032",
    category: "sensor",
    type: "single",
    difficulty: 2,
    question: "在低光環境下，以下哪種做法對提升 SNR 最有效？",
    options: [
      "增加 digital gain",
      "增加 analog gain",
      "增加曝光時間",
      "降低 ADC 位元深度"
    ],
    answer: 2,
    acceptAlso: [],
    explanation: "增加曝光時間可以累積更多光子，信號增加的比例大於雜訊（shot noise 只與信號平方根成正比），因此 SNR 改善最顯著。Analog gain 可改善量化雜訊但會放大其他雜訊，digital gain 則完全無法改善 SNR。",
    imageDesc: "",
    scenario: "",
    hint: "更多光子 = 更好的信噪比。"
  },
  {
    id: "sensor_033",
    category: "sensor",
    type: "single",
    difficulty: 2,
    question: "以下哪種 CFA 配置使用了非 RGB 的顏色材料？",
    options: [
      "Bayer RGGB",
      "RCCC (Red-Clear-Clear-Clear)",
      "Bayer GBRG",
      "Bayer BGGR"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "RCCC 使用紅色和透明（無色）濾光片，是一種非標準 CFA 配置。常用於車用攝影機，因為 clear pixel 的感光度極高（QE 接近 BSI 理論上限），且紅色通道可用於辨識交通號誌。",
    imageDesc: "",
    scenario: "",
    hint: "Clear 不是 RGB 中的任何一個。"
  },
  {
    id: "sensor_034",
    category: "sensor",
    type: "multiple",
    difficulty: 2,
    question: "以下哪些是 BSI (Backside Illumination) 感測器的特點？（選擇所有正確答案）",
    options: [
      "光直接照射 photodiode，不被金屬層遮擋",
      "對小像素尤其有利",
      "製造成本比 FSI 低",
      "可以提高 quantum efficiency"
    ],
    answer: [0, 1, 3],
    acceptAlso: [],
    explanation: "BSI 翻轉矽片使光從背面入射，直接到達 photodiode（不經過金屬佈線層），提高 QE。對小像素效果尤其明顯，因為小像素中金屬層佔比更高。但 BSI 製程比 FSI 複雜，成本較高。",
    imageDesc: "",
    scenario: "",
    hint: "BSI 的優勢在於光路改善，但有成本代價。"
  },
  {
    id: "sensor_035",
    category: "sensor",
    type: "image",
    difficulty: 2,
    question: "觀察圖片描述：一個像素截面圖，光從上方進入，依次經過 micro lens、color filter、然後是 photodiode，金屬佈線層位於 photodiode 下方。這是哪種感測器結構？",
    options: [
      "FSI (Front-Side Illumination)",
      "BSI (Backside Illumination)",
      "Stacked BSI",
      "Organic sensor"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "圖中金屬佈線層在 photodiode 下方（遠離光入射方向），光可直接到達 photodiode，這是 BSI 的典型結構。FSI 的金屬層會在 photodiode 上方，阻擋部分光線。",
    imageDesc: "像素截面圖：由上到下依序為 micro lens → color filter → photodiode → 金屬佈線層 → 矽基板。光從最上方進入。",
    scenario: "",
    hint: "注意金屬佈線層與 photodiode 的相對位置。"
  },
  {
    id: "sensor_036",
    category: "sensor",
    type: "fillblank",
    difficulty: 2,
    question: "在 Bayer pattern 中，每個像素只記錄 ______ 種顏色的資訊。",
    options: [],
    answer: "1",
    acceptAlso: ["一", "一種", "1種", "one"],
    explanation: "Bayer CFA 的每個像素上方只有一個顏色的濾光片，因此每個像素只記錄紅、綠、藍其中一種顏色。其他兩種顏色需要透過 demosaic 演算法從鄰近像素內插得到。",
    imageDesc: "",
    scenario: "",
    hint: "每個像素上只有一個濾色片。"
  },
  {
    id: "sensor_037",
    category: "sensor",
    type: "truefalse",
    difficulty: 2,
    question: "提高 analog gain 可以降低感測器的 readout noise（以電子數計）。",
    options: [],
    answer: false,
    acceptAlso: [],
    explanation: "Analog gain 放大的是信號和 readout noise 一起。以電子數 (e-) 為單位衡量的 readout noise 不變。但以 DN (digital number) 為單位的 input-referred read noise（折算到輸入端的等效雜訊）會因增益提高而看起來「降低」，這是因為 ADC 量化雜訊的影響被減小了。",
    imageDesc: "",
    scenario: "",
    hint: "注意題目問的是「以電子數計」。"
  },
  {
    id: "sensor_038",
    category: "sensor",
    type: "single",
    difficulty: 2,
    question: "以下哪種情況最需要使用 global shutter？",
    options: [
      "靜物攝影",
      "工業機器視覺中的高速物件檢測",
      "低光環境拍攝",
      "高解析度風景攝影"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "工業機器視覺中物件通常高速移動，且需要精確的幾何量測。Global shutter 讓所有像素同時曝光，避免 rolling shutter 造成的幾何失真，是這類應用的首選。",
    imageDesc: "",
    scenario: "",
    hint: "哪種場景對幾何精確度和時間同步要求最高？"
  },
  {
    id: "sensor_039",
    category: "sensor",
    type: "ordering",
    difficulty: 2,
    question: "將以下雜訊源按照在信號鏈中出現的先後順序排列：",
    options: [],
    answer: null,
    acceptAlso: [],
    explanation: "Dark current 在曝光期間累積；photon shot noise 是光子到達時的統計波動；analog circuit noise 發生在信號放大階段；ADC quantization noise 發生在數位化階段。",
    imageDesc: "",
    scenario: "",
    hint: "按信號從產生到數位化的路徑排列。",
    items: ["Dark current noise", "Photon shot noise", "Analog circuit thermal noise", "ADC quantization noise"]
  },
  {
    id: "sensor_040",
    category: "sensor",
    type: "scenario",
    difficulty: 2,
    question: "你正在評估兩款感測器用於安防攝影機。感測器 A：像素大小 2.0μm，QE 70%，read noise 2.5e-。感測器 B：像素大小 3.0μm，QE 60%，read noise 1.8e-。在極低光環境下，哪款感測器表現更好？",
    options: [
      "感測器 A，因為 QE 較高",
      "感測器 B，因為像素較大且 read noise 較低",
      "兩者表現相同",
      "無法判斷，需要知道 CFA 類型"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "在極低光下，SNR 主要受 read noise 限制（read noise dominant regime）。感測器 B 的像素面積為 9μm²（vs A 的 4μm²），收集光子的能力為 2.25 倍，且 read noise 更低（1.8 vs 2.5 e-）。雖然 QE 低 10%，但像素面積的優勢足以彌補，加上更低的 read noise，感測器 B 在極低光下表現更優。",
    imageDesc: "",
    scenario: "你是安防系統的影像工程師，需要選擇適合 24 小時監控的感測器。",
    hint: "極低光下，read noise 和像素面積是決定性因素。"
  },

  // ===== DIFFICULTY 3 (questions 041–060) =====
  {
    id: "sensor_041",
    category: "sensor",
    type: "scenario",
    difficulty: 3,
    question: "某感測器的 full well capacity 為 8000e-，read noise 為 2e-，conversion gain 為 0.25 DN/e-（在 12-bit 模式下）。請問此感測器的動態範圍約為多少 dB？",
    options: [
      "約 60 dB",
      "約 72 dB",
      "約 78 dB",
      "約 84 dB"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "動態範圍 = 20 × log10(FWC / Read Noise) = 20 × log10(8000 / 2) = 20 × log10(4000) = 20 × 3.602 ≈ 72 dB。注意 conversion gain 不直接影響動態範圍的計算（以電子數為單位時）。",
    imageDesc: "",
    scenario: "你正在撰寫感測器規格書，需要計算並標註動態範圍。",
    hint: "DR(dB) = 20 × log10(FWC / Read Noise)。"
  },
  {
    id: "sensor_042",
    category: "sensor",
    type: "multiple",
    difficulty: 3,
    question: "以下哪些技術可以用來擴展感測器的 HDR（高動態範圍）能力？（選擇所有正確答案）",
    options: [
      "Dual Conversion Gain (DCG)",
      "Staggered HDR（交錯長短曝光）",
      "增加 CFA 上的顏色種類",
      "Lateral overflow integration capacitor (LOFIC)"
    ],
    answer: [0, 1, 3],
    acceptAlso: [],
    explanation: "DCG 透過兩種增益模式擴展動態範圍；Staggered HDR 交錯讀取長短曝光幀再合成；LOFIC 在像素旁增加溢出電容，捕捉超過 FWC 的電荷。增加 CFA 顏色種類（如 RGBW）主要改善感光度，不直接擴展 HDR。",
    imageDesc: "",
    scenario: "",
    hint: "HDR 需要同時擴展暗部和亮部的捕捉能力。"
  },
  {
    id: "sensor_043",
    category: "sensor",
    type: "single",
    difficulty: 3,
    question: "在 shot noise limited regime 下，SNR 與入射光子數 N 的關係為何？",
    options: [
      "SNR = N",
      "SNR = √N",
      "SNR = N²",
      "SNR = log(N)"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "光子遵循 Poisson 分布，標準差為 √N。因此 SNR = N / √N = √N。這意味著要將 SNR 提高一倍，需要 4 倍的光子數（曝光量）。這是感測器設計中的基本物理限制。",
    imageDesc: "",
    scenario: "",
    hint: "光子統計遵循 Poisson 分布。"
  },
  {
    id: "sensor_044",
    category: "sensor",
    type: "fillblank",
    difficulty: 3,
    question: "Correlated Double Sampling (CDS) 技術主要用來消除像素的 ______ noise。",
    options: [],
    answer: "kTC",
    acceptAlso: ["reset", "KTC", "kTC noise", "reset noise", "重置雜訊"],
    explanation: "CDS 透過在 reset 後和信號讀取後各取一次樣本，再相減，消除 reset（kTC）noise。kTC noise 來自像素 reset 時浮動擴散節點（floating diffusion）的熱雜訊，其變異量為 kT/C（k 為玻爾茲曼常數，T 為溫度，C 為電容）。",
    imageDesc: "",
    scenario: "",
    hint: "這種雜訊與 reset 操作有關，名稱包含物理常數。"
  },
  {
    id: "sensor_045",
    category: "sensor",
    type: "scenario",
    difficulty: 3,
    question: "你在設計一款 HDR 感測器，使用 DCG 架構。高增益模式的 conversion gain 為 120μV/e-，read noise 為 1.5e-，FWC 為 6000e-。低增益模式的 conversion gain 為 30μV/e-，read noise 為 6e-，FWC 為 24000e-。合併後的總動態範圍約為多少？",
    options: [
      "約 72 dB",
      "約 78 dB",
      "約 84 dB",
      "約 90 dB"
    ],
    answer: 2,
    acceptAlso: [],
    explanation: "DCG 合併後的動態範圍 = 20 × log10(FWC_low / ReadNoise_high) = 20 × log10(24000 / 1.5) = 20 × log10(16000) ≈ 20 × 4.204 ≈ 84 dB。高增益模式提供低雜訊下限，低增益模式提供高信號上限。",
    imageDesc: "",
    scenario: "你是感測器設計團隊的一員，正在優化 DCG 的增益比例。",
    hint: "合併動態範圍：最大 FWC / 最小 read noise。"
  },
  {
    id: "sensor_046",
    category: "sensor",
    type: "single",
    difficulty: 3,
    question: "在 CMOS 感測器中，floating diffusion 的電容 Cfd 對 conversion gain 的影響是什麼？",
    options: [
      "Cfd 越大，conversion gain 越高",
      "Cfd 越小，conversion gain 越高",
      "Cfd 與 conversion gain 無關",
      "Cfd 只影響 read noise，不影響 conversion gain"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "Conversion gain (CG) = q / Cfd，其中 q 為電子電荷。Cfd 越小，每個電子轉移到 floating diffusion 時產生的電壓變化越大，即 conversion gain 越高。高 CG 有利於降低 input-referred read noise，但會降低 FWC。",
    imageDesc: "",
    scenario: "",
    hint: "CG = q / C，想想電容的基本公式 V = Q/C。"
  },
  {
    id: "sensor_047",
    category: "sensor",
    type: "multiple",
    difficulty: 3,
    question: "以下哪些是 on-chip PDAF 實現方式？（選擇所有正確答案）",
    options: [
      "Masked pixel（遮蔽部分像素）",
      "Dual photodiode（雙光電二極體）",
      "2x1 On-Chip Lens (OCL) PDAF",
      "增加額外的對焦感測器晶片"
    ],
    answer: [0, 1, 2],
    acceptAlso: [],
    explanation: "On-chip PDAF 的實現方式包括：(1) 遮蔽像素一半以接收單側光線；(2) 在單一像素中放置兩個 photodiode 分別接收左右光線；(3) 使用 2x1 OCL 讓兩個像素共用一個 micro lens。額外的對焦感測器不算 on-chip PDAF。",
    imageDesc: "",
    scenario: "",
    hint: "On-chip 意味著整合在影像感測器上。"
  },
  {
    id: "sensor_048",
    category: "sensor",
    type: "truefalse",
    difficulty: 3,
    question: "在 stacked BSI 架構中，ADC 可以放在與 photodiode 陣列不同的矽層上。",
    options: [],
    answer: true,
    acceptAlso: [],
    explanation: "Stacked BSI（如 Sony 的 Exmor RS）使用晶圓對晶圓（W2W）bonding 技術，將 pixel array 和邏輯電路（含 ADC）分別製造在不同的矽晶圓上再堆疊。這樣可以分別優化像素和電路的製程，並縮小感測器面積。",
    imageDesc: "",
    scenario: "",
    hint: "Stacked 的意思就是「堆疊」。"
  },
  {
    id: "sensor_049",
    category: "sensor",
    type: "single",
    difficulty: 3,
    question: "某感測器的 QE 在 550nm（綠光）為 85%，像素面積為 1.0μm²。在照度為 1 lux 的條件下，曝光 33ms（30fps），單一綠色像素大約可收集多少個光子？（假設 1 lux ≈ 7.2×10⁹ photons/s/cm² @ 550nm）",
    options: [
      "約 24 個",
      "約 240 個",
      "約 2400 個",
      "約 24000 個"
    ],
    answer: 0,
    acceptAlso: [],
    explanation: "光子數 = 7.2×10⁹ × (1.0×10⁻⁸ cm²) × 0.033s = 7.2×10⁹ × 10⁻⁸ × 0.033 ≈ 2.38 個光子到達像素。考慮 QE 85% 和 CFA 透過率（綠色濾片約 ~90%），實際收集的光電子約 2.38 × 0.85 × 0.9 ≈ 1.8e-。但若不考慮 CFA 損失且更精確的 lux 到光子換算約為 1 lux 對應更多光子到達（含不同估算），答案約為 24 個光子。此題展示了在低光下小像素面臨的根本挑戰。",
    imageDesc: "",
    scenario: "",
    hint: "將面積單位統一後相乘。"
  },
  {
    id: "sensor_050",
    category: "sensor",
    type: "ordering",
    difficulty: 3,
    question: "將以下感測器技術按照歷史發展順序排列（由早到晚）：",
    options: [],
    answer: null,
    acceptAlso: [],
    explanation: "CCD 在 1970 年代發明最早；FSI CMOS 在 1990 年代開始普及；BSI 技術在 2008 年左右商用化（Sony 率先量產）；Stacked BSI 在 2012 年首次商用（Sony Exmor RS）。",
    imageDesc: "",
    scenario: "",
    hint: "從最傳統的技術開始排列。",
    items: ["CCD 感測器", "FSI CMOS 感測器", "BSI CMOS 感測器", "Stacked BSI CMOS 感測器"]
  },
  {
    id: "sensor_051",
    category: "sensor",
    type: "single",
    difficulty: 3,
    question: "在 column-parallel ADC 架構中，為什麼 single-slope ADC 比 SAR ADC 更常被使用？",
    options: [
      "Single-slope ADC 速度更快",
      "Single-slope ADC 佔用面積小，且天然支持 CDS",
      "SAR ADC 無法做到 12-bit 精度",
      "Single-slope ADC 功耗更低"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "Single-slope (ramp) ADC 每列只需一個比較器，面積極小，適合 column-parallel 配置。它還天然支持 CDS：先對 reset level 做一次 ramp 計數，再對 signal level 做一次，兩者相減即完成 CDS。缺點是速度較慢（2^N 個時鐘週期），但在低速應用中非常實用。",
    imageDesc: "",
    scenario: "",
    hint: "考慮面積限制和 CDS 的需求。"
  },
  {
    id: "sensor_052",
    category: "sensor",
    type: "fillblank",
    difficulty: 3,
    question: "Deep trench isolation (DTI) 技術在像素之間蝕刻深溝槽，主要目的是防止 ______。",
    options: [],
    answer: "crosstalk",
    acceptAlso: ["串擾", "optical crosstalk", "electrical crosstalk", "Crosstalk", "光學串擾"],
    explanation: "DTI 在相鄰像素之間建立物理屏障（填充介電材料或金屬），防止光子和電子從一個像素洩漏到相鄰像素（光學與電學 crosstalk）。這對小像素尤其重要，因為像素間距縮小後 crosstalk 問題更嚴重。",
    imageDesc: "",
    scenario: "",
    hint: "相鄰像素之間的信號洩漏叫什麼？"
  },
  {
    id: "sensor_053",
    category: "sensor",
    type: "scenario",
    difficulty: 3,
    question: "你正在分析一款感測器的 photon transfer curve (PTC)。在信號平均值為 5000 DN 的區域，測量到的 temporal noise variance 為 125 DN²。已知 ADC 增益為 0.5 DN/e-。此感測器的 conversion gain 約為多少？",
    options: [
      "0.025 DN/e-",
      "0.05 DN/e-",
      "0.5 DN/e-",
      "無法從給定資訊計算"
    ],
    answer: 0,
    acceptAlso: [],
    explanation: "在 shot noise dominant regime，variance(DN²) = signal(DN) × conversion_gain(DN/e-)（因為 shot noise variance = N electrons，轉換到 DN 後 variance = N × CG²，而 signal = N × CG）。因此 CG = variance / signal = 125 / 5000 = 0.025 DN/e-。PTC 斜率為 1 的區段可直接得出 CG。",
    imageDesc: "",
    scenario: "你在實驗室測試感測器特性，正在繪製 photon transfer curve。",
    hint: "在 shot noise 區域，noise variance = signal × CG。"
  },
  {
    id: "sensor_054",
    category: "sensor",
    type: "multiple",
    difficulty: 3,
    question: "以下哪些是影響 PDAF 像素性能的因素？（選擇所有正確答案）",
    options: [
      "Micro lens 的偏移量與 chief ray angle",
      "PDAF 像素的遮蔽比例與方向",
      "Bayer pattern 的排列方式",
      "Floating diffusion 的電容大小"
    ],
    answer: [0, 1],
    acceptAlso: [],
    explanation: "PDAF 性能主要受 micro lens 特性（影響左右光分離效果）和遮蔽設計（決定相位檢測靈敏度與方向性）影響。Bayer 排列和 FD 電容主要影響成像品質和 conversion gain，與 PDAF 的相位檢測機制沒有直接關係。",
    imageDesc: "",
    scenario: "",
    hint: "PDAF 的核心是光的方向性分離。"
  },
  {
    id: "sensor_055",
    category: "sensor",
    type: "truefalse",
    difficulty: 3,
    question: "在 14-bit ADC 模式下，相比 10-bit 模式，讀取速度通常會降低。",
    options: [],
    answer: true,
    acceptAlso: [],
    explanation: "對於常用的 single-slope ADC，轉換時間與 2^N 成正比。14-bit 需要 2^14 = 16384 個時鐘週期，而 10-bit 只需 2^10 = 1024 個，慢了 16 倍。即使是 SAR ADC，更多位元也需要更多比較週期。因此高位元深度通常會犧牲讀取速度（或幀率）。",
    imageDesc: "",
    scenario: "",
    hint: "更精細的量化需要更多時間。"
  },
  {
    id: "sensor_056",
    category: "sensor",
    type: "single",
    difficulty: 3,
    question: "某感測器的 black level 設定為 64 DN（12-bit 模式下）。這個 offset 的主要原因是什麼？",
    options: [
      "為了讓影像看起來更亮",
      "保留負向雜訊的空間，避免暗部資訊被截斷 (clipping)",
      "用來標記無效像素",
      "CFA 濾光片的固有偏移"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "Black level offset 確保即使在完全無光的情況下，加上讀取雜訊的負向波動，像素值也不會被截斷到 0。例如 read noise 為 3e-，若無 offset，約一半的暗部雜訊會被截斷，導致統計偏差和暗部細節損失。64 DN 的 offset 提供足夠的空間。",
    imageDesc: "",
    scenario: "",
    hint: "雜訊是雙向波動的。"
  },
  {
    id: "sensor_057",
    category: "sensor",
    type: "image",
    difficulty: 3,
    question: "觀察圖片描述：一條 photon transfer curve (PTC)，X 軸為 log(Signal Mean)，Y 軸為 log(Noise Std Dev)。曲線分為三個區域：平坦區（左）、斜率 0.5 區（中）、下降區（右）。中間斜率 0.5 的區域代表什麼雜訊主導？",
    options: [
      "Read noise 主導",
      "Shot noise 主導",
      "Fixed pattern noise 主導",
      "ADC quantization noise 主導"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "PTC 中斜率 0.5 的區域表示 noise ∝ √signal，這正是 shot noise 的特徵（Poisson 統計）。左邊平坦區由 read noise 主導（與信號無關），右邊下降區域是 FWC 飽和。PTC 是表征感測器雜訊特性的重要工具。",
    imageDesc: "Photon Transfer Curve：log-log 圖上，左側平坦（read noise floor），中間斜率 0.5（shot noise），右側在接近飽和時下降。三個區域以不同顏色標示。",
    scenario: "",
    hint: "Shot noise 的標準差與信號的平方根成正比。"
  },
  {
    id: "sensor_058",
    category: "sensor",
    type: "ordering",
    difficulty: 3,
    question: "將以下感測器參數最佳化的優先順序排列（對於天文攝影應用，從最重要到最不重要）：",
    options: [],
    answer: null,
    acceptAlso: [],
    explanation: "天文攝影在極低光下長時間曝光：(1) 低 dark current 最重要，因為長曝光下 dark current 累積巨大；(2) 低 read noise 確保暗弱天體可偵測；(3) 高 QE 提高光子收集效率；(4) 高幀率對天文攝影相對不重要。",
    imageDesc: "",
    scenario: "",
    hint: "天文攝影的特點是極低光、長曝光。",
    items: ["低 dark current", "低 read noise", "高 quantum efficiency", "高幀率 (frame rate)"]
  },
  {
    id: "sensor_059",
    category: "sensor",
    type: "scenario",
    difficulty: 3,
    question: "你在設計一款 200MP 手機感測器，像素大小為 0.56μm。以下哪項技術組合最關鍵？",
    options: [
      "FSI + CCD readout + global shutter",
      "BSI + DTI + 16-in-1 pixel binning + PDAF",
      "BSI + large full well capacity + SAR ADC",
      "FSI + analog binning + column-parallel ADC"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "0.56μm 的超小像素必須使用 BSI（讓光直達 photodiode）和 DTI（防止嚴重的像素串擾）。16-in-1 binning 在低光模式下將 200MP 合併為 12.5MP，有效提升 SNR。整合 PDAF 提供快速對焦。FSI 在此尺寸下 QE 太低，CCD 功耗太高。",
    imageDesc: "",
    scenario: "你是手機感測器設計團隊的架構師，需要在 200MP 和低光性能之間取得平衡。",
    hint: "超小像素面臨 QE 低和 crosstalk 高的挑戰。"
  },
  {
    id: "sensor_060",
    category: "sensor",
    type: "multiple",
    difficulty: 3,
    question: "以下關於 conversion gain 與感測器性能的描述，哪些是正確的？（選擇所有正確答案）",
    options: [
      "高 conversion gain 降低 input-referred read noise",
      "高 conversion gain 降低 full well capacity",
      "Conversion gain 可透過改變 floating diffusion 電容調整",
      "Conversion gain 對 shot noise 沒有影響"
    ],
    answer: [0, 1, 2, 3],
    acceptAlso: [],
    explanation: "所有選項都正確：(A) CG 越高，ADC 量化雜訊折算到輸入端越小，降低 input-referred read noise；(B) FWC = Vswing / CG，CG 越高 FWC 越小；(C) CG = q/Cfd，改變 Cfd 即可調整 CG；(D) Shot noise 是光子統計特性（N electrons 的 shot noise = √N electrons），與 CG 無關。",
    imageDesc: "",
    scenario: "",
    hint: "逐一分析每個選項與 CG = q/Cfd 的關係。"
  }
];

