const Q_SHARPENING = [
  // ===== DIFFICULTY 1 (questions 001–033) =====
  {
    id: "sharpening_001",
    category: "sharpening",
    type: "single",
    difficulty: 1,
    question: "Unsharp Mask (USM) 的基本原理是什麼？",
    options: ["直接增強所有像素的亮度", "將原圖減去模糊版本再加回原圖", "用高斯模糊取代原始影像", "僅對紅色通道做銳化"],
    answer: 1,
    acceptAlso: [],
    explanation: "USM 的原理是：先產生原圖的模糊版本，再計算原圖與模糊版的差值（即高頻細節），最後將此差值乘以增益量加回原圖。公式為 Sharpened = Original + Amount × (Original − Blurred)。",
    imageDesc: "",
    scenario: "",
    hint: "USM 的名稱源自傳統暗房的「unsharp mask」技術。"
  },
  {
    id: "sharpening_002",
    category: "sharpening",
    type: "truefalse",
    difficulty: 1,
    question: "銳化處理可以恢復影像中已完全丟失的細節。",
    options: [],
    answer: false,
    acceptAlso: [],
    explanation: "銳化只能增強影像中已存在但對比度較低的邊緣與細節，無法恢復因欠採樣或嚴重模糊而完全丟失的頻率資訊。這是資訊理論的基本限制。",
    imageDesc: "",
    scenario: "",
    hint: "想想銳化是「創造」還是「增強」細節。"
  },
  {
    id: "sharpening_003",
    category: "sharpening",
    type: "single",
    difficulty: 1,
    question: "USM 中的 Radius 參數控制什麼？",
    options: ["銳化的強度", "模糊核的大小，決定影響的邊緣寬度", "只對亮度通道的影響範圍", "銳化的次數"],
    answer: 1,
    acceptAlso: [],
    explanation: "Radius 決定高斯模糊核的大小。較大的 Radius 會影響較寬的邊緣區域，適合增強粗糙細節；較小的 Radius 則針對精細邊緣。",
    imageDesc: "",
    scenario: "",
    hint: "Radius 與模糊操作直接相關。"
  },
  {
    id: "sharpening_004",
    category: "sharpening",
    type: "single",
    difficulty: 1,
    question: "USM 中的 Amount 參數代表什麼？",
    options: ["模糊半徑大小", "銳化增益的倍率", "雜訊閾值", "邊緣偵測方向"],
    answer: 1,
    acceptAlso: [],
    explanation: "Amount（強度）控制銳化的增益倍率，即高頻細節被放大的程度。Amount 越大，邊緣對比度增強越明顯，但過高會產生光暈 (halo) 偽影。",
    imageDesc: "",
    scenario: "",
    hint: "Amount 直接影響銳化效果的「強弱」。"
  },
  {
    id: "sharpening_005",
    category: "sharpening",
    type: "truefalse",
    difficulty: 1,
    question: "Sobel 運算子是一種常用的邊緣偵測算子。",
    options: [],
    answer: true,
    acceptAlso: [],
    explanation: "Sobel 運算子是經典的一階微分邊緣偵測算子，使用 3×3 卷積核分別計算水平和垂直方向的梯度，常用於影像處理中的邊緣偵測。",
    imageDesc: "",
    scenario: "",
    hint: "Sobel 是影像處理教科書中最常見的算子之一。"
  },
  {
    id: "sharpening_006",
    category: "sharpening",
    type: "single",
    difficulty: 1,
    question: "以下哪個是 Laplacian 銳化的核心特性？",
    options: ["方向性邊緣偵測", "各向同性（isotropic）的二階微分運算", "僅適用於彩色影像", "不需要卷積運算"],
    answer: 1,
    acceptAlso: [],
    explanation: "Laplacian 是二階微分運算子，具有各向同性的特性，能同時偵測所有方向的邊緣。其卷積核的中心值為正（或負），周圍值之和與中心互為相反數。",
    imageDesc: "",
    scenario: "",
    hint: "Laplacian 不區分邊緣的方向。"
  },
  {
    id: "sharpening_007",
    category: "sharpening",
    type: "fillblank",
    difficulty: 1,
    question: "USM 的公式為 Sharpened = Original + _____ × (Original − Blurred)。",
    options: [],
    answer: "Amount",
    acceptAlso: ["amount", "Gain", "gain", "強度", "增益"],
    explanation: "USM 公式中的乘數即為 Amount（增益/強度），它控制高頻細節被放大的程度。Amount = 1 表示原始差值不縮放，Amount > 1 則額外放大。",
    imageDesc: "",
    scenario: "",
    hint: "這個參數控制銳化的「多寡」。"
  },
  {
    id: "sharpening_008",
    category: "sharpening",
    type: "single",
    difficulty: 1,
    question: "銳化過度最常見的偽影是什麼？",
    options: ["摩爾紋 (Moiré)", "光暈偽影 (Halo artifact)", "色偏 (Color cast)", "暗角 (Vignetting)"],
    answer: 1,
    acceptAlso: [],
    explanation: "過度銳化最典型的偽影是邊緣附近的明亮或暗色光暈 (halo)，這是因為邊緣對比度被過度增強，導致明顯的 overshoot 和 undershoot。",
    imageDesc: "",
    scenario: "",
    hint: "觀察過度銳化的照片邊緣，會看到亮邊或暗邊。"
  },
  {
    id: "sharpening_009",
    category: "sharpening",
    type: "truefalse",
    difficulty: 1,
    question: "High-pass filter 可以用來提取影像中的高頻細節，用於銳化。",
    options: [],
    answer: true,
    acceptAlso: [],
    explanation: "高通濾波器 (High-pass filter) 會濾除低頻成分，只保留高頻細節（邊緣、紋理等）。將提取的高頻分量加回原圖即可實現銳化效果。",
    imageDesc: "",
    scenario: "",
    hint: "高通 = 保留高頻、去除低頻。"
  },
  {
    id: "sharpening_010",
    category: "sharpening",
    type: "single",
    difficulty: 1,
    question: "USM 中的 Threshold 參數主要用於什麼目的？",
    options: ["增加銳化半徑", "避免平坦區域的雜訊被放大", "控制色彩飽和度", "限制輸出位元深度"],
    answer: 1,
    acceptAlso: [],
    explanation: "Threshold（閾值）設定一個最小差值門檻，只有當原圖與模糊版的差值超過此閾值時才進行銳化。這可以保護平坦區域不被雜訊放大。",
    imageDesc: "",
    scenario: "",
    hint: "平坦區域的微小差異通常是雜訊。"
  },
  {
    id: "sharpening_011",
    category: "sharpening",
    type: "single",
    difficulty: 1,
    question: "MTF 的全稱是什麼？",
    options: ["Modular Transfer Format", "Modulation Transfer Function", "Maximum Throughput Frequency", "Minimum Threshold Factor"],
    answer: 1,
    acceptAlso: [],
    explanation: "MTF（Modulation Transfer Function，調變傳遞函數）描述成像系統在不同空間頻率下保持對比度的能力。MTF 值從 1（完美保持）降到 0（完全丟失）。",
    imageDesc: "",
    scenario: "",
    hint: "這是衡量鏡頭與感測器解析力的重要指標。"
  },
  {
    id: "sharpening_012",
    category: "sharpening",
    type: "truefalse",
    difficulty: 1,
    question: "在 YUV 色彩空間中，通常只對 Y（亮度）通道做銳化。",
    options: [],
    answer: true,
    acceptAlso: [],
    explanation: "在 YUV 空間中，Y 通道包含亮度資訊（即人眼最敏感的細節），對 Y 通道銳化可以增強細節而不影響色彩。直接在 RGB 域銳化可能導致色彩偽影。",
    imageDesc: "",
    scenario: "",
    hint: "人眼對亮度變化比色彩變化更敏感。"
  },
  {
    id: "sharpening_013",
    category: "sharpening",
    type: "single",
    difficulty: 1,
    question: "以下哪個不是常見的邊緣偵測算子？",
    options: ["Sobel", "Prewitt", "Roberts", "Gaussian"],
    answer: 3,
    acceptAlso: [],
    explanation: "Gaussian（高斯）是平滑（低通）濾波器，不是邊緣偵測算子。Sobel、Prewitt、Roberts 都是經典的一階微分邊緣偵測算子。",
    imageDesc: "",
    scenario: "",
    hint: "其中一個是用來「模糊」而非「偵測邊緣」。"
  },
  {
    id: "sharpening_014",
    category: "sharpening",
    type: "fillblank",
    difficulty: 1,
    question: "Nyquist 頻率是取樣頻率的 _____ 倍。",
    options: [],
    answer: "1/2",
    acceptAlso: ["0.5", "二分之一", "一半", "half"],
    explanation: "根據 Nyquist-Shannon 取樣定理，Nyquist 頻率等於取樣頻率的 1/2。要完整重建信號，取樣頻率必須大於信號最高頻率的兩倍。",
    imageDesc: "",
    scenario: "",
    hint: "取樣定理要求取樣率至少是信號頻率的兩倍。"
  },
  {
    id: "sharpening_015",
    category: "sharpening",
    type: "single",
    difficulty: 1,
    question: "Anti-aliasing filter (OLPF) 在 ISP pipeline 中的作用是什麼？",
    options: ["增強銳度", "在感測器前過濾高於 Nyquist 頻率的成分以防止混疊", "增加色彩飽和度", "降低功耗"],
    answer: 1,
    acceptAlso: [],
    explanation: "Anti-aliasing filter（又稱 OLPF, Optical Low-Pass Filter）在感測器前方，用低通濾波衰減超過 Nyquist 頻率的空間頻率成分，防止產生混疊偽影 (aliasing)。",
    imageDesc: "",
    scenario: "",
    hint: "Aliasing 是因取樣不足導致的偽影。"
  },
  {
    id: "sharpening_016",
    category: "sharpening",
    type: "truefalse",
    difficulty: 1,
    question: "Overshoot 是指銳化後邊緣亮側出現比原始值更高的亮度值。",
    options: [],
    answer: true,
    acceptAlso: [],
    explanation: "Overshoot（過衝）發生在銳化後的邊緣亮側，其亮度超出原始值。相對地，Undershoot（下衝）發生在暗側，亮度低於原始值。兩者共同形成光暈偽影。",
    imageDesc: "",
    scenario: "",
    hint: "Over = 超過，shoot = 射出。"
  },
  {
    id: "sharpening_017",
    category: "sharpening",
    type: "single",
    difficulty: 1,
    question: "Canny 邊緣偵測器的第一步是什麼？",
    options: ["非極大值抑制", "高斯模糊去除雜訊", "雙閾值處理", "計算梯度方向"],
    answer: 1,
    acceptAlso: [],
    explanation: "Canny 邊緣偵測的步驟依序為：(1) 高斯模糊平滑以去除雜訊、(2) 計算梯度大小與方向、(3) 非極大值抑制、(4) 雙閾值處理與邊緣追蹤。",
    imageDesc: "",
    scenario: "",
    hint: "偵測邊緣前需先降低雜訊的干擾。"
  },
  {
    id: "sharpening_018",
    category: "sharpening",
    type: "single",
    difficulty: 1,
    question: "Clarity（清晰度）調整主要增強的是哪個頻率範圍？",
    options: ["最高頻率的極細紋理", "中頻 (mid-tone contrast / mid-frequency)", "最低頻率的整體亮度", "僅色彩頻率"],
    answer: 1,
    acceptAlso: [],
    explanation: "Clarity 調整主要增強中頻範圍的對比度（mid-frequency contrast），也稱為 micro-contrast。它不像銳化那樣專注於極高頻邊緣，而是增強中等尺度的細節立體感。",
    imageDesc: "",
    scenario: "",
    hint: "Clarity 讓影像看起來更有「立體感」。"
  },
  {
    id: "sharpening_019",
    category: "sharpening",
    type: "truefalse",
    difficulty: 1,
    question: "銳化會同時放大影像中的雜訊。",
    options: [],
    answer: true,
    acceptAlso: [],
    explanation: "銳化是增強高頻成分，而雜訊也屬於高頻信號。因此銳化會不可避免地放大雜訊，這就是為什麼銳化通常在降噪之後執行，且需要 threshold 機制來保護。",
    imageDesc: "",
    scenario: "",
    hint: "雜訊和細節都是高頻成分。"
  },
  {
    id: "sharpening_020",
    category: "sharpening",
    type: "single",
    difficulty: 1,
    question: "SFR 的全稱是什麼？",
    options: ["Spatial Frequency Response", "Signal Filtering Ratio", "Sharpening Factor Range", "Standard Focus Region"],
    answer: 0,
    acceptAlso: [],
    explanation: "SFR（Spatial Frequency Response，空間頻率響應）是量測影像系統在不同空間頻率下的對比度保持能力，與 MTF 概念密切相關，常用於數位相機的銳度評估。",
    imageDesc: "",
    scenario: "",
    hint: "SFR 與 MTF 都用來衡量系統的空間頻率特性。"
  },
  {
    id: "sharpening_021",
    category: "sharpening",
    type: "single",
    difficulty: 1,
    question: "Roberts Cross 運算子使用多大的卷積核？",
    options: ["2×2", "3×3", "5×5", "7×7"],
    answer: 0,
    acceptAlso: [],
    explanation: "Roberts Cross 是最簡單的邊緣偵測算子之一，使用兩個 2×2 的對角線卷積核來計算梯度。它計算簡單但對雜訊較敏感。",
    imageDesc: "",
    scenario: "",
    hint: "Roberts Cross 是最小尺寸的邊緣偵測核。"
  },
  {
    id: "sharpening_022",
    category: "sharpening",
    type: "truefalse",
    difficulty: 1,
    question: "Prewitt 運算子與 Sobel 運算子使用相同大小（3×3）的卷積核。",
    options: [],
    answer: true,
    acceptAlso: [],
    explanation: "Prewitt 和 Sobel 都使用 3×3 卷積核。差異在於 Sobel 對中心行/列賦予更大的權重（加權平均），而 Prewitt 使用均勻權重。Sobel 因此對雜訊有更好的抑制效果。",
    imageDesc: "",
    scenario: "",
    hint: "兩者都是 3×3 一階微分算子。"
  },
  {
    id: "sharpening_023",
    category: "sharpening",
    type: "fillblank",
    difficulty: 1,
    question: "LoG 邊緣偵測器的全稱是 Laplacian of _____。",
    options: [],
    answer: "Gaussian",
    acceptAlso: ["gaussian", "高斯"],
    explanation: "LoG（Laplacian of Gaussian）先用高斯濾波器平滑影像以減少雜訊，再用 Laplacian 算子偵測邊緣。結合兩步驟可以得到更穩定的邊緣偵測結果。",
    imageDesc: "",
    scenario: "",
    hint: "先做 G_____ 模糊，再做 Laplacian。"
  },
  {
    id: "sharpening_024",
    category: "sharpening",
    type: "single",
    difficulty: 1,
    question: "在 ISP pipeline 中，銳化通常在以下哪個步驟之後執行？",
    options: ["類比數位轉換 (ADC)", "降噪 (Noise Reduction)", "自動曝光 (AE)", "黑電位校正 (BLC)"],
    answer: 1,
    acceptAlso: [],
    explanation: "銳化通常在降噪之後執行。如果先銳化再降噪，銳化會放大雜訊，而降噪又會模糊掉銳化的效果。先降噪再銳化是更合理的順序。",
    imageDesc: "",
    scenario: "",
    hint: "先清理雜訊，再強化細節。"
  },
  {
    id: "sharpening_025",
    category: "sharpening",
    type: "truefalse",
    difficulty: 1,
    question: "DoG（Difference of Gaussians）可以近似 LoG 運算。",
    options: [],
    answer: true,
    acceptAlso: [],
    explanation: "DoG 使用兩個不同 σ 值的高斯模糊結果相減，在數學上可以近似 LoG（Laplacian of Gaussian）的效果，且計算成本更低。",
    imageDesc: "",
    scenario: "",
    hint: "兩個高斯的差值可以近似某種二階微分。"
  },
  {
    id: "sharpening_026",
    category: "sharpening",
    type: "single",
    difficulty: 1,
    question: "以下何者最適合描述 Micro-contrast enhancement？",
    options: ["全局亮度增加", "局部小尺度的對比度增強", "僅對色相通道操作", "減少影像解析度"],
    answer: 1,
    acceptAlso: [],
    explanation: "Micro-contrast enhancement（微對比度增強）指的是增強影像中局部小尺度範圍的對比度，讓紋理和細節看起來更清晰、更有立體感，而不是改變全局亮度。",
    imageDesc: "",
    scenario: "",
    hint: "Micro = 微小、局部。"
  },
  {
    id: "sharpening_027",
    category: "sharpening",
    type: "single",
    difficulty: 1,
    question: "Ringing artifact（振鈴偽影）通常發生在影像的什麼位置？",
    options: ["平坦區域中央", "銳利邊緣附近", "影像四角", "天空區域"],
    answer: 1,
    acceptAlso: [],
    explanation: "Ringing artifact 是一種在銳利邊緣附近出現的波紋狀偽影，通常由濾波器的 Gibbs 現象引起。在過度銳化或不當的頻率域處理後特別明顯。",
    imageDesc: "",
    scenario: "",
    hint: "如同音叉的振動，在邊緣附近「迴盪」。"
  },
  {
    id: "sharpening_028",
    category: "sharpening",
    type: "scenario",
    difficulty: 1,
    question: "你拍了一張風景照，發現整體細節看起來有些模糊，但雜訊不明顯。你應該如何調整 USM 參數？",
    options: ["Radius 大、Amount 大、Threshold 大", "Radius 中等、Amount 適中、Threshold 低", "Radius 極小、Amount 極大、Threshold 極大", "不需要任何銳化"],
    answer: 1,
    acceptAlso: [],
    explanation: "風景照細節豐富但模糊，可用中等 Radius 涵蓋各種邊緣尺度，適中的 Amount 避免光暈，低 Threshold 因為雜訊不明顯所以不需要高閾值保護。",
    imageDesc: "",
    scenario: "使用者拍攝了一張風景照片，整體稍微失焦但雜訊水平很低，需要適當的銳化設定。",
    hint: "雜訊低 = Threshold 可以設低。"
  },
  {
    id: "sharpening_029",
    category: "sharpening",
    type: "truefalse",
    difficulty: 1,
    question: "Laplacian 銳化的卷積核中，所有元素之和等於零。",
    options: [],
    answer: true,
    acceptAlso: [],
    explanation: "標準 Laplacian 核（如 [0,-1,0; -1,4,-1; 0,-1,0]）所有元素之和為 0。這確保在平坦區域（所有像素值相同）輸出為零，只在有變化的區域產生非零響應。",
    imageDesc: "",
    scenario: "",
    hint: "在均勻區域，Laplacian 的輸出應為零。"
  },
  {
    id: "sharpening_030",
    category: "sharpening",
    type: "single",
    difficulty: 1,
    question: "在頻率域中，銳化等同於什麼操作？",
    options: ["衰減高頻成分", "增強高頻成分", "僅保留直流分量", "消除所有低頻成分"],
    answer: 1,
    acceptAlso: [],
    explanation: "銳化在頻率域中等同於增強（放大）高頻成分。高頻對應影像中的邊緣和細節，增強它們就能讓影像看起來更銳利。",
    imageDesc: "",
    scenario: "",
    hint: "銳利 = 高頻。"
  },
  {
    id: "sharpening_031",
    category: "sharpening",
    type: "fillblank",
    difficulty: 1,
    question: "Overshoot 出現在邊緣的 _____ 側，Undershoot 出現在邊緣的暗側。",
    options: [],
    answer: "亮",
    acceptAlso: ["bright", "明亮", "亮側", "light"],
    explanation: "銳化增強邊緣對比度時，亮側被推得更亮（overshoot），暗側被推得更暗（undershoot）。這種不對稱增強在過度時形成可見的光暈。",
    imageDesc: "",
    scenario: "",
    hint: "Over = 超過原來的值，在邊緣哪一側會更亮？"
  },
  {
    id: "sharpening_032",
    category: "sharpening",
    type: "single",
    difficulty: 1,
    question: "為什麼在 RGB 域直接銳化可能產生色彩偽影？",
    options: ["RGB 沒有高頻資訊", "各通道獨立銳化可能改變通道間的比例，造成色偏", "RGB 銳化的計算量太大", "RGB 不支持卷積運算"],
    answer: 1,
    acceptAlso: [],
    explanation: "在 RGB 域獨立銳化每個通道時，各通道的增強量可能不同，導致通道間比例變化，在邊緣處產生不自然的彩色偽影。在 YUV 域只銳化 Y 通道可避免此問題。",
    imageDesc: "",
    scenario: "",
    hint: "三個通道各自增強，顏色的平衡可能被破壞。"
  },
  {
    id: "sharpening_033",
    category: "sharpening",
    type: "truefalse",
    difficulty: 1,
    question: "Texture enhancement（紋理增強）與 edge enhancement（邊緣增強）針對完全相同的空間頻率範圍。",
    options: [],
    answer: false,
    acceptAlso: [],
    explanation: "紋理增強通常針對較高頻的細微重複性紋理，而邊緣增強針對中高頻的顯著亮度跳變。兩者有重疊但目標頻率範圍不完全相同，在 ISP 中常分開處理。",
    imageDesc: "",
    scenario: "",
    hint: "紋理是細密的重複模式，邊緣是突然的變化。"
  },
  // ===== DIFFICULTY 2 (questions 034–066) =====
  {
    id: "sharpening_034",
    category: "sharpening",
    type: "single",
    difficulty: 2,
    question: "Coring technique 在銳化中的主要功能是什麼？",
    options: ["增加銳化半徑", "抑制小幅度的高頻成分以避免雜訊放大", "將影像轉換到頻率域", "自動偵測邊緣方向"],
    answer: 1,
    acceptAlso: [],
    explanation: "Coring（去核）技術會將幅度低於某閾值的高頻成分歸零或衰減，因為小幅度的高頻成分通常是雜訊。只有幅度較大的高頻（真實邊緣）才會被增強。",
    imageDesc: "",
    scenario: "",
    hint: "像蘋果去核一樣，去掉中心（小幅度）的部分。"
  },
  {
    id: "sharpening_035",
    category: "sharpening",
    type: "single",
    difficulty: 2,
    question: "Soft coring 與 Hard coring 的主要差異是什麼？",
    options: ["Soft coring 使用更大的卷積核", "Soft coring 在閾值附近平滑漸變，Hard coring 則在閾值處突然截斷", "Hard coring 不能用於銳化", "兩者完全相同，只是名稱不同"],
    answer: 1,
    acceptAlso: [],
    explanation: "Hard coring 在閾值處做硬截斷（小於閾值的直接歸零），可能造成不自然的過渡。Soft coring 使用平滑的非線性函數，在閾值附近漸進衰減，過渡更自然。",
    imageDesc: "",
    scenario: "",
    hint: "Soft = 柔和的過渡，Hard = 硬切。"
  },
  {
    id: "sharpening_036",
    category: "sharpening",
    type: "multiple",
    difficulty: 2,
    question: "以下哪些是 Wiener deconvolution 銳化的特點？（選擇所有正確答案）",
    options: ["需要估計 PSF（Point Spread Function）", "完全不受雜訊影響", "在頻率域中運算", "是一種非線性濾波器"],
    answer: [0, 2],
    acceptAlso: [],
    explanation: "Wiener deconvolution 需要已知或估計的 PSF，並在頻率域中透過最小化均方誤差來反卷積。它考慮了雜訊功率譜，但並非「不受雜訊影響」。它是線性濾波器。",
    imageDesc: "",
    scenario: "",
    hint: "Wiener 濾波是一種頻率域的線性方法。"
  },
  {
    id: "sharpening_037",
    category: "sharpening",
    type: "single",
    difficulty: 2,
    question: "Richardson-Lucy deconvolution 演算法的核心特性是什麼？",
    options: ["單次計算即可完成", "基於最大似然估計的迭代式方法", "僅適用於一維信號", "不需要 PSF 資訊"],
    answer: 1,
    acceptAlso: [],
    explanation: "Richardson-Lucy 是基於貝葉斯統計與最大似然估計的迭代式反卷積方法。它假設雜訊服從 Poisson 分佈，透過多次迭代逐步逼近原始影像，但過多迭代會放大雜訊。",
    imageDesc: "",
    scenario: "",
    hint: "這是一種需要「反覆計算」的方法。"
  },
  {
    id: "sharpening_038",
    category: "sharpening",
    type: "ordering",
    difficulty: 2,
    question: "請排列 Canny 邊緣偵測器的四個步驟的正確執行順序：",
    options: [],
    answer: 0,
    acceptAlso: [],
    explanation: "Canny 的四個步驟依序為：(1) 高斯模糊降噪 → (2) 計算梯度大小與方向 → (3) 非極大值抑制使邊緣變細 → (4) 雙閾值處理與邊緣連接追蹤。",
    imageDesc: "",
    scenario: "",
    hint: "先處理雜訊，最後處理邊緣的連續性。",
    items: ["高斯模糊降噪", "計算梯度大小與方向", "非極大值抑制 (NMS)", "雙閾值處理與邊緣追蹤"]
  },
  {
    id: "sharpening_039",
    category: "sharpening",
    type: "single",
    difficulty: 2,
    question: "Bandpass sharpening 的原理是什麼？",
    options: ["僅增強特定頻率範圍內的成分", "增強所有頻率成分", "只保留直流分量", "使用單一固定頻率的正弦波"],
    answer: 0,
    acceptAlso: [],
    explanation: "Bandpass sharpening 使用帶通濾波器提取特定頻率範圍的成分，然後將這些成分放大後加回原圖。這樣可以針對性地增強特定尺度的細節，避免增強不需要的頻率。",
    imageDesc: "",
    scenario: "",
    hint: "Bandpass = 帶通 = 只通過某個「頻帶」。"
  },
  {
    id: "sharpening_040",
    category: "sharpening",
    type: "multiple",
    difficulty: 2,
    question: "Adaptive sharpening（自適應銳化）可能根據以下哪些因素調整銳化強度？（選擇所有正確答案）",
    options: ["局部邊緣強度", "局部雜訊水平", "固定常數（所有區域相同）", "紋理複雜度"],
    answer: [0, 1, 3],
    acceptAlso: [],
    explanation: "自適應銳化根據影像局部特性動態調整參數：邊緣強區域加強銳化，雜訊高區域降低銳化，紋理豐富區域適度增強。它不使用固定常數，這正是其「自適應」的含義。",
    imageDesc: "",
    scenario: "",
    hint: "「自適應」意味著會根據環境條件改變行為。"
  },
  {
    id: "sharpening_041",
    category: "sharpening",
    type: "single",
    difficulty: 2,
    question: "Multi-scale sharpening 相比單一尺度銳化的主要優勢是什麼？",
    options: ["計算速度更快", "可以同時增強不同大小的細節", "完全不產生光暈偽影", "不需要任何參數調整"],
    answer: 1,
    acceptAlso: [],
    explanation: "Multi-scale sharpening 在多個空間尺度上分別提取並增強細節，可以同時銳化精細紋理（小尺度）和較大邊緣（大尺度），比單一 Radius 的銳化更全面。",
    imageDesc: "",
    scenario: "",
    hint: "Multi-scale = 多尺度，不同大小的細節。"
  },
  {
    id: "sharpening_042",
    category: "sharpening",
    type: "scenario",
    difficulty: 2,
    question: "你正在處理一張高 ISO 夜景照片，影像有明顯雜訊但也需要銳化。如何設定 USM 參數？",
    options: ["Radius 大、Amount 大、Threshold 低", "Radius 小、Amount 低、Threshold 高", "Radius 大、Amount 大、Threshold 低", "不用 USM，直接用 Laplacian"],
    answer: 1,
    acceptAlso: [],
    explanation: "高 ISO 影像雜訊明顯，應使用小 Radius 避免光暈過大、低 Amount 避免過度銳化放大雜訊、高 Threshold 保護平坦區域不被雜訊影響。這是一個保守但安全的設定。",
    imageDesc: "",
    scenario: "攝影師在 ISO 6400 下拍攝夜景，照片有可見的亮度雜訊，但希望保持建築物的邊緣清晰。",
    hint: "高雜訊環境需要高 Threshold 來保護。"
  },
  {
    id: "sharpening_043",
    category: "sharpening",
    type: "fillblank",
    difficulty: 2,
    question: "Wiener filter 的頻率域公式中，分母包含 PSF 的功率譜加上 _____ 比。",
    options: [],
    answer: "雜訊與信號功率譜",
    acceptAlso: ["NSR", "noise-to-signal ratio", "N/S ratio", "雜訊功率譜比信號功率譜", "noise to signal power spectrum ratio"],
    explanation: "Wiener filter: H_w(f) = H*(f) / (|H(f)|² + NSR)，其中 NSR 為雜訊功率譜與信號功率譜的比值 (Noise-to-Signal Ratio)。NSR 越大表示雜訊越強，濾波器越保守。",
    imageDesc: "",
    scenario: "",
    hint: "Wiener 濾波在去模糊與抑制雜訊之間取得平衡。"
  },
  {
    id: "sharpening_044",
    category: "sharpening",
    type: "single",
    difficulty: 2,
    question: "High-pass filter 可以用以下哪種方式在空間域實現？",
    options: ["Original − Low-pass filtered", "Low-pass filtered × 2", "Original + Low-pass filtered", "Original ÷ Low-pass filtered"],
    answer: 0,
    acceptAlso: [],
    explanation: "高通濾波 = 原圖減去低通濾波結果。因為原圖 = 低頻 + 高頻，減去低頻部分（低通結果）就得到高頻部分（高通結果）。",
    imageDesc: "",
    scenario: "",
    hint: "全部 − 低頻 = 高頻。"
  },
  {
    id: "sharpening_045",
    category: "sharpening",
    type: "truefalse",
    difficulty: 2,
    question: "Negative feedback sharpening 使用負回饋機制來抑制銳化過度的問題。",
    options: [],
    answer: true,
    acceptAlso: [],
    explanation: "Negative feedback sharpening（負回饋銳化）透過回饋迴路限制銳化增益，當銳化量過大時負回饋會自動降低增益，防止 overshoot 和 halo 偽影變得過於明顯。",
    imageDesc: "",
    scenario: "",
    hint: "負回饋系統會自我調節，避免失控。"
  },
  {
    id: "sharpening_046",
    category: "sharpening",
    type: "image",
    difficulty: 2,
    question: "觀察下列 Laplacian 3×3 卷積核，這個核的類型是什麼？\n\n核矩陣：\n  0  -1   0\n -1   4  -1\n  0  -1   0",
    options: ["4-connectivity Laplacian", "8-connectivity Laplacian", "Sobel 水平核", "Gaussian 平滑核"],
    answer: 0,
    acceptAlso: [],
    explanation: "此核只考慮上下左右 4 個鄰居（4-connectivity），中心值為 4。8-connectivity Laplacian 則考慮所有 8 個鄰居，核為 [-1,-1,-1; -1,8,-1; -1,-1,-1]，中心值為 8。",
    imageDesc: "顯示一個 3×3 的 Laplacian 卷積核矩陣，中心值為 4，上下左右為 -1，對角為 0。",
    scenario: "",
    hint: "計算非零的非中心元素個數。"
  },
  {
    id: "sharpening_047",
    category: "sharpening",
    type: "single",
    difficulty: 2,
    question: "MTF50 代表什麼含義？",
    options: ["MTF 值降到 50% 時對應的空間頻率", "50 個像素寬的 MTF", "MTF 的第 50 階諧波", "在 50mm 焦距下的 MTF"],
    answer: 0,
    acceptAlso: [],
    explanation: "MTF50 是 MTF 曲線降到 50%（即對比度保持 50%）時對應的空間頻率（line pairs/mm 或 cycles/pixel）。它是衡量影像銳度的重要指標，數值越高越銳利。",
    imageDesc: "",
    scenario: "",
    hint: "50 指的是 MTF 值的百分比。"
  },
  {
    id: "sharpening_048",
    category: "sharpening",
    type: "multiple",
    difficulty: 2,
    question: "以下哪些因素會降低影像系統的 MTF？（選擇所有正確答案）",
    options: ["鏡頭像差 (Lens aberration)", "感測器像素填充率", "Anti-aliasing filter", "增加曝光時間（無運動模糊時）"],
    answer: [0, 2],
    acceptAlso: [],
    explanation: "鏡頭像差會降低光學 MTF，Anti-aliasing filter 刻意衰減高頻以防止混疊，也會降低 MTF。像素填充率主要影響靈敏度。在無運動模糊時，增加曝光時間不影響 MTF。",
    imageDesc: "",
    scenario: "",
    hint: "哪些因素會讓影像「變模糊」？"
  },
  {
    id: "sharpening_049",
    category: "sharpening",
    type: "single",
    difficulty: 2,
    question: "Sobel 水平方向邊緣偵測核的正確矩陣是？",
    options: [
      "[[-1,0,1],[-2,0,2],[-1,0,1]]",
      "[[-1,-2,-1],[0,0,0],[1,2,1]]",
      "[[1,1,1],[0,0,0],[-1,-1,-1]]",
      "[[0,1,0],[1,-4,1],[0,1,0]]"
    ],
    answer: 0,
    acceptAlso: [],
    explanation: "Sobel Gx（水平梯度/垂直邊緣偵測）核為 [[-1,0,1],[-2,0,2],[-1,0,1]]，偵測水平方向的亮度變化（即垂直邊緣）。Gy 核為 [[-1,-2,-1],[0,0,0],[1,2,1]]。",
    imageDesc: "",
    scenario: "",
    hint: "注意：Gx 偵測的是 x 方向的梯度變化。"
  },
  {
    id: "sharpening_050",
    category: "sharpening",
    type: "scenario",
    difficulty: 2,
    question: "你在檢查手機 ISP 的銳化模組，發現人物膚色區域出現不自然的色彩斑點。最可能的原因是什麼？",
    options: ["銳化只對亮度通道操作", "在 RGB 域做銳化導致色彩偽影", "使用了 YUV 轉換", "Threshold 設定太高"],
    answer: 1,
    acceptAlso: [],
    explanation: "RGB 域銳化會獨立增強各色彩通道，在膚色等柔和漸變區域容易產生色彩不一致的斑點。解決方案是改在 YUV 域只銳化 Y（亮度）通道。",
    imageDesc: "",
    scenario: "手機攝影團隊回報，拍攝人像時膚色區域偶爾出現彩色雜點，特別是在皮膚與頭髮的交界處。",
    hint: "色彩偽影通常與在哪個色彩空間做銳化有關。"
  },
  {
    id: "sharpening_051",
    category: "sharpening",
    type: "single",
    difficulty: 2,
    question: "Deconvolution sharpening 與 USM 的根本差異是什麼？",
    options: ["USM 計算更慢", "Deconvolution 試圖反轉已知的模糊過程，USM 只是簡單地增強高頻", "USM 使用頻率域，Deconvolution 只用空間域", "兩者完全等價"],
    answer: 1,
    acceptAlso: [],
    explanation: "Deconvolution 銳化基於光學系統的 PSF 模型，試圖數學上反轉模糊過程以恢復原始影像。USM 則不考慮模糊的物理模型，只是經驗性地增強高頻成分。",
    imageDesc: "",
    scenario: "",
    hint: "Deconvolution = 反卷積 = 反轉模糊過程。"
  },
  {
    id: "sharpening_052",
    category: "sharpening",
    type: "truefalse",
    difficulty: 2,
    question: "增大 USM 的 Radius 會使 Halo（光暈）偽影變得更寬。",
    options: [],
    answer: true,
    acceptAlso: [],
    explanation: "Radius 決定高斯模糊核的大小，也就決定了銳化影響的範圍。較大的 Radius 意味著邊緣兩側更大範圍的像素被影響，因此光暈偽影也會更寬更明顯。",
    imageDesc: "",
    scenario: "",
    hint: "模糊範圍越大，銳化的影響範圍也越大。"
  },
  {
    id: "sharpening_053",
    category: "sharpening",
    type: "fillblank",
    difficulty: 2,
    question: "Canny 邊緣偵測器使用 _____ 閾值法來決定最終的邊緣像素。",
    options: [],
    answer: "雙",
    acceptAlso: ["double", "dual", "two", "hysteresis", "遲滯", "雙閾值"],
    explanation: "Canny 使用雙閾值（hysteresis thresholding）：高閾值以上的梯度一定是邊緣，低閾值以下一定不是，介於兩者之間的只有連接到強邊緣時才保留。",
    imageDesc: "",
    scenario: "",
    hint: "有一個「高」閾值和一個「低」閾值。"
  },
  {
    id: "sharpening_054",
    category: "sharpening",
    type: "single",
    difficulty: 2,
    question: "在 Multi-scale sharpening 中，通常使用什麼方法來分解影像？",
    options: ["直方圖均衡化", "Laplacian 金字塔 (Laplacian Pyramid)", "色彩空間轉換", "二值化處理"],
    answer: 1,
    acceptAlso: [],
    explanation: "Laplacian 金字塔將影像分解為不同尺度的細節層（頻帶），每層對應特定的空間頻率範圍。可以對各層獨立調整增益，再重建回最終影像，實現多尺度銳化。",
    imageDesc: "",
    scenario: "",
    hint: "金字塔結構可以分離不同尺度的資訊。"
  },
  {
    id: "sharpening_055",
    category: "sharpening",
    type: "single",
    difficulty: 2,
    question: "為什麼過多的 Richardson-Lucy 迭代會導致問題？",
    options: ["計算結果會收斂到零", "雜訊會被逐漸放大，產生 noise amplification", "影像會持續模糊", "記憶體會歸零"],
    answer: 1,
    acceptAlso: [],
    explanation: "Richardson-Lucy 演算法在迭代初期有效恢復細節，但過多迭代會開始擬合雜訊（overfitting），導致雜訊被放大並出現顆粒狀偽影。需要適時停止迭代（early stopping）。",
    imageDesc: "",
    scenario: "",
    hint: "過度擬合雜訊是迭代方法的常見問題。"
  },
  {
    id: "sharpening_056",
    category: "sharpening",
    type: "multiple",
    difficulty: 2,
    question: "以下哪些屬於 deconvolution sharpening 的方法？（選擇所有正確答案）",
    options: ["Wiener filter", "Richardson-Lucy algorithm", "Unsharp Mask", "Constrained least-squares filter"],
    answer: [0, 1, 3],
    acceptAlso: [],
    explanation: "Wiener filter、Richardson-Lucy、Constrained least-squares filter 都是反卷積方法，試圖根據 PSF 模型反轉模糊。USM 不是反卷積方法，它只是經驗性的高頻增強。",
    imageDesc: "",
    scenario: "",
    hint: "哪些方法需要 PSF 資訊？"
  },
  {
    id: "sharpening_057",
    category: "sharpening",
    type: "truefalse",
    difficulty: 2,
    question: "在 Laplacian 金字塔中，最底層（最大解析度層）包含最精細的高頻細節。",
    options: [],
    answer: true,
    acceptAlso: [],
    explanation: "Laplacian 金字塔的底層對應最高空間頻率（最精細的細節），越往上層空間頻率越低、解析度越小。頂層通常是低解析度的殘餘影像（低頻基底）。",
    imageDesc: "",
    scenario: "",
    hint: "底層 = 最大解析度 = 最高頻率。"
  },
  {
    id: "sharpening_058",
    category: "sharpening",
    type: "image",
    difficulty: 2,
    question: "觀察以下 USM 銳化前後的 1D 邊緣剖面圖描述：\n原始邊緣：由暗（值 50）平滑過渡到亮（值 200）\n銳化後：暗側在邊緣附近下降到 30，亮側在邊緣附近上升到 220\n\n值 30 和 220 分別代表什麼現象？",
    options: ["雜訊與訊號", "Undershoot 與 Overshoot", "低頻與高頻", "黑電位與白電位"],
    answer: 1,
    acceptAlso: [],
    explanation: "暗側低於原始值（50→30）是 undershoot，亮側高於原始值（200→220）是 overshoot。兩者都是銳化增強邊緣對比度的副產品，過度時形成可見的光暈。",
    imageDesc: "一維邊緣剖面圖，顯示原始平滑過渡邊緣（50→200）與銳化後帶有 undershoot（30）和 overshoot（220）的邊緣對比。",
    scenario: "",
    hint: "觀察哪裡的值超過了原始範圍。"
  },
  {
    id: "sharpening_059",
    category: "sharpening",
    type: "single",
    difficulty: 2,
    question: "Content-aware adaptive sharpening 中，如何區分平坦區域與紋理區域？",
    options: ["比較 RGB 三通道的差異", "分析局部方差或梯度統計量", "使用固定閾值", "比較連續兩幀的差異"],
    answer: 1,
    acceptAlso: [],
    explanation: "Content-aware 銳化通常計算局部區域的方差、梯度大小或紋理能量等統計量。高方差/梯度表示紋理或邊緣區域，低方差表示平坦區域，據此調整銳化強度。",
    imageDesc: "",
    scenario: "",
    hint: "方差高 = 變化大 = 有紋理。"
  },
  {
    id: "sharpening_060",
    category: "sharpening",
    type: "ordering",
    difficulty: 2,
    question: "在典型的 ISP pipeline 中，請按正確順序排列以下處理步驟：",
    options: [],
    answer: 0,
    acceptAlso: [],
    explanation: "ISP 典型順序：BLC 校正黑電位 → Demosaic 從 Bayer 重建彩色影像 → Denoise 去除雜訊 → Sharpening 增強細節。銳化必須在降噪之後以避免放大雜訊。",
    imageDesc: "",
    scenario: "",
    hint: "銳化是 pipeline 中較後期的步驟。",
    items: ["Black Level Correction (BLC)", "Demosaic", "Noise Reduction", "Sharpening"]
  },
  {
    id: "sharpening_061",
    category: "sharpening",
    type: "single",
    difficulty: 2,
    question: "OLPF（Optical Low-Pass Filter）與銳化之間的關係是什麼？",
    options: ["兩者功能完全相同", "OLPF 消除混疊但會降低銳度，後續需要銳化來補償", "銳化可以完全取代 OLPF", "OLPF 會自動增強銳度"],
    answer: 1,
    acceptAlso: [],
    explanation: "OLPF 在感測器前衰減高頻以防止混疊，但副作用是降低了影像的整體銳度。ISP 的銳化模組需要補償 OLPF 造成的銳度損失，同時避免引入新的偽影。",
    imageDesc: "",
    scenario: "",
    hint: "OLPF 降低銳度以換取抗混疊，是一種取捨。"
  },
  {
    id: "sharpening_062",
    category: "sharpening",
    type: "truefalse",
    difficulty: 2,
    question: "Sobel 算子的卷積核對中心行/列賦予的權重比 Prewitt 算子更大。",
    options: [],
    answer: true,
    acceptAlso: [],
    explanation: "Sobel Gx 核 [[-1,0,1],[-2,0,2],[-1,0,1]] 中心行權重為 2，而 Prewitt Gx 核 [[-1,0,1],[-1,0,1],[-1,0,1]] 所有行權重相同為 1。Sobel 的加權提供了更好的雜訊抑制。",
    imageDesc: "",
    scenario: "",
    hint: "比較兩者核矩陣中非零元素的數值。"
  },
  {
    id: "sharpening_063",
    category: "sharpening",
    type: "scenario",
    difficulty: 2,
    question: "你正在設計車載鏡頭的 ISP，需要在保證低延遲的同時對影像銳化。以下哪個方法最適合？",
    options: ["Richardson-Lucy 迭代 50 次", "固定 3×3 Laplacian 核搭配 Coring", "多次 Wiener deconvolution", "大 Radius 的 USM"],
    answer: 1,
    acceptAlso: [],
    explanation: "車載 ISP 對即時性要求極高，固定 3×3 Laplacian 核計算量最小且可硬體實現，搭配 coring 技術抑制雜訊。迭代方法和大 Radius 的計算量太大，不適合即時處理。",
    imageDesc: "",
    scenario: "車載攝影系統需要在 30fps 的嚴格延遲要求下完成影像銳化，且硬體資源有限。",
    hint: "車載系統需要簡單高效的演算法。"
  },
  {
    id: "sharpening_064",
    category: "sharpening",
    type: "fillblank",
    difficulty: 2,
    question: "Non-maximum suppression（非極大值抑制）在 Canny 邊緣偵測中的作用是將邊緣細化為 _____ 像素寬。",
    options: [],
    answer: "1",
    acceptAlso: ["一", "one", "單", "單一"],
    explanation: "非極大值抑制沿梯度方向比較每個像素的梯度值，只保留局部極大值的像素，從而將模糊的粗邊緣細化為單像素寬的精確邊緣線。",
    imageDesc: "",
    scenario: "",
    hint: "最終邊緣應該是最細的線。"
  },
  {
    id: "sharpening_065",
    category: "sharpening",
    type: "single",
    difficulty: 2,
    question: "在 USM 中，如果 Amount = 0 會發生什麼？",
    options: ["影像變得極度銳利", "輸出等於原始影像，無銳化效果", "影像變成模糊版本", "只輸出高頻成分"],
    answer: 1,
    acceptAlso: [],
    explanation: "USM 公式：Sharpened = Original + Amount × (Original − Blurred)。當 Amount = 0 時，加入的高頻成分為零，輸出 = Original，即沒有任何銳化效果。",
    imageDesc: "",
    scenario: "",
    hint: "代入 Amount = 0 到公式中。"
  },
  {
    id: "sharpening_066",
    category: "sharpening",
    type: "truefalse",
    difficulty: 2,
    question: "DoG（Difference of Gaussians）中兩個高斯核的 σ 值相差越大，提取的頻帶越寬。",
    options: [],
    answer: true,
    acceptAlso: [],
    explanation: "DoG 等效為一個帶通濾波器，其中心頻率和帶寬取決於兩個 σ 值。σ 差距越大，通過的頻帶越寬；σ 差距越小，帶通越窄，更精確地選取特定頻率。",
    imageDesc: "",
    scenario: "",
    hint: "兩個高斯之差形成的帶通範圍取決於 σ 的差距。"
  },
  // ===== DIFFICULTY 3 (questions 067–100) =====
  {
    id: "sharpening_067",
    category: "sharpening",
    type: "single",
    difficulty: 3,
    question: "Wiener deconvolution filter 在 PSF 的頻率響應接近零的頻率處會出現什麼問題？",
    options: ["輸出為零", "雜訊被極度放大（noise amplification）", "計算結果為負數", "自動跳過該頻率"],
    answer: 1,
    acceptAlso: [],
    explanation: "在 PSF 頻率響應（OTF）接近零的頻率處，逆濾波需要除以極小值，導致雜訊被極度放大。Wiener filter 透過加入 NSR 項來正規化，但在這些頻率處仍然需要謹慎。",
    imageDesc: "",
    scenario: "",
    hint: "數學上除以接近零的數會得到很大的結果。"
  },
  {
    id: "sharpening_068",
    category: "sharpening",
    type: "multiple",
    difficulty: 3,
    question: "以下哪些方法可以抑制銳化過程中的 halo artifact？（選擇所有正確答案）",
    options: ["使用 coring technique", "限制 overshoot/undershoot 的最大值 (clipping)", "使用 edge-aware 銳化避免跨邊緣擴散", "增加銳化的 Amount 參數"],
    answer: [0, 1, 2],
    acceptAlso: [],
    explanation: "Coring 抑制小幅度雜訊、Clipping 限制最大 overshoot/undershoot 幅度、Edge-aware 方法避免銳化跨越邊緣。增加 Amount 只會加重 halo，不能抑制它。",
    imageDesc: "",
    scenario: "",
    hint: "增加 Amount 會讓 halo 更明顯。"
  },
  {
    id: "sharpening_069",
    category: "sharpening",
    type: "single",
    difficulty: 3,
    question: "在設計 ISP 的銳化模組時，為什麼有些系統會同時使用 edge enhancement 和 texture enhancement 兩個獨立的處理路徑？",
    options: ["為了增加計算量", "因為邊緣和紋理具有不同的空間頻率特性，需要不同的增益和保護策略", "因為兩者使用完全相同的演算法", "只是為了行銷目的"],
    answer: 1,
    acceptAlso: [],
    explanation: "邊緣（中低頻跳變）和紋理（中高頻重複模式）需要不同的銳化策略。邊緣需要控制 halo，紋理需要避免放大雜訊。分開處理可以分別優化增益、coring 和保護參數。",
    imageDesc: "",
    scenario: "",
    hint: "不同類型的細節需要不同的處理策略。"
  },
  {
    id: "sharpening_070",
    category: "sharpening",
    type: "scenario",
    difficulty: 3,
    question: "你在調試 ISP 時發現 MTF 曲線在某個空間頻率後出現大於 1.0 的值（MTF > 100%）。這代表什麼？",
    options: ["感測器有超高解析力", "銳化模組產生了過度增強，存在 overshoot 風險", "量測設備故障", "OLPF 失效"],
    answer: 1,
    acceptAlso: [],
    explanation: "MTF > 1.0 表示在該頻率下對比度被增強超過了原始輸入，這通常是 ISP 銳化模組過度增強的結果。在空間域上對應 overshoot/halo 現象，可能影響影像自然度。",
    imageDesc: "",
    scenario: "你對 ISP 輸出進行 SFR 量測，發現 MTF 曲線在 0.2 cycles/pixel 附近出現一個突起，峰值達到 1.15。",
    hint: "自然光學系統的 MTF 不會超過 1.0。"
  },
  {
    id: "sharpening_071",
    category: "sharpening",
    type: "fillblank",
    difficulty: 3,
    question: "Wiener filter 的頻率域表達式為 H_w(f) = H*(f) / (|H(f)|² + _____) ，其中 H(f) 是 PSF 的頻率響應。",
    options: [],
    answer: "NSR",
    acceptAlso: ["Sn/Ss", "N/S", "noise-to-signal ratio", "Snn/Sff", "雜訊功率譜/信號功率譜"],
    explanation: "完整公式中的正規化項是 NSR（Noise-to-Signal power spectral density Ratio），即雜訊功率譜密度與信號功率譜密度之比。它防止在 H(f) 接近零時雜訊被過度放大。",
    imageDesc: "",
    scenario: "",
    hint: "這個項平衡了去模糊與雜訊抑制。"
  },
  {
    id: "sharpening_072",
    category: "sharpening",
    type: "single",
    difficulty: 3,
    question: "在 Edge-directed sharpening 中，為什麼銳化核需要根據邊緣方向旋轉？",
    options: ["為了增加計算複雜度", "沿邊緣方向銳化會產生偽影，應該只在垂直於邊緣的方向銳化", "旋轉核可以消除所有雜訊", "邊緣方向與銳化無關"],
    answer: 1,
    acceptAlso: [],
    explanation: "Edge-directed sharpening 沿垂直於邊緣的方向增強，沿平行於邊緣的方向不增強或平滑。如果沿邊緣方向也銳化，會破壞邊緣的平滑連續性並產生鋸齒偽影。",
    imageDesc: "",
    scenario: "",
    hint: "銳化應該「穿過」邊緣，而非「沿著」邊緣。"
  },
  {
    id: "sharpening_073",
    category: "sharpening",
    type: "multiple",
    difficulty: 3,
    question: "以下哪些是 Multi-scale sharpening 相比單尺度銳化的技術優勢？（選擇所有正確答案）",
    options: ["可對不同尺度的細節施加不同增益", "可避免大 Radius 帶來的寬 halo", "計算量一定更低", "可精確控制各頻帶的銳化程度"],
    answer: [0, 1, 3],
    acceptAlso: [],
    explanation: "Multi-scale 方法在各尺度獨立控制增益，避免了單一大 Radius 的寬 halo，且可精確控制各頻帶。但計算量通常比單尺度更高（需要金字塔分解與重建），所以選項 C 不正確。",
    imageDesc: "",
    scenario: "",
    hint: "Multi-scale 需要更多計算來分解和重建。"
  },
  {
    id: "sharpening_074",
    category: "sharpening",
    type: "single",
    difficulty: 3,
    question: "在 ISP 中實現 soft coring 時，通常使用什麼類型的非線性函數？",
    options: ["線性函數", "Sigmoid 或 tanh 形式的 S 型曲線", "階梯函數", "常數函數"],
    answer: 1,
    acceptAlso: [],
    explanation: "Soft coring 常用 sigmoid、tanh 或類似的 S 型非線性函數。這種函數在原點附近衰減小信號（雜訊），對大信號（邊緣）保持線性，且過渡平滑不會產生不連續偽影。",
    imageDesc: "",
    scenario: "",
    hint: "S 型函數在零附近平緩，遠處趨於線性。"
  },
  {
    id: "sharpening_075",
    category: "sharpening",
    type: "scenario",
    difficulty: 3,
    question: "你在開發一個 ISP 的 adaptive sharpening 模組，需要在邊緣區域強銳化、平坦區域不銳化、紋理區域適度銳化。你會如何設計分類邏輯？",
    options: [
      "只用局部亮度判斷",
      "結合局部梯度大小與方向一致性：高梯度+方向一致=邊緣，高梯度+方向隨機=紋理，低梯度=平坦",
      "使用全局直方圖決定所有像素的類型",
      "隨機分配銳化強度"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "邊緣具有高梯度且方向一致（因為邊緣有明確方向），紋理具有高梯度但方向較隨機（因為紋理是多方向的），平坦區域梯度低。結合梯度大小與方向一致性可有效分類。",
    imageDesc: "",
    scenario: "ISP 團隊需要設計一個像素級的區域分類器，用於驅動自適應銳化引擎的增益控制。",
    hint: "邊緣有明確方向，紋理則是多方向的。"
  },
  {
    id: "sharpening_076",
    category: "sharpening",
    type: "single",
    difficulty: 3,
    question: "PSF（Point Spread Function）與 MTF 之間的數學關係是什麼？",
    options: ["MTF 是 PSF 的傅立葉轉換的模（magnitude）", "MTF 是 PSF 的微分", "PSF 是 MTF 的積分", "兩者沒有數學關係"],
    answer: 0,
    acceptAlso: [],
    explanation: "PSF 經傅立葉轉換得到 OTF（Optical Transfer Function），OTF 的模（magnitude/absolute value）即為 MTF。數學上 MTF(f) = |FT{PSF}(f)|。OTF 的相位部分稱為 PTF。",
    imageDesc: "",
    scenario: "",
    hint: "空間域與頻率域之間的橋梁是傅立葉轉換。"
  },
  {
    id: "sharpening_077",
    category: "sharpening",
    type: "truefalse",
    difficulty: 3,
    question: "在 ISP 設計中，銳化模組的 MTF compensation 目標是讓系統總 MTF 在所有頻率都達到 1.0。",
    options: [],
    answer: false,
    acceptAlso: [],
    explanation: "讓所有頻率 MTF = 1.0 會在高頻處過度放大雜訊（因為光學 MTF 在高頻很低，需要極大增益補償）。實際設計中會設定一個目標 MTF 曲線，在高頻處允許適度衰減以平衡銳度和雜訊。",
    imageDesc: "",
    scenario: "",
    hint: "追求完美 MTF = 1.0 在雜訊方面會付出代價。"
  },
  {
    id: "sharpening_078",
    category: "sharpening",
    type: "ordering",
    difficulty: 3,
    question: "在設計 deconvolution sharpening 時，請按正確的工程流程排列以下步驟：",
    options: [],
    answer: 0,
    acceptAlso: [],
    explanation: "Deconvolution 流程：先量測/估計光學系統的 PSF → 選擇合適的去卷積方法 → 加入正規化項平衡銳度與雜訊 → 對結果做 artifact 控制（如 coring、clipping）。",
    imageDesc: "",
    scenario: "",
    hint: "必須先知道模糊的模型，才能反轉它。",
    items: ["量測或估計系統 PSF", "選擇去卷積方法 (Wiener/RL)", "加入正規化項控制雜訊放大", "後處理以抑制偽影 (coring/clipping)"]
  },
  {
    id: "sharpening_079",
    category: "sharpening",
    type: "single",
    difficulty: 3,
    question: "為什麼有些高階相機會移除 OLPF（如 Nikon D800E）？",
    options: ["降低成本", "移除 OLPF 可獲得更高原始銳度，仰賴高像素密度和軟體處理來控制混疊", "OLPF 會導致感測器損壞", "所有現代相機都不需要 OLPF"],
    answer: 1,
    acceptAlso: [],
    explanation: "移除 OLPF 不會衰減高頻，可獲得更高的原始銳度。但代價是可能產生混疊。高像素密度的感測器因為 Nyquist 頻率更高，混疊風險較低，配合軟體除混疊可以接受。",
    imageDesc: "",
    scenario: "",
    hint: "高像素密度 = 更高的 Nyquist 頻率 = 更少混疊。"
  },
  {
    id: "sharpening_080",
    category: "sharpening",
    type: "fillblank",
    difficulty: 3,
    question: "Constrained least-squares deconvolution 在 Wiener filter 的基礎上引入了 _____ 運算子作為正規化約束。",
    options: [],
    answer: "Laplacian",
    acceptAlso: ["laplacian", "拉普拉斯"],
    explanation: "Constrained least-squares (CLS) filter 使用 Laplacian 運算子作為正規化項，約束結果的平滑度。公式為 H_cls = H* / (|H|² + γ|C|²)，其中 C 通常是 Laplacian 核的頻率響應，γ 是正規化參數。",
    imageDesc: "",
    scenario: "",
    hint: "使用一個常見的二階微分運算子來約束平滑度。"
  },
  {
    id: "sharpening_081",
    category: "sharpening",
    type: "multiple",
    difficulty: 3,
    question: "在 ISP 中設計銳化模組時，哪些因素需要根據 ISO 值（感光度）動態調整？（選擇所有正確答案）",
    options: ["Sharpening amount/gain", "Coring threshold", "邊緣偵測的靈敏度", "輸出影像的解析度"],
    answer: [0, 1, 2],
    acceptAlso: [],
    explanation: "高 ISO 雜訊更多，需要降低銳化增益、提高 coring 閾值以避免放大雜訊、降低邊緣偵測靈敏度以減少雜訊誤判為邊緣。輸出解析度通常不隨 ISO 變化。",
    imageDesc: "",
    scenario: "",
    hint: "高 ISO = 高雜訊，銳化策略需要更保守。"
  },
  {
    id: "sharpening_082",
    category: "sharpening",
    type: "single",
    difficulty: 3,
    question: "在頻率域銳化中，如果直接使用 inverse filter H_inv(f) = 1/H(f)，當 H(f) 在某些頻率接近零時會發生什麼？",
    options: ["結果完美恢復", "無法計算（除以零）且雜訊被無限放大", "自動忽略這些頻率", "結果收斂到原始影像"],
    answer: 1,
    acceptAlso: [],
    explanation: "Inverse filter 直接除以 H(f)，當 H(f)→0 時 1/H(f)→∞，不僅數學上無法計算，且即使 H(f) 很小但不為零，微小的雜訊也會被放大到極大值。這就是為什麼需要 Wiener filter 等正規化方法。",
    imageDesc: "",
    scenario: "",
    hint: "這是 inverse filter 的根本缺陷。"
  },
  {
    id: "sharpening_083",
    category: "sharpening",
    type: "scenario",
    difficulty: 3,
    question: "你在設計 Multi-scale sharpening，使用 3 層 Laplacian 金字塔。你希望增強細紋理但不增強粗邊緣。如何設定各層增益？",
    options: [
      "所有層增益相同",
      "Layer 0（最高頻）增益最高，Layer 1 中等，Layer 2（最低頻）增益為 0 或很低",
      "Layer 2 增益最高，Layer 0 增益為 0",
      "只增強 Layer 1"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "Layer 0 是最精細的高頻細節（細紋理），Layer 2 是最粗的低頻細節（粗邊緣）。要增強細紋理但不影響粗邊緣，應該 Layer 0 增益最高，Layer 2 增益最低或為零。",
    imageDesc: "",
    scenario: "ISP 設計師需要針對布料紋理進行增強，但不希望人臉輪廓出現明顯的光暈偽影。",
    hint: "金字塔底層 = 高頻 = 細紋理。"
  },
  {
    id: "sharpening_084",
    category: "sharpening",
    type: "truefalse",
    difficulty: 3,
    question: "Richardson-Lucy deconvolution 天然保證輸出值為非負的，這是因為其乘法更新規則。",
    options: [],
    answer: true,
    acceptAlso: [],
    explanation: "RL 演算法的迭代更新公式為 f_{n+1} = f_n × (h* ⊛ (g / (h ⊛ f_n)))，其中 × 是逐元素乘法。只要初始估計非負，每次迭代的結果都是非負的，這在物理上有意義（如光子計數不能為負）。",
    imageDesc: "",
    scenario: "",
    hint: "乘法更新不會改變正數的符號。"
  },
  {
    id: "sharpening_085",
    category: "sharpening",
    type: "single",
    difficulty: 3,
    question: "在 ISP sharpening 設計中，「shoot control」機制的目的是什麼？",
    options: ["控制相機快門速度", "限制 overshoot 和 undershoot 的最大幅度以控制 halo 強度", "控制自動對焦的射擊次數", "決定連拍的張數"],
    answer: 1,
    acceptAlso: [],
    explanation: "Shoot control 是銳化後處理的一種 clipping 機制，對 overshoot（正向超調）和 undershoot（負向超調）的幅度設定上限。這可以有效控制光暈的可見性，同時保持邊緣銳度。",
    imageDesc: "",
    scenario: "",
    hint: "Shoot = overshoot/undershoot。"
  },
  {
    id: "sharpening_086",
    category: "sharpening",
    type: "image",
    difficulty: 3,
    question: "觀察以下描述的 MTF 曲線：\n- 光學系統 MTF（藍線）：從 1.0 開始，在 Nyquist 頻率處降到約 0.2\n- ISP 銳化後 MTF（紅線）：在低頻處約 1.0，中頻處出現一個峰值約 1.3，在 Nyquist 附近降到約 0.4\n\n紅線中頻峰值的含義是什麼？",
    options: ["量測誤差", "銳化在中頻過度補償，可能產生可見的 halo/ringing", "光學系統在中頻特別好", "Nyquist 頻率偏移"],
    answer: 1,
    acceptAlso: [],
    explanation: "MTF > 1.0 的峰值表示該頻率的對比度被人為增強超過了原始場景，這是銳化過度補償的特徵。在空間域對應邊緣的 overshoot/undershoot（halo），在頻域表現為 MTF 峰值。",
    imageDesc: "MTF 曲線圖，x 軸為空間頻率（0 到 Nyquist），y 軸為 MTF 值。藍色線從 1.0 單調下降到 0.2。紅色線在中頻處出現超過 1.0 的峰值。",
    scenario: "",
    hint: "MTF 值不應超過 1.0，除非有人為增強。"
  },
  {
    id: "sharpening_087",
    category: "sharpening",
    type: "single",
    difficulty: 3,
    question: "在 ISP 中使用 bilateral filter 作為銳化前置處理的優勢是什麼？",
    options: ["加速銳化計算", "在降噪的同時保留邊緣，使後續銳化不會過度放大雜訊且邊緣保持清晰", "增加色彩飽和度", "自動調整白平衡"],
    answer: 1,
    acceptAlso: [],
    explanation: "Bilateral filter 是一種 edge-preserving 降噪濾波器，它在平坦區域平滑雜訊但在邊緣處保持銳利跳變。這為後續銳化提供了理想的輸入：乾淨的平坦區域和保持完整的邊緣。",
    imageDesc: "",
    scenario: "",
    hint: "Bilateral filter = 邊緣保持的降噪。"
  },
  {
    id: "sharpening_088",
    category: "sharpening",
    type: "fillblank",
    difficulty: 3,
    question: "在 Laplacian 金字塔的重建過程中，需要將上層影像 _____ 後再加上對應層的 Laplacian 細節。",
    options: [],
    answer: "上採樣",
    acceptAlso: ["upsample", "upsampling", "放大", "插值放大", "interpolate"],
    explanation: "Laplacian 金字塔重建時，從最頂層的低解析度影像開始，上採樣（upsample）到下一層大小，再加上該層的 Laplacian 細節（高頻殘差），逐層往下重建直到原始解析度。",
    imageDesc: "",
    scenario: "",
    hint: "從小影像恢復到大影像需要什麼操作？"
  },
  {
    id: "sharpening_089",
    category: "sharpening",
    type: "multiple",
    difficulty: 3,
    question: "以下哪些是 Ringing artifact 的成因？（選擇所有正確答案）",
    options: ["Gibbs 現象（在不連續處的傅立葉級數截斷）", "理想低通/高通濾波器的使用", "高斯模糊核", "頻率域的矩形窗口截斷"],
    answer: [0, 1, 3],
    acceptAlso: [],
    explanation: "Ringing 源自 Gibbs 現象，在信號不連續處的傅立葉級數截斷造成振盪。理想濾波器（磚牆型）和矩形窗口截斷都會導致此現象。高斯核的頻率響應平滑衰減，不會產生 ringing。",
    imageDesc: "",
    scenario: "",
    hint: "高斯函數在空間域和頻率域都是平滑的。"
  },
  {
    id: "sharpening_090",
    category: "sharpening",
    type: "single",
    difficulty: 3,
    question: "在 YUV 域進行銳化時，如果不小心也對 U、V 色度通道做了少量銳化，最可能出現什麼問題？",
    options: ["影像整體變暗", "彩色邊緣出現色彩過飽和或色彩振鈴", "白平衡偏移", "解析度降低"],
    answer: 1,
    acceptAlso: [],
    explanation: "色度通道的銳化會增強色彩邊緣的對比度，導致色彩過飽和、邊緣處出現彩色光暈或色彩振鈴。這就是為什麼通常只對 Y 通道銳化，U/V 通道保持不變或僅做輕微處理。",
    imageDesc: "",
    scenario: "",
    hint: "銳化色度 = 增強色彩邊緣的對比度。"
  },
  {
    id: "sharpening_091",
    category: "sharpening",
    type: "scenario",
    difficulty: 3,
    question: "你在設計手機 ISP 的銳化模組，需要在低光和高光場景之間自動切換銳化策略。你的 adaptive 控制邏輯應該如何設計？",
    options: [
      "固定銳化參數不隨場景變化",
      "根據 AE 統計的亮度/ISO/增益值，建立 LUT（Look-Up Table）映射不同場景到不同銳化參數組合",
      "只在高光場景銳化，低光完全不處理",
      "使用隨機數決定銳化參數"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "實際 ISP 設計中，銳化參數通常透過 LUT 根據 ISO/增益值/亮度等 AE 統計資訊進行插值調整。低光高 ISO 時降低 gain、提高 coring；高光低 ISO 時可以更積極銳化。",
    imageDesc: "",
    scenario: "手機 ISP 團隊需要設計一套自動化的銳化參數控制系統，能在不同光照條件下提供最佳的銳度與雜訊平衡。",
    hint: "ISP 常用查找表來映射場景參數。"
  },
  {
    id: "sharpening_092",
    category: "sharpening",
    type: "truefalse",
    difficulty: 3,
    question: "在 deconvolution sharpening 中，空間域的 PSF 越寬（模糊越嚴重），頻率域的 OTF 截止頻率越低，反卷積難度越大。",
    options: [],
    answer: true,
    acceptAlso: [],
    explanation: "寬 PSF 對應窄 OTF（低截止頻率），意味著更多高頻成分已被嚴重衰減甚至丟失。反卷積需要對這些極低的 OTF 值進行補償，雜訊放大風險極高，因此難度更大。",
    imageDesc: "",
    scenario: "",
    hint: "空間域寬 ↔ 頻率域窄，這是傅立葉轉換的基本性質。"
  },
  {
    id: "sharpening_093",
    category: "sharpening",
    type: "single",
    difficulty: 3,
    question: "在高動態範圍 (HDR) 影像的銳化中，為什麼需要特別注意 tone mapping 與銳化的順序？",
    options: [
      "HDR 影像不需要銳化",
      "在 tone mapping 前銳化可能導致高頻細節在壓縮後失真，在 tone mapping 後銳化才能正確反映最終顯示的對比度",
      "順序完全不影響結果",
      "Tone mapping 會自動完成銳化"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "Tone mapping 會非線性壓縮動態範圍，改變局部對比度。在 TM 前銳化的高頻增益可能在 TM 後被壓縮或失真。通常建議在 TM 後銳化，或在 TM 前後分別處理不同尺度。",
    imageDesc: "",
    scenario: "",
    hint: "Tone mapping 的非線性壓縮會改變銳化的效果。"
  },
  {
    id: "sharpening_094",
    category: "sharpening",
    type: "fillblank",
    difficulty: 3,
    question: "在 Coring 技術中，將小幅度高頻成分的傳遞函數設為零的做法稱為 _____ coring。",
    options: [],
    answer: "Hard",
    acceptAlso: ["hard", "硬"],
    explanation: "Hard coring 在閾值處做硬截斷：低於閾值的高頻幅度直接歸零，高於閾值的完全保留。這種做法簡單但可能產生不自然的過渡，相比之下 soft coring 使用漸變更為平滑。",
    imageDesc: "",
    scenario: "",
    hint: "「硬」截斷 = 非此即彼。"
  },
  {
    id: "sharpening_095",
    category: "sharpening",
    type: "single",
    difficulty: 3,
    question: "在設計 ISP 的 edge enhancement 模組時，asymmetric sharpening（非對稱銳化）的目的是什麼？",
    options: [
      "讓影像不對稱",
      "對 overshoot 和 undershoot 施加不同的增益限制，利用人眼對亮暗不對稱的感知特性",
      "只銳化影像的左半部",
      "使用不對稱的高斯核"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "人眼對亮側的 overshoot 比暗側的 undershoot 更敏感。非對稱銳化允許更大的 undershoot 但嚴格限制 overshoot，這樣可以在獲得足夠銳度感的同時減少可見的光暈偽影。",
    imageDesc: "",
    scenario: "",
    hint: "人眼對明暗的感知是非對稱的。"
  },
  {
    id: "sharpening_096",
    category: "sharpening",
    type: "multiple",
    difficulty: 3,
    question: "在 ISP 中，銳化模組的硬體實現通常需要考慮哪些約束？（選擇所有正確答案）",
    options: ["Line buffer 的數量（決定了核的垂直尺寸）", "乘法器數量與位元精度", "支援的最大影像解析度", "是否能即時處理（滿足幀率要求）"],
    answer: [0, 1, 3],
    acceptAlso: [],
    explanation: "硬體 ISP 銳化需考慮：line buffer 數量限制了卷積核的行數、乘法器精度影響計算品質、必須滿足即時幀率。最大解析度通常由系統規格決定，不是銳化模組特有的約束。",
    imageDesc: "",
    scenario: "",
    hint: "硬體 ISP 的核心約束是面積、速度和精度。"
  },
  {
    id: "sharpening_097",
    category: "sharpening",
    type: "scenario",
    difficulty: 3,
    question: "你在分析競品手機的影像品質，發現其在低頻文字邊緣有明顯的白色光暈但紋理區域很銳利。推測其銳化架構可能有什麼問題？",
    options: [
      "完全沒有銳化",
      "可能使用了單一大 Radius 的 USM，導致低頻邊緣 halo 過大，但高頻紋理被有效增強",
      "使用了完美的 Multi-scale sharpening",
      "只做了降噪沒有銳化"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "大 Radius USM 會在粗邊緣產生寬光暈（因為模糊核大），但同時也會增強較高頻的紋理。這是單尺度 USM 的典型問題，Multi-scale 方法可以對不同尺度獨立控制以避免此問題。",
    imageDesc: "",
    scenario: "品質分析團隊拍攝了測試圖卡，在文字邊緣看到明顯的亮色光暈（約 3-5 像素寬），但衣服布料紋理細節表現良好。",
    hint: "大光暈 = 大 Radius 的副作用。"
  },
  {
    id: "sharpening_098",
    category: "sharpening",
    type: "truefalse",
    difficulty: 3,
    question: "在 frequency-based sharpening 中，使用 Hamming 或 Hanning 窗口函數可以減少 ringing artifact。",
    options: [],
    answer: true,
    acceptAlso: [],
    explanation: "Ringing 源自頻率域的矩形截斷（Gibbs 現象）。使用 Hamming、Hanning 等窗口函數可以讓頻率響應平滑過渡到零，大幅減少空間域的振鈴偽影，代價是稍微降低頻率選擇性。",
    imageDesc: "",
    scenario: "",
    hint: "窗口函數的目的就是平滑頻率響應的截斷。"
  },
  {
    id: "sharpening_099",
    category: "sharpening",
    type: "single",
    difficulty: 3,
    question: "在 ISP 的 sharpening pipeline 中，為什麼有些設計會在銳化核的基礎上加入 negative lobe（負旁瓣）？",
    options: [
      "減少計算量",
      "負旁瓣產生受控的 undershoot/overshoot，增強邊緣的視覺銳度感知",
      "消除所有偽影",
      "使影像整體變暗"
    ],
    answer: 1,
    acceptAlso: [],
    explanation: "適度的 negative lobe 會在邊緣附近產生受控的明暗對比增強（Mach band effect），利用人眼的視覺特性增強銳度感知。過大的負旁瓣則會產生可見的光暈偽影。",
    imageDesc: "",
    scenario: "",
    hint: "人眼的 Mach band 效應使邊緣對比增強看起來更銳利。"
  },
  {
    id: "sharpening_100",
    category: "sharpening",
    type: "ordering",
    difficulty: 3,
    question: "在完整的 ISP sharpening 子系統中，請按正確的處理順序排列以下模組：",
    options: [],
    answer: 0,
    acceptAlso: [],
    explanation: "完整的銳化子系統：先用邊緣偵測分析內容 → 基於偵測結果做自適應高頻提取 → Coring 去除雜訊成分 → 對 overshoot/undershoot 做 shoot control 限幅。每步都依賴前一步的結果。",
    imageDesc: "",
    scenario: "",
    hint: "先分析、再提取、再清理、再限制。",
    items: ["邊緣/紋理偵測與分類", "自適應高頻增益 (Adaptive gain)", "Coring 去除小幅度雜訊", "Shoot control 限制 overshoot/undershoot"]
  }
];
